### ISSUE TITLE
能在短信模板中添加一个收信号码就更好了

### ISSUE THREAD

**Issue by xfaifai** [pppscn/SmsForwarder#1]
手机有两个卡AB卡，转发后的模板不清楚该短信是发给A的还是B的，如果能做一个识别就好了

**Comment by pppscn** [comment]
对于安卓开发我也不是很熟悉，翻阅了一下文档，貌似没有提供获取卡槽2手机号的API，最多只能标记是卡槽1或2收到短信。

如果你有看到类似的案例，贴一下网址我去研究一下，谢谢

**Comment by pppscn** [comment]
![微信图片_20210301235045](https://user-images.githubusercontent.com/5105854/109522319-1e583d00-7ae9-11eb-8e29-9a3741ae2227.jpg)

**Comment by pppscn** [comment]
[v1.2.2](app/release/SmsForwarder_release_20210302_1.2.2.apk) 【预发布】短信模板增加卡槽标识（SIM1：188xxxxxxxx 或 SIMx：unknown）

**Comment by pppscn** [comment]
请升级至[v1.2.3](app/release/SmsForwarder_release_20210302_1.2.3.apk) 

1、短信模板增加卡槽标识（SIM-0_中国联通_Unknown 或 SIM-1_中国移动_+8615866666666）
2、转发日志详情增加卡槽标识（SIM1 或 SIM2）
