### ISSUE TITLE
发送历史里面最好有状态，很多短信没转发，也不知道什么原因

### ISSUE THREAD

**Issue by zhi1ong** [pppscn/SmsForwarder#10]
RT

**Comment by pppscn** [comment]
v1.7.1 新增转发记录的转发状态(成功/失败&应答信息)

**Comment by zhi1ong** [comment]
话说能不能扩大一下功能，通知转发，不只是短信，要是能筛选应用，那就更完美了

**Comment by pppscn** [comment]
> 话说能不能扩大一下功能，通知转发，不只是短信，要是能筛选应用，那就更完美了

暂不考虑添加其他监听
