### ISSUE TITLE
请问telegram转发的自定义地址格式是怎么样的

### ISSUE THREAD

**Issue by lincww** [pppscn/SmsForwarder#104]
试过https://forward.address/bot<key\>，提示无效
谢谢

**Comment by pppscn** [comment]
是不是你的反代，只支持get形式？

**Comment by lincww** [comment]
> 是不是你的反代，只支持get形式？

用的是CF worker，试了一下应该是支持post的
![image](https://user-images.githubusercontent.com/56734434/149470223-6f811924-c168-4fdb-b8dd-acb7bdacadd6.png)

（顺带一提吐槽一下，在miui12 20.6.18/小米6 上，tg api输入框是密码控件，没有粘贴选项，只能手打）

**Comment by pppscn** [comment]
试试  https://forward.address/bot<key>/sendMessage

**Comment by pppscn** [comment]
不太清楚你的反代是怎么配置的，目前的机制：填写 http 开头时，不再进行api地址拼接，需要填写的完整的api接口地址

**Comment by lincww** [comment]
> 试试 https://forward.address/bot/sendMessage

成功了

**Comment by lincww** [comment]
多谢您的回答
是需要把~/sendMessage加上
