### ISSUE TITLE
小米后台应用通知太多，能否快速屏蔽一些通知

### ISSUE THREAD

**Issue by jarodlee** [pppscn/SmsForwarder#107]
感谢大神提供的这么强大的工具，在小米mix3备机上使用了，非常棒。
只有一个小问题，就是小米后台经常运行各种通知，平时都没有发现，现在都转发到电报上来了，比如扫描设备、小米画报之类的，我都禁用了也还会出现通知，在转发规则中也不会设备多个不同应用的不转发，有没有快速指定多个应用不转发的办法？

**Comment by pppscn** [comment]
按需转发指定包名的通知吧，不要全部转发

**Comment by jarodlee** [comment]
> 

如何设置按需要转发包呢？多个包的规则不会写呢，，，有没有指导的教程，谢谢。

**Comment by pppscn** [comment]
匹配字段：APP包名
匹配模式：正则匹配
匹配的值： com.aaa.ccc|cn.bbb.ddd
