### ISSUE TITLE
您好，有时候用邮件转发短信会失败。

### ISSUE THREAD

**Issue by xifeng0** [pppscn/SmsForwarder#108]
请问这是163那边服务器的问题吗还是？
或者是软件会自动重试转发吗？因为最近发现漏了几个比较重要的短信所以去查看了一下手机。发现偶尔会有几个转发失败的。
![1642534882471](https://user-images.githubusercontent.com/76558682/150007756-3d5a8e7b-03b8-4e58-91d3-0f6051c21272.jpg)
![1642534882466](https://user-images.githubusercontent.com/76558682/150007768-7d88bee2-9ca0-4fd1-8c68-407af9b51305.jpg)

**Comment by pppscn** [comment]
网络问题，排查一下手机系统的电源管理，有没有息屏断网之类的省电设置
