### ISSUE TITLE
可以添加短信内容接收存储手机存储卡吗

### ISSUE THREAD

**Issue by xiaoxin3005** [pppscn/SmsForwarder#109]
在使用post请求过程中，发现有时电脑端由于网络问题或者网络环境发生变化导致信息转发不成功。于是，希望能够添加一个功能，当接收到短信生成本次信息内容到手机路径下，程序可以通过usb接口直接获取到文件，

**Comment by pppscn** [comment]
小众需求，一般备用机用不上，暂不考虑
