### ISSUE TITLE
请求支持pushdeer

### ISSUE THREAD

**Issue by nageshuizeii** [pppscn/SmsForwarder#110]
请求支持pushdeer，项目地址https://github.com/easychen/pushdeer/

**Comment by Mosney** [comment]
感觉应该可以用WebHook间接支持，但是试了试不行，看到有这个issue但是关闭了，请问是配置上了吗？该怎么配置呢？

**Comment by pppscn** [comment]
新增：Webhook的GET形式支持webParams【例如：PushDeer】

下一版本见！

![Screenshot_1642950759](https://user-images.githubusercontent.com/5105854/150686005-a172693f-4586-48d2-853f-24e09541498b.png)

**Comment by yjw0628** [comment]
试过webHook形式,但是会闪退
