### ISSUE TITLE
反馈3个小问题

### ISSUE THREAD

**Issue by Mosney** [pppscn/SmsForwarder#111]
左图1，英文界面下Sender Setting按钮下沉
左图2，电量转发莫名多出来一个钉钉log，然而我从来没设置过钉钉的转发器
右图，电量上下限在英文界面被遮挡

![result-2022-01-25-12-03-31](https://user-images.githubusercontent.com/22477230/150908830-0354db8f-5cb2-4fdd-b4b3-50f96f95c335.png)

**Comment by Mosney** [comment]
还有第4个小问题，刚发现的，也是英文UI异常
![Screenshot_20220125-120944](https://user-images.githubusercontent.com/22477230/150909389-e8590a52-61c1-4846-896f-c958c10205bb.jpg)

**Comment by pppscn** [comment]
加入QQ群，测试一下 2.4.0 内测版本
