### ISSUE TITLE
短信无法转发

### ISSUE THREAD

**Issue by peney83** [pppscn/SmsForwarder#112]
2.3.0设置中转发应用通知、转发未接来电、转发短信广播都已打开，同时
小米10 miui 12.0.11, 同时授权管理里面 ”读取短信“和 ”通知类短信“都已授权，无法转发。
从现象来看是无法读取手机的短信和未接来电，短信转发器中的短信列表为空

**Comment by pppscn** [comment]
对应的 Android 版本是多少？ 具体的配置截图出来一下

通道测试、规则测试都能通过？

权限全部授予了？

先对照 wiki 的 FAQ 排查一下

https://github.com/pppscn/SmsForwarder/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by pppscn** [comment]
加QQ群沟通吧
