### ISSUE TITLE
希望能添加新版本推送

### ISSUE THREAD

**Issue by sunny7010** [pppscn/SmsForwarder#113]
1. 添加定时检查更新选项
2. 当客户端发现有新版本时自动推送到比如企业微信机器人等

**Comment by pppscn** [comment]
目前更新都是手动触发的，也不打算弄成自动检查更新的，所以更进一步的更新推送暂不考虑他添加

主要是这个工具软件，更新不会频繁，实在要的话，可以定时去请求更新接口获取

**Comment by pppscn** [comment]
在线更新请求接口

https://xupdate.bms.ink/update/checkVersion?appKey=com.idormy.sms.forwarder&versionCode=300032

versionCode=等于你当前的就好了
