### ISSUE TITLE
正则解析有问题？

### ISSUE THREAD

**Issue by gitiray** [pppscn/SmsForwarder#116]
为避免规则太多造成干扰，只保留问题规则，分别进行测试

1. 多重匹配规则 `并且 不是 短信内容 正则匹配 退订[a-zA-Z]`，短信内容`退订TD`，**会转发**
2. 多重匹配规则 `并且 不是 短信内容 正则匹配 退订[a-zA-Z]`，短信内容`退订T`，不转发
3. 多重匹配规则 `并且 不是 短信内容 正则匹配 退订[a-zA-Z]+`，短信内容`退订TD`，不转发
4. 多重匹配规则 `并且 不是 短信内容 正则匹配 退订[a-zA-Z]+`，短信内容`退订T`，不转发

**第1条的解析有点问题，期望结果是匹配到正则、不转发**。
使用[工具](https://c.runoob.com/front-end/854/)验证也符合期望。

**Comment by gitiray** [comment]
上面的是多重匹配规则，匹配时不执行。
如果改用短信内容里的正则匹配，理论应该和上面的结果完全相反。

进一步验证：
1. 短信内容正则匹配规则 `退订[a-zA-Z]`，短信内容 `退订TD`，**会转发**
2. 短信内容正则匹配规则 `退订[a-zA-Z]`，短信内容 `退订T`，会转发
3. 短信内容正则匹配规则 `退订[a-zA-Z]+`，短信内容 `退订TD`，会转发
4. 短信内容正则匹配规则 `退订[a-zA-Z]+`，短信内容 `退订T`，会转发

这么一比较应该能看出来了。

**Comment by pppscn** [comment]
刚看了一下代码：多重匹配中的正则匹配（1）  与 单独的正则匹配（2） 的代码确实不一样，上一次优化应该只优化了（2）

(1)  [RuleLine.java](https://github.com/pppscn/SmsForwarder/blob/main/app/src/main/java/com/idormy/sms/forwarder/utils/RuleLine.java)
341行：
```
checked = Pattern.matches(this.value, msgValue);
```

(2) [RuleModel.java](https://github.com/pppscn/SmsForwarder/blob/main/app/src/main/java/com/idormy/sms/forwarder/model/RuleModel.java)
217行：
```
//checked = Pattern.matches(this.value, msgValue);
Pattern pattern = Pattern.compile(this.value, Pattern.CASE_INSENSITIVE);
Matcher matcher = pattern.matcher(msgValue);
//noinspection LoopStatementThatDoesntLoop
while (matcher.find()) {
    checked = true;
    break;
}
```

**Comment by pppscn** [comment]
区别就是 Pattern.matches 需要正则表达式 全部匹配，多重匹配那边也改成 pattern.matcher

https://github.com/pppscn/SmsForwarder/commit/415e8ebcab68d6c7b75e29ea7e5fb4aef50ae490
