### ISSUE TITLE
想要获取短信发送状态

### ISSUE THREAD

**Issue by dcsunny** [pppscn/SmsForwarder#117]
主动请求发送短信的功能，能否增加发送的短信是否成功的回调呢

**Comment by pppscn** [comment]
等3.0.0版本发布，届时以API接口文档为准

https://github.com/pppscn/SmsForwarder/wiki/%E9%99%84%E5%BD%952%EF%BC%9A%E4%B8%BB%E5%8A%A8%E8%AF%B7%E6%B1%82(%E8%BF%9C%E7%A8%8B%E6%8E%A7%E5%88%B6)
