### ISSUE TITLE
短信转发使用SMS原收原出发送短信错误

### ISSUE THREAD

**Issue by GamerNoTitle** [pppscn/SmsForwarder#118]
之前发送是成功的，也没有做出什么改动，但是后来就不太行了

下面附上几张有关的图

![发送日志](https://user-images.githubusercontent.com/28426291/154097660-c2e300e2-534c-4488-9064-e79edf5da2a9.png)
![配置文件](https://user-images.githubusercontent.com/28426291/154100274-c04f1d9e-c89d-4c64-aefb-cac1c553f875.png)
![信息内容](https://user-images.githubusercontent.com/28426291/154100464-6909c6d4-af1e-4413-8a13-3e1f57cf0286.png)
![设备信息](https://user-images.githubusercontent.com/28426291/154100476-ac5d29e2-3423-4876-806c-e0b157de0dec.png)

**Comment by pppscn** [comment]
你当前的版本号是多少？ Android版本是多少？ 2.4.2 专门修复过这个问题

https://github.com/pppscn/SmsForwarder/commit/89cd86326ae45c5a5335d4f6f162911e199a49df

**Comment by GamerNoTitle** [comment]
发上面这些图的是2.4.1，我刚更成2.4.2，我再试试

**Comment by GamerNoTitle** [comment]
已经可以了，感谢
