### ISSUE TITLE
请问webhook里，可以用的变量有哪些呢？

### ISSUE THREAD

**Issue by thoreausolo** [pppscn/SmsForwarder#119]
除了msg，好像from、content、timestamp都取不到值

**Comment by pppscn** [comment]
具体查看wiki

https://github.com/pppscn/SmsForwarder/wiki/%E9%99%84%E5%BD%951%EF%BC%9A%E5%90%91webhook%E5%8F%91%E9%80%81post-get%E8%AF%B7%E6%B1%82

**Comment by thoreausolo** [comment]
你是说post form 参数列表吗？这里面的3个参数from、content、timestamp都取不到

{"Msg":"[msg]","SendTel":"[from]","ReceiptTime":"[timestamp]"}
{Msg:[msg],SendTel:[from],ReceiptTime:[timestamp]}

2种方式都取不到值，服务端接收到的json只是替换了[msg]，其他的都是原文

**Comment by pppscn** [comment]
下一版把参数列表的节点都弄成标签
