### ISSUE TITLE
HTTPS支持

### ISSUE THREAD

**Issue by 1itt1eB0y** [pppscn/SmsForwarder#12]
希望能增加证书导入，或者设置https不验证，实现对https的支持

**Comment by pppscn** [comment]
详细说说用哪个转发方式不行；或者不支持的url提供一个，我试试，我没碰到这个情况

**Comment by 1itt1eB0y** [comment]
> 详细说说用哪个转发方式不行；或者不支持的url提供一个，我试试，我没碰到这个情况

我自己服务器上的gotify推送，用了ssl。需要设置https不验证或者加载证书才可以。
Post方式推送的。gotify在github开源，您可以看下

**Comment by pppscn** [comment]
https://github.com/pppscn/SmsForwarder/commit/f50cdc56ddd554e827668971c7a2e4ea5a54b169

转发到webhook时忽略ssl证书校验（提高自建服务端兼容性）
