### ISSUE TITLE
一个保活失败样本

### ISSUE THREAD

**Issue by Aztand** [pppscn/SmsForwarder#123]
一加7型号安卓11，安装的是最新版。大约在晚上九点半配置完毕手机端，并且打开了一像素保活和无声音乐保活。此时起直到至少凌晨一点半均可正常转发。再之后就失联了。(或许还是期待做个无障碍保活)

**Comment by pppscn** [comment]
其他保活有打开吗？ 例如：自启动、系统的电源管理等

**Comment by pppscn** [comment]
无障碍保活暂不考虑搞

**Comment by Aztand** [comment]
dian'y电源管理已设置，t多任务已经上锁，自启动软件里打开了但没有权限提示

**Comment by Mosney** [comment]
HOS或ColorOS去手机管家/安全中心之类的软件里找找有没有隐藏设置项，或者直接刷成OOS从根本上解决问题
