### ISSUE TITLE
Content-Type: multipart/form-data的发送形式。

### ISSUE THREAD

**Issue by canwushuang** [pppscn/SmsForwarder#124]
我自建了一个cloudflare的workers用于反代tg的API，Content-Type以form形式或者标准json格式都可以(json,x-www-form-urlencoded)，但多次调试失败后抓包查看，发现本项目发送的类型数据以 Content-Type: multipart/form-data; boundary=XXXX-XXXX-XXXX-XXXX-XXXXXX，查询本项目的源码，看到webhook的发送带的content-type并没有写死multipart这个方式，请教下该如何处理可以支持我自建的单头格式。谢谢！

**Comment by pppscn** [comment]
tg反代可以直接走  tg那个发送通道

使用webhook的话  参考 https://github.com/pppscn/SmsForwarder/wiki/%E9%99%84%E5%BD%951%EF%BC%9A%E5%90%91webhook%E5%8F%91%E9%80%81post-get%E8%AF%B7%E6%B1%82

2.2 webParams 非空，包含 [msg] 标签、不以 { 开头

**Comment by canwushuang** [comment]
嗯，问之前都看了，可能cf workers的脚本需要改一下，暂时使用webhook + get方式请求。
