### ISSUE TITLE
单纯保存日志不需要使用外部储存权限

### ISSUE THREAD

**Issue by Mosney** [pppscn/SmsForwarder#125]
在应用专属存储空间中读写文件是不需要申请权限的，参见 https://developer.android.com/training/data-storage 
请问是有什么必要将文件放到公共储存目录里呢？

**Comment by pppscn** [comment]
原计划导出配置备份之类的，重装后的不会丢失，后面没搞就先搁置那里了

**Comment by Mosney** [comment]
> 原计划导出配置备份之类的，重装后的不会丢失，后面没搞就先搁置那里了

其实单纯导出导入配置文件也不需要请求直接读取外部储存的权限，调用documents ui即可在不申请权限的情况下存取文件
