### ISSUE TITLE
Bug反馈，Bark通道转发规则正则导致转发失败

### ISSUE THREAD

**Issue by Mosney** [pppscn/SmsForwarder#126]
之前在用2.3.0没有这个问题，刚更新到2.4.3发现了这个问题。
具体复现步骤为：
1. 添加Bark并配置转发规则
2. 转发规则中使用常见问题文档中推荐的`(\d{3})\d{4}(\d{4})===$1****$2`正则表达式
3. 用普通+86 11位手机号“13012341234”发送短信内容为11手机号如“131123456789”到安装了转发器的手机上
4. Bark通道会转发失败，此时同样触发条件的Email通道正常

失败log如下：
```
`Syntax error in regexp pattern near index 9

+86130 ****1234(.*)
    ^
```

- 同样条件下，发送方号码为106服务号码，则Bark通道转发正常
- 同样条件下，清除转发规则中的正则文本框，则Bark通道转发正常

**Comment by pppscn** [comment]
已经修复，去除对标题的正则替换

https://github.com/pppscn/SmsForwarder/commit/ef5b62fbeac67755e63c66c0a40834c1de255249
