### ISSUE TITLE
功能请求：将标题换为发送方/验证码

### ISSUE THREAD

**Issue by Mosney** [pppscn/SmsForwarder#132]
在邮件等有标题正文之分的发送渠道中：
- 将106短信括号中的【发件人】放到标题中，原始发送号码可以放到正文内容中
- 带验证码的短信，提取出验证码放到标题中，方便直接查看关键内容

不知我说的这两点是否实用？实现起来麻烦不麻烦呢？

**Comment by pppscn** [comment]
`将106短信括号中的【发件人】放到标题中，原始发送号码可以放到正文内容中`
这个【发件人】获取不到，一般是手机系统在线识别的结果

`带验证码的短信，提取出验证码放到标题中，方便直接查看关键内容`
email发送通道目前已经支持正则替换，其他支持标题的通道（bark、飞书、PUSHPLUS）感觉没有多大意义，暂不考虑

**Comment by Mosney** [comment]
> 这个【发件人】获取不到，一般是手机系统在线识别的结果

我是指那种短信内容里自带身份标识的短信，比如
> 【京东】短信登录验证码：123456。京东客服绝不会索取此验证码，切勿转发或告知他人。
这里的发件人就是【】内的【京东】，把这个放在标题上远比106xxxxx一串数字有意义的多。
