### ISSUE TITLE
希望增加导出配置，导入配置功能

### ISSUE THREAD

**Issue by longbinzhao** [pppscn/SmsForwarder#133]
如题，希望增加导出导入配置的功能，某些时候由于网络原因，无法使用克隆
这样也可以通过其它方式帮助别人设置一键转发。

**Comment by pppscn** [comment]
新增：一键克隆增加离线模式（导出备份json文件到Download目录，其他机器读取文件导入）
优化：一键克隆机制优化（替换db文件→操作现有db）

https://github.com/pppscn/SmsForwarder/commit/31017609f9d3450b190c91e8df15e8c7c5a5ee48

**Comment by longbinzhao** [comment]
生日快乐。 没有在更新日志中看到这个，是忘写了吗

pppscn ***@***.***> 于 2022年4月2日周六 14:54写道：

**Comment by pppscn** [comment]
下一版发布时才有，着急用就23:37过后来下载每夜构建版

https://github.com/pppscn/SmsForwarder/actions/workflows/Nightly_Build.yml
