### ISSUE TITLE
一键克隆bug

### ISSUE THREAD

**Issue by longbinzhao** [pppscn/SmsForwarder#134]
一键克隆bug
1. 频繁出现提示“使用无线网络”无法启动服务
2. 当克隆完毕，新手机发送的提醒提示的卡槽信息和旧手机一样，号码都是旧手机上的号码

已经尝试重启手机，bug依旧

**Comment by pppscn** [comment]
1、关闭“通用设置”中的“被动接收本地 HttpServer”，因为两个功能共用这个服务，下一版时考虑怎么优化

2、设备名称、SIM1备注、SIM2备注 不在“一键克隆”范畴，检查一下这三个值哪里来的
