### ISSUE TITLE
能否添加一个 Action 用于构建最新的测试版本

### ISSUE THREAD

**Issue by Xm798** [pppscn/SmsForwarder#135]
如题，想要使用 Webhook 的 Headers，发现12天前已经有 commit，但是暂无 release，fork 后构建缺少 token，因此能否开放 Action 版本作为测试版？公共仓库的 Action 并不会占用免费的 Action 额度。

**Comment by pppscn** [comment]
可以参考一下 https://github.com/pppscn/SmsForwarder/wiki/%E5%85%B3%E4%BA%8E%E5%AE%9A%E5%88%B6%E5%BC%80%E5%8F%91

在线编译方式

**Comment by pppscn** [comment]
签名证书这个不会公开，避免有心之人利用我的签名发布apk

**Comment by Xm798** [comment]
明白了，我去看一下在线编译方式。
本条 issue 的本意并不是想让您公开签名证书，而是希望这个项目借助 Action 自动构建最新的 beta 版，这样有需要的用户可以直接从这个 repo 的 Action 页面下载 beta 版使用，不用自己 fork，就像大多数软件一样。而且这样能够避免因为自编译签名不同，导致覆盖安装的时候在没有核心破解模块的时候需要卸载原APP，导致配置丢失的问题。因为是公开的 repo，所以也不会占用您账号的 Action 免费额度，个人觉得没有什么负面的影响。

**Comment by Xm798** [comment]
看了一下 Google 的开发者文档，创建签名需要 Android Studio，貌似成本有点高QAQ（非安卓开发者）

**Comment by pppscn** [comment]
> 就像大多数软件一样

列举一下几个仓库，我学习一下他们的测试版发布机制

**Comment by Xm798** [comment]
- 例如VS-Code的网页版 [code-server](https://github.com/coder/code-server/actions)，使用 Action 自动构建测试版和发行版，[测试版](https://github.com/coder/code-server/blob/main/.github/workflows/ci.yaml)的 Action 触发动作被设置为主分支上的 push 和 PR 动作，自动构建最新的版本供开发人员和用户进行测试，而[发行版](https://github.com/coder/code-server/blob/main/.github/workflows/docker.yaml)的 Action 触发动作被设置为创建 Release，提供稳定版本供生产环境部署。
- 例如密码管理器 [Bitwarden](https://github.com/bitwarden) 下的几个项目 [browser](https://github.com/bitwarden/browser/actions)、[server](https://github.com/bitwarden/server/actions)和 [手机客户端](https://github.com/bitwarden/mobile/actions) 也采用了类似的自动构建和发布方式。
- 例如博客框架 [Typecho](https://github.com/typecho/typecho)，在 Action 中有两个构建的 Workflow，分别是 [Release](https://github.com/typecho/typecho/actions/workflows/Typecho-release-Ci.yml) 和 [Dev](https://github.com/typecho/typecho/actions/workflows/Typecho-dev-Ci.yml)，Dev 版本不发布 Release，需要的用户可以自行从 Action 页面进行下载。
- 例如订阅转换工具 [subconverter](https://github.com/tindy2013/subconverter)，也是采用了 Action 发布 beta 版，Release 发布稳定版的方案。
- 
简单看了几个自己正在用的软件的 repo，不过或许确实上文的表述有些不恰当，应当修改为“就像许多软件一样”。

**Comment by Xm798** [comment]
另外 issue 的标题表述有误，应该是需要增加一个用于构建测试版本的 Action，而不是直接修改现有 Action，之前考虑有误，已经修改标题。

**Comment by pppscn** [comment]
https://github.com/pppscn/SmsForwarder/commit/cb90d44c8fc6dae11744ca647e6114a533c2400c

新增：定时发布 每夜构建 版本（北京时间：23:30）

下载地址：https://github.com/pppscn/SmsForwarder/actions/workflows/Nightly_Build.yml

**Comment by pppscn** [comment]
鉴于更新频率与避免空间爆满限速，`每夜构建` 调整为 `每周构建`（每周天23点启动编译）]
https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by Xm798** [comment]
或许可以调整为推送代码时触发构建

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
