### ISSUE TITLE
能否做一个http服务，局域网直接能访问到短信列表和短信内容

### ISSUE THREAD

**Issue by ranhuan** [pppscn/SmsForwarder#138]
目前已有http服务，但只有send_api

**Comment by pppscn** [comment]
等3.0.0版本发布，届时以API接口文档为准

https://github.com/pppscn/SmsForwarder/wiki/%E9%99%84%E5%BD%952%EF%BC%9A%E4%B8%BB%E5%8A%A8%E8%AF%B7%E6%B1%82(%E8%BF%9C%E7%A8%8B%E6%8E%A7%E5%88%B6)
