### ISSUE TITLE
建议：解锁状态下不转发

### ISSUE THREAD

**Issue by gitiray** [pppscn/SmsForwarder#139]
不知道可否实现：
设备已解锁，说明用户是在操作设备的，直接能看到通知，无需再转发，避免造成重复通知
可以做成开关的形式，防止部分用户依然需要转发

**Comment by pppscn** [comment]
新增：仅锁屏状态转发APP通知开关
https://github.com/pppscn/SmsForwarder/commit/60dde070b56fda41d0a88e2b92af90dd8dabd5db

等下一次发版 或 下载每夜构建版
https://github.com/pppscn/SmsForwarder/actions/workflows/Nightly_Build.yml
