### ISSUE TITLE
tg转发‘#‘号被替换为’井‘

### ISSUE THREAD

**Issue by xingxichen** [pppscn/SmsForwarder#142]
tg转发‘#‘号被替换为’井‘

**Comment by jiz4oh** [comment]
Hi @pppscn, 关于这个修复可以单独发一个 2.x 版本吗，

由于一些 [小众需求](https://github.com/pppscn/SmsForwarder/issues/16) 添加的功能不应该成为程序默认值，应该由用户自己 [配置](https://github.com/pppscn/SmsForwarder/wiki/%E3%80%90%E5%BF%85%E8%AF%BB%E3%80%91%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#q%E5%8D%87%E7%BA%A7%E5%88%B0-230-%E7%89%88%E6%9C%AC%E4%BB%A5%E4%B8%8A%E8%BD%AC%E5%8F%91%E8%A7%84%E5%88%99%E4%B8%8A%E6%96%B0%E5%A2%9E%E7%9A%84%E6%AD%A3%E5%88%99%E6%9B%BF%E6%8D%A2%E5%86%85%E5%AE%B9%E5%8A%9F%E8%83%BD%E6%80%8E%E4%B9%88%E7%94%A8)
