### ISSUE TITLE
功能请求：Bark自动复制

### ISSUE THREAD

**Issue by DazeCake** [pppscn/SmsForwarder#149]
Bark允许使用`copy`和`autoCopy`参数来实现自动复制，希望可以添加这两个参数用于正则匹配短信验证码以及一键复制，非常感谢:D

**Comment by pppscn** [comment]
已经有自动处理，但是ios版本过高就失效了
代码：app/src/main/java/com/idormy/sms/forwarder/sender/SenderBarkMsg.java  62行

### 自动复制推送失效

iOS 14.5 之后的版本因权限收紧，不能在收到推送时自动复制推送内容到剪切板。
可暂时先下拉推送或在锁屏界面左滑推送点查看即可自动复制，或点击弹出的推送复制按钮。

参见：https://day.app/2021/06/barkfaq/
