### ISSUE TITLE
红米Note9 4G无法转发短信，已经授予权限

### ISSUE THREAD

**Issue by scutdk** [pppscn/SmsForwarder#15]
手机型号是 红米Note9 4G
安卓版本是10，MIUI版本是12
已经在应用权限里面，允许读取短信和通知短信了
也允许程序后台运行了，自启动里面设置过了
bark设置测试是可以转发的

经过以上设置后，始终无法转发短信。
似乎还是权限的问题？
因为短信转发器的主界面始终是空白的。我另外一台华为手机主界面可以看到，能够正常读取到手机上的短信。

![image](https://user-images.githubusercontent.com/22823/117273111-63ed0980-ae8e-11eb-98f1-b518d8b26304.png)

![image](https://user-images.githubusercontent.com/22823/117273201-7d8e5100-ae8e-11eb-9da9-4a51cb1f5008.png)

![image](https://user-images.githubusercontent.com/22823/117274172-66039800-ae8f-11eb-9afc-f1aa4e2e7ad1.png)

**Comment by pppscn** [comment]
1、保持转发器在前台且亮屏情况下，测试一下(普通短信/验证码短信)

2、如果上面可行，应该是进程被杀了，找找电源相关或进程清理设置

3、如果上面不行，可能是监听不到短信广播，找其他app试试吧，例如：tasker

**Comment by op-cell** [comment]
我也有一样的问题
手机型号是 红米Note9 Pro 5G 
安卓版本是12，MIUI版本是13
已经在应用权限里面，允许读取短信和通知短信了
也允许程序后台运行了，自启动里面设置过了
bark设置测试是可以转发的
