### ISSUE TITLE
每次推送都会出现多条重复消息

### ISSUE THREAD

**Issue by wudongdefeng** [pppscn/SmsForwarder#150]
![Screenshot_20220425_115616](https://user-images.githubusercontent.com/32961310/165018452-eb685c19-a18d-431d-9f48-1170188d87fd.jpg)
bug见截图

**Comment by wudongdefeng** [comment]
已解决

**Comment by lcy1364** [comment]
我也遇到了 请问如何解决的？

**Comment by lcy1364** [comment]
最后强行停止一下smsF就好了，排查了半天别的组件的问题
