### ISSUE TITLE
关于通过短信转发时“仅在无网络时启用”的一个问题。

### ISSUE THREAD

**Issue by FreeWillDeveloper** [pppscn/SmsForwarder#154]
在连接路由器正常但是网络运营商不正常时无法由通过邮件转发换为通过短信转发。
在上面的问题场景里邮件发送会在一段时间后显示“timeout -1”，但是短信发送显示“当前网络状态：2”
不知道这个网络有无是通过什么检测的？只是检测安卓端无线网络和数据网络的开关吗？
是否可以在检测网络连接时通过类似ping的方式来检测是否是真连接？
或者在短信转发通道设置中，添加一开关为“当发送超时时启用”，这样在没有网络时也可以通过短信转发。

**Comment by pppscn** [comment]
1、当前只判断是否连上移动网络或Wifi，没有增加

2、后面考虑加入发送通道组概念，即一个转发规则可以设置一个通道组（内含2个以上通道），可以设置：串行(成功即返回)或并行

**Comment by pppscn** [comment]
v3.0.0 先加上 ping 223.5.5.5 来判断是否真的有网络，通道组的这个延后再说

**Comment by FreeWillDeveloper** [comment]
感谢回复，期待新版本。

**Comment by Saxon-Sun** [comment]
> v3.0.0 先加上 ping 223.5.5.5 来判断是否真的有网络，通道组的这个延后再说

问下这个ping判断有无网络添加了吗？

**Comment by pppscn** [comment]
> > v3.0.0 先加上 ping 223.5.5.5 来判断是否真的有网络，通道组的这个延后再说
> 
> 问下这个ping判断有无网络添加了吗？

看上去已经有了

https://github.com/pppscn/SmsForwarder/blob/main/app/src/main/java/com/idormy/sms/forwarder/utils/sender/SmsUtils.kt

```kotlin
//仅当无网络时启用 && 判断是否真实有网络
if (setting.onlyNoNetwork && NetworkUtils.isHaveInternet() && NetworkUtils.isAvailableByPing()) {
    SendUtils.updateLogs(logId, 0, getString(R.string.OnlyNoNetwork))
    SendUtils.senderLogic(0, msgInfo, rule, senderIndex, msgId)
    return
}
```
