### ISSUE TITLE
主动请求改造建议

### ISSUE THREAD

**Issue by HaujetZhao** [pppscn/SmsForwarder#155]
使用邮箱下达命令，定时检查邮件收件箱，如 5min 检查一次。

在软件上登陆某邮箱，定时检查该邮箱的收件箱，当收到指定命令的邮箱时，执行一些命令，如：

查短信：
```
标题：查询
```

发短信：
```
标题：发送
内容：
10010
查询余量
```
> 内容中第一行表示收件人，第二行表示内容
> 
> 标题没有指定卡槽，则使用默认卡槽
> 
> 标题可以用 `发送 2` 这样的形式指定第 2 卡槽发送信息
> 
> 如果发送完成，推送一个通知。

使用邮箱，是免外部 API 设置最佳的实践。

**Comment by pppscn** [comment]
之前考虑过这个方案，在安全性方面还没考虑好怎么弄，3.0.0 只会留下 http server 的api接口

**Comment by pppscn** [comment]
暂不考虑，无法实时交互，不满足未来功能规划
