### ISSUE TITLE
oppo手机没反应

### ISSUE THREAD

**Issue by 1273082756** [pppscn/SmsForwarder#156]
oppo手机没反应, 设置好通道和sim1 sim2后, 没反应, 转发日志也没内容, 但是点测试是能收到消息的

**Comment by 1273082756** [comment]
版本是2.4.4, 机型是oppo r17

**Comment by pppscn** [comment]
先按wiki的常见问题排查一遍，[SmsForwarder v2.4.3](https://github.com/pppscn/SmsForwarder/releases/tag/v2.4.3) 开始，已经针对优化：兼容OV系手机短信广播（可以不用在通过APP通知转发了）

**Comment by kebukeYi** [comment]
'[SmsForwarder v2.4.3]开始，已经针对优化：兼容OV系手机短信广播（可以不用在通过APP通知转发了）'  这个回答是我昨天遇到的问题吗?
问题描述 'oppo 的系统在 选择 短信方式转发时, 发送方的手机还会弹窗 询问是否发送短信; 这还想着 短信来了, 自动化转发, 到头来还得手动确认, 真是无语....'  昨天我下载的软件是 最新版本. 也设置 手机短信广播了, 但是在转发短信时, 依然有弹窗提示 是否发送短信;
