### ISSUE TITLE
手机黑屏状态下好像不能自动转发，解锁后可以。

### ISSUE THREAD

**Issue by ihih2g** [pppscn/SmsForwarder#157]

**Comment by ihih2g** [comment]
自启动管理弄成手动管理：允许自启动、允许关联启动、允许后台运行,修改后好像可以了

**Comment by pppscn** [comment]
https://github.com/pppscn/SmsForwarder/wiki/%E3%80%90%E5%BF%85%E8%AF%BB%E3%80%91%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by introspection3** [comment]
> 自启动管理弄成手动管理：允许自启动、允许关联启动、允许后台运行,修改后好像可以了

你好,设置之后还是不行,可能是啥情况
