### ISSUE TITLE
谷歌邮箱发送者失败

### ISSUE THREAD

**Issue by longbinzhao** [pppscn/SmsForwarder#158]
服务商选择gmail，会导致失败，只能选择其它邮箱，填写完整邮箱地址才可以。

相同版本的离线导出功能，无法在另一手机导入。
版本2.4.4

**Comment by pppscn** [comment]
贴一下具体的报错信息

**Comment by pppscn** [comment]
v3.0.0 已进入内测阶段，敬请期待，或加QQ群参与内测

**Comment by sorrybeman** [comment]
Gmail的密码需要重新生成一个应用使用的密码 


https://stackoverflow.com/questions/72577189/gmail-smtp-server-stopped-working-as-it-no-longer-support-less-secure-apps
