### ISSUE TITLE
轉發到telegram bug

### ISSUE THREAD

**Issue by LSOIVNE** [pppscn/SmsForwarder#16]
![20210515_172135](https://user-images.githubusercontent.com/30148130/118355429-92f82f00-b5a2-11eb-82ac-e6ff86489501.jpg)

短信裡面包含#的話有機率被當成標籤而出錯，建議在轉發到telegram把#過濾/替換掉。

**Comment by pppscn** [comment]
转发telegram时将 # 替换为 井，避免被当作标签

https://github.com/pppscn/SmsForwarder/commit/3de9471c2e43bf68d9853e7f4b4c600cffa8fd17

**Comment by longbinzhao** [comment]
这样

> 转发telegram时将 # 替换为 井，避免被当作标签
> 
> [3de9471](https://github.com/pppscn/SmsForwarder/commit/3de9471c2e43bf68d9853e7f4b4c600cffa8fd17)

这样解决不了的，因为<会被当作标签开始，<井>不是允许的标签，建议将<处理掉
