### ISSUE TITLE
[Feature Request] 希望能增加自动开启网络的功能

### ISSUE THREAD

**Issue by zxkmm** [pppscn/SmsForwarder#161]
例如：收到短信，检测Wi-Fi连接，如果没有连接，打开Wi-Fi，如果没有连接，打开蜂窝数据。
感谢开发者！

**Comment by pppscn** [comment]
什么场景下 这两个网络连接 会自动关闭？

如果是手动关闭的，为什么需要自动打开？

**Comment by zxkmm** [comment]
@pppscn 亲爱的开发者您好，我个人的需求是，保证验证码转发的成功率。例如一台设备在家，不知道有没有开网络，但是又急切需要短信验证码的场景。

**Comment by pppscn** [comment]
问题是 例如wifi的wan口实际已经断了，你已经手动关闭wifi，这时再自动打开WiFi，有可能就死在那里了

**Comment by zxkmm** [comment]
@pppscn 谢谢您的解释，您的意思是，例如Wi-Fi没有网络或者没有Wi-Fi的情况下，会影响转发流程吗？我不是很懂安卓，不太清楚这个场景能不能较好地规避，例如连上wifi信号以后20s后还没有网络，就执行打开蜂窝网络，如果20s后还是没有网络就放弃。不过我的需求确实比较模糊，我会仔细整理一下逻辑。谢谢您！
