### ISSUE TITLE
3.0+版本短信转发，无网络时转发功能无效。

### ISSUE THREAD

**Issue by mymine** [pppscn/SmsForwarder#163]
3.0+版本短信转发，无网络时转发功能无效。有网络也转发短信。

**Comment by pppscn** [comment]
https://github.com/pppscn/SmsForwarder/blob/main/app/src/main/java/com/idormy/sms/forwarder/utils/sender/SmsUtils.kt

```
            //仅当无网络时启用 && 判断是否真实有网络
            if (setting.onlyNoNetwork == true && NetworkUtils.isHaveInternet() && NetworkUtils.isAvailableByPing()) {
                return
            }
```

3.0 新增了 ping 阿里dns，能ping的通才算有网络，再观察看看

**Comment by mymine** [comment]
手机问题，只能ping通本地和路由。
