### ISSUE TITLE
发现两个BUG

### ISSUE THREAD

**Issue by spysir** [pppscn/SmsForwarder#164]
1.充电状态：充电器显示未知，只有在充满电的情况下才显示AC
2.自动控制-客户端：远程查话簿显示空白(联系人权限已开)，其它远程查短信，远程发短信，远程查通话均正常(远程查电量充电器有时候显示未知）
![ac-bug](https://user-images.githubusercontent.com/59646715/173210499-c144c217-7557-42b8-af2d-f4f5a97b279d.jpg)
![huabuBUG](https://user-images.githubusercontent.com/59646715/173210502-825ed0ab-c143-4cac-a073-7688085c3dd0.jpg)

**Comment by pppscn** [comment]
这个比较难搞，我没有OV系手机没法测试，等其他群友测试反馈一下

**Comment by mymine** [comment]
> 

远程查短信，能增加卡位显示吗

**Comment by mymine** [comment]
> 这个比较难搞，我没有OV系手机没法测试，等其他群友测试反馈一下

远程查短信，能增加卡位显示吗

**Comment by pppscn** [comment]
sim作为查询条件还是 标识？

**Comment by mymine** [comment]
> sim作为查询条件还是 标识？

都有最好。

**Comment by dysf888** [comment]
> sim作为查询条件还是 标识？
主动控制有考虑做成web么,这样可以照顾到ios且 主力机不需要下多余app

**Comment by pppscn** [comment]
永远不会有web端，具体按原因看 wiki 第一条

https://github.com/pppscn/SmsForwarder/wiki/%E3%80%90%E5%BF%85%E8%AF%BB%E3%80%91%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

>

**Comment by dysf888** [comment]
> 永远不会有web端，具体按原因看 wiki 第一条
> 
> https://github.com/pppscn/SmsForwarder/wiki/%E3%80%90%E5%BF%85%E8%AF%BB%E3%80%91%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
> 
> >

好多谢谢 ,已star ,多谢开发如此便捷的app

**Comment by mymine** [comment]
> > sim作为查询条件还是 标识？
> > 主动控制有考虑做成web么,这样可以照顾到ios且 主力机不需要下多余app

自己写个自用不就好了。

**Comment by pppscn** [comment]
升级到 3.0.4 试试，今晚发版

**Comment by wainyang** [comment]
请问这个web端在哪里下载，我没找到，可否发我一份，谢谢🙏
wainyang@hotmail.com

**Comment by mymine** [comment]
> 请问这个web端在哪里下载，我没找到，可否发我一份，谢谢🙏 [wainyang@hotmail.com](mailto:wainyang@hotmail.com)

没有，自己写
