### ISSUE TITLE
3.0+版本 小米8UD 转发通话记录获取不到卡槽信息

### ISSUE THREAD

**Issue by LemonZuo** [pppscn/SmsForwarder#165]
已经给给应用开放所有权限
![e925426ab51811033db20877a4d0ebce](https://user-images.githubusercontent.com/31127261/173220434-30a398db-e6d6-430c-907c-0633c1a108d6.jpg)
应用也已经设定不被杀掉
<img width="188" alt="Snipaste_2022-06-12_14-35-50" src="https://user-images.githubusercontent.com/31127261/173220648-a3050873-1b7e-4bbd-b7ea-97a1c6fcf8be.png">
转发模板设置
![e041f53714c76cb70db1a4686f64a662](https://user-images.githubusercontent.com/31127261/173220718-fd0d4454-930c-46c8-ab97-5
![42456330d22014fd701be7e535bd96a6](https://user-images.githubusercontent.com/31127261/173220871-a7af9620-e938-4292-92c9-b21469917839.jpg)
dbce4799a2d.jpg)

企业微信实际接收到内容
<img width="640" alt="image" src="https://user-images.githubusercontent.com/31127261/173220770-1d1c3c47-75ba-46f7-9f79-f4721c062ebd.png">
bark实际接收到内容
<img width="346" alt="image" src="https://user-images.githubusercontent.com/31127261/173220853-359acc8b-68e5-4c56-bcdb-1a57038f58fb.png">

**Comment by pppscn** [comment]
通用设置  卡槽备注那里  刷新 按钮点一下 能获取到手机号吗？  Android 4.x ？

**Comment by LemonZuo** [comment]
> 通用设置 卡槽备注那里 刷新 按钮点一下 能获取到手机号吗？ Android 4.x ？

> 可以正常获取到手机号码
<img width="374" alt="image" src="https://user-images.githubusercontent.com/31127261/173222059-85e8dc3f-5804-42e3-b4b8-a4cae5d59f4d.png">

> 使用的是MIUI 12 对应的是 Android 10
<img width="359" alt="image" src="https://user-images.githubusercontent.com/31127261/173222134-9ff82f02-ba1b-4b90-b217-f86eb3205208.png">
<img width="354" alt="image" src="https://user-images.githubusercontent.com/31127261/173222156-5c354382-c81e-4f68-b93c-64fa1e3a0c5f.png">

**Comment by pppscn** [comment]
修复：v3.0.2来电转发卡槽信息获取失败
https://github.com/pppscn/SmsForwarder/commit/51e845dceac46cd4bb649cc3f069d18dee94f819

bug出现原因，被转换2次
https://github.com/pppscn/SmsForwarder/commit/e941fcf62bbc7d00b7ad8d0a5e6a2f4eccbc55e8
