### ISSUE TITLE
frpc动态库下载失败

### ISSUE THREAD

**Issue by Mosney** [pppscn/SmsForwarder#167]
失败后的这个提示也挺奇怪的
> 应用下载失败，是否考虑切换到酷安下载？

酷安的apk也不包含这个lib啊

**Comment by pppscn** [comment]
你的版本号多少？现在还不能下载吗

这个是复用在线升级的代码，所以失败之后的提示有问题，下一次改掉

**Comment by Mosney** [comment]
> 你的版本号多少？现在还不能下载吗
> 

现在可以了，版本号是3.0.4 

莫非是之前刚发布新版配套运行库还没配置好🤣
