### ISSUE TITLE
Bark 时效性通知选择保存后未生效

### ISSUE THREAD

**Issue by xream** [pppscn/SmsForwarder#168]
![image](https://user-images.githubusercontent.com/1210282/174557894-f611b15b-ecb8-4a80-8004-086d212edcdb.png)

![image](https://user-images.githubusercontent.com/1210282/174557610-7bb0f07e-39b0-44f0-a154-bca24179a45e.png)

![image](https://user-images.githubusercontent.com/1210282/174557636-40117e31-71fe-478d-9852-8061f746eedd.png)

**Comment by pppscn** [comment]
"未生效" 是指再次进入编辑 还是修改前的  还是说实际请求接口的时候 值没变化？

**Comment by pppscn** [comment]
暂时无法重现bug，后面有遇到时再说
