### ISSUE TITLE
Bark Server HTTP Basic Authentication Support

### ISSUE THREAD

**Issue by zfmy** [pppscn/SmsForwarder#170]
私有化部署bark server，加入了http basic auth
![1](https://user-images.githubusercontent.com/7541239/174959494-478673cb-bed8-4919-a2ad-efa2e1361667.png)

**Comment by pppscn** [comment]
已经提交了  23:30 过后下载每夜构建版试试

https://github.com/pppscn/SmsForwarder/actions/workflows/Nightly_Build.yml

**Comment by zfmy** [comment]
`请求失败：HTTP 418`，用户名和密码依旧没有传递过去？

**Comment by pppscn** [comment]
不应该是 401 ？ 418 是个啥

**Comment by zfmy** [comment]
418差不多是拒绝服务的意思吧！我用postman试过，用户名密码不正确就是418，怀疑后面发起请求时用户名密码没有带上
