### ISSUE TITLE
希望发送通道支持chanify

### ISSUE THREAD

**Issue by venpong** [pppscn/SmsForwarder#171]
一个类似Bark的IOS端推送软件，但是查看消息记录比Bark方便很多。
我使用webhook调用异常，但是我用postman调用是可以成功的。
官网:https://www.chanify.net
开源地址：https://github.com/chanify/chanify

**Comment by pppscn** [comment]
“使用webhook调用异常”  怎么个异常法？报什么错误

**Comment by venpong** [comment]
跟隔壁issue:teams转发的那个截图的异常一样，也是报请求失败:okhttpxxx,我晚上下班回去了可以再贴截图上来

**Comment by vicdorke** [comment]
我不是报请求失败，是直接软件卡死

**Comment by Panintosh** [comment]
我不是报请求失败，是直接软件卡死

**Comment by venpong** [comment]
![3ac1ebc2ff07d041701d58fc6395000](https://user-images.githubusercontent.com/14030911/175307216-1190aabf-7b5e-4381-96d4-e8a6ca3a31c4.png)
![123109c721337a4d1f5a2f91488cdaa](https://user-images.githubusercontent.com/14030911/175307295-a3109d70-7a2f-4387-99eb-eb5f4f4072d2.jpg)
![c53f39794f37a1a40ac822adfb4ef83](https://user-images.githubusercontent.com/14030911/175307336-8a3bf4df-6cfd-4c20-b625-d86453d4b4d5.jpg)
postman请求能成功,webhook请求就失败

**Comment by pppscn** [comment]
{"text":"[msg]"}

**Comment by venpong** [comment]
可以了，谢谢。希望后续可以在发送通道里面直接支持chanify。

**Comment by pppscn** [comment]
webhook能支持 就不单独加了  累计3或4个时加一个  不然菜单孤零零的一个  强迫症受不了
