### ISSUE TITLE
发现一个bug，tg机器人转发设置带密码的代理后无法正常工作

### ISSUE THREAD

**Issue by Marionic0723** [pppscn/SmsForwarder#172]
如题。我在我家宽带的公网上开放了S5端口，直通外网，手机不方便装翻墙，希望在自家网络外的环境下也能正常发送TG消息。
而暴露在公网会被人滥用，因此还设置了密码，但是程序无法使用，点击发送渠道测试会出现null，在转发规则里测试会直接闪退。版本是3.0.4。早期版本貌似也不能工作，但TG本身可以使用这个代理，说明代理无问题。
![Screenshot_2022-06-23-21-02-59-57](https://user-images.githubusercontent.com/76898556/175305591-d9f31ebc-5f33-4cca-abaf-440f3aec4316.png)

![image](https://user-images.githubusercontent.com/76898556/175305789-d471b1d1-3a62-436a-85d1-cee125408476.png)

**Comment by pppscn** [comment]
已经提交了 23:30 过后下载每夜构建版试试
https://github.com/pppscn/SmsForwarder/actions/workflows/Nightly_Build.yml

或者 下载附件中的apk
[SmsForwarder_release_3.0.4_100042_20220624_universal.zip](https://github.com/pppscn/SmsForwarder/files/8977132/SmsForwarder_release_3.0.4_100042_20220624_universal.zip)
[SmsForwarder_release_3.0.4_200042_20220624_armeabi-v7a.zip](https://github.com/pppscn/SmsForwarder/files/8977134/SmsForwarder_release_3.0.4_200042_20220624_armeabi-v7a.zip)
[SmsForwarder_release_3.0.4_300042_20220624_arm64-v8a.zip](https://github.com/pppscn/SmsForwarder/files/8977136/SmsForwarder_release_3.0.4_300042_20220624_arm64-v8a.zip)

**Comment by Marionic0723** [comment]
> 已经提交了 23:30 过后下载每夜构建版试试 https://github.com/pppscn/SmsForwarder/actions/workflows/Nightly_Build.yml
> 
> 或者 下载附件中的apk [SmsForwarder_release_3.0.4_100042_20220624_universal.zip](https://github.com/pppscn/SmsForwarder/files/8977132/SmsForwarder_release_3.0.4_100042_20220624_universal.zip) [SmsForwarder_release_3.0.4_200042_20220624_armeabi-v7a.zip](https://github.com/pppscn/SmsForwarder/files/8977134/SmsForwarder_release_3.0.4_200042_20220624_armeabi-v7a.zip) [SmsForwarder_release_3.0.4_300042_20220624_arm64-v8a.zip](https://github.com/pppscn/SmsForwarder/files/8977136/SmsForwarder_release_3.0.4_300042_20220624_arm64-v8a.zip)

啊哦 我刚刚看见。我又试了下，服务器地址填写公网IP和内网IP都可以成功，但是填写域名不行，依然提示null。本地DNS解析正常。域名服务商是dynv6.com ，免费的三级域名。

**Comment by pppscn** [comment]
已经提交了 23:30 过后下载每夜构建版试试
https://github.com/pppscn/SmsForwarder/actions/workflows/Nightly_Build.yml

或者 下载附件中的apk
[SmsForwarder_release_3.0.4_100042_20220627_universal.zip](https://github.com/pppscn/SmsForwarder/files/8990695/SmsForwarder_release_3.0.4_100042_20220627_universal.zip)
[SmsForwarder_release_3.0.4_200042_20220627_armeabi-v7a.zip](https://github.com/pppscn/SmsForwarder/files/8990707/SmsForwarder_release_3.0.4_200042_20220627_armeabi-v7a.zip)
[SmsForwarder_release_3.0.4_300042_20220627_arm64-v8a.zip](https://github.com/pppscn/SmsForwarder/files/8990722/SmsForwarder_release_3.0.4_300042_20220627_arm64-v8a.zip)

**Comment by Marionic0723** [comment]
完美解决，没问题
