### ISSUE TITLE
功能请求，主动控制加入发送USSD代码功能

### ISSUE THREAD

**Issue by Mosney** [pppscn/SmsForwarder#173]
USSD可以方便的控制呼叫转移等功能
https://zh.wikipedia.org/zh-cn/非结构化补充服务数据

现有实现：
https://github.com/telegram-sms/telegram-sms

**Comment by pppscn** [comment]
**综合考虑，不加入该功能，USSD指令具有一定的危险性！**

避免被其他人举报为恶意软件 
_（我怀疑现在就有人举报了，毕竟断人财路）_

尽管我已经快写完了，不想授人以柄，还是删了代码吧

![微信截图_20220627111702](https://user-images.githubusercontent.com/5105854/175853590-8fa507ea-a8f3-4325-a574-7a8acd64047e.png)
