### ISSUE TITLE
主动控制支持查询卡槽信息

### ISSUE THREAD

**Issue by xingxichen** [pppscn/SmsForwarder#174]
主动控制支持查询卡槽信息（号码和备注）

**Comment by pppscn** [comment]
详见 wiki 文档 2.0 远程查配置

https://github.com/pppscn/SmsForwarder/wiki/%E9%99%84%E5%BD%952%EF%BC%9A%E4%B8%BB%E5%8A%A8%E8%AF%B7%E6%B1%82(%E8%BF%9C%E7%A8%8B%E6%8E%A7%E5%88%B6)#20-%E8%BF%9C%E7%A8%8B%E6%9F%A5%E9%85%8D%E7%BD%AE

**Comment by xingxichen** [comment]
![image](https://user-images.githubusercontent.com/50514349/175802370-90780476-6232-4078-b860-f2605da5830f.png)
最新版的好像没有卡槽信息

**Comment by pppscn** [comment]
/config/query 接口啊，而且你下每夜构建版或自己编译

**Comment by xingxichen** [comment]
看错接口了😂
