### ISSUE TITLE
功能请求，webhook 支持base auth

### ISSUE THREAD

**Issue by m986883511** [pppscn/SmsForwarder#175]

**Comment by pppscn** [comment]
已经提交了 23:30 过后下载每夜构建版试试
https://github.com/pppscn/SmsForwarder/actions/workflows/Nightly_Build.yml

或者 下载附件中的apk
[SmsForwarder_release_3.0.4_100042_20220630_universal.zip](https://github.com/pppscn/SmsForwarder/files/9016107/SmsForwarder_release_3.0.4_100042_20220630_universal.zip)
[SmsForwarder_release_3.0.4_200042_20220630_armeabi-v7a.zip](https://github.com/pppscn/SmsForwarder/files/9016108/SmsForwarder_release_3.0.4_200042_20220630_armeabi-v7a.zip)
[SmsForwarder_release_3.0.4_300042_20220630_arm64-v8a.zip](https://github.com/pppscn/SmsForwarder/files/9016110/SmsForwarder_release_3.0.4_300042_20220630_arm64-v8a.zip)

**Comment by m986883511** [comment]
非常感谢
