### ISSUE TITLE
功能请求　－　短信基站发送时间

### ISSUE THREAD

**Issue by musicyin** [pppscn/SmsForwarder#176]
因为一些网站，需要收发短信验证码，但验证码上没有唯一码，很难识别哪个验证码是属于哪个
而安卓短信功能上，有短讯接收时间（客户端接收到的时间timestamp），还有一个是短讯发送的时间(基站发送短讯的时间timestamp 后面尾数都是000的
希望可以增加这功能

**Comment by pppscn** [comment]
暂不考虑，普通的备用机用途用不到这么精确的时间，当前以收到短信广播的时间为准
