### ISSUE TITLE
请问v3版是没有失败重试功能了吗

### ISSUE THREAD

**Issue by Editst** [pppscn/SmsForwarder#177]
请问v3版是没有失败重试功能了吗？升级后找了一下没看到

**Comment by pppscn** [comment]
![Uploading 微信图片_20220627155451.jpg…]()

**Comment by pppscn** [comment]
![微信图片_20220627155451](https://user-images.githubusercontent.com/5105854/175889009-6225c68f-aa0c-4f87-8752-7eb0ca6aad99.jpg)
