### ISSUE TITLE
遇到一个神奇问题，可以转发正常的短信，但是无法转发运营商发送的验证码之类的短信

### ISSUE THREAD

**Issue by beimengyeyu** [pppscn/SmsForwarder#179]
红米note8 pro

**Comment by beimengyeyu** [comment]
没有任何报错日志

**Comment by pppscn** [comment]
https://github.com/pppscn/SmsForwarder/wiki/%E3%80%90%E5%BF%85%E8%AF%BB%E3%80%91%E4%BD%BF%E7%94%A8%E6%B5%81%E7%A8%8B#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9

认真看看wiki

**Comment by pppscn** [comment]
https://github.com/pppscn/SmsForwarder/wiki/%E3%80%90%E5%BF%85%E8%AF%BB%E3%80%91%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
