### ISSUE TITLE
能否加个低电量提醒功能?

### ISSUE THREAD

**Issue by wallpass** [pppscn/SmsForwarder#18]
能否添加一个低电量提醒，比如电量下降到了10%以下，自动发动信息给远程端进行提醒。

**Comment by wallpass** [comment]
主要是有时候突然收不到验证码了，也不知道是软件被杀后台了，还是手机没电自动关机了

**Comment by tenwx** [comment]
同支持

**Comment by ktownag** [comment]
复议。也可以在短信内容后面附加当前电量

**Comment by pppscn** [comment]
下一版本发布时，会带上此功能：当到达低电量预警阈值时，调用所有发送方通知2次
![微信截图_20210927114909](https://user-images.githubusercontent.com/5105854/134842923-e67070d1-0137-47c8-887a-f1b77dd2f264.png)

敬请期待
