### ISSUE TITLE
android4.4的设备闪退

### ISSUE THREAD

**Issue by zqs125** [pppscn/SmsForwarder#180]
在android4.4的设备上安装了3.0.5版本，启动应用后闪退，无法正常使用

**Comment by pppscn** [comment]
提供一下闪退的日志  不然这issue没有任何意义
目前Android 4.4 在随身wifi上测试 没什么问题  不知道你是什么机器

**Comment by zqs125** [comment]
> 提供一下闪退的日志 不然这issue没有任何意义 目前Android 4.4 在随身wifi上测试 没什么问题 不知道你是什么机器

太好了，我就是用在随身wifi上的，怎么提取日志？

**Comment by zqs125** [comment]
> Refere

我也是随身wifi，高通410，android 4.4的系统，日志我抓取了，你看看有没有用

W/PackageManager(  853): Package com.idormy.sms.forwarder desires unavailable shared library androidx.window.extensions; ignoring!

W/PackageManager(  853): Package com.idormy.sms.forwarder desires unavailable shared library androidx.window.sidecar; ignoring!

I/ActivityManager(  853): Force stopping com.idormy.sms.forwarder appid=10034 user=-1: update pkg

W/PackageManager(  853): Unknown permission android.permission.QUERY_ALL_PACKAGES in package com.idormy.sms.forwarder

W/PackageManager(  853): Not granting permission android.permission.READ_PRIVILEGED_PHONE_STATE to package com.idormy.sms.forwarder (protectionLevel=18 flags=0x58be44)

W/PackageManager(  853): Unknown permission android.permission.MANAGE_EXTERNAL_STORAGE in package com.idormy.sms.forwarder

W/PackageManager(  853): Unknown permission android.permission.READ_PHONE_NUMBERS in package com.idormy.sms.forwarder

W/PackageManager(  853): Unknown permission android.permission.FOREGROUND_SERVICE in package com.idormy.sms.forwarder

W/PackageManager(  853): Unknown permission android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS in package com.idormy.sms.forwarder

W/PackageManager(  853): Not granting permission android.permission.BATTERY_STATS to package com.idormy.sms.forwarder (protectionLevel=18 flags=0x58be44)

W/PackageManager(  853): Not granting permission android.permission.BIND_NOTIFICATION_LISTENER_SERVICE to package com.idormy.sms.forwarder (protectionLevel=2 flags=0x58be44)

W/PackageManager(  853): Unknown permission android.permission.ACTION_NOTIFICATION_LISTENER_SETTINGS in package com.idormy.sms.forwarder

W/PackageManager(  853): Not granting permission android.permission.INSTALL_PACKAGES to package com.idormy.sms.forwarder (protectionLevel=18 flags=0x58be44)

W/PackageManager(  853): Not granting permission android.permission.READ_LOGS to package com.idormy.sms.forwarder (protectionLevel=50 flags=0x58be44)

W/PackageManager(  853): Not granting permission android.permission.MOUNT_UNMOUNT_FILESYSTEMS to package com.idormy.sms.forwarder (protectionLevel=18 flags=0x58be44)

W/PackageManager(  853): Unknown permission android.permission.REQUEST_INSTALL_PACKAGES in package com.idormy.sms.forwarder

W/PackageManager(  853): Not granting permission android.permission.MODIFY_PHONE_STATE to package com.idormy.sms.forwarder (protectionLevel=18 flags=0x58be44)

D/BackupManagerService(  853): Received broadcast Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.idormy.sms.forwarder flg=0x4000010 (has extras) }

I/ActivityManager(  853): START u0 {flg=0x10000000 cmp=com.idormy.sms.forwarder/.activity.SplashActivity} from pid 1075

I/ActivityManager(  853): Start proc com.idormy.sms.forwarder for activity com.idormy.sms.forwarder/.activity.SplashActivity: pid=10554 uid=10034 gids={50034, 3003, 1028, 1023, 1015, 3001, 3002}

E/WindowManager(  853): Starting window AppWindowToken{4213cfa8 token=Token{41a29df8 ActivityRecord{41b803a0 u0 com.idormy.sms.forwarder/.activity.SplashActivity t5}}} timed out

I/ActivityManager(  853): START u0 {flg=0x10000000 cmp=com.idormy.sms.forwarder/.activity.MainActivity} from pid 10554

E/AndroidRuntime(10554): Process: com.idormy.sms.forwarder, PID: 10554

E/AndroidRuntime(10554): 	at com.idormy.sms.forwarder.widget.GuideTipsDialog$Companion.d(GuideTipsDialog.kt:3)

E/AndroidRuntime(10554): 	at com.idormy.sms.forwarder.widget.GuideTipsDialog$Companion.c(GuideTipsDialog.kt:2)

E/AndroidRuntime(10554): 	at com.idormy.sms.forwarder.activity.MainActivity.e0(MainActivity.kt:1)

E/AndroidRuntime(10554): 	at com.idormy.sms.forwarder.activity.MainActivity.onCreate(MainActivity.kt:3)

W/ActivityManager(  853):   Force finishing activity com.idormy.sms.forwarder/.activity.MainActivity

I/WindowManager(  853): Screenshot max retries 4 of Token{41c9a360 ActivityRecord{41be70e0 u0 com.idormy.sms.forwarder/.activity.MainActivity t6 f}} appWin=Window{41c333e8 u0 Starting com.idormy.sms.forwarder} drawState=4

I/ActivityManager(  853): Process com.idormy.sms.forwarder (pid 10554) has died.

I/WindowState(  853): WIN DEATH: Window{41ed41e0 u0 com.idormy.sms.forwarder/com.idormy.sms.forwarder.activity.SplashActivity}

W/ActivityManager(  853): Scheduling restart of crashed service com.idormy.sms.forwarder/.service.ForegroundService in 1000ms

W/ActivityManager(  853): Scheduling restart of crashed service com.idormy.sms.forwarder/.service.BatteryService in 10999ms

I/ActivityManager(  853): Start proc com.idormy.sms.forwarder for service com.idormy.sms.forwarder/.service.ForegroundService: pid=10940 uid=10034 gids={50034, 3003, 1028, 1023, 1015, 3001, 3002}

E/AndroidRuntime(10940): Process: com.idormy.sms.forwarder, PID: 10940

E/AndroidRuntime(10940): java.lang.RuntimeException: Unable to start service com.idormy.sms.forwarder.service.ForegroundService@41951418 with null: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.e, parameter intent

E/AndroidRuntime(10940): 	at com.idormy.sms.forwarder.service.ForegroundService.onStartCommand(ForegroundService.kt)

I/ActivityManager(  853): Process com.idormy.sms.forwarder (pid 10940) has died.

W/ActivityManager(  853): Service crashed 2 times, stopping: ServiceRecord{41c7f3a8 u0 com.idormy.sms.forwarder/.service.ForegroundService}

W/ActivityManager(  853): Service crashed 2 times, stopping: ServiceRecord{41c42d50 u0 com.idormy.sms.forwarder/.service.BatteryService}

I/ActivityManager(  853): START u0 {flg=0x10000000 cmp=com.idormy.sms.forwarder/.activity.SplashActivity} from pid 1075

I/ActivityManager(  853): Start proc com.idormy.sms.forwarder for activity com.idormy.sms.forwarder/.activity.SplashActivity: pid=14802 uid=10034 gids={50034, 3003, 1028, 1023, 1015, 3001, 3002}

I/ActivityManager(  853): START u0 {flg=0x10000000 cmp=com.idormy.sms.forwarder/.activity.MainActivity} from pid 14802

E/AndroidRuntime(14802): Process: com.idormy.sms.forwarder, PID: 14802

E/AndroidRuntime(14802): 	at com.idormy.sms.forwarder.widget.GuideTipsDialog$Companion.d(GuideTipsDialog.kt:3)

E/AndroidRuntime(14802): 	at com.idormy.sms.forwarder.widget.GuideTipsDialog$Companion.c(GuideTipsDialog.kt:2)

E/AndroidRuntime(14802): 	at com.idormy.sms.forwarder.activity.MainActivity.e0(MainActivity.kt:1)

E/AndroidRuntime(14802): 	at com.idormy.sms.forwarder.activity.MainActivity.onCreate(MainActivity.kt:3)

W/ActivityManager(  853):   Force finishing activity com.idormy.sms.forwarder/.activity.MainActivity

I/WindowManager(  853): Screenshot max retries 4 of Token{41c95680 ActivityRecord{41bd10c0 u0 com.idormy.sms.forwarder/.activity.MainActivity t9 f}} appWin=Window{41c6ba10 u0 Starting com.idormy.sms.forwarder} drawState=4

I/ActivityManager(  853): Process com.idormy.sms.forwarder (pid 14802) has died.

I/WindowState(  853): WIN DEATH: Window{41c2d040 u0 com.idormy.sms.forwarder/com.idormy.sms.forwarder.activity.SplashActivity}

W/ActivityManager(  853): Scheduling restart of crashed service com.idormy.sms.forwarder/.service.ForegroundService in 1000ms

W/ActivityManager(  853): Scheduling restart of crashed service com.idormy.sms.forwarder/.service.BatteryService in 10998ms

I/ActivityManager(  853): Start proc com.idormy.sms.forwarder for service com.idormy.sms.forwarder/.service.ForegroundService: pid=14909 uid=10034 gids={50034, 3003, 1028, 1023, 1015, 3001, 3002}

E/AndroidRuntime(14909): Process: com.idormy.sms.forwarder, PID: 14909

E/AndroidRuntime(14909): java.lang.RuntimeException: Unable to start service com.idormy.sms.forwarder.service.ForegroundService@41c37c30 with null: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.e, parameter intent

E/AndroidRuntime(14909): 	at com.idormy.sms.forwarder.service.ForegroundService.onStartCommand(ForegroundService.kt)

I/ActivityManager(  853): Process com.idormy.sms.forwarder (pid 14909) has died.

W/ActivityManager(  853): Service crashed 2 times, stopping: ServiceRecord{4219fc28 u0 com.idormy.sms.forwarder/.service.ForegroundService}

W/ActivityManager(  853): Service crashed 2 times, stopping: ServiceRecord{4219f698 u0 com.idormy.sms.forwarder/.service.BatteryService}

I/Timeline( 1075): Timeline: Activity_launch_request id:com.idormy.sms.forwarder time:10609616

I/ActivityManager(  853): START u0 {flg=0x10000000 cmp=com.idormy.sms.forwarder/.activity.SplashActivity} from pid 1075

I/ActivityManager(  853): Start proc com.idormy.sms.forwarder for activity com.idormy.sms.forwarder/.activity.SplashActivity: pid=17493 uid=10034 gids={50034, 3003, 1028, 1023, 1015, 3001, 3002}

D/ActivityThread(17493): handleBindApplication:com.idormy.sms.forwarder

I/dalvikvm(17493): Could not find method android.app.Application.startForegroundService, referenced from method com.idormy.sms.forwarder.App.onCreate

I/MultiDex(17493): MultiDexExtractor(/data/app/com.idormy.sms.forwarder-1.apk, /data/data/com.idormy.sms.forwarder/code_cache/secondary-dexes)

I/MultiDex(17493): Blocking on lock /data/data/com.idormy.sms.forwarder/code_cache/secondary-dexes/MultiDex.lock

I/MultiDex(17493): /data/data/com.idormy.sms.forwarder/code_cache/secondary-dexes/MultiDex.lock locked

I/MultiDex(17493): MultiDexExtractor.load(/data/app/com.idormy.sms.forwarder-1.apk, false, )

W/ContextImpl(17493): Failed to ensure directory: /storage/sdcard1/Android/data/com.idormy.sms.forwarder/files

W/ContextImpl(17493): Failed to ensure directory: /storage/sdcard1/Android/data/com.idormy.sms.forwarder/cache

W/ContextImpl(17493): Failed to ensure directory: /storage/sdcard1/Android/data/com.idormy.sms.forwarder/files

W/ContextImpl(17493): Failed to ensure directory: /storage/sdcard1/Android/data/com.idormy.sms.forwarder/cache

W/ContextImpl(17493): Failed to ensure directory: /storage/sdcard1/Android/data/com.idormy.sms.forwarder/cache

D/dalvikvm(17493): Trying to load lib /data/app-lib/com.idormy.sms.forwarder-1/libmmkv.so 0x4194d400

D/dalvikvm(17493): Added shared lib /data/app-lib/com.idormy.sms.forwarder-1/libmmkv.so 0x4194d400

I/MMKV    (17493): <MMKV.cpp:207::initializeMMKV> root dir: /data/data/com.idormy.sms.forwarder/files/mmkv

I/MMKV    (17493): <MemoryFile.cpp:97::open> open fd[0x32], /data/data/com.idormy.sms.forwarder/files/mmkv/History

I/MMKV    (17493): <MemoryFile.cpp:97::open> open fd[0x33], /data/data/com.idormy.sms.forwarder/files/mmkv/History.crc

I/MMKV    (17493): <MemoryFile.cpp:97::open> open fd[0x34], /data/data/com.idormy.sms.forwarder/files/mmkv/mmkv.default

I/MMKV    (17493): <MemoryFile.cpp:97::open> open fd[0x35], /data/data/com.idormy.sms.forwarder/files/mmkv/mmkv.default.crc

E/Tinker.LoadLibrary(17493): installNativeLibraryPath, folder /data/data/com.idormy.sms.forwarder/files/libs is illegal

D/dalvikvm(17493): Trying to load lib /data/app-lib/com.idormy.sms.forwarder-1/libumeng-spy.so 0x4194d400

D/dalvikvm(17493): Added shared lib /data/app-lib/com.idormy.sms.forwarder-1/libumeng-spy.so 0x4194d400

D/dalvikvm(17493): No JNI_OnLoad found in /data/app-lib/com.idormy.sms.forwarder-1/libumeng-spy.so 0x4194d400, skipping init

W/AndroidAutoSize(17493): com.idormy.sms.forwarder.activity.SplashActivity canceled the adaptation!

W/AndroidAutoSize(17493): com.idormy.sms.forwarder.activity.SplashActivity canceled the adaptation!

E/dalvikvm(17493): Could not find class 'android.app.NotificationChannel', referenced from method com.idormy.sms.forwarder.service.ForegroundService.f

I/ActivityManager(  853): Displayed com.idormy.sms.forwarder/.activity.SplashActivity: +3s168ms

I/Timeline(  853): Timeline: Activity_windows_visible id: ActivityRecord{41bd10c0 u0 com.idormy.sms.forwarder/.activity.SplashActivity t11} time:10612798

I/Timeline(17493): Timeline: Activity_launch_request id:com.idormy.sms.forwarder time:10613217

I/ActivityManager(  853): START u0 {flg=0x10000000 cmp=com.idormy.sms.forwarder/.activity.MainActivity} from pid 17493

I/dalvikvm(17493): Could not find method android.app.ActivityManager.getAppTasks, referenced from method com.idormy.sms.forwarder.activity.MainActivity.onCreate

D/AndroidAutoSize(17493): com.idormy.sms.forwarder.activity.MainActivity used the global configuration.

D/AndroidAutoSize(17493): The com.idormy.sms.forwarder.activity.MainActivity has been adapted! 

I/dalvikvm(17493): Could not find method android.app.ActivityManager.getAppTasks, referenced from method com.idormy.sms.forwarder.fragment.SettingsFragment.r1

I/dalvikvm(17493): Could not find method java.util.HashMap.getOrDefault, referenced from method com.idormy.sms.forwarder.fragment.SettingsFragment$hashMap$1.getOrDefault

I/dalvikvm(17493): Could not find method java.util.HashMap.remove, referenced from method com.idormy.sms.forwarder.fragment.SettingsFragment$hashMap$1.remove

E/AndroidRuntime(17493): Process: com.idormy.sms.forwarder, PID: 17493

E/AndroidRuntime(17493): 	at com.idormy.sms.forwarder.widget.GuideTipsDialog$Companion.d(GuideTipsDialog.kt:3)

E/AndroidRuntime(17493): 	at com.idormy.sms.forwarder.widget.GuideTipsDialog$Companion.c(GuideTipsDialog.kt:2)

E/AndroidRuntime(17493): 	at com.idormy.sms.forwarder.activity.MainActivity.e0(MainActivity.kt:1)

E/AndroidRuntime(17493): 	at com.idormy.sms.forwarder.activity.MainActivity.onCreate(MainActivity.kt:3)

W/ActivityManager(  853):   Force finishing activity com.idormy.sms.forwarder/.activity.MainActivity

I/WindowManager(  853): Screenshot max retries 4 of Token{41e30700 ActivityRecord{41e32248 u0 com.idormy.sms.forwarder/.activity.MainActivity t12 f}} appWin=Window{41c0c070 u0 Starting com.idormy.sms.forwarder} drawState=4

I/ActivityManager(  853): Process com.idormy.sms.forwarder (pid 17493) has died.

W/ActivityManager(  853): Scheduling restart of crashed service com.idormy.sms.forwarder/.service.BatteryService in 1000ms

I/WindowState(  853): WIN DEATH: Window{41f594a0 u0 com.idormy.sms.forwarder/com.idormy.sms.forwarder.activity.SplashActivity}

W/ActivityManager(  853): Scheduling restart of crashed service com.idormy.sms.forwarder/.service.ForegroundService in 10999ms

I/ActivityManager(  853): Start proc com.idormy.sms.forwarder for service com.idormy.sms.forwarder/.service.BatteryService: pid=17589 uid=10034 gids={50034, 3003, 1028, 1023, 1015, 3001, 3002}

D/ActivityThread(17589): handleBindApplication:com.idormy.sms.forwarder

I/dalvikvm(17589): Could not find method android.app.Application.startForegroundService, referenced from method com.idormy.sms.forwarder.App.onCreate

I/MultiDex(17589): MultiDexExtractor(/data/app/com.idormy.sms.forwarder-1.apk, /data/data/com.idormy.sms.forwarder/code_cache/secondary-dexes)

I/MultiDex(17589): Blocking on lock /data/data/com.idormy.sms.forwarder/code_cache/secondary-dexes/MultiDex.lock

I/MultiDex(17589): /data/data/com.idormy.sms.forwarder/code_cache/secondary-dexes/MultiDex.lock locked

I/MultiDex(17589): MultiDexExtractor.load(/data/app/com.idormy.sms.forwarder-1.apk, false, )

W/ContextImpl(17589): Failed to ensure directory: /storage/sdcard1/Android/data/com.idormy.sms.forwarder/files

W/ContextImpl(17589): Failed to ensure directory: /storage/sdcard1/Android/data/com.idormy.sms.forwarder/cache

W/ContextImpl(17589): Failed to ensure directory: /storage/sdcard1/Android/data/com.idormy.sms.forwarder/files

W/ContextImpl(17589): Failed to ensure directory: /storage/sdcard1/Android/data/com.idormy.sms.forwarder/cache

W/ContextImpl(17589): Failed to ensure directory: /storage/sdcard1/Android/data/com.idormy.sms.forwarder/cache

D/dalvikvm(17589): Trying to load lib /data/app-lib/com.idormy.sms.forwarder-1/libmmkv.so 0x4194e828

D/dalvikvm(17589): Added shared lib /data/app-lib/com.idormy.sms.forwarder-1/libmmkv.so 0x4194e828

I/MMKV    (17589): <MMKV.cpp:207::initializeMMKV> root dir: /data/data/com.idormy.sms.forwarder/files/mmkv

I/MMKV    (17589): <MemoryFile.cpp:97::open> open fd[0x32], /data/data/com.idormy.sms.forwarder/files/mmkv/History

I/MMKV    (17589): <MemoryFile.cpp:97::open> open fd[0x33], /data/data/com.idormy.sms.forwarder/files/mmkv/History.crc

I/MMKV    (17589): <MemoryFile.cpp:97::open> open fd[0x34], /data/data/com.idormy.sms.forwarder/files/mmkv/mmkv.default

I/MMKV    (17589): <MemoryFile.cpp:97::open> open fd[0x35], /data/data/com.idormy.sms.forwarder/files/mmkv/mmkv.default.crc

E/Tinker.LoadLibrary(17589): installNativeLibraryPath, folder /data/data/com.idormy.sms.forwarder/files/libs is illegal

D/dalvikvm(17589): Trying to load lib /data/app-lib/com.idormy.sms.forwarder-1/libumeng-spy.so 0x4194e828

D/dalvikvm(17589): Added shared lib /data/app-lib/com.idormy.sms.forwarder-1/libumeng-spy.so 0x4194e828

D/dalvikvm(17589): No JNI_OnLoad found in /data/app-lib/com.idormy.sms.forwarder-1/libumeng-spy.so 0x4194e828, skipping init

E/AndroidRuntime(17589): Process: com.idormy.sms.forwarder, PID: 17589

E/AndroidRuntime(17589): java.lang.RuntimeException: Unable to start service com.idormy.sms.forwarder.service.BatteryService@41991280 with null: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.e, parameter intent

E/AndroidRuntime(17589): 	at com.idormy.sms.forwarder.service.BatteryService.onStartCommand(BatteryService.kt)

I/ActivityManager(  853): Process com.idormy.sms.forwarder (pid 17589) has died.

W/ActivityManager(  853): Service crashed 2 times, stopping: ServiceRecord{41c21700 u0 com.idormy.sms.forwarder/.service.BatteryService}

W/ActivityManager(  853): Service crashed 2 times, stopping: ServiceRecord{41bce3a8 u0 com.idormy.sms.forwarder/.service.ForegroundService}

**Comment by xuyuan140** [comment]
> 在android4.4的设备上安装了3.0.5版本，启动应用后闪退，无法正常使用

讯唐410 安卓4.4 3.05 3.06都不行。打开都闪退。哎

**Comment by pppscn** [comment]
23:30 过后下载 每夜构建版 测试
https://github.com/pppscn/SmsForwarder/actions/workflows/Nightly_Build.yml

相关提交：https://github.com/pppscn/SmsForwarder/commit/6ec0f42afa93f209e0af25237dd85b956d24f2ad

**Comment by lixh00** [comment]
> 23:30 过后下载 每夜构建版 测试 https://github.com/pppscn/SmsForwarder/actions/workflows/Nightly_Build.yml
> 
> 相关提交：[6ec0f42](https://github.com/pppscn/SmsForwarder/commit/6ec0f42afa93f209e0af25237dd85b956d24f2ad)

@pppscn 最新release版本还是没法儿在随身WiFi上打开，日志如下
```

07-26 13:13:48.631 D/dalvikvm( 2855): GC_FOR_ALLOC freed <1K, 19% free 8948K/11012K, paused 14ms, total 14ms
07-26 13:13:48.651 I/MMKV    ( 7933): Disable checkProcessMode()
07-26 13:13:48.651 D/AndroidRuntime( 7933): Shutting down VM
07-26 13:13:48.651 W/dalvikvm( 7933): threadid=1: thread exiting with uncaught exception (group=0x415e0d58)
07-26 13:13:48.651 D/dalvikvm( 2855): GC_FOR_ALLOC freed 3217K, 34% free 7332K/11012K, paused 9ms, total 9ms
07-26 13:13:48.661 E/AndroidRuntime( 7933): FATAL EXCEPTION: main
07-26 13:13:48.661 E/AndroidRuntime( 7933): Process: com.idormy.sms.forwarder, PID: 7933
07-26 13:13:48.661 E/AndroidRuntime( 7933): java.lang.UnsatisfiedLinkError: Couldn't load mmkv from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.idormy.sms.forwarder-1.apk", zip file "/data/data/com.idormy.sms.forwarder/code_cache/secondary-dexes/com.idormy.sms.forwarder-1.apk.classes2.zip"],nativeLibraryDirectories=[/data/app-lib/com.idormy.sms.forwarder-1, /vendor/lib, /system/lib]]]: findLibrary returned null
07-26 13:13:48.661 E/AndroidRuntime( 7933): 	at java.lang.Runtime.loadLibrary(Runtime.java:358)
07-26 13:13:48.661 E/AndroidRuntime( 7933): 	at java.lang.System.loadLibrary(System.java:526)
07-26 13:13:48.661 E/AndroidRuntime( 7933): 	at com.tencent.mmkv.MMKV.g(MMKV.java:2)
07-26 13:13:48.661 E/AndroidRuntime( 7933): 	at com.tencent.mmkv.MMKV.t(MMKV.java:5)
07-26 13:13:48.661 E/AndroidRuntime( 7933): 	at com.tencent.mmkv.MMKV.s(MMKV.java:3)
07-26 13:13:48.661 E/AndroidRuntime( 7933): 	at com.idormy.sms.forwarder.utils.HistoryUtils$Companion.e(HistoryUtils.kt:1)
07-26 13:13:48.661 E/AndroidRuntime( 7933): 	at com.idormy.sms.forwarder.App.q(App.kt:2)
07-26 13:13:48.661 E/AndroidRuntime( 7933): 	at com.idormy.sms.forwarder.App.onCreate(App.kt:3)
07-26 13:13:48.661 E/AndroidRuntime( 7933): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:007)
07-26 13:13:48.661 E/AndroidRuntime( 7933): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4422)
07-26 13:13:48.661 E/AndroidRuntime( 7933): 	at android.app.ActivityThread.access$1500(ActivityThread.java:138)
07-26 13:13:48.661 E/AndroidRuntime( 7933): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1259)
07-26 13:13:48.661 E/AndroidRuntime( 7933): 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-26 13:13:48.661 E/AndroidRuntime( 7933): 	at android.os.Looper.loop(Looper.java:136)
07-26 13:13:48.661 E/AndroidRuntime( 7933): 	at android.app.ActivityThread.main(ActivityThread.java:5095)
07-26 13:13:48.661 E/AndroidRuntime( 7933): 	at java.lang.reflect.Method
.invokeNative(Native Method)
07-26 13:13:48.661 E/AndroidRuntime( 7933): 	at java.lang.reflect.Method.invoke(Method.java:515)
07-26 13:13:48.661 E/AndroidRuntime( 7933): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
07-26 13:13:48.661 E/AndroidRuntime( 7933): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
07-26 13:13:48.661 E/AndroidRuntime( 7933): 	at dalvik.system.NativeStart.main(Native Method)
07-26 13:13:48.671 W/ActivityManager(  866):   Force finishing activity com.idormy.sms.forwarder/.activity.SplashActivity
07-26 13:13:48.681 D/dalvikvm( 2855): GC_FOR_ALLOC freed <1K, 23% free 8549K/11012K, paused 7ms, total 7ms
```

日志文件:
[logcat.log](https://github.com/pppscn/SmsForwarder/files/9186741/logcat.log)
