### ISSUE TITLE
重启后设置丢失

### ISSUE THREAD

**Issue by hongwen000** [pppscn/SmsForwarder#181]
软件版本：3.0.5
设备：一加9@ColorOS 12.1
Bug描述：重启后重新显示第一次期待提示语，通用设置一栏所有设置丢失

**Comment by pppscn** [comment]
一直这样无限循环？配置是保存在 mmkv 的，第一次有人反馈这个现象

https://github.com/Tencent/MMKV

**Comment by hongwen000** [comment]
是的，重现了3次。
detail：我启动了3.0.5版本的高级保活功能选项，该选项提示让重启应用，因此我才重启设备。在2.x版本中似乎没有该选项（而是分散的保活选项，也没有提示重启应用）。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年7月5日 11:00
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [pppscn/SmsForwarder] 重启后设置丢失 (Issue #181)


一直这样无限循环？配置是保存在 mmkv 的，第一次有人反馈这个现象

https://github.com/Tencent/MMKV

―

**Comment by hongwen000** [comment]
升级安装后出现的问题。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年7月5日 17:47
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [pppscn/SmsForwarder] 重启后设置丢失 (Issue #181)


全新安装的 还是 从2.x 升级上来的？ 建议全新安装一次试试

―
