### ISSUE TITLE
从另一部手机里面导入设置之后无法正常转发短信

### ISSUE THREAD

**Issue by Imcodingcc** [pppscn/SmsForwarder#182]
旧手机是2.3版本的，把旧手机升级到3.0.5之后，再把配置转到新的手机上，新手机无法正常发送转发短信，尝试几次过后，好像是需要把发送通道重新编辑保存一遍就可以正常转发短信了

**Comment by pppscn** [comment]
"无法正常发送" 是转发失败了还是什么？ 有转发日志吗

**Comment by Imcodingcc** [comment]
> "无法正常发送" 是转发失败了还是什么？ 有转发日志吗

toast提示 “x 请求失败 null”

**Comment by Imcodingcc** [comment]
> "无法正常发送" 是转发失败了还是什么？ 有转发日志吗

输入了模拟手机号和内容点击“测试规则”，toast提示 “x 请求失败 null”，但是所选“发送通道”单独进行测试又是可以的，我的发送通道是webhook

**Comment by pppscn** [comment]
2.3的webhook 跟 3.0 确实差别很大了，这个暂不考虑兼容问题了  之前应该修复过类似的bug  需要重新编辑一下 通道（增加默认参数节点）

**Comment by Imcodingcc** [comment]
> 2.3的webhook 跟 3.0 确实差别很大了，这个暂不考虑兼容问题了 之前应该修复过类似的bug 需要重新编辑一下 通道（增加默认参数节点）

好的
