### ISSUE TITLE
是否考虑添加一个动态 url 的Webhook？

### ISSUE THREAD

**Issue by zyiLoong** [pppscn/SmsForwarder#183]
# 我的使用场景
想要将手机验证码短信发送到笔记本上，使用的是 Webhook 这个发送通道，因为可以在笔记本上对于收到的信息进行一些操作，比如解析出验证码内容、发送系统消息通知、将验证码写进系统剪切板。

# 我的问题
笔记本连接的是公司WIFI、所以IP地址是会变化的，需要频繁修改发送通道的 server 地址。
公司不允许使用内网穿透，所以也不能使用 frpc

# 我的解决方案
1. Webhook 发送消息之前，先调用一下配置的 webhook server url (中间服务器)，该 url 返回一个内网的指向笔记本IP的 url，实际发送消息时使用新的 url
2. 笔记本跑一个脚本，定时刷新 webhook server url 的返回值，将变更后的内网 ip 更新到中间服务器
---
下面是我 fork 后自己的修改，因为没有接触过 android 和 kotlin 开发，所以修改方式极其简陋，直接在原 Webhook 上面进行的修改，也不敢献丑提PR了。不知道是否会考虑添加这么个发送通道。
https://github.com/zyiLoong/SmsForwarder/commit/f616d6de0c5d4e497ef806f7014108981bf2fb7a

最后，多谢作者

**Comment by pppscn** [comment]
中间服务器是公网 还是 内网的？  有中间服务器了，为什么还要搞这么复杂？ 

如果在内网，直接由 中间服务器 转发给 笔记本不行吗？ 反正它都有你笔记本现有IP

如果在公网，这饶了一圈再回来，路径有点长啊，我建议上直接不要它了，定时动态修改 webhook 域名的ip为内网IP，参考：https://github.com/jeessy2/ddns-go

**Comment by zyiLoong** [comment]
公网服务器：在其他WIFI环境下也可以正常使用（比如在家），但是不能由 服务器 直接转发给 笔记本，
内网服务器：恰好相反

目的就是为了在笔记本IP变动的情况下，依然可以正常调用，我上面说的只是我目前的一个初步的想法，多一次网络IO也还能接受，凑合能用。可以仔细想想搞个好一些的方案。

公司内网搞不到域名，ddns-go 这个我先看看能不能用，多谢。
