### ISSUE TITLE
[功能建议]增加发送通道规则，根据条件自动选择不同的发送通道

### ISSUE THREAD

**Issue by photkey** [pppscn/SmsForwarder#186]
先说下应用场景：我是通过SmsForwarder配合一个简单的python脚本实现：手机收到验证码后 在PC上就自动填充验证码。
之前是通过邮箱转发，效果基本满意 延迟稍大，后来改成了 局域网内通过webhook转发，这个效果是巨爽的，就是在手机还没弹出短信通知的时候 PC上已经填充完验证码了，真的体验超级棒！

那么现在有个问题，家里跟公司的局域网ip不同，转发通道设置成家里的局域网ip的时候 在公司不好用；设置成公司的局域网ip 在家里又不好用……

所以我想能不能设置一下转发通道的规则，比方，根据当前链接的WiFi名自动选择不同转发通道，没有连接WiFi的时候 又是另外一个转发通道。

**Comment by pppscn** [comment]
你这个需求跟这个兄弟有点像，可以参考一下他的做法

https://github.com/pppscn/SmsForwarder/issues/183

**Comment by photkey** [comment]
是有点像，好像也不太一样，其实我根本看的不是很明白……
如果按他现在的中间服务器的方式 可能到达会没那么及时了。
我之前是通过邮箱发送，QQ邮箱的到达速度是最快的。实现的效果是 手机上的短信通知弹出来后 1-2秒 PC开始输入验证码。
而用局域网webhook 在手机短信弹出通知前，就已经完成验证码输入了，这个感觉是非常爽的。

另外如果加上规则 可以组合更多的方式，更灵活一点吧，比方 输入验证码这个场景，如果没有连接wifi 可能就是不在电脑旁，可能就不需要转发了。

其实，我几乎用不到这个功能，因为一直都是在家办公，出门的次数都很少，只是觉得这是不错的功能，就提出来了。

**Comment by pppscn** [comment]
都是通过webhook转发到自己的电脑，这个电脑会随着连入的WIFI不同，内网IP变了（这里假设，你没权限设置静态IP）

我的建议是，webhook的地址用域名代替，电脑连入不同wifi时去修改这个域名对应的IP，可参考ddns-go或自己脚本ping网关动态改域名解析

更简便的做法就是，在路由器上设置静态IP，然后做域名解析到内网IP

**Comment by zuozhehao** [comment]
@photkey webhook 绑定一个域名(forward.com)，家里、公司的路由静态解析下对应的PC内网ip。
@pppscn webhook 是否可以把当前WIFI名称和内网IP一起推送。
