### ISSUE TITLE
webhook 请求失败

### ISSUE THREAD

**Issue by loveqianool** [pppscn/SmsForwarder#187]
向 `https://github.com/K0IN/Notify` 的演示地址发送一直收到以下错误，而我自建的收到的错误一直是 `http 401` 无法正常使用。

![微信图片_20220719123642](https://user-images.githubusercontent.com/739497/179666278-31743794-d823-41fc-b2ce-3169045197ca.jpg)

同一时间使用
`curl -X POST -H "Content-Type: application/json" -d '{"title":"Hello", "message":"World"}' https://notify_app-demo.thisk0in.workers.dev/api/notify`
能正常收到消息

![微信图片_20220719123647](https://user-images.githubusercontent.com/739497/179666439-fdec9c2a-4cdd-470b-ba7e-b58803228347.jpg)

**Comment by pppscn** [comment]
这地址需要梯子才能访问？

**Comment by pppscn** [comment]
看报错像是连不上，smsf用不上梯子的感觉
