### ISSUE TITLE
应用通道里加包名黑名单

### ISSUE THREAD

**Issue by ihuge820920** [pppscn/SmsForwarder#188]
如果可以的话，在应用通道里加一个包名黑名单，不然一个一个设置有点小麻烦

**Comment by pppscn** [comment]
转发规则上用`正则匹配`排除多个包名，试试吧

**Comment by xingyunjohn1** [comment]
可以增加短信、通话的黑白名单功能方便配置吗，或者更新regex的Wiki，好像用得不是很明白。谢谢
