### ISSUE TITLE
outlook邮箱被封锁

### ISSUE THREAD

**Issue by zhixwang** [pppscn/SmsForwarder#189]
专门注册了一个outlook邮箱用来转发短信，但没几天就被封锁了。请问有人知道换成哪个邮箱可以避免这个问题吗？

**Comment by zhixwang** [comment]
谢谢！

**Comment by pppscn** [comment]
这个每个邮箱服务商都有可能封，主要看你发的频率跟内容

**Comment by zhixwang** [comment]
> 这个每个邮箱服务商都有可能封，主要看你发的频率跟内容

我看到您写，转发到iOS的最佳方案是Bark，请问这里说的是安卓转iOS吗？叫Bark的app有好几个，不知道具体是哪个？

**Comment by pppscn** [comment]
是Android到IOS的  https://github.com/Finb/Bark

或者用 pushdeer 也行，参考文档用 webhook 直接发 https://github.com/easychen/pushdeer

**Comment by zhixwang** [comment]
谢谢！
