### ISSUE TITLE
能否添加一个低电量提醒?

### ISSUE THREAD

**Issue by wallpass** [pppscn/SmsForwarder#19]
能否添加一个低电量提醒，比如电量下降到了10%以下，自动发动信息给远程端进行提醒。
主要是有时候突然收不到验证码了，也不知道是软件被杀后台了，还是手机没电自动关机了。

**Comment by wallpass** [comment]
为什么反馈了，没有什么响应。加群也加不上😭

**Comment by pppscn** [comment]
下一版本发布时，会带上此功能：当到达低电量预警阈值时，调用所有发送方通知2次
![微信截图_20210927114909](https://user-images.githubusercontent.com/5105854/134842923-e67070d1-0137-47c8-887a-f1b77dd2f264.png)

敬请期待
