### ISSUE TITLE
能否添加一个发送WOL数据包的附属功能，可以由其他设备将WOL需要用到的mac地址发送到此设备

### ISSUE THREAD

**Issue by 1873505600** [pppscn/SmsForwarder#190]
能否添加一个发送WOL数据包的附属功能，可以由其他设备将WOL需要用到的mac地址发送到此设备，实现远程开机功能

**Comment by pppscn** [comment]
这……是把smsf当全能选手啊，难度是没什么难度，问题是为什么需要通过smsf来发wol包？

**Comment by 1873505600** [comment]
> 这……是把smsf当全能选手啊，难度是没什么难度，问题是为什么需要通过smsf来发wol包？

想着功能集成，我了解这个项目的渠道是有人用这个功能实现的远程办公，想着能不能把电脑的远程开机也加上，这样就更方便一些

**Comment by pppscn** [comment]
![远程wol](https://user-images.githubusercontent.com/5105854/181148048-c87eba3d-9dca-4566-9212-72ab15fc54f1.jpg)

孤零零的加一个，逼死强迫症，等累积到9个时再发版

**Comment by 1873505600** [comment]
> ![远程wol](https://user-images.githubusercontent.com/5105854/181148048-c87eba3d-9dca-4566-9212-72ab15fc54f1.jpg)
> 
> 孤零零的加一个，逼死强迫症，等累积到9个时再发版

好的，辛苦作者大大了

**Comment by pppscn** [comment]
已经提交了，下载每夜构建版测试一下
https://github.com/pppscn/SmsForwarder/actions/workflows/Nightly_Build.yml

**Comment by pppscn** [comment]
![微信图片_20220729114304](https://user-images.githubusercontent.com/5105854/181678388-c238bb1f-4343-43dc-9dce-f3f8c9cd0a59.jpg)
