### ISSUE TITLE
能否增加一个可以选择内置服务器资源目录的功能?

### ISSUE THREAD

**Issue by xingxichen** [pppscn/SmsForwarder#191]
能否增加一个可以选择内置服务器资源目录的功能?自行选择服务器内的内容.

**Comment by pppscn** [comment]
![微信图片_20220812103713](https://user-images.githubusercontent.com/5105854/184274712-8ac16bf6-ecd0-4160-8e99-06e892b9ea34.jpg)

**Comment by pppscn** [comment]
https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml 20分钟后下载
