### ISSUE TITLE
一个小建议：转发信息模板中内容能否设置换行？

### ISSUE THREAD

**Issue by FreeWillDeveloper** [pppscn/SmsForwarder#194]
转发信息模板设置中，内容标签选择好之后，内容标签之间不管是换行还是挨在一起的，短信显示内容（邮件端）都是挨在一起的，看起来有点乱。
显示效果如图：
![IMG_20220731_013200](https://user-images.githubusercontent.com/88413337/181935005-e8b6a979-601a-493e-b12c-5187ee376c70.jpg)

是否可以在转发信息模板设置的输入框中添加换行符的识别？
当内容标签之间是换行的时候，如图：
![IMG_20220731_012007](https://user-images.githubusercontent.com/88413337/181934779-72c6c61a-a577-4573-bf1e-002830eb52a0.jpg)
邮件正文内容就根据内容标签的位置换行显示。

当内容标签之间是挨在一起的时候，如图：
![IMG_20220731_012832](https://user-images.githubusercontent.com/88413337/181934901-e6c9349f-50ec-405b-85a7-93afc7a8e41f.jpg)
邮件正文内容就就根据内容标签的位置挨在一起显示。

**Comment by FreeWillDeveloper** [comment]
@pppscn

**Comment by pppscn** [comment]
邮件的正文是html，所以你插入 `<br>`即可，其他发送通道，纯文本直接回车换行就好了

**Comment by FreeWillDeveloper** [comment]
感谢回复，现在没问题了。
