### ISSUE TITLE
Android TV 适配 开机启动不显示主程序

### ISSUE THREAD

**Issue by aston314** [pppscn/SmsForwarder#195]
现在的界面在Android盒子上很大，不能自动适配。

开机自启动会显示主App，能不能作到静默启动。

**Comment by pppscn** [comment]
Android TV 为什么需要这个软件？

**Comment by aston314** [comment]
因为，所以。
因为有下载，需要有完成通知。

**Comment by aston314** [comment]
![Uploading BF217833-49C9-4B6E-ABD6-7BAB1BA8BA9A.png…]()

**Comment by pppscn** [comment]
暂不考虑适配TV版

**Comment by aston314** [comment]
嗯，已删除。
