### ISSUE TITLE
在410棒子上使用3.0.7版Webhook通道发送到饭碗警告提示证书验证失败

### ISSUE THREAD

**Issue by tedcriss** [pppscn/SmsForwarder#197]
在410棒子上使用3.0.7版Webhook通道发送到饭碗警告提示证书验证失败
![转发报错](https://user-images.githubusercontent.com/20439247/182010951-5a46673a-2898-40d0-9714-56ec8b8d98d5.png)

**Comment by pppscn** [comment]
系统时间是否正确？ 
自建的bark服务端你的ssl根证书，棒子上有没有？

**Comment by tedcriss** [comment]
时间是对的，ssl证书我不知道是什么😂。另外，饭碗警告中没有下载ssl证书的地方。

**Comment by pppscn** [comment]
[https Android 5.0 以下TLS 版本过低造成的问题](https://www.cnblogs.com/mingfeng002/p/8436416.html)
应该是这个原因，空闲的时候尝试看看怎么修复

**Comment by pppscn** [comment]
饭碗警告用的TLSv1.3，这个要 29+ 才能支持
![微信截图_20220803114206](https://user-images.githubusercontent.com/5105854/182519380-8e42e78e-cfb8-42f5-bb57-5111ad3235cd.png)

https://developer.android.com/reference/javax/net/ssl/SSLSocket.html

**Comment by pppscn** [comment]
已经解决，下载每周构建版试试
