### ISSUE TITLE
bark能否增加group参数实现分组

### ISSUE THREAD

**Issue by AdoShan** [pppscn/SmsForwarder#198]
bark目前不支持消息分组。能不能支持一下呢。消息比较多的话可以直接按照分组查看

**Comment by pppscn** [comment]
![微信图片_20220731192702](https://user-images.githubusercontent.com/5105854/182024080-f16a89cb-e664-4ed0-b6b7-4b6252d338aa.jpg)

现在就已经支持呃，`发送通道`上的`分组名称`

**Comment by AdoShan** [comment]
尴尬了😅。不好意思😅

Sent from my iPhone

On Jul 31, 2022, at 19:28, pppscn ***@***.***> wrote:

﻿

[微信图片_20220731192702]<https://user-images.githubusercontent.com/5105854/182024080-f16a89cb-e664-4ed0-b6b7-4b6252d338aa.jpg>

现在就已经支持呃，发送通道上的分组名称
