### ISSUE TITLE
可以添加GET转发吗

### ISSUE THREAD

**Issue by mymine** [pppscn/SmsForwarder#2]
可以添加GET转发吗

**Comment by mymine** [comment]
> 抽时间改造一下webhook那个模块，允许可选get还是post

坐等更新

**Comment by mymine** [comment]
> 抽时间改造一下webhook那个模块，允许可选get还是post

模板可以全部自定义吗？像这种，时间，消息，来信号码和内容。
2021-03-12 22:01:40=>来自10086的新消息,尊敬的用户，您已免费获得中国移动“流量包1GB（24小时）”，内含1GB国内通用流量（不含港澳台），请在2021-03-13 22:00:59前使用有效。【中国移动】【卡2】【MI 5s】


目前好像是这样好像不能
10010/2021-03-12 18:09:1110010尊敬的用户，截止到2021年03月12日
来信号码和/不能修改

**Comment by pppscn** [comment]
get参见1.6.3版本

自定义模板可以自己组合标签

**Comment by mymine** [comment]
> get参见1.6.3版本
> 
> 自定义模板可以自己组合标签

好了！新版本正常

**Comment by pppscn** [comment]
> > get参见1.6.3版本
> > 自定义模板可以自己组合标签
> 
> 好了！新版本正常

多谢反馈
