### ISSUE TITLE
Android 4.4机型无法安装（解析程序包时出现问题）

### ISSUE THREAD

**Issue by Sostay** [pppscn/SmsForwarder#200]
具体机型：Nokia X（非常古老【doge】~
universal和armeabi-v7a版本都试过了，都是一样的提示：解析程序包时出现问题，无法安装

**Comment by pppscn** [comment]
连安装都装不上，这个我就没办法了，也没有机器可以搞适配（盲猜是比 armeabi-v7a 更古老的cpu）

还是劝你花个十来块买个 随身wifi 410/210 更实在

**Comment by hackermari** [comment]
@pppscn 十来块买个 随身wifi 410/210 能详细说说嘛，我好像没看到这么便宜的，都基本上要几十块
