### ISSUE TITLE
设备的备注

### ISSUE THREAD

**Issue by Xtaoge** [pppscn/SmsForwarder#201]
大佬，远程控制能不能加一个备注，或者远程发送短信的时候把sim卡号显示出来

**Comment by pppscn** [comment]
![微信图片_20220802145104](https://user-images.githubusercontent.com/5105854/182310525-efeb8af6-ba3a-42ce-a78f-af730fbf654d.jpg)

卡槽备注的这个会加上的，在计划中了（客户端体验优化）

**Comment by pppscn** [comment]
已提交坐等下一次发版 或 [Weekly_Build](https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml)
