### ISSUE TITLE
[Bug]: 短信内容包含“<"（即小于号）字符时，用tg转发失败（其他的转发方式未测试）。

### ISSUE THREAD

**Issue by LudwigEuler** [pppscn/SmsForwarder#205]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

V3.0.7

### 问题描述

短信内容包含“<"（即小于号）字符时，用tg转发失败（其他的转发方式未测试），tg代理使用socks，请求方式是POST（GET方式可以正常转发）。无论是真实收到短信，或者是测试，或者是重发，重新匹配规则，只要有这个符号，即失败。

### 复现步骤

先建立可用的tg发送通道。在转发规则测试中的短信内容填写"<"，按”测试规则“按钮，即出现”请求失败，HTTP 400“。

### 是否必现

是（Yes）

### 出现问题的手机信息

HUAWEI P9P

### 出现问题的安卓版本、系统版本

Android 7.0    EMUI 5.0

### 提供解决方案

问题可能是出在TelegramUtils.kt的第55行，bodyMap["text"] = content，没有对content编码而直接发送post请求导致。

本想帮忙修理这个bug，无奈太菜，同步项目到本地后试着编译，出现

Build file '.\SmsForwarder\app\build.gradle' line: 21

A problem occurred evaluating project ':app'.
> No signature of method: build_a4lll7knb8s46f4j5pgmsw7q0.android() is applicable for argument types: (build_a4lll7knb8s46f4j5pgmsw7q0$_run_closure1) values: [build_a4lll7knb8s46f4j5pgmsw7q0$_run_closure1@6cd6bde1]

的错误，就不会处理了，所以只能提个issue。

**Comment by pppscn** [comment]
已转义 `<` `>` `&` `"` 四个字符，20分钟后下载 每周构建版测试

参考资料：https://core.telegram.org/bots/api#formatting-options
