### ISSUE TITLE
[Suggestion]: 发送通道中的webhook是否可以增加PATCH的请求方式

### ISSUE THREAD

**Issue by BetaXOi** [pppscn/SmsForwarder#206]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

目前仅有POST和GET，是否可以新增PATCH请求方式，这样可以利用gihub的OpenAPI不断地将新消息推送到某个地方（如Issuse地某条评论）。
当然也可以用POST请求方式新建，但这样地结果就是导致消息越来越多，还需要当时清理。

**Comment by pppscn** [comment]
测试一下

**Comment by pppscn** [comment]
请下载每周构建版本帮忙测试一下 PUT/PATCH 请求方式

https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

PS. 上一楼是通过smsf修改的，参考文档：https://docs.github.com/cn/rest/issues/comments#update-an-issue-comment

**Comment by BetaXOi** [comment]
测试PATCH方式正常，
