### ISSUE TITLE
[Bug]: 请求http协议的bark 的sever 的时候会爆空指针错误

### ISSUE THREAD

**Issue by foglede** [pppscn/SmsForwarder#207]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.0.8

### 问题描述

请求http协议的bark 的sever 的时候会爆空指针错误 （2.0）版本无此错误。
另外请添加一个 https 不检查证书选项。

### 复现步骤

bark 填 http 地址 名称 其它全留空即能复现

### 是否必现

是（Yes）

### 出现问题的手机信息

xiaomi

### 出现问题的安卓版本、系统版本

7

**Comment by foglede** [comment]
找到问题原因了，勉强算是BUG，就是在极端情况下，流量不足，或者流量转为2G，运营商网络不正常情况下，有可能返回非200HTTP响应，或者BOdy 内容被劫持。此时BUG复现。下个版本可以多写一些判断即可。

**Comment by pppscn** [comment]
等下一个版本发布 或 下载每周构建版本
