### ISSUE TITLE
telegram 转义问题

### ISSUE THREAD

**Issue by wolfsilver** [pppscn/SmsForwarder#210]
### 是否有人曾提过类似的问题？

是（Yes）

### 你觉得APP有什么不足之处？

对于 #205 提到的问题，现在对自定义正则之后的内容做了转义，会导致之前使用正则处理的内容也转义了
针对验证码的场景，使用`code`标签将数字包裹，可以在telegram上直接点击复制,类似这种
```
<code>441530</code>
```
如果转义之后，在telegram上也展示的`<code>441530</code>`，没办法直接复制了

### 你觉得该怎么去完善会比较好？【非必答】

可以将短信内容转义，正则替换的不再处理

**Comment by pppscn** [comment]
等待下一次发版测试
