### ISSUE TITLE
[Suggestion]: 是否可以增加短信自动回复功能

### ISSUE THREAD

**Issue by etion2008** [pppscn/SmsForwarder#211]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

是否可以增加短信自动回复功能，比如针对某些特定号码前缀，包含特定关键字的短信，自动回复设定的内容。

**Comment by pppscn** [comment]
![Screenshot_20220822_222527](https://user-images.githubusercontent.com/5105854/185947552-160d0341-d76e-4a24-ad28-57a8e1286bda.png)
![Screenshot_20220822_223346](https://user-images.githubusercontent.com/5105854/185947561-421680fd-edd5-4bef-9ef1-9c7799800ee4.png)

**Comment by pppscn** [comment]
等待下一次发版测试

**Comment by etion2008** [comment]
大佬给力，期待新版本。

**Comment by ZL-ZedeL** [comment]
感谢提供大佬方案
