### ISSUE TITLE
[Suggestion]: 功能请求：主动控制可以增加控制规则的功能吗（主要用于增加黑白名单）

### ISSUE THREAD

**Issue by xingyunjohn1** [pppscn/SmsForwarder#212]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

能用上主动控制很多时候是漏收消息了，此时可能是规则配置不合理，建议可以远程修改规则。

### 你觉得该怎么去完善会比较好？【非必答】

增加远程控制规则的功能

**Comment by pppscn** [comment]
本机配置好，一键换新机，直接覆盖吧，一条一条修改的话 就啰嗦了
