### ISSUE TITLE
[Suggestion]: 增加来电直接转发（而不是变成未接来电才转发）的功能

### ISSUE THREAD

**Issue by xingyunjohn1** [pppscn/SmsForwarder#213]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

通话转发可能存在延迟。

### 你觉得该怎么去完善会比较好？【非必答】

增加接到通话立即转发的功能

**Comment by sorawub** [comment]
恕我直言，这个需求，运营商自带的呼叫转移不是可以满足吗？

**Comment by monkeyRing** [comment]
有呼叫转移  多此一举

**Comment by haygcao** [comment]
> 有呼叫转移 
打个比方，你有香港号码或者其他的号码，你在出境时候不方便接电话，有了这个就很方便了，甚至是你出国的时候，变相的变成wifi calling了。总共是有他的合理的地方的
