### ISSUE TITLE
[Suggestion]: 转发消息遇到超链接时只会转发文字

### ISSUE THREAD

**Issue by wudongdefeng** [pppscn/SmsForwarder#215]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

转发消息遇到超链接时只会转发文字

### 你觉得该怎么去完善会比较好？【非必答】

转发消息遇到超链接时可以让超链接直接显示

**Comment by pppscn** [comment]
转发的是什么消息？ 里面有超链接？

**Comment by pppscn** [comment]
无后续反馈，暂时关闭
