### ISSUE TITLE
[Bug]: 构建问题，gradle同步失败

### ISSUE THREAD

**Issue by GodManRui** [pppscn/SmsForwarder#216]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

否（No）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

main分支

### 问题描述

main分支，clone下来之后同步失败
![image](https://user-images.githubusercontent.com/30816530/187020192-a2152ce0-f13f-436c-a351-3c3ec28290d3.png)

### 复现步骤

![image](https://user-images.githubusercontent.com/30816530/187020253-e57dbf0f-89bd-482d-b8ec-79b059d6baf1.png)
只要同步就会失败

### 是否必现

是（Yes）

### 出现问题的手机信息

android studio 2021.2.1 

### 出现问题的安卓版本、系统版本

无

**Comment by pppscn** [comment]
请参照wiki，先在项目根目录新建keystore目录

https://github.com/pppscn/SmsForwarder/wiki/%E5%85%B3%E4%BA%8E%E5%AE%9A%E5%88%B6%E5%BC%80%E5%8F%91

**Comment by GodManRui** [comment]
> 请参照wiki，先在项目根目录新建keystore目录
> 
> https://github.com/pppscn/SmsForwarder/wiki/%E5%85%B3%E4%BA%8E%E5%AE%9A%E5%88%B6%E5%BC%80%E5%8F%91

好的大佬
