### ISSUE TITLE
[Suggestion]: 用短信转发能否优先走网络短信通道

### ISSUE THREAD

**Issue by xmzhangya** [pppscn/SmsForwarder#217]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

短信转发功能可以完善

### 你觉得该怎么去完善会比较好？【非必答】

miui系统间可以在短信界面互发免费短信（通过网络），不知道能否在选择转发通道为短信的时候优先走网络短信通道。目前短信转发直接走的运营商的收费短信。

**Comment by pppscn** [comment]
第三方应用没法调用miui的免费网络短信 （或许是我孤陋寡闻了，你找个项目给我参考试试）
