### ISSUE TITLE
[Bug]: 通过转发日志中重新发送短信时，{{接收时间}}错误

### ISSUE THREAD

**Issue by wjfz** [pppscn/SmsForwarder#218]
### 是否有人曾提过类似的问题

是（Yes）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.0.9

### 问题描述

已转发的历史短信，在转发日志中点击重发消息，模板中的{{接收时间}}应该是短信的接收时间，但实际上短信通知文案中是当前时间。自定义模板和默认模板均是如此。

### 复现步骤

在转发日志中，找到历史短信，点击重发消息。

### 是否必现

是（Yes）

### 出现问题的手机信息

红米1S

### 出现问题的安卓版本、系统版本

MIUI9.2，安卓4.4.4

### 提供解决方案

是不是日期字段取错了。

**Comment by pppscn** [comment]
等下一个版本发布 或 下载每周构建版本
