### ISSUE TITLE
[Suggestion]: 短时间内大量通知能否增加设置只提醒一次？

### ISSUE THREAD

**Issue by zeuszc** [pppscn/SmsForwarder#220]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

有些工作群消息不能不看，短时间内又有大量回复没必要看，全是类似于收到，好的之类的回复。但是软件中设置的重复消息貌似没法屏蔽这样的消息，最大时间2分钟可能也不太够。

### 你觉得该怎么去完善会比较好？【非必答】

有没有可能设置某一软件，比如企业微信，在5分钟内持续有新消息的话就只提醒一次？

**Comment by pppscn** [comment]
建议使用多重匹配，指定包名并过滤你不想要的信息

https://github.com/pppscn/SmsForwarder/wiki/%E9%99%84%E5%BD%955%EF%BC%9A%E8%BD%AC%E5%8F%91%E8%A7%84%E5%88%99%E4%B9%8B%E5%A4%9A%E9%87%8D%E8%A7%84%E5%88%99
