### ISSUE TITLE
[Suggestion]: 能否添加nps内网穿透？

### ISSUE THREAD

**Issue by liuyunwuhen** [pppscn/SmsForwarder#221]
### 是否有人曾提过类似的问题？

是（Yes）

### 你觉得APP有什么不足之处？

能否添加nps内网穿透？

### 你觉得该怎么去完善会比较好？【非必答】

能否添加nps内网穿透？

**Comment by pppscn** [comment]
**经过慎重考虑，暂不添加npc：**

- 看上去作者已经放弃这个项目了，已经好久没有更新了，一大堆issues没处理

- frp v2 据说已经在开发了，配置管理会多样化：[关于V2版本](https://github.com/fatedier/frp/issues/3082)，到时我也会跟进

- 可以自行安装 [android_client.apk](https://github.com/ehang-io/nps/releases/download/v0.26.10/android_client.apk)

https://github.com/ehang-io/nps/releases
