### ISSUE TITLE
[Bug]: 服务器宕机后，Frpc必须点亮屏幕才会重新连接服务器

### ISSUE THREAD

**Issue by spysir** [pppscn/SmsForwarder#222]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

 v3.0.9

### 问题描述

当服务器Frps宕机后，Frpc必须要点亮手机屏幕才会重新连接服务器,其它功能都没有问题

### 复现步骤

当服务器Frps宕机后，Frpc必须要点亮手机屏幕才会重新连接服务器

### 是否必现

是（Yes）

### 出现问题的手机信息

VIVO Z3

### 出现问题的安卓版本、系统版本

9

**Comment by pppscn** [comment]
贴一下 frpc 的配置，敏感信息记得脱敏

**Comment by pppscn** [comment]
https://gofrp.org/docs/reference/client-configures/

dial_server_keepalive 时间调整短一些试试
