### ISSUE TITLE
[Bug]: 通道Server酱在410棒子设备上无法使用

### ISSUE THREAD

**Issue by Sc-Eric-B** [pppscn/SmsForwarder#223]
### 是否有人曾提过类似的问题

是（Yes）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.09

### 问题描述

纸盒棒子410，安卓版本4.4.4，无法使用Server酱通道，测试报警bad request，更换其他通道正常。

### 复现步骤

通道选择Server酱，每次都会复现相同问题。

### 是否必现

是（Yes）

### 出现问题的手机信息

纸盒棒子410

### 出现问题的安卓版本、系统版本

安卓4.4.4

### 提供截图或视频

![Snipaste_2022-09-15_09-49-13](https://user-images.githubusercontent.com/69334742/190294571-49366938-6f2c-4bc6-8d13-875ae68a4d63.png)
![Snipaste_2022-09-15_09-52-14](https://user-images.githubusercontent.com/69334742/190294683-8a9d9004-1aad-4ec6-8cf1-65113e98cc6e.png)

**Comment by pppscn** [comment]
![微信截图_20220921111316](https://user-images.githubusercontent.com/5105854/191406310-1928094d-1a3f-4334-a33a-01a0be26e5df.png)
![微信截图_20220921111346](https://user-images.githubusercontent.com/5105854/191406316-28e4eb07-aef4-4e7d-be0c-d08e42320c45.png)

没有纸盒410的棒子，在先机410上测试没有问题，暂时不处理（我买那么多棒子也没用，不想买了）

**Comment by mucunmjin** [comment]
只用插卡才会出现问题  连接wifi不会
