### ISSUE TITLE
[Bug]: 小米mix2 所有权限都开了, 还是无法读取SIM卡信息

### ISSUE THREAD

**Issue by leebin17** [pppscn/SmsForwarder#225]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

3.0.9

### 问题描述

系统 miui 12.0.1
型号 mix2 
全部26个权限设置为始终允许(除了系统限制了摄像头为仅在使用中允许外)
SIM备注 刷新还是无法读取, 提示 确认获取手机信息为始终允许
导致无法读取手机信息

### 复现步骤

基本操作

### 是否必现

是（Yes）

### 出现问题的手机信息

小米 mix2

### 出现问题的安卓版本、系统版本

ANDROID 9, MIUI 12.0.1 稳定版(PDECNXM)

### 提供截图或视频

![074c35059fff61c457412eef271625c](https://user-images.githubusercontent.com/5846833/193115971-6b116d80-94bd-40c4-86f6-c3644231447d.jpg)

https://user-images.githubusercontent.com/5846833/193116079-868d995f-e286-4459-b1e6-47866174d8c0.mp4

**Comment by pppscn** [comment]
详见wiki常见问题：https://github.com/pppscn/SmsForwarder/wiki/%E3%80%90%E5%BF%85%E8%AF%BB%E3%80%91%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#q%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E5%B7%B2%E7%BB%8F%E5%85%A8%E9%83%A8%E6%8E%88%E4%BA%88%E6%9D%83%E9%99%90%E4%BA%86%E9%80%9A%E7%94%A8%E8%AE%BE%E7%BD%AE%E9%87%8C%E9%9D%A2%E8%8E%B7%E5%8F%96%E5%8D%A1%E6%A7%BD%E4%BF%A1%E6%81%AF%E8%BF%98%E6%98%AF%E6%8F%90%E7%A4%BA%E6%9D%83%E9%99%90%E4%B8%8D%E8%B6%B3
