### ISSUE TITLE
[Suggestion]: 发送通道的Bark的消息链接取消限制

### ISSUE THREAD

**Issue by DJonesT** [pppscn/SmsForwarder#229]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

![微信截图_20221007174639](https://user-images.githubusercontent.com/44050935/194526007-d8956706-9044-4494-be20-faafdf86a81d.png)
可以填入APP的url scheme，方便点击Bark的通知时，跳转到对应的应用。

**Comment by pppscn** [comment]
等下一个版本发布 或 下载每周构建版本
