### ISSUE TITLE
能否给APP增加一个自定义Scheme，通过浏览器启动App

### ISSUE THREAD

**Issue by cjd6568358** [pppscn/SmsForwarder#23]
首先感谢大佬开发这么好用的软件！
在本人实际使用中遇到一个问题就是红米8A手机MIUI 12系统下重新启动后通知栏可以看到软件启动了，但此时任何短信都无法监听转发。所有的权限全部给到，省电模式也已经关闭。这个时候只能手动打开后才能正常转发。
因此想到一个方案，能否给APP增加一个自定义Scheme，通过浏览器启动App。
比较常见的使用场景就是手机号码给父母使用，临时需要接收短信验证码，这个时候就可以通过主动发送自定义Scheme让父母点击启动，或者通过airdroid主动执行自定义Scheme自动打开
![image](https://user-images.githubusercontent.com/3970494/123128264-958d5480-d47d-11eb-8601-677c5dedffe5.png)
提供下相关文章：、
https://blog.csdn.net/xc765926174/article/details/51397847

**Comment by pppscn** [comment]
尝试了一下，已经加上  forwarder://main 但是短信里面并不会识别为链接，等待你的实际测试反馈
