### ISSUE TITLE
[Bug]: openwrt x86-64 + passwall2科学网络下无法转发

### ISSUE THREAD

**Issue by DLGum** [pppscn/SmsForwarder#230]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.0.9

### 问题描述

openwrt x86-64 + passwall2科学网络下163的smtp无法转发

### 复现步骤

openwrt x86-64 + passwall2科学网络下163的smtp无法转发

### 是否必现

是（Yes）

### 出现问题的手机信息

荣耀X10

### 出现问题的安卓版本、系统版本

鸿蒙2

### 提供解决方案

我去换谷歌试试

**Comment by pppscn** [comment]
网络环境导致smtp不能用，不属于smsf的bug
