### ISSUE TITLE
[Suggestion]: 自动消除通知需要处理短信的通知

### ISSUE THREAD

**Issue by TomKing062** [pppscn/SmsForwarder#232]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

我个人开启了转发短信和只转发88888888包名的电量，我对于 https://github.com/pppscn/SmsForwarder/commit/c2df047dc1b36f7ed24559adca823b8c7a84c53e 的理解是com.android.mms包名并没有被匹配，造成短信通知不会被自动清除了

### 你觉得该怎么去完善会比较好？【非必答】

临时解决是关闭短信转发并开启com.android.mms和88888888包名转发

似乎可以把com.android.mms包名直接内置在自动清除的内部？

**Comment by pppscn** [comment]
短信广播的形式转发短信，却想要消除 短信通知 是吗？

**Comment by TomKing062** [comment]
是的，外加不同ui短信包名不同和有人用第三方短信，内置包名估计行不通

**Comment by pppscn** [comment]
下载每周构建版测试一下

https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

【注意】因为去除了 mmkv 依赖，采用 SharedPreferences 来保存配置，建议测试前离线导出配置，然后全新安装后重新导入配置

![自动消除额外APP通知](https://user-images.githubusercontent.com/5105854/216807108-b3f83d44-6439-4d6c-8954-101bc409224e.png)
