### ISSUE TITLE
[Bug]: 每次打开都弹隐私政策

### ISSUE THREAD

**Issue by milomylo** [pppscn/SmsForwarder#233]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.1.1

### 问题描述

1. 每次打开都要同意隐私政策，但已经配置过转发规则等。
2. 从通知栏点击短信转发器无反应，不能打开软件界面。
3. 有新消息时没有转发，也没有日志（只有此前转发成功的日志）。
4. “转发短信广播”被置为关闭状态。

### 复现步骤

1. 华为Mate 30 Pro，鸿蒙系统。
2. 运行几天后偶现，没有办法稳定复现。
3. 清除缓存后，各个功能都恢复正常。

### 是否必现

否（No）

### 出现问题的手机信息

华为Mate 30 Pro

### 出现问题的安卓版本、系统版本

鸿蒙2.0.0.280 

### 提供截图或视频

https://hk-1252104623.cos.ap-hongkong.myqcloud.com/SVID_20221111_154327_1.mp4

### 提供解决方案

APP内清除缓存。

**Comment by PaulHerrero** [comment]
+1 iQOO 也是

**Comment by henryrabbit** [comment]
+1 我也是，更新系统之后就这样了

**Comment by TomLuck1** [comment]
SONY Xperia Pro-I shows the same issue.
Android version: 13
app version: 3.1.1

**Comment by licess** [comment]
华为nova 5i pro 鸿蒙系统也是这样的问题，应用管理里面强制停止后，重新打开恢复正常

**Comment by pppscn** [comment]
**下载每周构建版测试一下**

https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

【注意】因为去除了 `mmkv` 依赖，采用 `SharedPreferences` 来保存配置，建议测试前离线导出配置，然后全新安装后重新导入配置

**引申阅读：**
https://developer.android.com/training/articles/direct-boot?hl=zh-cn
https://blog.csdn.net/wuweikai0617/article/details/114323540
