### ISSUE TITLE
[Bug]: 转发短信无法获取卡槽信息

### ISSUE THREAD

**Issue by wech88** [pppscn/SmsForwarder#235]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

v3.1.1 1024

### 问题描述

测试手机 化为P9、红米9

服务端收到的转发数据：
{"sign":"Fwvr1ZHfysuVWQqcD%2BQG2lKPqaYSqEBZjS8jTHIQbbQ%3D","from":"+XXXXXXXXXX","content":"+XXXXXXXXXX\nHello this is my now\n\n2022-11-03 23:29:33\ncsalex1","timestamp":"1667489374043"}

\n\n 两个回车中间应该有一行是卡槽信息， 不知道是bug 还是配置问题。

配置规则的时候测试，是可以收到卡槽信息的
{"sign":"MTkMy0IuVdctZdk%2FBHQTfYKGfMcxEwfgX45IHUhO8K8%3D","from":"1235698456","content":"1235698456\ncs123\nSIM1_XXXXXXXXXX\n2022-11-03 23:08:20\ncsalex1","timestamp":"1667488100605"}

### 复现步骤

1. 添加WebHook发送通道， 只填写WebHook地址，其他默认
2. 添加转发规则，选择新建的webhook通道，卡槽选全部，匹配字段全部，其他默认
3. 收到短信后，app自动将短信转发到webhook，WebHook打印出的结果中不包含卡槽信息

### 是否必现

是（Yes）

### 出现问题的手机信息

化为P9、红米9

### 出现问题的安卓版本、系统版本

Android 11             MIUI 12

**Comment by pppscn** [comment]
https://github.com/pppscn/SmsForwarder/wiki/%E3%80%90%E5%BF%85%E8%AF%BB%E3%80%91%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#q%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E5%B7%B2%E7%BB%8F%E5%85%A8%E9%83%A8%E6%8E%88%E4%BA%88%E6%9D%83%E9%99%90%E4%BA%86%E9%80%9A%E7%94%A8%E8%AE%BE%E7%BD%AE%E9%87%8C%E9%9D%A2%E8%8E%B7%E5%8F%96%E5%8D%A1%E6%A7%BD%E4%BF%A1%E6%81%AF%E8%BF%98%E6%98%AF%E6%8F%90%E7%A4%BA%E6%9D%83%E9%99%90%E4%B8%8D%E8%B6%B3

先看看wiki

**Comment by FreeWillDeveloper** [comment]
我也遇到了类似的问题, 我的是双卡手机, 系统是miui11, 在赋予了所有权限依然无法读卡, 甚至在通用设置里手动输入卡槽信息后, 转发的短信还无法带上卡槽信息, 只能在发送通道里手动设置, 后来我就去系统sim卡设置那里, 手动输入运营商和手机号, 然后软件就可以读取卡槽信息了, 转发短信也正常了.

**Comment by sixgod21** [comment]
我也无法识别卡槽，请问解决了吗

**Comment by pppscn** [comment]
下载每周构建版测试一下

https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by pppscn** [comment]
如果转发信息中的卡槽匹配错误，根据`SubId`设置`卡槽主键`（先全部转发，根据转发信息的中SubId，标注对应的卡槽主键，例如下图：卡槽1的SubId实际为2）

![卡槽主键标注](https://foruda.gitee.com/images/1676192538865612361/654d4763_16273.jpeg "卡槽主键标注.jpg")

**Comment by li673835103** [comment]
可以试一试关闭网络短信这项功能，在短信设置中，名字叫miui免费网络短信，估计是网络短信转换成普通短信后转发器没有识别到，作者看到可以测试一下，我的手机型号是红米note10 pro，备机也是同型号同系统

**Comment by bowencool** [comment]
> https://github.com/pppscn/SmsForwarder/wiki/%E3%80%90%E5%BF%85%E8%AF%BB%E3%80%91%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#q%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E5%B7%B2%E7%BB%8F%E5%85%A8%E9%83%A8%E6%8E%88%E4%BA%88%E6%9D%83%E9%99%90%E4%BA%86%E9%80%9A%E7%94%A8%E8%AE%BE%E7%BD%AE%E9%87%8C%E9%9D%A2%E8%8E%B7%E5%8F%96%E5%8D%A1%E6%A7%BD%E4%BF%A1%E6%81%AF%E8%BF%98%E6%98%AF%E6%8F%90%E7%A4%BA%E6%9D%83%E9%99%90%E4%B8%8D%E8%B6%B3
> 
> 先看看wiki

我看了，设置里都正常显示了，未接来电也正常，就短信转发获取不到。

**Comment by imldy** [comment]
> 我也遇到了类似的问题, 我的是双卡手机, 系统是miui11, 在赋予了所有权限依然无法读卡, 甚至在通用设置里手动输入卡槽信息后, 转发的短信还无法带上卡槽信息, 只能在发送通道里手动设置, 后来我就去系统sim卡设置那里, 手动输入运营商和手机号, 然后软件就可以读取卡槽信息了, 转发短信也正常了.

@FreeWillDeveloper  有用，感谢

**Comment by taoliujun** [comment]
> 甚至在通用设置里手动输入卡槽信息后, 转发的短信还无法带上卡槽信息, 只能在发送通道里手动设置, 后来我就去系统sim卡设

我也如此设置了，但是发送短信给卡槽1的号码，转发器却转发了卡槽2的卡信息。
