### ISSUE TITLE
[Suggestion]: 添加停止功能

### ISSUE THREAD

**Issue by hellofinch** [pppscn/SmsForwarder#238]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

希望能够添加退出功能，在启用任务页面隐藏后，没有合适的方法结束程序。强行停止的话，软件有保活机制会自动重启。

### 你觉得该怎么去完善会比较好？【非必答】

想软件后台能够发送停止信号，退出保活机制，结束程序运行。直到下次用户人工启动软件。

**Comment by pppscn** [comment]
通用设置 -- 纯客户端模式
