### ISSUE TITLE
[Suggestion]: 增加接听电话后自动语音回复（自动播放音频文件）的功能

### ISSUE THREAD

**Issue by Zyx-A** [pppscn/SmsForwarder#240]
### 是否有人曾提过类似的问题？

是（Yes）

### 你觉得APP有什么不足之处？

这个功能此前21年有人提过，但没看到下文，被关闭了。
增加接听电话后自动语音回复（自动录制及播放音频文件）的功能。
语音内容的合成，可以留一个接口，用第三方的语音合成功能去识别、合成语音，从而实现机器人应答骚扰电话。

### 你觉得该怎么去完善会比较好？【非必答】

我在这里看到有说怎么播放音频文件，应该有参考价值。
[Android10.0(Q) 实现通话中播放音乐/通话背景音(答录机/魔音功能)](https://blog.csdn.net/u012932409/article/details/113827212)

我只找到这个方法，其他更高版本的实现方法，我没找到。

**Comment by pppscn** [comment]
通话相关的不会去碰，具体原因参考之前的回复或wiki
