### ISSUE TITLE
[Suggestion]: 请求增加定期读取最新短信的功能

### ISSUE THREAD

**Issue by ahfuzhang** [pppscn/SmsForwarder#241]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

不知道为什么，今天的几条短信都没同步。

### 你觉得该怎么去完善会比较好？【非必答】

能否定期读取短信列表，当新短信不在已发送短信的列表中时，自动把上次发送时间点之后的短信都同步一次。
谢谢。

**Comment by pppscn** [comment]
建议直接通过api接口获取

https://github.com/pppscn/SmsForwarder/wiki/%E9%99%84%E5%BD%952%EF%BC%9A%E4%B8%BB%E5%8A%A8%E8%AF%B7%E6%B1%82(%E8%BF%9C%E7%A8%8B%E6%8E%A7%E5%88%B6)
