### ISSUE TITLE
[Suggestion]: 建议增加root权限获取，一劳永逸

### ISSUE THREAD

**Issue by mini1025** [pppscn/SmsForwarder#243]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

各种国产手机都有无法获取权限的问题，有的只能通过应用通知来实现短信转发，但是某些短信，仍然无法获取，建议增加root选项，最高权限应该能解决这种问题

**Comment by pppscn** [comment]
你都有root权限了，尝试直接移动到 /system/app 下试试
