### ISSUE TITLE
[Bug]: 无法读取短信

### ISSUE THREAD

**Issue by leoxu1007** [pppscn/SmsForwarder#244]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

3.1.1

### 问题描述

在MIUI升级到最新Global（MIUI13）版本之后，无法再读取短信，只能读取app通知进行转发。
已经升级到最新版本，但是还是不可以读取。读取短信，以及所有其他权利都授予了，但是仍然不行

### 复现步骤

在MIUI13Global版本之后，安装app，并且到设置里允许所有权利读取。就可以发现，这个app根本不能读取短信内容

### 是否必现

是（Yes）

### 出现问题的手机信息

红米9 Redmi 9 Global

### 出现问题的安卓版本、系统版本

MIUI Global 13.0.1稳定版

**Comment by leoxu1007** [comment]
这里是类似问题：
https://www.zhihu.com/question/513540809/answer/2816268696

**Comment by leoxu1007** [comment]
现在的解决办法是：设置读取app：com.google.android.apps.messaging的通知，然后再把通知内容转发到tg，
效果是这样的：
com.google.android.apps.messaging
【知乎】你的验证码是 739700，此验证码用于登录知乎或重置密码。10 分钟内有效。
10680379460100588194
2022-12-30 11:37:09
Redmi 9

**Comment by pppscn** [comment]
MIUI 13 对应的是Android 12吧，我的10s没切换到开发版之前就是miui 13，应该没问题吧

通知类短信权限开启了吗？关闭miui免费短信

再不行 就开启开发者模式，关闭miui优化

**Comment by leoxu1007** [comment]
你好，所有权限都开启了，甚至包括不使用的权限，比如位置权限等，全都给了，软件耗电无优化，常驻后台全都给了。
不过这个好像不只是smsforwarder的问题，其他读取短信的软件都出问题了，Tracker直接读取不到，MacroDroid提示需要READ SMS权限... 权限我是都给了的，但是没有一个软件读的到。。。

**Comment by leoxu1007** [comment]
之前miui12一直都是好用的，就是升级了13之后，没办法读取短信了。不过现在我改成了读取短信app的通知，也算是曲线救国了

**Comment by leoxu1007** [comment]
问题解决了。在这周，软件更新了之后，能够直接从短信读取了，而不需要读取com.google.android.apps.messaging的通知了。

**Comment by danfate** [comment]
> 问题解决了。在这周，软件更新了之后，能够直接从短信读取了，而不需要读取com.google.android.apps.messaging的通知了。

老哥用的什么版本的smsforwarder？我今天下的最新的，miui14 国际版也碰到了
