### ISSUE TITLE
[Suggestion]: 希望添加转发重试（限定次数）

### ISSUE THREAD

**Issue by rRiInNgG** [pppscn/SmsForwarder#246]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

我使用的是邮件推送（outlook）。有时候会出现邮件转发失败的结果：一般是（①Couldn't connet to host  ****   or  ② Exception reading response*），我觉得应该是网络及服务异常的原因。希望能添加推迟重试转发，通过返回报文返回结果来判断。

### 你觉得该怎么去完善会比较好？【非必答】

希望能添加推迟重试转发，通过返回报文返回结果来判断。非常感谢。

**Comment by pppscn** [comment]
1、`通用设置` 里面的 `请求重试机制` 看看

2、smtp 通常根据返回的状态码判断是否成功

**Comment by rRiInNgG** [comment]
> 1、`通用设置` 里面的 `请求重试机制` 看看
> 
> 2、smtp 通常根据返回的状态码判断是否成功

不好意思没看见，谢谢。
