### ISSUE TITLE
[Suggestion]: 建议 单个”转发规则“ 可绑定多个 ”发送通道“，实现一个规则多渠道转发。

### ISSUE THREAD

**Issue by whenco** [pppscn/SmsForwarder#247]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

建议 单个”转发规则“ 可绑定多个 ”发送通道“，实现一个规则多渠道转发。

**Comment by pppscn** [comment]
下载每周构建版测试一下

https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

【注意】因为去除了 mmkv 依赖，采用 SharedPreferences 来保存配置，建议测试前离线导出配置，然后全新安装后重新导入配置

![转发规则](https://user-images.githubusercontent.com/5105854/216800961-d921203e-d836-49bd-b96e-d58b802f9c06.jpg)
