### ISSUE TITLE
[Suggestion]: 使用  ”自动消除通知“ 配合 ”应用转发规则“   实现应用垃圾通知自动过滤（消除）功能。

### ISSUE THREAD

**Issue by whenco** [pppscn/SmsForwarder#248]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

使用  ”自动消除通知“ 配合 ”应用转发规则“   实现应用垃圾通知自动过滤（消除）功能。

**Comment by pppscn** [comment]
首先 `自动消除通知` 在你的机器上是否可用？ 如果可用的话，创建一个规格 转发到 webhook （url随便填写一个  例如 `https://www.baidu.com` ）这样是否能实现你要的效果？

**Comment by pppscn** [comment]
下载每周构建版测试一下

https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

【注意】因为去除了 mmkv 依赖，采用 SharedPreferences 来保存配置，建议测试前离线导出配置，然后全新安装后重新导入配置

![自动消除额外APP通知](https://user-images.githubusercontent.com/5105854/216807148-f2f5aa0c-8c1c-4f5d-8679-690fe1dd182a.png)
