### ISSUE TITLE
[Bug]: MIUI14无法转发应用通知||手动选择消息重复无效

### ISSUE THREAD

**Issue by YBYCS** [pppscn/SmsForwarder#251]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.1.1

### 问题描述

应用通知无法获取和转发，日志是空的，在勾选转发应用通知会错误跳转权限请求界面（跳转到了允许通知而不是获取通知使用权，并且会卡bug返回又跳转，并且提示没有获取权限，实际上是获取了），猜测与此有关，猜测源码是检测到权限未获取就不转发了。我亲自写了个监听应用消息的软件，使用的是NotificationListenerService来实现，是可以获取到应用通知，所以不是权限问题。其他有怀疑过是因为正则表达式过滤掉了消息，但是去除后依然无效。第二个bug：手动选择消息重复无效，正常接收到短信是可以转发的，但是使用重发消息无反应，测试功能也是正常的。

### 复现步骤

任意情况下都不转发应用通知，任何情况下重发消息不生效。

### 是否必现

是（Yes）

### 出现问题的手机信息

红米 note11TPRO

### 出现问题的安卓版本、系统版本

Android 13 MIUI 14

**Comment by YBYCS** [comment]
主要问题是在miui14中，无法允许给予通知权限（按钮是灰色的）

**Comment by pppscn** [comment]
下载 Weekly Build 版本试试

https://github.com/pppscn/SmsForwarder/actions/runs/3972664649

**Comment by YBYCS** [comment]
仍然没有解决无法允许通知的bug但是可以转发消息

**Comment by pppscn** [comment]
保留一个issue，合并到 https://github.com/pppscn/SmsForwarder/issues/255
