### ISSUE TITLE
[Suggestion]: 能否增加转发到mqtt通道

### ISSUE THREAD

**Issue by gpanzl** [pppscn/SmsForwarder#252]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

能否增加转发到mqtt通道，物联网中这个协议用的很多

**Comment by pppscn** [comment]
什么场景下需要用到这样的方式，罗列几个app看看他们的文档设计

**Comment by gpanzl** [comment]
短信转发到mqtt服务器，终端订阅短信验证码，然后用验证码登录系统进行运行RPA或自动化测试

**Comment by pppscn** [comment]
界面都做完了，现在找不到可以用的依赖包

基本都是基于 `org.eclipse.paho:org.eclipse.paho.client.mqtt` 开发的，但是这玩意最低支持 minSdk 21

**Comment by pppscn** [comment]
下载weekly版，帮忙测试一下

https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

目前只测试了mqtt（通过 http://www.emqx.io/online-mqtt-client#/）

**Comment by pppscn** [comment]
后续有问题再提issue吧

**Comment by KleinerSource** [comment]
请问mqtt应该如何配置? 我配置好了测试的时候 显示请求失败: MQTT连接成功 
服务器那边收到的信息只有 {"terminal_uid":"客户端id"} 而且只生成了 输入消息主题  没有输出消息主题

**Comment by pppscn** [comment]
参考这个重新测试

https://github.com/pppscn/SmsForwarder/issues/310#issuecomment-1624789325

> 后续有问题再提issue吧
