### ISSUE TITLE
[Bug]: Android 13 无法授予通知权限

### ISSUE THREAD

**Issue by yinguohang** [pppscn/SmsForwarder#255]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.1.1

### 问题描述

在Pixel 7 Pro和iQOO Neo 7上测试，均无法成功打开通知。前者开关是灰色的，后者打开之后推出会自动关上。可能与Android 13 相关：https://developer.android.com/about/versions/13/changes/notification-permission?hl=zh-cn

### 复现步骤

在授予通知权限的时候，会跳转到系统通知权限页面，打开后会调回应用但是其实通知权限没有打开。

### 是否必现

是（Yes）

### 出现问题的手机信息

Pixel 7 Pro / iQOO Neo 7

### 出现问题的安卓版本、系统版本

Android 13

### 提供解决方案

https://developer.android.com/about/versions/13/changes/notification-permission?hl=zh-cn
可能需要额外的权限

**Comment by pppscn** [comment]
下载每周构建版试试
https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by yinguohang** [comment]
还是不行哎，会循环这个过程

https://user-images.githubusercontent.com/6234533/216780891-a25d5310-7018-4c22-afc2-78b662b6edc3.mp4

**Comment by pppscn** [comment]
测试机器：MI 10S
系统版本：MIUI 14 V14.0.23.1.30.DEV
安卓版本：Android 13

测试可以，其他机型的机油也帮忙测试一下

**Comment by pppscn** [comment]
![Screenshot_20230208-223332_Trebuchet](https://user-images.githubusercontent.com/5105854/217561248-a37c78fd-a939-412e-873f-df44657430bf.png)
![Screenshot_20230208-223658_Trebuchet](https://user-images.githubusercontent.com/5105854/217561261-dad13fd2-3a1a-4549-87e9-4b7951031da5.png)

测试机器：Google Pixel 2 XL
系统版本：LineageOS-20.0-20230202-nightly-taimen
安卓版本：Android 13

测试通过

**Comment by mirtu-ko** [comment]
测试机器：Redmi K40 Gaming
系统版本：MIUI 14 V14.0.23.2.6.DEV
安卓版本：Android 13

每周构建版本#72，仍然无法开启通知。
![photo_2023-02-11 12 26 22](https://user-images.githubusercontent.com/5743981/218239805-bc7e68d2-5f0d-4dcb-ad2c-4fdc15d10751.jpeg)

**Comment by pppscn** [comment]
> 测试机器：Redmi K40 Gaming 系统版本：MIUI 14 V14.0.23.2.6.DEV 安卓版本：Android 13
> 
> 每周构建版本#72，仍然无法开启通知。 ![photo_2023-02-11 12 26 22](https://user-images.githubusercontent.com/5743981/218239805-bc7e68d2-5f0d-4dcb-ad2c-4fdc15d10751.jpeg)

![微信截图_20230211144214](https://user-images.githubusercontent.com/5105854/218244682-9d3eeffb-4dd8-44d0-a69e-0899129abf63.png)

按这个方式手动开启试试

**Comment by mirtu-ko** [comment]
> 

尝试后无法找到“隐私管理”及相关设置。目前已知的两个设置入口， 都无法开启：
1. App的“应用信息”-“通知管理”，进入后无法开启，见上面截图；
2. “设置”-“通知与控制中心”-“通知管理”，列表无法找到“短信转发器”，故无法开启。

**Comment by pppscn** [comment]
> > 
> 
> 尝试后无法找到“隐私管理”及相关设置。目前试过的两个设置入口， 都无法开启：
> 
> 1. App的“应用信息”-“通知管理”，进入后无法开启，见上面截图；
> 2. “设置”-“通知与控制中心”-“通知管理”，列表无法找到“短信转发器”，故无法开启。
> 
> 可否指导一下“隐私管理”及相关设置的操作方式～

设置里面搜索【设备和应用通知】

**Comment by mirtu-ko** [comment]
> > > 
> > 
> > 
> > 尝试后无法找到“隐私管理”及相关设置。目前试过的两个设置入口， 都无法开启：
> > 
> > 1. App的“应用信息”-“通知管理”，进入后无法开启，见上面截图；
> > 2. “设置”-“通知与控制中心”-“通知管理”，列表无法找到“短信转发器”，故无法开启。
> > 
> > 可否指导一下“隐私管理”及相关设置的操作方式～
> 
> 设置里面搜索【设备和应用通知】

【设备和应用通知】里所有项都是开启的，应该是授权读取通知的时候开启的。尝试关闭再打开，仍然不能在通知栏常驻通知；

升级MIUI14前，运行应用时，通知栏会显示常驻通知（可以自定义通知文案）。升级后，应用使用正常，可以转发短信、通话和通知，只是无法常驻通知；

**Comment by pppscn** [comment]
请以上各位机油重新下载weekly版，再帮忙测试一下

https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by mirtu-ko** [comment]
Weekly build #74，仍然无法开启。尝试卸载应用，重新安装，依然无法开启。MIUI 14 V14.0.23.2.6.DEV

**Comment by pppscn** [comment]
再来，应该破案了，我的机器是debug模式安装的  自带的LeakCanary会帮它自动加上申请的权限

重新下载weekly版，再帮忙测试一下

https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by mirtu-ko** [comment]
> 再来，应该破案了，我的机器是debug模式安装的 自带的LeakCanary会帮它自动加上申请的权限
> 
> 重新下载weekly版，再帮忙测试一下
> 
> https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

可以了！👍

**Comment by qw805880101** [comment]
想了解一下这个问题是怎么解决的？
![image](https://github.com/pppscn/SmsForwarder/assets/13215988/891913b0-29c4-4d02-a17d-e2571a647682)
