### ISSUE TITLE
[Suggestion]: 能否添加【远程定位】和【远程修改通讯录】功能

### ISSUE THREAD

**Issue by spysir** [pppscn/SmsForwarder#256]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

建议大佬添加【远程定位】和【远程修改通讯录】功能

**Comment by pppscn** [comment]
你想用这两个功能干嘛?

**Comment by spysir** [comment]
> 你想用这两个功能干嘛?

帮父母远程添加联系人到通讯录，定位父母孩子的位置

**Comment by mymine** [comment]
> 你想用这两个功能干嘛?

最新代码编译版，点击通道测试闪退。

**Comment by pppscn** [comment]
> 

收到，晚上有空测试一下

**Comment by pppscn** [comment]
> > 你想用这两个功能干嘛?
> 
> 最新代码编译版，点击通道测试闪退。

已修复，等 actions 编译完再试试

**Comment by mymine** [comment]
> > > 你想用这两个功能干嘛?
> > 
> > 
> > 最新代码编译版，点击通道测试闪退。
> 
> 已修复，等 actions 编译完再试试

👌

**Comment by pppscn** [comment]
远程定位 功能已经加上

https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by pppscn** [comment]
远程加话簿 功能已经加上

https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml
