### ISSUE TITLE
[Suggestion]: 有个脑洞

### ISSUE THREAD

**Issue by Bitcion** [pppscn/SmsForwarder#257]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

在找一个短信转发，把家里的短信接受号码转发到常用设备上，找到了这个应用。

看了下突然想起打算收一台pixel当Google无限空间相册的备份相册，但是没找到好的方案把图片传到手机的相册里实现自动备份。

既然能把短信转发出来，那不妨也把图片转入pixel相册，这样也算是有个远程备份方案。pixel设想中的方案都是局域网方案，实现起来也不方便。

**Comment by pppscn** [comment]
来来来，跟我念一遍 `[SmsForwarder](https://github.com/pppscn/SmsForwarder)` 

这脑洞严重超出了项目初衷了吧？（虽然现在也好像也超了）

**Comment by Bitcion** [comment]
> 来来来，跟我念一遍 [SmsForwarder](https://github.com/pppscn/SmsForwarder)
> 
> 这脑洞严重超出了项目初衷了吧？（虽然现在也好像也超了）

对呀，我看你都整了微信小程序，感觉不差这一个小接口。哈哈哈哈哈

**Comment by pppscn** [comment]
暂不考虑支持该功能

**Comment by shellus** [comment]
使用syncthing，在两个机器都安装好来实现相册同步。
