### ISSUE TITLE
[Suggestion]: 内置ddns服务

### ISSUE THREAD

**Issue by Ynkcc** [pppscn/SmsForwarder#259]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

随着ipv6的普及，大多数安卓设备都能够得到ipv6公网地址。使用ipv6进行主动控制是十分可行的。但是获得的ipv6地址并不是固定的。所以需要ddns，将ipv6地址绑定到域名。

### 你觉得该怎么去完善会比较好？【非必答】

能够简单配置，像ddns-go那样

**Comment by pppscn** [comment]
问题是不是所有获取的ipv6都能直接公网访问，你试试你当地的ipv6能不能访问？

我手机测试：福州电信、福州移动，获取的ipv6都不行

**Comment by Ynkcc** [comment]
我当地的ipv6可以访问，湖南永州移动和上海电信网络。

**Comment by pppscn** [comment]
**连接WiFi**
```
77777777
网络类型: Wifi
本地IP: 10.8.11.99
Http Server: http://10.8.11.99:5000
网络状态监控
SubId：0
2023-02-14 09:51:12
pppscn的Mi 10S
```

**移动网络**
```
77777777
网络类型: 5G网络
运营商: 中国移动
本地IP: 240e:464:318:3797:f735:8348:3a59:0000
Http Server: http://[240e:464:318:3797:f735:8348:3a59:0000]:5000
网络状态监控
SubId：0
2023-02-14 09:47:24
pppscn的Mi 10S
```

**Comment by pppscn** [comment]
DDNS就算了，加一个网络状态变化提醒，需要ddns自己在webhook端实现

https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by iguri** [comment]
> **连接WiFi**
> ```
> 77777777
> 网络类型: Wifi
> 本地IP: 10.8.11.99
> Http Server: http://10.8.11.99:5000
> 网络状态监控
> SubId：0
> 2023-02-14 09:51:12
> pppscn的Mi 10S
> ```
> 
> **移动网络**
> ```
> 77777777
> 网络类型: 5G网络
> 运营商: 中国移动
> 本地IP: 240e:464:318:3797:f735:8348:3a59:0000
> Http Server: http://[240e:464:318:3797:f735:8348:3a59:0000]:5000
> 网络状态监控
> SubId：0
> 2023-02-14 09:47:24
> pppscn的Mi 10S
> ```

我想知道开发者你是怎么获取的ipv6地址的，我的ipv6不止一条，而且也没有特征可言，所以ddns-go每次获取到的基本都不能访问，而sms的网络监控里的地址恰好每次都是能用的
