### ISSUE TITLE
短信通过邮件转发功能，是否可以做成调用系统邮件客户端配置。发送邮件

### ISSUE THREAD

**Issue by linweifu** [pppscn/SmsForwarder#26]
短信通过邮件转发功能，是否可以做成调用系统邮件客户端转发短信邮件
可以加强一下安全控制。
就可以禁止 SMSFORWARDER 联网。
增加了安全风险控制

**Comment by pppscn** [comment]
禁止 SMSFORWARDER 联网是出于什么目的呢？ 都开源在这里了
