### ISSUE TITLE
[Suggestion]: 请问可以适配Android 4.3吗？

### ISSUE THREAD

**Issue by EileenFengGu** [pppscn/SmsForwarder#260]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

请问可以适配Android 4.3吗？谢谢，您辛苦了！

**Comment by pppscn** [comment]
不会继续往下适配，现在为了兼容4.4，很多依赖库没法用，代码里面更是要特殊处理
