### ISSUE TITLE
[Bug]: 3.1.1 3.1.0 企业微信应用无法转发，日志显示处理中，点击重发后闪退

### ISSUE THREAD

**Issue by renzcu** [pppscn/SmsForwarder#261]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.1.1 v3.1.0

### 问题描述

3.11 3.10 企业微信应用无法转发，日志显示处理中，点击重发后闪退,然后测试降低版本，3.0.9正常

### 复现步骤

正常使用即出现，使用百度验证码和给运营商发短信测试

### 是否必现

是（Yes）

### 出现问题的手机信息

非手机，wifi棒子

### 出现问题的安卓版本、系统版本

Android 4.4.4

### 提供解决方案

降版本到3.0.9后正常

**Comment by pppscn** [comment]
先测试一下weekly版本是否还有这个问题
https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by pppscn** [comment]
没有后续反馈，先关闭了
