### ISSUE TITLE
[Suggestion]: 关于远程控制的疑问

### ISSUE THREAD

**Issue by sunny7010** [pppscn/SmsForwarder#262]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

目前采取Frpc的方式连通
如果服务端网络环境经常变化（如本地ip变化导致公网ip改变，或手机使用移动数据），是否远程控制就无法较好地使用

**Comment by pppscn** [comment]
frpc的意义是什么?  就是用 frps 的公网ip（固定的）来实现远程控制吗？

认真看看wiki：https://github.com/pppscn/SmsForwarder/wiki/%E9%99%84%E5%BD%957%EF%BC%9AFrpc%E5%86%85%E7%BD%91%E7%A9%BF%E9%80%8F

**Comment by sunny7010** [comment]
看不懂哈哈

**Comment by yang3121099** [comment]
> 图上的服务端公网IP：88.88.88.88 就是固定的，不管frpc客户端的ip怎么变，都可以通过 88.88.88.88 来远程控制

作者您好，我正在尝试远程控制发短信的新功能，正好看到这个帖子解释的很清楚，想请教一下您。

这个原理我清楚了，但也有这个issue类似的问题，rpc的目的就是保证固定端口，但是这个rpc开启的过程中配置文件里面有local_ip这个不应该要设置成和当前手机ip对应吗，还是说他是动态的自动连接手机和公网ip呢，因为我注意到wifi/5G的切换，监听端口就变化了，这时rpc还能连接二者吗？

另一个问题是咱们的小程序还在更新，目前阶段登录后也没有反应，这是正常情况还是我这里配置不正确呢？

再次表示感谢！
