### ISSUE TITLE
[Suggestion]: 很好用, 公安局很快就给我打电话了

### ISSUE THREAD

**Issue by lly-ke** [pppscn/SmsForwarder#263]
### 是否有人曾提过类似的问题？

是（Yes）

### 你觉得APP有什么不足之处？

使用风险提示有点不足

### 你觉得该怎么去完善会比较好？【非必答】

检测手机安装国家反诈中心app, 特殊提示一下使用风险 

我上午安装使用几下, 晚上公安局就来电话了

**Comment by lly-ke** [comment]
我刚使用看了帮助文档有这个风险, 但还是持有侥幸心理

**Comment by pppscn** [comment]
https://github.com/pppscn/SmsForwarder/wiki/%E3%80%90%E5%BF%85%E8%AF%BB%E3%80%91%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#q%E8%A3%85%E4%BA%86%E7%9F%AD%E4%BF%A1%E8%BD%AC%E5%8F%91%E5%99%A8%E4%B8%BA%E4%BB%80%E4%B9%88%E6%94%B6%E5%88%B0%E5%8F%8D%E8%AF%88%E4%B8%AD%E5%BF%83%E7%9A%84%E6%9D%A5%E7%94%B5%E6%88%96%E7%9F%AD%E4%BF%A1

**Comment by sunny7010** [comment]
反诈app和转发app都没错，错的是俩碰一起了
