### ISSUE TITLE
[Bug]: frpc 客户端发送短信，取消对手机号检测限制

### ISSUE THREAD

**Issue by sunteta** [pppscn/SmsForwarder#264]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

否（No）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

V all

### 问题描述

在 frpc 客户端，远程连接成功后，进入 发送短信，在输入手机号的时候。只能中国的手机号这样受很大的局限
因为我用的是HK卡，他就不是那位数。会造成不能发。
如果使用外卡也会有不同的位数。所以建议取消检测。

其实手机发短信也是不检测的手机号的。不然都无法发特定号码上载信息的比方 1066XXXXXX QQ号找回用得到。

### 复现步骤

在 frpc 客户端，远程连接成功后，进入 发送短信，在输入手机号的时候。只能中国的手机号这样受很大的局限

### 是否必现

是（Yes）

### 出现问题的手机信息

全品牌

### 出现问题的安卓版本、系统版本

全版本

### 提供解决方案

建议取消手机号检测。

**Comment by pppscn** [comment]
已调整，下载weekly版试试
https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml
