### ISSUE TITLE
更新v3.2.0后无法转发短信

### ISSUE THREAD

**Issue by kof8855** [pppscn/SmsForwarder#265]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

否（No）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

v3.2.0

### 问题描述

小米12X miui 13.0.15
昨天在酷安点了更新后，短信就不会自动转发了，发送通道没有问题。感觉是没有真正读取到短信，但是权限已经给了。清理数据卸载干净重装也是一样。重装上一个版本就正常

### 复现步骤

小米12X miui 13.0.15
昨天在酷安点了更新后，短信就不会自动转发了，发送通道没有问题。感觉是没有真正读取到短信，但是权限已经给了。清理数据卸载干净重装也是一样。重装上一个版本就正常

### 是否必现

是（Yes）

### 出现问题的手机信息

小米12X

### 出现问题的安卓版本、系统版本

MIUI 13.0.15

**Comment by kof8855** [comment]
所有权限都给了，也不行。
![0a95d186613c6b96a5cd12b2cfa523a](https://user-images.githubusercontent.com/57129756/219305773-9ece2c81-387d-4843-971f-6778d1941500.jpg)

**Comment by kof8855** [comment]
哪个目录里面能看到日志？？我看看日志记录，到底是哪一步出问题导致无法转发

**Comment by kof8855** [comment]
哪个目录里面能看到日志？？我看看日志记录，到底是哪一步出问题导致无法转发

**Comment by mini1025** [comment]
我的也是，360N4S，3.1.1用的是转发应用通知的形式，来转发短信，更新成3.2.0之后，无法转发

**Comment by pppscn** [comment]
是全新安装的，还是直接升级的?   总开关重新打开了没?

参见更新日志：

- `v3.2.0` 去除了 mmkv 依赖，采用 SharedPreferences 来保存配置，升级之后通用设置中的配置请重新配置，具体原因参见 https://github.com/pppscn/SmsForwarder/issues/245
- 升级完毕后，建议离线导出配置，完全卸载干净全新安装后再导入配置（可以避免一些莫名其妙的玄学问题，例如：耗电异常）

**Comment by massten** [comment]
更新完之后会提示是否发送短信，需要手动确认才能发送
