### ISSUE TITLE
[Bug]: 红米note10 pro开启miui免费网络短信功能后，会导致转发器无法转发

### ISSUE THREAD

**Issue by li673835103** [pppscn/SmsForwarder#266]
### 是否有人曾提过类似的问题

是（Yes）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

3.2.0

### 问题描述

打开该功能后，转发器日志没有记录，转发就更没有可能了，我看到文档有好几个同样问题的，权限授予依然不能转发的，很有可能是同样的问题，该功能只有开机第一次使用时会提示开启，或者之前开启过，手机登陆账号后会同步设置也会自动开启

### 复现步骤

只要打开该功能，就会导致转发器不转发，也读取不到短信内容，百分百复现，关闭即可正常转发

### 是否必现

是（Yes）

### 出现问题的手机信息

主机备机都是同型号note10 pro

### 出现问题的安卓版本、系统版本

系统版本13.0.11稳定版，安卓12

### 提供解决方案

推测网络短信转换成短信的过程，转发器无法读取，没有读取，更没有日志提供，只能靠作者大大测试了找问题了

**Comment by pppscn** [comment]
参见wiki常见问题

https://github.com/pppscn/SmsForwarder/wiki/%E3%80%90%E5%BF%85%E8%AF%BB%E3%80%91%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#q%E5%B0%8F%E7%B1%B3%E7%BA%A2%E7%B1%B3%E6%89%8B%E6%9C%BA%E4%B8%BA%E4%BB%80%E4%B9%88%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9nft%E6%95%B0%E5%AD%97%E8%97%8F%E5%93%81%E4%B9%8B%E7%B1%BBapp%E7%9A%84%E9%80%9A%E7%9F%A5%E7%B1%BB%E7%9F%AD%E4%BF%A1%E7%BB%8F%E5%B8%B8%E6%80%A7%E8%BD%AC%E5%8F%91%E4%B8%8D%E4%BA%86

这个不是bug，是它不会有短信广播
