### ISSUE TITLE
[Bug]: 华为手机转换为系统程序必闪退

### ISSUE THREAD

**Issue by NekoMua** [pppscn/SmsForwarder#267]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.2.0

### 问题描述

在3.2.0之前的版本中并没有这个问题，但是升级到3.2.0之后，只要转换为系统程序那么必定闪退，程序根本打不开，从系统程序中移动回用户程序也会闪退，但在移动到系统程序之前，第一次直接安装的时候并不会闪退，还有一个问题就是，软件运行久了，程序就再也不会转发短信了，总是会延迟很久很久，或者说是根本不转发短信，权限都是给齐的，而那些电量，或者是网络状况有时候会转发有时候不会

### 复现步骤

通过相关工具，如高级助手，通过Magisk转换成系统应用，重启之后打开必定闪退，长时间不熄屏一直开着，软件在转发几天之后就再也不会转发任何短信，或者是延迟好几天才有通知

### 是否必现

是（Yes）

### 出现问题的手机信息

华为Nova2Plus(BAC-AL00)

### 出现问题的安卓版本、系统版本

Android 8.0，EMUI8.0.0.385

**Comment by pppscn** [comment]
转为系统应用的目的是什么？  没有华为手机，只能自己调试看看了

如果有能力，用Android Studio的Logcat抓一下日志，贴出来才有意义

**Comment by NekoMua** [comment]
> 转为系统应用的目的是什么？  没有华为手机，只能自己调试看看了
> 
> 如果有能力，用Android Studio的Logcat抓一下日志，贴出来才有意义

我再研究一下，到时候试试看

**Comment by pppscn** [comment]
请提供一下crash日志，adb命令logcat抓取日志

https://blog.csdn.net/m0_64776928/article/details/126005119

**Comment by pppscn** [comment]
没有后续反馈信息，先行关闭
