### ISSUE TITLE
[Suggestion]: 请问能否定时发送一个心跳包到服务器

### ISSUE THREAD

**Issue by Xwudao** [pppscn/SmsForwarder#268]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

如题，这样服务可以知道应用是否正常运行，能否正常工作；然后作相应逻辑处理；

**Comment by pppscn** [comment]
说实话，我有点懒得弄，可以曲线救国

通过 网络状态通知`77777777`、电池状态、电量变化通知` 88888888` 转发到你的api去，自定义模板里面填写你要的心跳包内容

设置可以通过httpserver的api定时来查也行

**Comment by Xwudao** [comment]
好的，了解，谢谢；
