### ISSUE TITLE
[Suggestion]: 希望添加“保存到本地日志”作为一个发送通道

### ISSUE THREAD

**Issue by haozihong** [pppscn/SmsForwarder#269]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

希望能将“保存到本地日志”也添加为发送通道之一。

**进一步希望的功能**：可以按照一些规则新开日志文件。如在每天某时间新开日志文件，或与上次消息间隔xx分钟后新开日志，或超过多少条消息后新开日志等。

**我遇到的使用场景**：有一些群每天有巨量的消息，都看的话浪费时间，不看又怕错过关键信息。所以想每天空闲时一并喂给AI来概括一下聊天概要。因此需要把聊天记录保存下来。本想尝试微信机器人，但据反馈大概率会被封，不敢冒险，因此考虑从通知消息入手。
虽说通过软件现有的网络转发再结合一些手段，也可以实现这个功能，但感觉是绕了很远的弯路。

感谢开发者带给我们的非常棒的实用软件！

**Comment by pppscn** [comment]
建议内网建webhook来接收，保存到手机本地之后，取出来也不方便吧

**Comment by haozihong** [comment]
是指发送到127.0.0.1，并在手机上运行一个server将其写入文件吗？

目前我是用各种同步软件（如onedrive+foldersync）来实现手机与电脑之间的日常文件同步的。

**Comment by pppscn** [comment]
我指的是直接在电脑上起一个webhook，这样AI就能直接处理这个日志了

**Comment by haozihong** [comment]
嗯我也想过。这意味着我需要有个全天运行、不能移动的电脑，以及公网IP，换言之一个服务器。

思前想后，还是先保存在手机本地，然后在有空有AI分析的时候再传输日志比较简单。所以来提了这个issue。当然这只是我个人期望

**Comment by pppscn** [comment]
小众需求，暂不考虑加入该功能
