### ISSUE TITLE
[Suggestion]: 请问能支持小米的免费网络短信功能吗？

### ISSUE THREAD

**Issue by yienzhu** [pppscn/SmsForwarder#270]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

简单易用，功能非常全。

### 你觉得该怎么去完善会比较好？【非必答】

希望能增加对小米免费网络短信的支持

**Comment by pppscn** [comment]
支持不了，这玩意不走短信广播，你可以试试用APP通知的形式能不能转发
