### ISSUE TITLE
[Bug]: 电池充满电以后无限重复提醒

### ISSUE THREAD

**Issue by Sostay** [pppscn/SmsForwarder#271]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

否（No）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

v3.1.1

### 问题描述

设置的短信和电池状态转发到飞书，每次电池充满以后，飞书每隔4分钟持续收到提醒，经常一次能收到几百条通知……
希望能调整为充满电只提醒一次就好~

### 复现步骤

添加了应用转发规则（88888888），安全电量范围设置了20-100，未开启【监听电池状态变化】和【持续提醒】

### 是否必现

是（Yes）

### 出现问题的手机信息

Google Nexus 5

### 出现问题的安卓版本、系统版本

Android 13

**Comment by pppscn** [comment]
关闭【持续提醒】即可

**Comment by Sostay** [comment]
> 关闭【持续提醒】即可

是关着的……

**Comment by pppscn** [comment]
`安全电量范围设置了20-100`

充满电之后，充电器一直插着？  开启【监听电池状态变化】你可能会发现，它在不断的放电再充电（就是低于100又上100的过程）

把上限设置为 95% 试试

**Comment by pppscn** [comment]
或者 `通过低电量通知自动开关智能插座`，参考

https://github.com/pppscn/SmsForwarder/wiki/%E9%99%84%E5%BD%958%EF%BC%9A%E6%9C%BA%E6%B2%B9%E7%9A%84%E5%A5%87%E6%80%9D%E5%A6%99%E6%83%B3#%E9%80%9A%E8%BF%87%E4%BD%8E%E7%94%B5%E9%87%8F%E9%80%9A%E7%9F%A5%E8%87%AA%E5%8A%A8%E5%BC%80%E5%85%B3%E6%99%BA%E8%83%BD%E6%8F%92%E5%BA%A7iphone%E7%9A%84%E5%BF%AB%E6%8D%B7%E6%8C%87%E4%BB%A4%E5%AE%9E%E7%8E%B0
