### ISSUE TITLE
[Suggestion]: 你好，请问可以获取到 应用通知 的跳转 Schema 吗

### ISSUE THREAD

**Issue by findmio** [pppscn/SmsForwarder#272]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

你好，请问可以获取到 应用通知 的跳转 Schema 吗

比如这种，点击会跳转到用户聊天详情页面。请问可以获取到这个链接吗

![AE35D2F97C49C101BF7E5DDEC70005BE](https://user-images.githubusercontent.com/24765095/223094064-bd6211c4-f2e7-4bf0-8c51-febda0e02756.jpg)

**Comment by pppscn** [comment]
A手机获取的通知中Schema，转发到B手机中，然后点击一下跳转？  这是什么操作？

**Comment by findmio** [comment]
> A手机获取的通知中Schema，转发到B手机中，然后点击一下跳转？ 这是什么操作？

通知中的 Schema 可能会包含一些 id，想要获取这些数据

**Comment by pppscn** [comment]
新增：`{{通知Schema}}`(英文系统`{{SCHEMA}}`)标签以获取应用通知的Schema（试验性）

下载weekly版本试试，貌似获取到不是你想象的url

**Comment by Geolem** [comment]
> 新增：`{{通知Schema}}`(英文系统`{{SCHEMA}}`)标签以获取应用通知的Schema（试验性）
> 
> 下载weekly版本试试，貌似获取到不是你想象的url

使用{{通知Schema}}获取到的基本是null，就今日头条或央视新闻app的是类似“android.app.Notification$BigTextStyle”

![image](https://user-images.githubusercontent.com/7186314/227850511-2715322b-a957-4d30-a819-4f2df36e7701.png)

<img width="304" alt="image" src="https://user-images.githubusercontent.com/7186314/227850370-8f0a6fc6-eac7-4318-a944-35e542c6c53b.png">

**Comment by pppscn** [comment]
下载weekly版本试试，还是获取到不是你想象的url，暂时无解了

**Comment by findmio** [comment]
> 下载weekly版本试试，还是获取到不是你想象的url，暂时无解了

好奇问一下这个通知的数据结构是怎么样子的，可以讲一下吗

**Comment by pppscn** [comment]
暂时无解，期待专业人士提交PR吧
