### ISSUE TITLE
[Suggestion]: 支持Bark推送加密

### ISSUE THREAD

**Issue by HyWell** [pppscn/SmsForwarder#273]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

Bark 1.3.0版本支持推送加密，AES的，希望添加这块支持，在数据加密后进行发送

**Comment by Tam-0130** [comment]
希望添加bark 加密支持

**Comment by zhongwen25** [comment]
附议

**Comment by pppscn** [comment]
下载每周构建版测试
https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml
