### ISSUE TITLE
[Bug]: 通过转发日志中重新发送短信时，{{接收时间}}错误

### ISSUE THREAD

**Issue by luanzun** [pppscn/SmsForwarder#275]
### 是否有人曾提过类似的问题

是（Yes）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.2.0

### 问题描述

转发失败的历史短信，在转发日志中点击重发消息，模板中的{{接收时间}}应该是短信的接收时间，但实际上短信通知文案中是当前实时时间。自定义模板和默认模板均是如此。

3.0.9版本出现过这个问题，现在又有了。

### 复现步骤

1.转发日志中找到不是当前刚收到的短信信息;
2.点击 重新发送
3.在服务器查看数据

### 是否必现

是（Yes）

### 出现问题的手机信息

荣耀9

### 出现问题的安卓版本、系统版本

Android9 ,的、EMUI9.1.0

### 提供截图或视频

![img_v2_a79368a1-6c17-47e2-ba07-535b632e2f2g](https://user-images.githubusercontent.com/7591175/224545523-a3704d9d-2865-44f6-bbf2-706473511081.jpg)

![image](https://user-images.githubusercontent.com/7591175/224545439-e47d4051-9aef-450d-af94-580f5c7f16fa.png)

**Comment by pppscn** [comment]
已修复，下载weekly版本试试
