### ISSUE TITLE
[Suggestion]: 希望增加比如新闻类等客户端点击推送时的那个跳转文章地址的转发

### ISSUE THREAD

**Issue by Geolem** [pppscn/SmsForwarder#276]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

目前转发通知，有通知的标题、摘要、时间、app名称、包名，希望增加比如新闻类等客户端点击推送时的那个跳转文章URL地址的转发

**Comment by pppscn** [comment]
新增：`{{通知Schema}}`(英文系统`{{SCHEMA}}`)标签以获取应用通知的Schema（试验性）

下载weekly版本试试，貌似获取到不是你想象的url

**Comment by pppscn** [comment]
合并至 https://github.com/pppscn/SmsForwarder/issues/272 一起处理
