### ISSUE TITLE
[Suggestion]: 没有流量推送

### ISSUE THREAD

**Issue by Dream935** [pppscn/SmsForwarder#277]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

备用机大部分用来开热点，可以设置一个流量推送，监控手机数据，每天自动发，流量使用多少以及剩余多少，推送根据用户自己设置什么时候推送

### 你觉得该怎么去完善会比较好？【非必答】

监控收集数据用量，可以监控系统应用热点使用多少流量，

**Comment by pppscn** [comment]
不会考虑此功能

因为这个需要smsf主动发短信去运营商查询，到时又要被扣屎盆子，一群没事找事的人专门找茬

自己可以转发运营商的短信来实现，例如移动：

```
【流量日提醒】您好！截至3月26日 8时32分，您（158****4566）本月国内流量已使用0KB。信息仅供参考。回复“28”查询具体流量使用情况。【中国移动】
```
