### ISSUE TITLE
[Suggestion]: 建议增加软件总开关选项

### ISSUE THREAD

**Issue by lxr760** [pppscn/SmsForwarder#278]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

软件安装后即运行，当不想使用时，无法暂停。而后台保活机制也会造成手机耗电量增加

### 你觉得该怎么去完善会比较好？【非必答】

增加一个总开关。开启后软件进行各种转发操作和后台保活。当不需要时，开关关闭，软件不转发，不保持后台保活，减少耗电量

**Comment by pppscn** [comment]
通用设置中开启纯客户端模式 即可
