### ISSUE TITLE
请问MQTT如何配置

### ISSUE THREAD

**Issue by KleinerSource** [pppscn/SmsForwarder#280]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.2.0

### 问题描述

请问mqtt应该如何配置? 我配置好了测试的时候 显示   请求失败: MQTT连接成功
服务器那边收到的信息只有 {"terminal_uid":"客户端id"} 而且只生成了 输入消息主题 没有输出消息主题 

### 复现步骤

输入mqtt账号密码
填入了输入消息主题和输出消息主题 还有客户端ID

### 是否必现

是（Yes）

### 出现问题的手机信息

MI 5S

### 出现问题的安卓版本、系统版本

MIUI 10

**Comment by pppscn** [comment]
目前只测试了mqtt（通过 [http://www.emqx.io/online-mqtt-client#/）](http://www.emqx.io/online-mqtt-client#/%EF%BC%89)

**Comment by pppscn** [comment]
没有后续反馈，暂时关闭了

**Comment by KleinerSource** [comment]
错误日志内容为 
06-12 09:19:01.330  2676  2676 W MessengerIpcClient: Received response for unknown request: 1
06-12 09:19:10.871  3475  3518 D EGL_adreno: eglMakeCurrent: 0x7fff6a364d80: ver 3 0 (tinfo 0x7fff6a215f80)
06-12 09:19:10.920  1407  3226 D audio_hw_hal: raw_start_output_stream, stream=0xf671b000, sampleRate=48000, channel=2, bps=16, bufSize=4096
06-12 09:19:10.922  3475  3632 D SocketFragment: SocketSetting(method=MQTT, address=10.0.0.51, port=1883, msgTemplate=, secret=, username=ksmqtt, password=Ks123333, inCharset=UTF-8, outCharset=UTF-8, inMessageTopic=smsf/state, outMessageTopic=smsf/cmd, uriType=, path=, clientId=smstest)
06-12 09:19:10.925  3475  3633 V MQTT    : 寮€濮嬭繘琛岃繛鎺?{uri: 'tcp://10.0.0.51:1883', username: 'ksmqtt', password: 'Ks123333'}
06-12 09:19:10.937  3475  3475 I [LiveEventBus]: post: finish with key: key_sender_test
06-12 09:19:10.937  3475  3475 I [LiveEventBus]: message received: finish
06-12 09:19:11.407  3475  3633 V MQTT    : 杩炴帴鎴愬姛 {uri: 'tcp://10.0.0.51:1883', username: 'ksmqtt', password: 'Ks123333'}
06-12 09:19:11.409  3475  3633 W System.err: java.lang.Exception: Toast callstack! strTip=
06-12 09:19:11.409  3475  3633 W System.err:    at android.widget.Toast.show(Toast.java:143)
06-12 09:19:11.409  3475  3633 W System.err:    at com.idormy.sms.forwarder.utils.XToastUtils$Companion.b(Unknown Source:13)
06-12 09:19:11.409  3475  3633 W System.err:    at com.idormy.sms.forwarder.utils.SendUtils.f(SendUtils.kt:14)
06-12 09:19:11.409  3475  3633 W System.err:    at com.idormy.sms.forwarder.utils.sender.SocketUtils$Companion$sendMsg$2$1.invoke(SocketUtils.kt:2)
06-12 09:19:11.409  3475  3633 W System.err:    at com.idormy.sms.forwarder.utils.sender.SocketUtils$Companion$sendMsg$2$1.invoke(SocketUtils.kt:1)
06-12 09:19:11.409  3475  3633 W System.err:    at com.gitee.xuankaicat.kmnkt.socket.OnOpenCallback.success(OnOpenCallback.kt:2)
06-12 09:19:11.409  3475  3633 W System.err:    at com.gitee.xuankaicat.kmnkt.socket.MQTT.doClientConnection(MQTT.kt:5)
06-12 09:19:11.409  3475  3633 W System.err:    at com.gitee.xuankaicat.kmnkt.socket.MQTT.access$doClientConnection(Unknown Source:0)
06-12 09:19:11.409  3475  3633 W System.err:    at com.gitee.xuankaicat.kmnkt.socket.MQTT$open$1.invoke(MQTT.kt:21)
06-12 09:19:11.409  3475  3633 W System.err:    at com.gitee.xuankaicat.kmnkt.socket.MQTT$open$1.invoke(MQTT.kt:1)
06-12 09:19:11.409  3475  3633 W System.err:    at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Unknown Source:2)
06-12 09:19:11.413  1574  1588 E memtrack: Couldn't load memtrack module
06-12 09:19:11.413  1574  1588 W android.os.Debug: failed to get memory consumption info: -1
06-12 09:19:11.450  1574  1588 E memtrack: Couldn't load memtrack module
06-12 09:19:11.450  1574  1588 W android.os.Debug: failed to get memory consumption info: -1
06-12 09:19:11.459  3475  3518 E EGL_adreno: tid 3518: eglSurfaceAttrib(1338): error 0x3009 (EGL_BAD_MATCH)
06-12 09:19:11.459  3475  3518 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0x7fff506e7c00, error=EGL_BAD_MATCH
06-12 09:19:11.465  3475  3518 D EGL_adreno: eglMakeCurrent: 0x7fff6a364d80: ver 3 0 (tinfo 0x7fff6a215f80)
06-12 09:19:11.468  1574  1588 E memtrack: Couldn't load memtrack module
06-12 09:19:11.468  1574  1588 W android.os.Debug: failed to get memory consumption info: -1
06-12 09:19:11.478  1574  1588 E memtrack: Couldn't load memtrack module
06-12 09:19:11.478  1574  1588 W android.os.Debug: failed to get memory consumption info: -1
06-12 09:19:11.487  1574  1588 E memtrack: Couldn't load memtrack module
06-12 09:19:11.487  1574  1588 W android.os.Debug: failed to get memory consumption info: -1
06-12 09:19:12.122  1460  1511 E storaged: getDiskStats failed with result NOT_SUPPORTED and size 0
