### ISSUE TITLE
[Suggestion]: 对转发的（或全部）短信设置已读

### ISSUE THREAD

**Issue by deyangchu** [pppscn/SmsForwarder#281]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

对转发的（或全部）短信设置已读。隔段时间打开手机看到小红点好多数字真是逼死强迫症啊~

**Comment by pppscn** [comment]
不会直接去操作系统的短信，现在已经被人扣屎盆子了（诈骗app），加上这个狗子还不得继续喷？
