### ISSUE TITLE
通知转发规则中的多重匹配如何匹配多个包名

### ISSUE THREAD

**Issue by wowadz** [pppscn/SmsForwarder#282]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

![img](https://user-images.githubusercontent.com/63277113/230618820-2a901cbb-9026-4d42-9441-67436f9e1930.png)

**Comment by pppscn** [comment]
参考wiki，注意空格

https://github.com/pppscn/SmsForwarder/wiki/%E9%99%84%E5%BD%955%EF%BC%9A%E8%BD%AC%E5%8F%91%E8%A7%84%E5%88%99%E4%B9%8B%E5%A4%9A%E9%87%8D%E8%A7%84%E5%88%99

**Comment by pppscn** [comment]
你的截图下方 不就有例子了？
