### ISSUE TITLE
[Bug]: 鸿蒙系统手机短信通道报错 getGroupIdLevel1

### ISSUE THREAD

**Issue by wanglilong007** [pppscn/SmsForwarder#283]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

否（No）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

v3.2.0

### 问题描述

使用手机短信通道转发失败，报错信息为 getGroupIdLevel1

### 复现步骤

1. 点击发送通道
2. 新增一个手机短信通道
3. 填写接受手机
4. 点击测试
5. 提示请求失败：getGroupIdLevel1

### 是否必现

是（Yes）

### 出现问题的手机信息

Huawei Meta 30 5G

### 出现问题的安卓版本、系统版本

鸿蒙3.0.0.208

**Comment by pppscn** [comment]
买不起鸿蒙系统的手机  没有机器可以测试    哪个老板有闲置的机器可以帮忙调试一波

**Comment by handewo** [comment]
huawei畅想50 没有这个问题，短信使用正常

**Comment by chaneyPapa** [comment]
也遇到过这个问题，需要在权限设置里，手动把“通话”权限打开。以备后续有人查找这个问题提一下。

**Comment by jiladahe1997** [comment]
> 也遇到过这个问题，需要在权限设置里，手动把“通话”权限打开。以备后续有人查找这个问题提一下。

鸿蒙4.2.0.138，测试有效。 应用管理-短信转发器-电话 设置为允许。
