### ISSUE TITLE
[Bug]: 不识别卡槽、卡槽识别错误

### ISSUE THREAD

**Issue by a1245781245a** [pppscn/SmsForwarder#284]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.2.0

### 问题描述

不识别卡槽，转发的卡槽信息一律为SIM2

### 复现步骤

vivo x6d Android 5.1、Funtouch OS_2.5 

### 是否必现

是（Yes）

### 出现问题的手机信息

vivo x6d

### 出现问题的安卓版本、系统版本

Android 5.1、Funtouch OS_2.5

**Comment by pppscn** [comment]
转发出去的信息 SubId 是多少？

先参考这个wiki设置一下对应关系

https://github.com/pppscn/SmsForwarder/wiki/1.%E9%80%9A%E7%94%A8%E8%AE%BE%E7%BD%AE

**Comment by pppscn** [comment]
添加卡槽信息获取补偿机制,修复远程发短信指定卡不明确问题 #293

https://github.com/pppscn/SmsForwarder/pull/293

试试每周构建版
