### ISSUE TITLE
[Bug]: settings-Retry Interval 这里的三个数值框, 在我所有手机里都看不到内容

### ISSUE THREAD

**Issue by lovitus** [pppscn/SmsForwarder#285]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

latest

### 问题描述

[Bug]: settings-Retry Interval 这里的三个数值框, 在我所有手机里都看不到内容
在移动wifi(低分辨率)反而能看到内容.
建议这里的三个数值换一行, 就不会这么挤造成无法输入和阅读.

### 复现步骤

settings-Retry Interval 

### 是否必现

是（Yes）

### 出现问题的手机信息

三星s20fe

### 出现问题的安卓版本、系统版本

Android 13

**Comment by pppscn** [comment]
![Screenshot_20230507_105551](https://user-images.githubusercontent.com/5105854/236655239-9e929a76-aff1-4561-b7a3-4605c20bd8aa.png)
