### ISSUE TITLE
[Bug]: frpclib无法下载, 提示404, 可以手动离线安装么?

### ISSUE THREAD

**Issue by lovitus** [pppscn/SmsForwarder#287]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

latest

### 问题描述

![image](https://user-images.githubusercontent.com/14361541/231936325-61cae441-0793-44d7-9745-b594dce496dc.png)

### 复现步骤

安装sms forwarder, 点击frpc, 点击下载

### 是否必现

是（Yes）

### 出现问题的手机信息

honor v20

### 出现问题的安卓版本、系统版本

android 11

**Comment by pppscn** [comment]
多试几次，可能我的服务器不够稳定，目前测试是正常的
