### ISSUE TITLE
[Bug]: Http基本认证不能正确识别Uri中含有端口号的情况

### ISSUE THREAD

**Issue by iankane0** [pppscn/SmsForwarder#289]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.2.0

### 问题描述

http基本认证可以识别`http://username:password@host/path`，但是不能识别`http://username:password@host:port/path`的情况

### 复现步骤

添加bark发送通道，bark服务器地址使用带http basic认证的url，url中包含端口号，报错418

### 是否必现

是（Yes）

### 出现问题的手机信息

一加9

### 出现问题的安卓版本、系统版本

android 13

**Comment by pppscn** [comment]
![Screenshot_20230507_143421](https://user-images.githubusercontent.com/5105854/236661871-07c022e9-2447-462d-8aff-a290c3c97619.png)

自行排查一下服务端配置，百度一下 “HTTP状态码 418 I'm a teapot”

**Comment by iankane0** [comment]
换了一个不带url encode的密码成功了，我再看看是什么问题
