### ISSUE TITLE
[Suggestion]: 最新版本中发送通道的Bark的消息链接取消限制

### ISSUE THREAD

**Issue by gytaoyu** [pppscn/SmsForwarder#290]
### 是否有人曾提过类似的问题？

是（Yes）

### 你觉得APP有什么不足之处？

希望在最新版本中去除对消息链接格式的限制，使得Bark的消息链接支持URL Scheme，便于跳转到相应应用中。
类似问题在2.x.x.x中曾经修复过，最新版本重现。
可以参见https://github.com/pppscn/SmsForwarder/issues/229

**Comment by pppscn** [comment]
3.x的输入框加了正则校验，已经修正
