### ISSUE TITLE
[Suggestion]: 建议: 加入多设备管理, 加入设备在线查看

### ISSUE THREAD

**Issue by lovitus** [pppscn/SmsForwarder#291]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

我有6台设备运行smsforwarder, 需要频繁切换端口去检查各个设备. 还经常搞错.
client管理建议:
- 加入批量设备管理
-- 支持**命名设备**, 比如 ip:5001 三星,   ip:5002 小米
-- 支持设备**在线状态**批量查看
-- 支持设备当日信息**聚合查看.**

非常感谢这么好用的软件, 这是我唯一的痛点了.

**Comment by pppscn** [comment]
我不会添加这个功能，个人用户用不上

这个给猫池做嫁衣，已经有人把这个装在随身wifi打包当猫池卖了

已经有http server的api了，自己写客户端可以实现你要的【聚合查看】
