### ISSUE TITLE
[Suggestion]: 企业微信机器人Markdown消息格式问题

### ISSUE THREAD

**Issue by Chetni** [pppscn/SmsForwarder#292]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

我在企业微信文档中看到可以使用Markdown格式的文本，但是在「短信转发器」内怎样编辑都不能触发「企业微信」显示为Markdown格式。
<img width="925" alt="image" src="https://user-images.githubusercontent.com/128563962/232538091-5a07dce3-70ac-469d-89b0-6d5a0cef381d.png">
![image](https://user-images.githubusercontent.com/128563962/232538600-4a67ce26-0718-4776-9d82-6b7f52bf65ac.png)

**Comment by pppscn** [comment]
![markdown](https://user-images.githubusercontent.com/5105854/236661264-45d3b9ca-d792-48b4-954e-f1eab714caa9.png)
![markdown_自定义模板](https://user-images.githubusercontent.com/5105854/236661265-065afe40-2063-4850-9bb4-f02486468e17.png)

已支持，等下一次发版或下载每周构建版
