### ISSUE TITLE
[Bug]:CactusSave中为什么会修改SP_EXTRA_DEVICE_MARK？？？ 

### ISSUE THREAD

**Issue by lpylinan** [pppscn/SmsForwarder#294]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

否（No）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

3.2.0

### 问题描述

CactusSave中，
'var date: String by SharedPreference(SP_EXTRA_DEVICE_MARK, "0000-01-01 00:00:00")'
这行代码看着很奇怪。

### 复现步骤

CactusSave

### 是否必现

否（No）

### 出现问题的手机信息

none

### 出现问题的安卓版本、系统版本

none

**Comment by pppscn** [comment]
感谢反馈，已经修正
