### ISSUE TITLE
[Bug]: 小米手机接受小米账号短信验证码时无法转发，接收其他APP的短信验证码可以

### ISSUE THREAD

**Issue by troublecn** [pppscn/SmsForwarder#296]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

否（No）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

 3.2.0

### 问题描述

小米手机接受小米账号短信验证码时无法转发，接收其他APP的短信验证码可以

### 复现步骤

小米手机接受小米账号短信验证码时无法转发，接收其他APP的短信验证码可以

### 是否必现

是（Yes）

### 出现问题的手机信息

小米5

### 出现问题的安卓版本、系统版本

MIUI10.2.1.0 Android8.0.0

**Comment by pppscn** [comment]
关闭MIUI免费网络短信

https://github.com/pppscn/SmsForwarder/wiki/%E3%80%90%E5%BF%85%E8%AF%BB%E3%80%91%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#q%E5%B0%8F%E7%B1%B3%E7%BA%A2%E7%B1%B3%E6%89%8B%E6%9C%BA%E4%B8%BA%E4%BB%80%E4%B9%88%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9nft%E6%95%B0%E5%AD%97%E8%97%8F%E5%93%81%E4%B9%8B%E7%B1%BBapp%E7%9A%84%E9%80%9A%E7%9F%A5%E7%B1%BB%E7%9F%AD%E4%BF%A1%E7%BB%8F%E5%B8%B8%E6%80%A7%E8%BD%AC%E5%8F%91%E4%B8%8D%E4%BA%86
