### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by caixiaohaier** [pppscn/SmsForwarder#297]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

V3.2.0

### 问题描述

1.使用APP配置企业微信应用消息作为通道时，配置HTTP或者Socks5代理。第一次发送与在长时间未发送消息时在发送消息，会提示错误。
2.上述错误产生后，手动在转发失败的日志点击重新发送，消息还是未能成功发送出去。
3.APP在通用设置里面配置了请求重试机制，但出现这个Bug时候却未能生效，没有重试发送。
4.随身WiFi（410）测试发现使用Socks5作为代理时，会出现网络不可用的错误，无法链接到代理。

Ps:
1.HTTP与Socks代理是在Linux系统使用V2ray最新版搭建的。配置了基本的用户名密码。在国内企业电信固定公网IP。
2.使用旧的企业微信应用，也就是不需要检测IP的。选择不需要代理。测试没有这个Bug
3.在小米9，红米5A，随身WiFi（410）测试，均有该问题。

### 复现步骤

在通道中配置企业微信应用消息作为通道，输入完代理服务器信息。点击测试，第一次会错误，第二次请求成功。

### 是否必现

是（Yes）

### 出现问题的手机信息

小米9，红米5A，随身WiFi（410）

### 出现问题的安卓版本、系统版本

安卓9/7/4.4.4

### 提供截图或视频

![微信图片_20230423185846](https://user-images.githubusercontent.com/48126754/233835981-71fe3055-545f-46a1-b82c-0bf79437a96a.jpg)

**Comment by pppscn** [comment]
排查代理的问题 或者 换一个发送通道吧
