### ISSUE TITLE
[Suggestion]: Release Assets文件命名简化

### ISSUE THREAD

**Issue by Mosney** [pppscn/SmsForwarder#298]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

Release页文件名在移动视图下展示不完整，会仅显示相同的前半段而省略后半段的信息，如图所示，这样会导致不便找到想要的apk版本
![Screenshot_20230425-113441 (1)](https://user-images.githubusercontent.com/22477230/234168955-89c653cf-f08f-437d-814c-b1f9e7351296.png)

### 你觉得该怎么去完善会比较好？【非必答】

压缩文件名中的的冗余信息，或将有效信息（例如架构）前移

**Comment by pppscn** [comment]
![apk文件命名](https://user-images.githubusercontent.com/5105854/236653751-e72559e6-b9df-4c46-9f69-bd278a101218.png)

### APK版本说明：
* universal（10XXXX）: 通用版（不在乎安装包大小/懒得选就用这个版本，包含以下4种CPU架构so）
* armeabi-v7a（20XXXX）: 32位ARM设备（备用机首选）
* arm64-v8a（30XXXX）: 64位ARM设备（主流旗舰机）
* x86（40XXXX）: 32位Intel设备
* x86_64（50XXXX）: 64/32位Intel设备
