### ISSUE TITLE
[Bug]: 邮件转发经常显示超时

### ISSUE THREAD

**Issue by Konne06** [pppscn/SmsForwarder#299]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

3.20

### 问题描述

邮件转发的方式 屏幕关闭后经常无法转发 
确定app仍在运行 权限全部赋予  日志可以看到错误原因是连接邮件服务器超时
确定网络连接畅通 且手机没有省电设置

此外 之前的旧版本（具体是哪个忘了）似乎可以正常用 升级最新版之后开始出现此问题

### 复现步骤

单纯的锁屏就无法运行

### 是否必现

是（Yes）

### 出现问题的手机信息

魅族魅蓝S6

### 出现问题的安卓版本、系统版本

安卓8

**Comment by pppscn** [comment]
> 单纯的锁屏就无法运行

这个就已经能说明问题所在了，排查手机配置吧（锁屏断网了）
