### ISSUE TITLE
tg通知通道，设置socks始终不行，确认信息都是没问题的，因为tg代理都是正常的[Bug]: 

### ISSUE THREAD

**Issue by wfniub** [pppscn/SmsForwarder#301]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

否（No）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

v3.2.0

### 问题描述

tg通知通道，设置socks始终不行，确认信息都是没问题的，因为tg代理都是正常的

### 复现步骤

tg通知通道，设置socks始终不行，确认信息都是没问题的，因为tg代理都是正常的

### 是否必现

否（No）

### 出现问题的手机信息

xiaomi

### 出现问题的安卓版本、系统版本

11

### 提供截图或视频

tg通知通道，设置socks始终不行，确认信息都是没问题的，因为tg代理都是正常的

### 提供报错堆栈【请提供logcat抓取的日志，参考： https://blog.csdn.net/m0_64776928/article/details/126005119 】

tg通知通道，设置socks始终不行，确认信息都是没问题的，因为tg代理都是正常的

### 提供解决方案

tg通知通道，设置socks始终不行，确认信息都是没问题的，因为tg代理都是正常的

**Comment by pppscn** [comment]
重新不了，检查你的socks服务端配置吧

![微信截图_20230522145605](https://github.com/pppscn/SmsForwarder/assets/5105854/c312a949-91f1-4569-b94f-7e42b8fd1450)
![微信图片_20230522145709](https://github.com/pppscn/SmsForwarder/assets/5105854/161cab9a-190d-45dc-a958-249f30eba4fd)
![微信图片_20230522145713](https://github.com/pppscn/SmsForwarder/assets/5105854/9ab1fece-4b61-4644-a971-49d2a4ef6ec9)

**Comment by wangweitung** [comment]
如果开启代理身份验证，确实发不出去。
