### ISSUE TITLE
[Suggestion]: 【卡槽信息】内容

### ISSUE THREAD

**Issue by xytdj** [pppscn/SmsForwarder#302]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

在新增的如【来电提醒】等功能中，{{卡槽信息}}值为空。

### 你觉得该怎么去完善会比较好？【非必答】

建议统一规则，如88888888包名时，{{卡槽信息}}值为“电池状态监听”。
同理，建议：
1、【来电提醒】信息中，{{卡槽信息}}值为“来电提醒”；
2、【未接来电】信息中，{{卡槽信息}}值为“未接来电”；
3、【去电拨出】信息中，{{卡槽信息}}值为“去电拨出”；
4、【来电接通】信息中，{{卡槽信息}}值为“来电接通”；

**Comment by pppscn** [comment]
通话的卡槽信息必须挂机之后从通话记录中读取，所以响铃的时候（来电提醒）取不到这个值

另外这个字段就是卡槽信息（卡号等），不可能替换为提醒类型  造成混淆，咱不接受该建议

**Comment by xytdj** [comment]
理解为什么这个值是空的，但不理解为什么你明知道它是空的、是取不到值的情况下不愿意替换为有意义的内容，毕竟当88888888包名时，{{卡槽信息}}值你也设置为“电池状态监听”了啊
