### ISSUE TITLE
[Suggestion]: 修改88888888包的默认内容

### ISSUE THREAD

**Issue by xytdj** [pppscn/SmsForwarder#304]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

88888888包的默认内容如下：

88888888
【电量预警】已高于电量预警上限，请拔掉充电器！
剩余电量：100%
充满电量：100%
当前电压：4.49V
当前温度：32.10℃
电池状态：充电中
健康度：良好
充电器：AC
电池状态监听
SubId：0
2023-05-12 00:59:53
P30

### 你觉得该怎么去完善会比较好？【非必答】

建议修改默认模板的内容，去掉 88888888 这一行

**Comment by juice-prince** [comment]
可以去掉。
我的配置规则是：
{
匹配字段：APP包名
匹配模式：是
匹配值：88888888
}（自己设置，改成只转发这个包的通知就行）
★启用自定义模板
★★自定义模板格式为：
{{接收时间}}
{{通知内容}}

示例：
【充电状态】发生变化：充满电 → 放电中
剩余电量：100%
充满电量：100%
当前电压：4.38V
当前温度：26.50℃
电池状态：放电中
健康度：良好
充电器：未知

**Comment by pppscn** [comment]
转发规则上自定义模板即可

进阶玩法：对提示内容不满意 也可以正则替换
