### ISSUE TITLE
[Suggestion]: 增加新的可用变量

### ISSUE THREAD

**Issue by xytdj** [pppscn/SmsForwarder#305]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

目前的可用变量中，不包含【通话类型】这个信息

### 你觉得该怎么去完善会比较好？【非必答】

建议：
1、增加一个新的可用变量为 {{通话类型}}
2、通话的转发规则中，匹配字段 增加 匹配 通话类型

**Comment by pppscn** [comment]
![Screenshot_20230724_233131](https://github.com/pppscn/SmsForwarder/assets/5105854/edae8243-25e5-4159-a0b1-db722fc1ad72)
![Screenshot_20230724_233206](https://github.com/pppscn/SmsForwarder/assets/5105854/93cf4faf-92a1-4aed-bd25-73f025464dea)
![Screenshot_20230724_233229](https://github.com/pppscn/SmsForwarder/assets/5105854/02dd9e62-793c-4144-84b4-abfd0104796e)
![微信截图_20230724233303](https://github.com/pppscn/SmsForwarder/assets/5105854/d02b1a42-d7fc-4a29-80d4-d5f8fcf2f85a)

下载每周构建版测试

https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml
