### ISSUE TITLE
[Suggestion]: 增加转发延迟选项

### ISSUE THREAD

**Issue by xytdj** [pppscn/SmsForwarder#306]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

现在的转发，都是在收到短信后、来电去电时、收到应用通知后 就会立即触发，但往往此时因为锁屏等原因，网络连接并未链接，而需要等待

### 你觉得该怎么去完善会比较好？【非必答】

建议增加一个延迟转发选项，用户可自行配置，默认为0即立即转发，用户可选择1秒-60秒后转发 —— 最佳方案是，收到短信后 通过修改本应用通知文案引发手机设备 亮屏， 然后在配置的间隔，如 20秒 后转发，给设备一个建立网络链接的事件。

**Comment by pppscn** [comment]
先去检查系统的省电策略，关闭息屏断网之类的设置，更为妥当

另外，打开【通用设置】的重试机制

**Comment by xytdj** [comment]
锁屏断网这种情况，并不是每一个手机类型都可有完美解决方案的。但是，为什么不能调整一下思路，既然存在锁屏断网，为什么不能在收到短信后、先触发亮屏、让系统有足够的时间链接网络、然后再转发短信内容呢？ 这无非是多一种解决问题的方案吧。
