### ISSUE TITLE
[Bug]: bark加密推送，解密失败

### ISSUE THREAD

**Issue by Tam-0130** [pppscn/SmsForwarder#307]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.2.0

### 问题描述

1. 设置bark加密推送，推送成功，但接收端解密失败（自行用官方脚本测试推送，解密正常）

2. 保存设置后，再次编辑bark发送通道进行测试，测试显示成功，bark客户端可以正常收到消息，但是服务端bark的log会显示明文消息

3. 然后再保存，再次进入编辑SF的bark配置，会发现加密方式自动变成不加密。

自行编译和每周测试版都是这个问题。

### 复现步骤

1. 配置bark发送通道，进行测试，解密失败
2. 保存bark配置，再编辑，测试，测试正常，但服务端消息会显示明文
3. 再次保存bark配置，再进入编辑，加密方式自动变为：不加密

### 是否必现

是（Yes）

### 出现问题的手机信息

红米10x

### 出现问题的安卓版本、系统版本

Android10 MIUI11

**Comment by pppscn** [comment]
我这边重现不了，录个屏幕看看，会自行构建了 弄几个断点调试一下

**Comment by pppscn** [comment]
![mmexport1684765838606.jpg](https://github.com/pppscn/SmsForwarder/assets/5105854/0c66331e-1313-4eff-8b1a-91a43889bdc2)![mmexport1684765817452.jpg](https://github.com/pppscn/SmsForwarder/assets/5105854/8c81f0fe-fb7a-4bd1-8f71-3ccbf928e84f)![Screenshot_2023-05-22-22-24-24-947_com.idormy.sms.forwarder.jpg](https://github.com/pppscn/SmsForwarder/assets/5105854/1e8e7a77-48ee-43cc-b061-7aae73879fe9)

**Comment by meteor0027** [comment]
我也是同样的问题，用的每周测试版，我按bark接收端设置的key 和iv，填入转发器设置，可以推送但是接收会显示解密失败

**Comment by liuyangzuo** [comment]
<img width="376" alt="image" src="https://github.com/pppscn/SmsForwarder/assets/8985760/18144f88-2ae9-4850-aacf-426118699f53">
<img width="352" alt="image" src="https://github.com/pppscn/SmsForwarder/assets/8985760/ba3c39c4-ebc9-4743-9b3c-62f5f2396770">

最新版本 bark 通道 没有加密输入框。

**Comment by pppscn** [comment]
重新下载每周构建版测试

https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by Tam-0130** [comment]
最新版测试正常（仅16位key），但是lv偏移量匹配有问题，bark客户端lv只能设置16位，无论加密key32位还是16位都只能设置16位，但是sms客户端的配置需要key和lv的长度相等，也就是32位的key需要填写32位的lv。
