### ISSUE TITLE
[Suggestion]: 希望能够增加bark的自定义分组与自定义图标功能

### ISSUE THREAD

**Issue by jiaorong2023** [pppscn/SmsForwarder#308]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

自定义模板里如何添加自定义图标呢？转发的消息全是默认bark的红图标，还有就是如何自定义分组。

**Comment by pppscn** [comment]
认真看看 添加发送通道的界面
