### ISSUE TITLE
[Bug]: 远程发短信问题

### ISSUE THREAD

**Issue by tomcat927** [pppscn/SmsForwarder#309]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

否（No）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

最新版

### 问题描述

 问题描述见此文档，

随身WiFi远程发短信问题
https://0927.notion.site/WiFi-4e546279d76a40e9a7df52c3ed8f2548

建议取消此次pr
#293 

本人的设备集群已经花钱全部转换成新设备，不会再有卡槽问题

以后也不想折腾了，感谢开源。

### 复现步骤

 问题描述见此文档，

随身WiFi远程发短信问题
https://0927.notion.site/WiFi-4e546279d76a40e9a7df52c3ed8f2548

### 是否必现

是（Yes）

### 出现问题的手机信息

随身WiFi，等一些强行升级安卓版本的老rom，比如安卓13的小米4rom

### 出现问题的安卓版本、系统版本

4.4.4  ，等一系列行升级安卓版本的老rom

### 提供截图或视频

 问题描述见此文档，

随身WiFi远程发短信问题
https://0927.notion.site/WiFi-4e546279d76a40e9a7df52c3ed8f2548

### 提供报错堆栈【请提供logcat抓取的日志，参考： https://blog.csdn.net/m0_64776928/article/details/126005119 】

 问题描述见此文档，

随身WiFi远程发短信问题
https://0927.notion.site/WiFi-4e546279d76a40e9a7df52c3ed8f2548

### 提供解决方案

 问题描述见此文档，

随身WiFi远程发短信问题
https://0927.notion.site/WiFi-4e546279d76a40e9a7df52c3ed8f2548

**Comment by tomcat927** [comment]
搞了一下，我还是继续研究吧，因为目前市面上的rom都不太合适我的需求。


重新读了一下文档，可能还是表述不清楚。我这里补充一下。

问题1：引入 #293的变化后，随身WiFi远程发短信，会因为subid=0，无法发出。


问题2：双卡（且无法获取subid信息的）设备，无法远程发送短信，（卡1，卡2都无法发出）

目前而言：
取消此次mr可以，恢复随身WiFi发短信功能

对于，双卡（且无法获取subid信息的）设备，目前个人还在研究，


因为非专业安卓开发，很多东西都能只能借助搜索引擎来学习和实现，

请给一点时间，或者你有更好的方案请尽快修复，谢谢了。

**Comment by vircloud** [comment]
遇到类似的奇怪的问题，双卡手机识别到了卡槽和号码，不管点卡一还是点卡二发短信，实际发出的都是卡一，应该是手机问题，因为试了十几部手机，就三四部会有这个情况

**Comment by ouyang993670** [comment]
@tomcat927 能提供下新设备购买渠道不，我也想使用随身WIFI来代替日常真机收发短信管理
