### ISSUE TITLE
[Suggestion]: 钉钉群机器人能否支持markdown格式

### ISSUE THREAD

**Issue by YXYX212** [pppscn/SmsForwarder#311]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

钉钉企业机器人支持markdown格式,但是只能私发用户, 无法在群聊中使用
能否加上钉钉群机器人的markdown格式支持 ,谢谢

### 你觉得该怎么去完善会比较好？【非必答】

钉钉企业机器人群内自带webhook,是否可以从此处入手,在通道配置时 添加一个 选填的机器人webhook, 然后userid和 webhook其中一个必填

**Comment by pppscn** [comment]
下载每周构建版测试

https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by YXYX212** [comment]
感谢
