### ISSUE TITLE
[Suggestion]: 钉钉群聊机器人,转发时@某人 是否支持海外手机号

### ISSUE THREAD

**Issue by YXYX212** [pppscn/SmsForwarder#312]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

你好,请问钉钉群聊机器人,转发时@某人 是否支持海外手机号
我尝试过使用 
不带区号的 手机号 324*9****1
带+区号的 手机号 +39324*9****1
不带+区号的 手机号 39324*9****1
都没有成功@到用户

**Comment by pppscn** [comment]
国外的手机号没试过

被at的人在群里面吗？理论上不需要加国家码，或者再试试 `+39-32491`

钉钉的文档也没有特别说明：

https://open.dingtalk.com/document/orgapp/custom-robot-access?spm=ding_open_doc.document.0.0.cb6727699C9B0o

**Comment by YXYX212** [comment]
被at人在群内,+39-324试过也没有成功,应该是钉钉目前对海外手机支持性不是很好,我看文档自己再研究下,谢谢您抽空回答

**Comment by pppscn** [comment]
下载每周构建版测试

https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by pppscn** [comment]
增加 `atDingtalkIds` 的功能，如果手机号测试还是不行 直接 at 钉钉号 试试

参考钉钉机器人文档：https://open.dingtalk.com/document/robots/custom-robot-access#title-72m-8ag-pqw

**Comment by YXYX212** [comment]
成功了谢谢
