### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by gakiyukr** [pppscn/SmsForwarder#313]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.2.0 与 v2.4.4

### 问题描述

手机系统设置为繁体中文任何转发规则均无效。
规则是没问题的，测试规则的时候都能收到。
真正来短信的时候就拉闸了。

### 复现步骤

手机系统设置繁体中文

### 是否必现

是（Yes）

### 出现问题的手机信息

RedMi Note 11T Pro

### 出现问题的安卓版本、系统版本

A13 MIUI14

**Comment by pppscn** [comment]
目前仅支持：简体中文、英文

**Comment by gakiyukr** [comment]
感谢。
