### ISSUE TITLE
建议大佬添加远程开关WIFI功能

### ISSUE THREAD

**Issue by spysir** [pppscn/SmsForwarder#316]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

有些手机在WIFI无法连接互联网的时候不能自动切换到蜂窝网络，希望大佬可以添加一个远程开关WIFI的功能

**Comment by pppscn** [comment]
连上WiFi都没网了，还怎么远程控制切换？ 加到短信指令里面，发一条短信解决？

**Comment by spysir** [comment]
> 连上WiFi都没网了，还怎么远程控制切换？ 加到短信指令里面，发一条短信解决？

短信指令控制最好了

**Comment by pppscn** [comment]
下载每周构建版测试

https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**打开或关闭 WiFi 指令**

```
smsf#wifi#on
smsf#wifi#off
```

**Comment by pppscn** [comment]
从 Android 10（API 级别 29）开始，应用程序无法直接开启或关闭 WiFi，此需求无解了
