### ISSUE TITLE
[Suggestion]: 定时启用转发规则

### ISSUE THREAD

**Issue by leim** [pppscn/SmsForwarder#318]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

期望增加一个功能，转发规则按照时间段生效，比如每天07:00至18:00，启用A转发规则，每天18:00至23:59启用B转发规则，每天00:00至07:00，没有转发规则，类似这样的配置

**Comment by pppscn** [comment]
下载每周构建版测试

https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by pppscn** [comment]
![Screenshot_20230724_233131](https://github.com/pppscn/SmsForwarder/assets/5105854/4471c3ce-12ac-41f5-8363-34fc577bc2ab)
