### ISSUE TITLE
[Suggestion]: 简化 tgbot 配置流程

### ISSUE THREAD

**Issue by Ayx03** [pppscn/SmsForwarder#319]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得 app 有什么不足之处？

[配置](https://github.com/pppscn/SmsForwarder/wiki/2.%E5%8F%91%E9%80%81%E9%80%9A%E9%81%93#tele%E6%9C%BA%E5%99%A8%E4%BA%BA%E8%87%AA%E5%A4%87%E6%A2%AF%E5%AD%90) tgbot 的过程中感到使用 ApiToken 获取 Chat ID 有点麻烦（也踩了 /start 后需要再发送一条其它内容才能获取到 Chat ID 这样的坑），碰巧发现可以用 [@userinfobot](https://t.me/userinfobot) 处直接获取用户的 User ID

不过向群组中推送可能还是需要使用 Chat ID，获取 Chat ID 基本上也是一劳永逸的

### 你觉得该怎么去完善会比较好？【非必答】

- [x] 更新 Wiki，直接从 [@userinfobot](https://t.me/userinfobot) 处获取自己或群组的 Chat ID 填入即可，无须手动拼接 URL 在浏览器中访问再寻找自己的 Chat ID。需要获取群组的 ID 时转发一条以群组身份发送的消息至此机器人即可。

- [ ] 或者可以增加通过 ApiToken 调用 /getUpdate 接口自动获取给机器人发消息的 Chat ID 的功能，就不需要用户手动拼接网址再从浏览器返回的纯文本内容中寻找 Chat ID 了，不依赖于单一的机器人，数据也可以在本地处理（虽然也没什么敏感数据）

![image](https://github.com/pppscn/SmsForwarder/assets/75155322/aae8658a-2a61-45f8-af42-975a64fe6d52)

**Comment by pppscn** [comment]
你的诉求是把 `ChatID` 弄成非必填？

**Comment by Ayx03** [comment]
> 你的诉求是把 `ChatID` 弄成非必填？

@pppscn 使用 User ID 推送消息，就不必手动在浏览器中调用 API 再寻找机器人与自己的 Chat ID 了，用户只需要通过 userinfobot 获取自己的 User ID

**Comment by imldy** [comment]
看楼主描述，`ChatID`不等于`UserID`？可我的`result->message->chat->id`、`result->message->from->id`、`@userinfobot`返回的`id`一样。

我觉得还有个坑，如果要发送消息到群组时，需要将Bot设为群组管理员后，才能在`https://api.tele****.org/bot<apiToken>/getUpdates`接口获取到消息，才能拿到群组`ChatID`，否则即便是在群里@机器人，机器人也收不到信息。

**Comment by imldy** [comment]
我想到一个好办法，在APP输入BotToken或者反代地址后，可提示用户发送任意消息到Bot/群组，用户点击“我已发送”按钮，之后APP请求`/getUpdates`接口获取`ChatID`，这样用户就不用手动拼URL、操作浏览器、复制粘贴了。

流程类似用户发送微信注册短信、QQ解封短信等。

**Comment by Ayx03** [comment]
> 看楼主描述，`ChatID`不等于`UserID`？可我私聊机器人时，`result->message->chat->id`、`result->message->from->id`、`@userinfobot`返回的`id`一样。
> 
> 我觉得还有个坑，如果要发送消息到群组时，需要将Bot设为群组管理员后，才能在`https://api.tele****.org/bot<apiToken>/getUpdates`接口获取到消息，才能拿到群组`ChatID`，否则即便是在群里@机器人，机器人也收不到信息。

对比了一下确实是一样的，那其实更新一下 Wiki 就好了

**Comment by Ayx03** [comment]
> 我想到一个好办法，在APP输入BotToken或者反代地址后，可提示用户发送任意消息到Bot/群组，用户点击“我已发送”按钮，之后APP请求`/getUpdates`接口获取`ChatID`，这样用户就不用手动拼URL、操作浏览器、复制粘贴了。
> 
> 流程类似用户发送微信注册短信、QQ解封短信等。

不错的想法，这样就不用依赖单一的机器人了，数据也能本地处理

**Comment by pppscn** [comment]
wiki已加上该issues的链接，给其他网友参考
