### ISSUE TITLE
QQ交流群人满了，微信群二维码过期了，能不能在分享一下交流群

### ISSUE THREAD

**Issue by Triple-stones** [pppscn/SmsForwarder#32]
如题
还有我想转发到web上，然后通过爬虫获取到信息，然后发送到QQ上，因为我的华为watch3手表没有短信功能，但是可以安装QQ，目前卡在了爬虫阶段

**Comment by Triple-stones** [comment]
问题已经解决，但是这个通知网页不是太好用，建议可以session会话保持，里面的消息改为json格式，方便使用

**Comment by pppscn** [comment]
QQ 2群 31330492
