### ISSUE TITLE
[Bug]: 一键换机同步发送通道克隆不全的问题，以及一二建议

### ISSUE THREAD

**Issue by 7qin** [pppscn/SmsForwarder#320]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.2.0

### 问题描述

一键换新机时，不论是推送还是拉取，都只能克隆成功发送通道的第一条记录，且当转发规则如果是第二个发送通道也会改成第一通道。。。。
建议一   ：  “短信转发器”这个应用名是不是可以升级一下，这个名字给一般用感觉都不太安全，反诈中心也会重点关注。包名，应用名全换了应该都好点，再说“短信转发器——不仅只转发短信，备用机必备神器！”。LOGO图标看着可以叫纸飞机^^,换个内涵，深意点的英文名字
建议二 ： 虽然主动控制中可以远程发短信，但是在外网下不是用方便，我之前是用tasker过来的，可不可以加一个通一个微信或短信指令发送短信呢，现实需求是，有点程序不是收验证码，而是要发送短信验证。

### 复现步骤

一键换机同步发送通道克隆不全的问题

### 是否必现

是（Yes）

### 出现问题的手机信息

华为P9 

### 出现问题的安卓版本、系统版本

8.0

**Comment by pppscn** [comment]
1、一键换新机：这个等其他人反馈看看，我自己没遇到过这样的

2、APP改名：不会改名也不换包名！我不做偷偷摸摸的事情，不惧怕反诈中心！曾经老是有人拿这事情说事，自从我被投诉从“酷安”下架了，从此就没人说这事情了！无非就是我是免费开源，你懂的这些投诉是怎么来的

3、短信指令：下载 [每周构建版](https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml) 试试，用法参见 [wiki](https://github.com/pppscn/SmsForwarder/wiki/%E9%99%84%E5%BD%959%EF%BC%9A%E7%9F%AD%E4%BF%A1%E6%8C%87%E4%BB%A4)
