### ISSUE TITLE
[Bug]: 卡槽识别有问题

### ISSUE THREAD

**Issue by github-h** [pppscn/SmsForwarder#322]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.2.0

### 问题描述

对卡槽主键的识别有错误

### 复现步骤

将联通卡插入卡槽1 移动卡插入卡槽2

打开app自动获取  联通卡识别主键为2 移动卡主键为1  有问题

**但是开启全部转发后  转发信息匹配的是正确的  联通卡显示sim1  移动卡显示sim2**

**所以猜测仅仅是app界面那里的显示错误**

将联通卡插入卡槽2  移动卡插入卡槽1

打开app自动获取  联通卡识别主键为2 移动卡主键为1 无问题

### 是否必现

是（Yes）

### 出现问题的手机信息

小米8透明探索版

### 出现问题的安卓版本、系统版本

Android10 MIUI12.5.3稳定版

### 提供截图或视频

![图片](https://github.com/pppscn/SmsForwarder/assets/49114731/b623606a-85ae-4896-845f-4509d8b99693)
![图片](https://github.com/pppscn/SmsForwarder/assets/49114731/91849f6c-1544-460a-a4be-193b65f21351)
![图片](https://github.com/pppscn/SmsForwarder/assets/49114731/1236fcdf-f4d0-4c41-aa6f-ecdafa5b5fbc)

**Comment by pppscn** [comment]
看wiki中的SubId匹配关系

https://github.com/pppscn/SmsForwarder/wiki/1.%E9%80%9A%E7%94%A8%E8%AE%BE%E7%BD%AE

**Comment by github-h** [comment]
> 看wiki中的SubId匹配关系
> 
> https://github.com/pppscn/SmsForwarder/wiki/1.%E9%80%9A%E7%94%A8%E8%AE%BE%E7%BD%AE

我看了 所以这种显示的错位算是预期情况是嘛

**Comment by pppscn** [comment]
`SubId`不是`SoltID`，`SubId` 可以理解是初始化以来所有SIM卡插入手机的次序，后者才是你理解的卡槽顺序（0-1）

**Comment by github-h** [comment]
> `SubId`不是`SoltID`，`SubId` 可以理解是初始化以来所有SIM卡插入手机的次序，后者才是你理解的卡槽顺序（0-1）

懂了懂了  原来不是soltid
