### ISSUE TITLE
关于联系人匹配的建议

### ISSUE THREAD

**Issue by 7qin** [pppscn/SmsForwarder#323]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

收到通讯录里的号码正常提示是有联系人名称的，试过的现在的所有变量都不能获取到，如果能转发这个名称应该直观点

**Comment by pppscn** [comment]
![微信截图_20230722131344](https://github.com/pppscn/SmsForwarder/assets/5105854/365df1ac-4aab-4090-bde3-e153dc96be9b)

自行从 `{{短信内容}}` 或 `{{通知内容}}` 里面正则提取
