### ISSUE TITLE
[Bug]: 短信转发，在同一寝室，室友发送一条短信，webhook能够接收到，远距离不在同一区域发送，webhook和转发日志都无响应

### ISSUE THREAD

**Issue by zhangs1233** [pppscn/SmsForwarder#325]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

否（No）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

最新版

### 问题描述

短信转发，在同一寝室，室友发送一条短信，webhook能够接收到，远距离不在同一区域发送，webhook和转发日志都无响应

### 复现步骤

1.webhook已配置好
2.针对本机手机号发送一条消息
3.短信有消息，webhook无响应

### 是否必现

是（Yes）

### 出现问题的手机信息

vivo s5

### 出现问题的安卓版本、系统版本

Android 10

**Comment by pppscn** [comment]
前所未闻，这跟距离还能有关系？

---

怀疑：你的远距离短信是验证码？  验证码短信保护没关？

https://github.com/pppscn/SmsForwarder/wiki/%E3%80%90%E5%BF%85%E8%AF%BB%E3%80%91%E4%BD%BF%E7%94%A8%E6%B5%81%E7%A8%8B

**Comment by zhangs1233** [comment]
近距离，发送一条短信，不管短信内容是啥，我这边webhook都能接收到，远距离，比如我另一认识的，距离我10公里外的，发送一条消息，无响应，跟验证码短信无关

**Comment by pppscn** [comment]
远距离的那个人也是用vivo手机吗？

是不是走`免费网络信息`了？

关闭`免费网络信息`再试

没有OV系手机，自行参考：https://jingyan.baidu.com/article/6f2f55a193a99bf4b93e6c9c.html

**Comment by pppscn** [comment]
没有后续反馈，先关闭了

不可能有这样的bug，请自查
