### ISSUE TITLE
[Suggestion]:能不能开放个变量获取mac

### ISSUE THREAD

**Issue by 7qin** [pppscn/SmsForwarder#326]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

用IPV6做服务端，远程在外网不用内网穿透，但手机的临时IPV6关不了，而固定IPv6是运营商的公前缀加MAC转码过来的，
比如
![1689928716522_image](https://github.com/pppscn/SmsForwarder/assets/20149205/ebb38e1b-fb2b-4ca7-bf27-ea1fdb096d40)
查看了所有的变量，没有mac相前的，您看看这个能不能更新上去，辛苦了

**Comment by pppscn** [comment]
> 从 Android 6.0（API 级别 23）开始，Google 引入了一些限制，禁止直接获取设备的 MAC 地址。这是为了保护用户隐私和安全，因为 MAC 地址可以用于跟踪用户的位置

不具备通用性，且需求不大

**Comment by 7qin** [comment]
> > 从 Android 6.0（API 级别 23）开始，Google 引入了一些限制，禁止直接获取设备的 MAC 地址。这是为了保护用户隐私和安全，因为 MAC 地址可以用于跟踪用户的位置
> 
> 不具备通用性，且需求不大

大神，没MAC，只能手动一个一个的转IPV6公网IP哦
