### ISSUE TITLE
[Suggestion]: webParams 可以支持下自定义时间格式吗

### ISSUE THREAD

**Issue by bowencool** [pppscn/SmsForwarder#327]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

[滴答清单的 API](https://developer.dida365.com/api#/openapi?id=create-task) 只接受 "yyyy-MM-dd'T'HH:mm:ssZ" 这种格式，我也给他们反馈了，我觉得他们可能不会改

### 你觉得该怎么去完善会比较好？【非必答】

1. 可以用 `[receive_time:YYYY-MM-DDTHH:mm:ssZ]` 去格式化 [webParams](https://github.com/pppscn/SmsForwarder/wiki/%E9%99%84%E5%BD%951%EF%BC%9A%E5%90%91webhook%E5%8F%91%E9%80%81post-get-put-patch%E8%AF%B7%E6%B1%82#4webparams-%E5%8F%AF%E7%94%A8%E6%A0%87%E7%AD%BE%E5%88%97%E8%A1%A8%E6%B3%A8%E6%84%8Fv243-%E9%80%82%E7%94%A8)
2. 允许用户编写脚本自行发送请求？

**Comment by pppscn** [comment]
下载每周构建版，使用 `[receive_time:yyyy-MM-dd'T'HH:mm:ssZ]` 试试

https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by bowencool** [comment]
> 下载每周构建版，使用 `[receive_time:yyyy-MM-dd'T'HH:mm:ssZ]` 试试
> 
> https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

感谢，格式正确，添加成功！

但是 `receive_time` 好像是转发时间？这是另外一个问题，暂时不影响使用
<img width="283" alt="image" src="https://github.com/pppscn/SmsForwarder/assets/20217146/2a8f0a42-9989-4570-bbea-0ad8d264aceb">

**Comment by pppscn** [comment]
再试试

**Comment by bowencool** [comment]
可以了，谢谢

**Comment by bowencool** [comment]
这个功能会发布到正式版吗
