### ISSUE TITLE
[Bug]: 远程WOL有点问题

### ISSUE THREAD

**Issue by 7qin** [pppscn/SmsForwarder#328]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

v3.2.0

### 问题描述

根据  **wiki/附录2：主动请求(远程控制)** ,其中请求参数
ip | String | 否 | 内网IP地址
但ip地址如果不传的话，接口失效。目标电脑无法收到UDP包。

如果带IP，电脑如果只是休眠，可以正常唤醒，电脑如果关机时间比较长（一天以上），无法唤醒，，，

同样关机，使用局域网唤醒APP，不使用IP可以唤醒

### 复现步骤

重复以上步骤，

### 是否必现

是（Yes）

### 出现问题的手机信息

华为P9,小米14

### 出现问题的安卓版本、系统版本

8.0

**Comment by pppscn** [comment]
下载每周构建版试试

https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by 7qin** [comment]
![1](https://github.com/pppscn/SmsForwarder/assets/20149205/dc449944-a12e-46e1-98db-5a120439d3c4)
![2](https://github.com/pppscn/SmsForwarder/assets/20149205/feeda6bd-0997-4755-8f17-e3532430ec3b)
上次更新了IPV6,,,不行啊，还是不要升这个吧，感觉更乱

**Comment by 7qin** [comment]
> 下载每周构建版试试
> 
> https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

wol现在版可以无IP正常收发UDP包了
