### ISSUE TITLE
[Suggestion]: FRP升级了最新的XTCP

### ISSUE THREAD

**Issue by chendx-github** [pppscn/SmsForwarder#329]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

现在还是4.7

### 你觉得该怎么去完善会比较好？【非必答】

升级到5系列

**Comment by pppscn** [comment]
请重新下载每周构建版测试，重点测试XTCP行不行

https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml
