### ISSUE TITLE
每天自动断连接

### ISSUE THREAD

**Issue by necholas** [pppscn/SmsForwarder#33]
每天晚上23:30左右会自动重启，然后第二天就无法使用，快捷栏依旧有smsforwarder的logo，只有重新打开图标才能继续运行。这样就类似每天重启一遍软件了

**Comment by pppscn** [comment]
没有自动重启的机制，建议从手机系统方面排查一下，例如：网络、电源管理之类的

**Comment by necholas** [comment]
有新的qq群和微信群吗

**Comment by bumian** [comment]
> 每天晚上23:30左右会自动重启，然后第二天就无法使用，快捷栏依旧有smsforwarder的logo，只有重新打开图标才能继续运行。这样就类似每天重启一遍软件了

我也是同样的问题，需要重新打开图标才能用，请问下你现在解决了这个问题吗？

**Comment by pppscn** [comment]
qq 2 群：31330492
