### ISSUE TITLE
[Suggestion]: APP配置信息跨设备同步、WebDav配置备份建议 

### ISSUE THREAD

**Issue by Overbye** [pppscn/SmsForwarder#330]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

之前一直用Telegram-SMS，但目前短信转发器已经超越了该APP。但在Telegram-SMS上有一个比较好的功能：可以将A设备的APP的设置信息通过二维码扫描的方式同步传输给其他设备，免除重复配置的烦恼。虽然两个APP的设置信息量有差异，二维码的信息容量应该是够的。
不知道开发者是否有这种跨设备同步配置信息的想法，或者其他方案，比如WebDav同步配置？

### 你觉得该怎么去完善会比较好？【非必答】

- Qrcode分享设置信息跨设备同步
- 通过WebDav存储设备配置信息

**Comment by pppscn** [comment]
有没有可能已经有类似这样的功能了？

`客户端` → `一键换新机`
