### ISSUE TITLE
[Bug]: ipv6无法使用微信小程序的sms客户端

### ISSUE THREAD

**Issue by niueigang** [pppscn/SmsForwarder#331]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.2.0

### 问题描述

但是可以使用ipv6本地app的sms客户端,微信小程序的sms客户端连接不到

### 复现步骤

服务端开启，客户端输入服务端连接

### 是否必现

是（Yes）

### 出现问题的手机信息

华为mate20pro

### 出现问题的安卓版本、系统版本

EMUI12

**Comment by pppscn** [comment]
`微信小程序 SmsF客户端` 需要通过 `smsf.ppps.cn` 中转请求你的IPv6地址， [（ 具体原因详见）](https://github.com/pppscn/SmsForwarder/wiki/%E3%80%90%E5%BF%85%E8%AF%BB%E3%80%91%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#qv310%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%9A%84%E7%94%A8%E6%88%B7%E4%B8%BA%E4%BB%80%E4%B9%88%E4%BC%9A%E5%AF%B9%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%80%A0%E6%88%90%E5%8E%8B%E5%8A%9B)

但是阿里云ECS需要开通IPv6公网带宽（后付费）后才能访问外部的IPv6地址，

![ipv6网关](https://github.com/pppscn/SmsForwarder/assets/5105854/d131bf75-9424-43e0-b726-09b545bd551b)

而且收费不便宜（死贵），`SmsForwarder` 免费开源，没有盈利点，无法继续投入，抱歉！

![收费标准](https://github.com/pppscn/SmsForwarder/assets/5105854/9adf8407-ed0b-41d0-8b20-cab74135b668)

**Comment by pppscn** [comment]
感谢 `MY.` 提供 [教程](https://www.m6y.cc/archives/2001.html)，借助了第三方的隧道来曲线救国了

**其他参考教程：**

https://blog.csdn.net/WaiTinglw/article/details/104086370

https://blog.csdn.net/qq_37300767/article/details/115611946
