### ISSUE TITLE
[Suggestion]: 建议在选择Web客户端目录的时候弹出授权管理所有文件访问的权限

### ISSUE THREAD

**Issue by 955s** [pppscn/SmsForwarder#332]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

目前在软件内仅在主动控制.客户端 一键换机里面才会弹出授权管理所有文件访问的权限 这会导致要是你没使用过一键换机功能弹出授权管理所有文件访问的权限 就会导致即使你选了Web客户端目录后 也会无法通过浏览器访问Web界面

### 你觉得该怎么去完善会比较好？【非必答】

在选择Web客户端目录的时候检查是否已授权管理所有文件访问的权限 如未授权就弹出授权管理所有文件访问的权限

**Comment by pppscn** [comment]
请重新下载每周构建版（构建时间晚于2023年10月3日）测试

https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by wll8** [comment]
请求 web 客户端中的`选择目录`功能是做什么的？是可以在 `:5000` 中访问到该目录的文件吗？没有在 wiki 上找到具体说明。

**Comment by wll8** [comment]
支持目录列举模式吗？例如：

![image](https://github.com/pppscn/SmsForwarder/assets/28223260/37b283a4-70d2-464e-88f4-2945b48945d6)
