### ISSUE TITLE
[Bug]:  调用本地部署的Gotify时，通过发送通道测试报错，提示： Cleartext communication not enabled for client 

### ISSUE THREAD

**Issue by haoqi366** [pppscn/SmsForwarder#333]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.2.0 arm-v7a

### 问题描述

如题，在本地部署Gotify服务器，由于一些原因没有用ssl，所以只能通过http协议直接访问，但是在测试中会报错：java.net.UnknownServiceException: Cleartext communication not enabled for client ，同时实际接收短信也无法使用，此问题并非每台安卓设备都有，一台安卓6的手机(使用同一版本但是arm64架构的软件)完全正常，但是安卓4的儿童手表会报错。

### 复现步骤

自建一台Gotify服务器，关闭https，创建发送通道-Gotify，正常填入信息，测试-失败

### 是否必现

否（No）

### 出现问题的手机信息

米兔手表 4c

### 出现问题的安卓版本、系统版本

Android 4.4.4

### 提供解决方案

参考方案：https://blog.csdn.net/yzpbright/article/details/116020164

**Comment by pppscn** [comment]
> @pppscn 大佬 随身wifi 系统4.4.4 主动控制客户端登入服务提示java.net.UnknownServiceExceptiOn: CLEARTEXT communicationnot enabled for client，是不是系统太老不支持呀

覆盖安装 `每周构建版` 试试

**升级操作提示：** 
- `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
-  手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml
