### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by testwhite** [pppscn/SmsForwarder#336]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.2.0

### 问题描述

安卓端：配置多重规则，测试无法通过

并且 是 手机号 相等 13000000000
并且 是 短信内容 包含 迅雷
并且 是 短信内容 包含 登录账号

### 复现步骤

安卓端：配置多重规则，测试无法通过

并且 是 手机号 相等 13000000000
并且 是 短信内容 包含 迅雷
并且 是 短信内容 包含 登录账号

### 是否必现

是（Yes）

### 出现问题的手机信息

华为P40

### 出现问题的安卓版本、系统版本

鸿蒙3.0

**Comment by testwhite** [comment]
短信内容：【迅雷网络】验证码: 340364，用于登录帐号，请不要告诉他人。

测试了下：使用用于登录是没问题的   登录账号就不行

**Comment by pppscn** [comment]
到底是【账号】还是【帐号】，你这属于语文问题，跟我SmsF什么关系？
