### ISSUE TITLE
多重规则匹配有问题

### ISSUE THREAD

**Issue by parson1** [pppscn/SmsForwarder#337]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

否（No）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

v3.2.0

### 问题描述

转发规则中的多重规则有问题

### 复现步骤

我想实现转发手机号是12366或者手机号是1008611的所有短信，多重匹配的规则如下：
并且 是 手机号 相等 12366 
 或者 是 手机号 相等 1008611

测试时手机号填写12366，提示“未匹配中规则”
填写手机号1008611，可以正常转发

### 是否必现

否（No）

### 出现问题的手机信息

三星 s20 fe

### 出现问题的安卓版本、系统版本

安卓13

### 提供报错堆栈【请提供logcat抓取的日志，参考： https://blog.csdn.net/m0_64776928/article/details/126005119 】

![lADPJv8gZqs0yHLNCWDNBDg_1080_2400](https://github.com/pppscn/SmsForwarder/assets/48461546/db205160-3c1e-4d37-a166-055255e56536)
![a37f6fe6134414f4ff4e41bca27f735c](https://github.com/pppscn/SmsForwarder/assets/48461546/1d07137e-18fe-4539-b90a-96dae46d3a94)

**Comment by pppscn** [comment]
认真看一下wiki，注意空格缩进

https://github.com/pppscn/SmsForwarder/wiki/%E9%99%84%E5%BD%955%EF%BC%9A%E8%BD%AC%E5%8F%91%E8%A7%84%E5%88%99%E4%B9%8B%E5%A4%9A%E9%87%8D%E8%A7%84%E5%88%99
