### ISSUE TITLE
[Suggestion]: 建议短信指令增加短信发送功能

### ISSUE THREAD

**Issue by Autumn-one** [pppscn/SmsForwarder#338]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

我有另一个手机卡安装在另一个手机放在家里，通常我用该软件转发验证码，这样我就不用带两个手机了，但是有些时候我可能需要使用家里的那个手机发送短信，目前这是该软件无法做到的。

### 你觉得该怎么去完善会比较好？【非必答】

希望扩展短信指令的功能，可以控制另外一台手机发送短信。例如发出指令让卡2发送内容到10086：
smsf#send-sms#10086,卡2->这是要发送的内容

**Comment by pppscn** [comment]
### 5、发送短信（仅 `v3.3.0+` 适用）

```
smsf#sms#send#{"sim_slot":1,"phone_numbers":"15888888888;19999999999","msg_content":"短信内容"}
```
PS. 部分手机系统需要发送确认（无解，建议刷成类原生系统）

**请求参数** （与 [远程发短信](https://github.com/pppscn/SmsForwarder/wiki/%E9%99%84%E5%BD%952%EF%BC%9A%E4%B8%BB%E5%8A%A8%E8%AF%B7%E6%B1%82(%E8%BF%9C%E7%A8%8B%E6%8E%A7%E5%88%B6)#221-%E8%BF%9C%E7%A8%8B%E5%8F%91%E7%9F%AD%E4%BF%A1) 保持一致）

|  参数 | 类型  | 是否必填  | 说明  |
| :-------------: | :-------------: | :-------------: | ------------ |
| sim_slot | Int | 是 | 发送卡槽: 1=SIM1, 2=SIM2  |
| phone_numbers | String | 是 | 接收手机号码，多个手机号用半角分号分隔  |
| msg_content | String | 是 | 短信内容，70个字符内算一条，超过70个字符，每增加64字符累加1条，最多390字符（6条短信）  |

**Comment by pppscn** [comment]
请重新下载每周构建版测试

https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml
