### ISSUE TITLE
[Bug]: 测试Socket的mqtt功能，提示“请求失败：MQTT连接成功”

### ISSUE THREAD

**Issue by DeepooBelief** [pppscn/SmsForwarder#339]
### 是否有人曾提过类似的问题

是（Yes）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.2.0

### 问题描述

在配置Socket的mqtt发送通道中，点击测试，提示“请求失败：MQTT连接成功”，使用别的mqtt客户端可以在输入消息主题下会收到{"terminal_uid":"[Client_ID]"}的信息
之前有人提过类似问题，但是没有下文
[[Bug]: 关于MQTT能连接成功但是不能正常工作的问题 #310
](https://github.com/pppscn/SmsForwarder/issues/310)

### 复现步骤

服务器IP: test.mosquitto.org 端口: 1883
输入消息主题：任意
输出消息主题：任意
客户端ID：任意

### 是否必现

是（Yes）

### 出现问题的手机信息

Redmi K30s

### 出现问题的安卓版本、系统版本

Android12 MIUI14

### 提供截图或视频

![f3bfa8cffa06c7869cef75e47d5b656](https://github.com/pppscn/SmsForwarder/assets/101371088/35931cbb-dece-4dc0-87b6-aac3ce7105a0)
![image](https://github.com/pppscn/SmsForwarder/assets/101371088/719ad4f5-5035-43c0-8b5a-e8a7b2e74288)

**Comment by pppscn** [comment]
请重新下载每周构建版测试

https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by DeepooBelief** [comment]
> 请重新下载每周构建版测试
> 
> https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

成功了，感谢。再请问一下，如果需要使用SSL/TLS，我应该怎么做？端口直接填写8883会“连接失败”

**Comment by pppscn** [comment]
> > 请重新下载每周构建版测试
> > https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml
> 
> 成功了，感谢。再请问一下，如果需要使用SSL/TLS，我应该怎么做？端口直接填写8883会“连接失败”

看上去依赖的组件 https://gitee.com/xuankaicat/kmnkt 不支持

**Comment by pppscn** [comment]
> > > 请重新下载每周构建版测试
> > > https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml
> > 
> > 
> > 成功了，感谢。再请问一下，如果需要使用SSL/TLS，我应该怎么做？端口直接填写8883会“连接失败”
> 
> 看上去依赖的组件 https://gitee.com/xuankaicat/kmnkt 不支持

咱不考虑改造 kmnkt

**Comment by DeepooBelief** [comment]
好吧，谢谢帮助

**Comment by pppscn** [comment]
![通信方式](https://github.com/pppscn/SmsForwarder/assets/5105854/826f400d-8d5e-4bf2-b915-ba5b9a12a315)

这通信方式改成  `ssl`  试试

**Comment by DeepooBelief** [comment]
确实可以，感谢！
但是这个“通讯方式”能否改成选项菜单，之前试过“SSL/TLS”这种，点击“测试”后直接闪退或者重新进入主界面。如果能让用户进行选择而不是自己输入可能会更好。
谢谢你的帮助

**Comment by pppscn** [comment]
> 确实可以，感谢！ 但是这个“通讯方式”能否改成选项菜单，之前试过“SSL/TLS”这种，点击“测试”后直接闪退或者重新进入主界面。如果能让用户进行选择而不是自己输入可能会更好。 谢谢你的帮助

**已经改成单选** ，请重新下载每周构建版测试
https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

![微信截图_20231016143937](https://github.com/pppscn/SmsForwarder/assets/5105854/37510715-8e97-40ae-9a86-63d3ece63086)

**【注意】已经移除 `kmnkt` 依赖，重写了 `SocketUtils` ，帮忙重点测试一下**

**Comment by DeepooBelief** [comment]
你好，
现在功能似乎是正常的，但有两个地方有疑问
1. 配置完通道后点击“保存”再进来，选择的通信方式仍然是“TCP”，虽然实际测下来用的是SSL，只是一个显示问题。
2. 点击“测试“，如果测试失败，按钮会进入30秒的失能时间，不知这是否是刻意为之？

**Comment by pppscn** [comment]
> 你好， 现在功能似乎是正常的，但有两个地方有疑问
> 
> 1. 配置完通道后点击“保存”再进来，选择的通信方式仍然是“TCP”，虽然实际测下来用的是SSL，只是一个显示问题。
> 2. 点击“测试“，如果测试失败，按钮会进入30秒的失能时间，不知这是否是刻意为之？

1. 代码改漏一个变量，已修正
2. 测试按钮增加倒计时（时长取通用设置中的请求超时时间），避免重复点击

**Comment by DeepooBelief** [comment]
不好意思回复晚了。
万分感谢帮助，谢谢

**Comment by dahuazi** [comment]
大佬，请问这个输入消息主题是干嘛？能向里面发一个消息，让它返回一条电量信息吗？？
