### ISSUE TITLE
[Suggestion]: 是否可以在成功转发短信后一并删除掉短信呢

### ISSUE THREAD

**Issue by iferencz** [pppscn/SmsForwarder#340]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

我接受的都是验证码，转发成功后，无用的验证码堆积的越来越多，是否可以一并删除呢？谢谢开发者。

**Comment by pppscn** [comment]
不会考虑此功能，已经被人举报了，加上这个更坐实了是恶意软件

https://github.com/pppscn/SmsForwarder/wiki/%E3%80%90%E5%BF%85%E8%AF%BB%E3%80%91%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#q%E8%A3%85%E4%BA%86%E7%9F%AD%E4%BF%A1%E8%BD%AC%E5%8F%91%E5%99%A8%E4%B8%BA%E4%BB%80%E4%B9%88%E6%94%B6%E5%88%B0%E5%8F%8D%E8%AF%88%E4%B8%AD%E5%BF%83%E7%9A%84%E6%9D%A5%E7%94%B5%E6%88%96%E7%9F%AD%E4%BF%A1

**Comment by ywjheart** [comment]
绝对不能加自动删除短信或通话记录的功能，因为如果用户确实需要整理，可以人工批量删除的。如果存在自动删除行为，这安装smsf的人的用意让人质疑。
