### ISSUE TITLE
[Suggestion]: 电量回报，网络回报转为可配置的预定义规则，增加地理位置上报

### ISSUE THREAD

**Issue by ywjheart** [pppscn/SmsForwarder#341]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

目前这个app已经预定义了电话和短信的设置，但电量和网络则存在于设置界面，这些功能近期看起来已经没什么变化了，建议转为预定义规则， 电话和短信也是如此。
此外，安装在老人机或者儿童手机时，很需要一个功能，就是地理位置上报，比如可以选择5/10/15/60这样的不同频率的地理位置上报。

**Comment by pppscn** [comment]
预定义规则 暂不考虑，还是自行按需创建

自定义模板可用标签 `{{定位信息}}`（英文系统：`{{LOCATION}}`）

请重新下载每周构建版测试
https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by ywjheart** [comment]
自定义标签已经可以满足需求，感谢更新
