### ISSUE TITLE
[Bug]: 内置模块翻译错误：Linkman -> Contact

### ISSUE THREAD

**Issue by ywjheart** [pppscn/SmsForwarder#342]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.2

### 问题描述

在server/client 模块， 里面有Query Linkman, Add Linkman， 我推测是联系人，建议改成Query contacts, Add contact

### 复现步骤

点击左侧菜单，进入client，滚动到页面底部。进入server，也可以看到对应的设置。

### 是否必现

是（Yes）

### 出现问题的手机信息

所有机型

### 出现问题的安卓版本、系统版本

所有版本

### 提供截图或视频

看介绍部分

### 提供报错堆栈【请提供logcat抓取的日志，参考： https://blog.csdn.net/m0_64776928/article/details/126005119 】

看介绍部分

### 提供解决方案

看介绍部分

**Comment by pppscn** [comment]
已替换，感谢反馈

**Comment by ywjheart** [comment]
server/client 两个界面都已修复，感谢。
