### ISSUE TITLE
[Suggestion]: 格式化字段增加Location标签

### ISSUE THREAD

**Issue by ywjheart** [pppscn/SmsForwarder#343]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

目前转发消息格式时，可以自定义包括Phone,Sim card, Device, Time这些字段，建议增加location字段，这样在转发消息时，可以带上地理位置，比如通话记录如果有location，那我们就知道孩子或者老人打电话时当时大概的位置。对于一些可能的恶意短信，我们也可以知道当时大概在什么位置收到的。建议采纳。
比起server/client这种实时请求的操作，随消息转发或者我之前提到的定期回报机制，省去了frp server, 省去了smsforwader和frps之间的连接，降低了耗电。

**Comment by pppscn** [comment]
这样反而更加耗电，需要无时不刻不在后台刷新gps信息，才能在转发信息时获取到当前位置

**Comment by ywjheart** [comment]
能否在格式化时再获取地理位置？

**Comment by bohailaoyao** [comment]
这个功能好

**Comment by dxwq** [comment]
> 这样反而更加耗电，需要无时不刻不在后台刷新gps信息，才能在转发信息时获取到当前位置

可不可以在收到指定来电(或其它条件)时才去刷新gps

**Comment by pppscn** [comment]
自定义模板可用标签 `{{定位信息}}`（英文系统：`{{LOCATION}}`）

请重新下载每周构建版测试
https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by ywjheart** [comment]
测试正常，感谢作者细节优化。
