### ISSUE TITLE
[Suggestion]: 增加情景 scenarios 模块

### ISSUE THREAD

**Issue by ywjheart** [pppscn/SmsForwarder#344]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

目前已经存在事件驱动的rules模块，但电量变化是程序硬编码的，网络变化也是硬编码的。我提议增加一个情景模块，它使用3个部分来完成功能，triggers， message, senders.
triggers可以指定一个或多个变化条件，比如，电量变化，充电状态变化，网络类型变化，网络ip变化，时间，锁屏，解锁屏，前台程序切换
message可以是根据提供的标签来格式化。
sender 就是目前的rules里调用的方式。

通过这样的设计，我们可以在创建许多情景， 比如
1. 电量低于30%，或者高于80%， 发送消息，提醒充电或者拔掉充电器
2. 在每月1，15号发短信给运营商，查询流量，或者剩余通话时间
3. 网络类型或ip变化时，发送当前网络类型和ip
4. 每周六中午1点发送当前地理位置，这样家长可以知道儿童手表是否已经到指定的补习地点。

不同人实际用到的情景肯定很多，通过合理的trigger和格式化message来实现。

**Comment by pppscn** [comment]
想法很好，但是与 `【短信】转发器`  的初衷越来越远了，这些都可以重新搞一个类似 takser 或 todolist 一样强大的app了

所谓灵活的 `triggers`，这是最难实现的部分，越灵活编码越困难，这就是为什么当前是直接写死的原因

**Comment by ywjheart** [comment]
目前已经不仅仅是sms转发，更像是把一个手机上收到的消息（电话，短信，app通知）转发到一个主力手机，把备用手机留家里，或者是从儿童手表转发消息。
作者可以考虑做一个儿童手表版本，主要侧重的是地理位置。至于app通知那些反而是没什么用的，手表的RAM普遍都很小。

**Comment by pppscn** [comment]
儿童手表 自己的管理端app本来都可以直接查看位置跟短信了，为什么还需要安装一个smsf

**Comment by ywjheart** [comment]
手表配套app确实是可以看短信，但是它是不能像smsf这样在收到消息或者来电时，通过自定义通道发送提醒的。而且，还有很多限制，比如手表app在ios需要切换到中国区，家长的其他设备没法都安装一个手表app。smsf转发儿童消息/来电这些到telegram群组这类操作非常好用，家庭成员都可以看到。当然，如果带上地理位置标签就更好了，儿童手表本身每隔几分钟在后台刷新地理位置，smsf去取位置可能没什么额外负担。

**Comment by pppscn** [comment]
![Screenshot_20231205_115550](https://github.com/pppscn/SmsForwarder/assets/5105854/3826aab8-4f84-42d5-bd82-4447ee86019e)

参考MIUI的自动任务，开发中

**Comment by pppscn** [comment]
![Screenshot_20231207_111016](https://github.com/pppscn/SmsForwarder/assets/5105854/00dff8e2-c101-441b-80cd-fa95dee055db)

**注意：crontab 的时间间隔，不要造成短信轰炸了**
