### ISSUE TITLE
[Bug]: rules/senders修改后，通过在线或离线clone得到的依然是旧配置

### ISSUE THREAD

**Issue by ywjheart** [pppscn/SmsForwarder#345]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

3.2 weekly build on 2 oct

### 问题描述

在修改rules或者senders后，用另一个手机在线导入配置，或者在旧手机离线导出配置，都得到修改前的配置。

### 复现步骤

在A手机添加一个规则或者修改任意规则的sender，或者增加sender，用B手机在线导入，得到的是修改前的配置。
如果在A手机force stop，然后启动smsforwarder，再做一样的操作，则可以得到最新的配置

### 是否必现

是（Yes）

### 出现问题的手机信息

Pixel 6P, MIUI 14,MIUI 10

### 出现问题的安卓版本、系统版本

Android 10, Android 13

**Comment by pppscn** [comment]
请重新下载每周构建版测试
https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by ywjheart** [comment]
确认已修复，感谢
