### ISSUE TITLE
[Bug]: 转发记录里面显示false，但是仍然标记成功，导致收不到通知。

### ISSUE THREAD

**Issue by kkxg** [pppscn/SmsForwarder#346]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.2.0

### 问题描述

你好，我是通过简介中的机油链接，搭配quicker发送通知到电脑使用的。
动作文档见链接：[https://getquicker.net/KC/Manual/Doc/connection](https://getquicker.net/KC/Manual/Doc/connection)

应用通知的设置如图，只替换了蓝框的部分：
![image](https://github.com/pppscn/SmsForwarder/assets/20535377/96f92155-ea64-455f-a894-e52e2f1c5b63)

它平时工作得很好，但是偶尔会出现手机有通知，电脑上没有的情况。（因为手机的通知没有规律，我也没发现出问题的时间规律）
如截图：
![image](https://github.com/pppscn/SmsForwarder/assets/20535377/f8160eb6-e7ce-421b-bc35-c0d1fc22952b)

在里面显示false的时候，转发结果仍然标记为“成功”。没有判断，和这种情况下的重发措施，导致电脑收不到通知。

直到有一次我发现quicker在自动重连。状态点点是黄色的：
![image](https://github.com/pppscn/SmsForwarder/assets/20535377/c17c72f3-490d-40e1-9266-158a57a5b6ac)

猜测是因为quicker长连接在自动重连导致的。

### 复现步骤

自动重连的过程中那就是还没有建立连接，因此我手动断开了quicker的长连接：
![image](https://github.com/pppscn/SmsForwarder/assets/20535377/9a177c64-75be-453b-9b46-0343085fdf33)

用软件重发通知：
![image](https://github.com/pppscn/SmsForwarder/assets/20535377/7689ae8d-461b-4e96-8092-1c0994977da9)
显示了相同的错误。

在消息里面反映是false的情况下是否可以判断为失败，而不是转发成功？
从而可以使用软件里面的请求重试机制进行重发。。

### 是否必现

是（Yes）

### 出现问题的手机信息

Redmi K20Pro

### 出现问题的安卓版本、系统版本

MIUI 12.5.6稳定版 ,Android 11

**Comment by kkxg** [comment]
自动重连的截图忘了加：
![image](https://github.com/pppscn/SmsForwarder/assets/20535377/31668322-0929-46ce-a9cc-43a166f712ef)

**Comment by pppscn** [comment]
`webhook` 只要返回 http 200 状态就算成功，并不会具体解析返回报文（每个webhook返回的东西千差万别，没法去解析）

**Comment by ywjheart** [comment]
会不会是你没有设置miui的virtual number/虚拟号码, 应该允许smsf读取真实sim 卡号。

**Comment by pppscn** [comment]
![微信截图_20231014144809](https://github.com/pppscn/SmsForwarder/assets/5105854/15a8e69d-d69e-4b54-9bb1-43a687577bb6)

已优化，请重新下载每周构建版测试

https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml
