### ISSUE TITLE
[Suggestion]: 增加选项：转发如果失败，自动打开wifi

### ISSUE THREAD

**Issue by ywjheart** [pppscn/SmsForwarder#347]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

老手机如果保持wifi，则耗电比较快，如果不开启wifi，则smsf无法转发消息。

### 你觉得该怎么去完善会比较好？【非必答】

添加一个选项，收到短信或者电话这类关键消息时，如果程序无法读取到ip或出现转发失败，应该自动启动wifi。数据开关也可以考虑，建议分开选项。

**Comment by pppscn** [comment]
目前测试仅部分手机系统支持，不会考虑添加此功能，自行fork之后修改吧

详见 [4、【试验性】打开或关闭 WiFi](https://github.com/pppscn/SmsForwarder/wiki/%E9%99%84%E5%BD%959%EF%BC%9A%E7%9F%AD%E4%BF%A1%E6%8C%87%E4%BB%A4#4%E8%AF%95%E9%AA%8C%E6%80%A7%E6%89%93%E5%BC%80%E6%88%96%E5%85%B3%E9%97%AD-wifi)](https://github.com/pppscn/SmsForwarder/wiki/%E9%99%84%E5%BD%959%EF%BC%9A%E7%9F%AD%E4%BF%A1%E6%8C%87%E4%BB%A4#4%E8%AF%95%E9%AA%8C%E6%80%A7%E6%89%93%E5%BC%80%E6%88%96%E5%85%B3%E9%97%AD-wifi)
