### ISSUE TITLE
[Suggestion]: 增加专有钉钉的支持

### ISSUE THREAD

**Issue by kylinpoet** [pppscn/SmsForwarder#348]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

企业专有钉钉的 token地址是：
https://zwopenplatform.10e.alibaba-inc.com/robot/send?access_token=xxx

但是钉钉的 token地址是:
https://oapi.dingtalk.com/robot/send...
如果 只填 token 是不能成功的。

**Comment by pppscn** [comment]
只有链接的区别吗？ 其他都一样？  贴一下钉钉官方的文档地址

**Comment by kylinpoet** [comment]
https://openplatform-portal.dg-work.cn/portal/?spm=a2q2b.13441934.0.0.147d6fbaZhdaa9#/helpdoc?apiType=DEV_GUIDE&docKey=3355127

**Comment by pppscn** [comment]
已调整输入框的限制

请重新下载每周构建版测试

https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by mymine** [comment]
> https://openplatform-portal.dg-work.cn/portal/?spm=a2q2b.13441934.0.0.147d6fbaZhdaa9#/helpdoc?apiType=DEV_GUIDE&docKey=3355127
> 
> 晕，怎么忘了贴文档地址。。
> 
> 应该是一样的

企业版的和普通版有啥区别呀？

**Comment by kylinpoet** [comment]
已正常使用，谢谢
