### ISSUE TITLE
[Suggestion]: 希望增加彩信转发功能

### ISSUE THREAD

**Issue by rbzan** [pppscn/SmsForwarder#351]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

有的短信是带有图片发来的，不能转发导致有时候没有及时看到。

### 你觉得该怎么去完善会比较好？【非必答】

添加彩信转发功能

**Comment by pppscn** [comment]
问题在于接收下来的图片、音频等内容通过什么通道转发出去？  你不会要求还要搞一个上传图床的功能吧？

**Comment by rbzan** [comment]
非常感谢作者回复，我遇到的几个彩信，只有文字是有效信息，可以暂时只转发文字部分，图片的话彩信是能提取到图片链接吗，可以的话也可以图片单独用URL显示，点击自行打开查看。

pppscn ***@***.***> 于2023年10月16日周一 23:36写道：

**Comment by pppscn** [comment]
是什么网站或软件发出来的？先来几个彩信样本，看看能不能解析到 

> 非常感谢作者回复，我遇到的几个彩信，只有文字是有效信息，可以暂时只转发文字部分，图片的话彩信是能提取到图片链接吗，可以的话也可以图片单独用URL显示，点击自行打开查看

**Comment by pppscn** [comment]
暂时无解，先关闭
