### ISSUE TITLE
[Suggestion]: 希望可以给企业微信应用推送添加自定义推送api地址

### ISSUE THREAD

**Issue by samir2015dzh** [pppscn/SmsForwarder#352]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

大佬在wiki里面也提到了，现在的企业微信应用需要可信ip才能进行转发，但是家用宽带最多只给动态公网ip，我专门买了一台vps做微信转发代理，但是应用里面并没有这个选项

**Comment by pppscn** [comment]
直接反向代理（proxy_pass）api地址？

**Comment by pppscn** [comment]
请重新下载每周构建版测试
https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by samir2015dzh** [comment]
> 请重新下载每周构建版测试 https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

已经下载测试了，但是填入我自己搭建的微信转发代理之后，点击测试提示not found

**Comment by pppscn** [comment]
反向代理到这个  `https://qyapi.weixin.qq.com/cgi-bin` 吗?

**Comment by samir2015dzh** [comment]
> 反向代理到这个 `https://qyapi.weixin.qq.com/cgi-bin` 吗?
> 
> 或者 你贴一下你的反向代理配置

location /cgi-bin/gettoken {
    proxy_pass https://qyapi.weixin.qq.com;
}
location /cgi-bin/message/send {
    proxy_pass https://qyapi.weixin.qq.com;
}
location  /cgi-bin/menu/create {
    proxy_pass https://qyapi.weixin.qq.com;
}

**Comment by pppscn** [comment]
已经按 `proxy_pass https://qyapi.weixin.qq.com/;` 处理，请重新下载每周构建版测试

https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by samir2015dzh** [comment]
> 已经按 `proxy_pass https://qyapi.weixin.qq.com;` 处理，请重新下载每周构建版测试
> 
> https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

已经测试成功了，非常感谢大佬的耐心
