### ISSUE TITLE
[Bug]: 微信消息最大长度只有52

### ISSUE THREAD

**Issue by aohanhongzhi** [pppscn/SmsForwarder#353]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

否（No）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

3.2.5

### 问题描述

微信消息最大文字太少，只有52个，后面就变成三个点了

### 复现步骤

微信

### 是否必现

是（Yes）

### 出现问题的手机信息

小米 11 lite

### 出现问题的安卓版本、系统版本

android12

**Comment by pppscn** [comment]
哪有 3.2.5 版本？

`APP通知转发` 转发的是你通知栏上能看到的消息，不是入侵微信直接获取消息
