### ISSUE TITLE
[Bug]: 每条消息都会推送多次

### ISSUE THREAD

**Issue by lcy1364** [pppscn/SmsForwarder#354]
### 是否有人曾提过类似的问题

是（Yes）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.2.0

### 问题描述

出现每条消息推送两次到三次的情况
打开软件后一两天内就会出现
已经设置自动过滤2秒内重复消息，不起作用
设置了bark的推送
设置了权限全部允许，后台无限制，允许自启动
转为系统app后会闪退所以没有操作
有人提过类似问题但未提供解决方法：
#150 

### 复现步骤

打开软件后一两天内随机出现

### 是否必现

否（No）

### 出现问题的手机信息

红米note12 turbo

### 出现问题的安卓版本、系统版本

Android 13 MIUI 14.0.19

### 提供截图或视频

![IMG_20231023_173915](https://github.com/pppscn/SmsForwarder/assets/26016484/18377a75-b10a-4286-927d-55aafb970eab)
![Screenshot_2023-10-23-17-32-05-318_com idormy sms forwarder](https://github.com/pppscn/SmsForwarder/assets/26016484/5b8cadda-a296-43df-80e6-065c6d7ea8e8)

### 提供报错堆栈【请提供logcat抓取的日志，参考： https://blog.csdn.net/m0_64776928/article/details/126005119 】

稍后可以上传

### 提供解决方案

强制关闭重新打开可以暂时解决，一两天之内又会重新出现

**Comment by pppscn** [comment]
转发规则有几天？ 列表跟详情都截图

**Comment by lcy1364** [comment]
![Screenshot_2023-10-23-18-07-51-925_com idormy sms forwarder-edit](https://github.com/pppscn/SmsForwarder/assets/26016484/33119b23-982f-4cfe-8bb7-60f52f888b37)
![Screenshot_2023-10-23-18-07-57-905_com idormy sms forwarder-edit](https://github.com/pppscn/SmsForwarder/assets/26016484/c9d6cd76-ab2d-4d3a-8958-ad1a3ec18560)
![Screenshot_2023-10-23-18-08-02-880_com idormy sms forwarder-edit](https://github.com/pppscn/SmsForwarder/assets/26016484/f107c3db-fee6-415b-88bc-95d97cc406e8)

麻烦作者了，只设置了这几条，应用转发用的是包名匹配

**Comment by Frankcsc** [comment]
+1，我这也经常有这个bug，一般都是杀后台然后好了（日志我给删了，才看到这个issue）

**Comment by pppscn** [comment]
下次碰到这个情况，不强制重启app，进入【关于软件】点击【清理缓存】试试

**Comment by Frankcsc** [comment]
今天已经进化到一条推送五次了，尝试清理缓存，无法解决。图1，清理前一条推送五次。图2，清理缓存。图3，仍推送五次。图四，转发规则。
![Screenshot_2023-11-22-14-15-12-407_com idormy sms forwarder](https://github.com/pppscn/SmsForwarder/assets/45666537/39beb18e-6e8f-49d8-81f7-a9c82701b20c)
![Screenshot_2023-11-22-14-15-17-572_com idormy sms forwarder](https://github.com/pppscn/SmsForwarder/assets/45666537/37efd680-fb7e-40a0-84eb-817cb2ffeb55)
![Screenshot_2023-11-22-14-16-07-607_com idormy sms forwarder](https://github.com/pppscn/SmsForwarder/assets/45666537/3c1ff218-522a-4e84-81a7-86b846732cb6)
![Screenshot_2023-11-22-14-20-54-301_com idormy sms forwarder-edit](https://github.com/pppscn/SmsForwarder/assets/45666537/bc491854-47fa-4d16-87ee-f18f366cdf66)

**Comment by tianvier** [comment]
+1 清理缓存没用

**Comment by pppscn** [comment]
有条件的的话，提供一下logcat抓取的日志，参考： https://blog.csdn.net/m0_64776928/article/details/126005119

**Comment by Frankcsc** [comment]
[logcat.log](https://github.com/pppscn/SmsForwarder/files/13446540/logcat.log)
我的规则是使用webhook转发支付宝的通知，目前状态是一条通知转发3次，上面这个log是用“adb logcat 10 *:E > D:\Logcat\logcat.log”抓取的，抓取过程：支付宝转账进行到等待按指纹的那一步，开始抓取，按指纹付款，有通知后ctrl+c停止抓取。
对adb的使用没啥了解，上面这个log我看内容非常多，我也不会看，如果需要其他log可以提。

**Comment by pppscn** [comment]
> [logcat.log](https://github.com/pppscn/SmsForwarder/files/13446540/logcat.log) 我的规则是使用webhook转发支付宝的通知，目前状态是一条通知转发3次，上面这个log是用“adb logcat 10 *:E > D:\Logcat\logcat.log”抓取的，抓取过程：支付宝转账进行到等待按指纹的那一步，开始抓取，按指纹付款，有通知后ctrl+c停止抓取。 对adb的使用没啥了解，上面这个log我看内容非常多，我也不会看，如果需要其他log可以提。

没看到有效的日志，我想确认的是多次通知时  通知栏的 内容是否 完全一模一样

**Comment by pppscn** [comment]
> 手机通知栏弹出一条符合条件的通知 A - 转发器用webhook推送三次 A - 内容完全一致：A A A； 手机通知栏又弹出一条符合条件的通知 B - 转发器用webhook推送三次 B - 内容完全一致：B B B；
> 
> 和手机通知栏的通知几次无关，通知1次，webhook 3条，通知2次，webhook 6条，通知3次，webhook 9条。

你看到一条通知，不一定是通知一次，这才是要抓日志的原因，到底有几次广播，每次广播的原始内容是否一致

**Comment by Frankcsc** [comment]
上次抓的log时Error级别的，新抓了两个看看呢：
第一个是“.\adb logcat *:V > D:\logs\logcat.log”
第二个是“.\adb logcat -v time > D:\logs\logcat2.log”
[logcat.log](https://github.com/pppscn/SmsForwarder/files/13447330/logcat.log)
[logcat2.log](https://github.com/pppscn/SmsForwarder/files/13447331/logcat2.log)
两次日志都是用支付宝给别人转账1分钱，通知栏显示有1条通知。第一次转发器webhook发送了3次均成功，第二次转发器webhook发送了3次，成功一次。
![OZJ{2NVM}V}6URALBI3)@42](https://github.com/pppscn/SmsForwarder/assets/45666537/52da6163-38f2-4e78-84d3-fc16f5f9a39d)

**Comment by ywjheart** [comment]
建议遇到问题的同学尝试：超时类设置都设为最大值，比如： 超时时长设为99秒，把重复消息过滤设置为120秒，重复间隔99秒，重复1次。

这可能与部分手机的省电策略有关， 我在Pixel6p从没遇到这个问题，在小米12 Turbo之前经常遇到，修改设置后似乎没这个问题了。
