### ISSUE TITLE
[Suggestion]: About network status changes monitor 

### ISSUE THREAD

**Issue by rRiInNgG** [pppscn/SmsForwarder#355]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

希望可以提取到 wifi 网络的 ssid，以及更换的sim卡槽。
I want the monitor to provide the changed network information including ssid and sim.

**Comment by CozmoAlien** [comment]
English version ?

**Comment by rRiInNgG** [comment]
> English version ?

I have updated.Hope you can read my poor speaking.

**Comment by pppscn** [comment]
**请重新下载每周构建版测试**
https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

监听开关：
![监听开关](https://github.com/pppscn/SmsForwarder/assets/5105854/51a6f1a1-1dfa-48ae-8633-2ed286c2e5d6)

转发规则：
![转发规则](https://github.com/pppscn/SmsForwarder/assets/5105854/b855a968-6287-436a-8702-e8f5adc3efba)

通知内容：
```
66666666
[SIM-1]
运营商名: 中国电信
卡槽索引: 0
手机号码: +8619905050505
国家代码: cn
订阅标识: 2
[SIM-2]
运营商名: 中国移动
卡槽索引: 1
手机号码: +8615806060606
国家代码: cn
订阅标识: 1
SIM卡槽状态监控
2023-11-21 17:13:20
pppscn的Mi 10S
```

PS. 英语水平有限，自行翻译吧

**Comment by rRiInNgG** [comment]
谢谢开发者。我目前发现有一些小问题。我是用的是meizu 17 flyme10.2.0.0A，有一些判断时机需要调整一下：

1.这个是更换蜂窝网络，可能需要一点延时或者当前网络信息 前后对比（应该有一张显示 电信）；
![1700624984236](https://github.com/pppscn/SmsForwarder/assets/38179618/46a1293c-873c-4e9a-9dbb-34340e247c19)
2.这两种是 wifi 跟蜂窝切换 或者 wifi ssid切换是遇到的，或许问题类型跟上述的类似；
![image](https://github.com/pppscn/SmsForwarder/assets/38179618/c3404b57-eb2c-40f9-88f9-9bb7963f7a5b)
![image](https://github.com/pppscn/SmsForwarder/assets/38179618/3e136def-bf14-40dc-a12c-630f52ce240c)

非常感谢能忙里抽出宝贵时间修改。

**Comment by pppscn** [comment]
延迟2秒再获取信息

请重新下载每周构建版测试
https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by rRiInNgG** [comment]
蜂窝网络 切换 的包名 77777777，有问题。如图，getNetworkOperatorName 好像只能获取手机第一次注册的 Sim 卡的信息。
![dce6048d98b5cc1f97a84d125798c24](https://github.com/pppscn/SmsForwarder/assets/38179618/3b440038-c03f-4b18-a972-886182f36a3e)
我根据别人的一些方法，拼凑了一下效果达成。我 push 一下你看一下，我才开始学习 and 开发，望修整。
![d389441dcefa6fd900b341d30fbaccd](https://github.com/pppscn/SmsForwarder/assets/38179618/b384adb1-79e5-4885-b16b-2e8aa9365883)

**Comment by pppscn** [comment]
> 蜂窝网络 切换 的包名 77777777，有问题。如图，getNetworkOperatorName 好像只能获取手机第一次注册的 Sim 卡的信息。 ![dce6048d98b5cc1f97a84d125798c24](https://user-images.githubusercontent.com/38179618/284848602-3b440038-c03f-4b18-a972-886182f36a3e.png) 我根据别人的一些方法，拼凑了一下效果达成。但是有一个版本限制 @RequiresApi(Build.VERSION_CODES.Q) 我 push 一下你看一下，我才开始学习 and 开发，望修整。 ![d389441dcefa6fd900b341d30fbaccd](https://user-images.githubusercontent.com/38179618/284848660-b384adb1-79e5-4885-b16b-2e8aa9365883.jpg) 要 push request 哪个分支？

main 分支

**Comment by pppscn** [comment]
感谢PR，已合并
