### ISSUE TITLE
[Suggestion]: 希望 手机短信转发通道能 添加检测 bark服务器或者其他服务器无法推送的时候启用短信转发功能

### ISSUE THREAD

**Issue by h605290713** [pppscn/SmsForwarder#356]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

希望 手机短信转发通道能添加检测 bark服务器或者其他服务器无法推送的时候启用短信转发功能

### 你觉得该怎么去完善会比较好？【非必答】

希望 手机短信转发通道能添加检测 bark服务器或者其他服务器无法推送的时候启用短信转发功能

**Comment by pppscn** [comment]
现有功能已经能满足你的需求：

一个转发规则上可以指定多个 `发送通道`：依次指定 bark 、短信 发送通道，然后 `执行逻辑` 设置为 `成功即止`

参考之前的issues

https://github.com/pppscn/SmsForwarder/issues/247#issuecomment-1416917488
