### ISSUE TITLE
[Suggestion]: 忽略已被系统拦截的来电

### ISSUE THREAD

**Issue by bowencool** [pppscn/SmsForwarder#357]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

有一些推销电话，被系统（MIUI 14）拦截了，但记录还是被转发了

### 你觉得该怎么去完善会比较好？【非必答】

被系统拦截的来电应当被忽略

**Comment by pppscn** [comment]
做不到，自己制定好规则
