### ISSUE TITLE
使用企业微信应用消息无法复制Secret - Version 1.7.4

### ISSUE THREAD

**Issue by dzvision** [pppscn/SmsForwarder#36]
Version: v1.7.4
Android: MIUI 12.0.1 (Android 9)
重现步骤： 
直接打开添加发送方后输入Secret长按无复制选项。

可以复制企业ID, App ID，但是Secret无法复制且无法查看已输入的。Secret非常长比较难每次都输对。

可不可以添加可查看、可复制、或可二维码扫描的功能。

**Comment by pppscn** [comment]
出于隐私保护，关键字段都采用星号显示，但是可以粘贴的

**Comment by dzvision** [comment]
经测试，无法粘贴
视频如下：
https://rdfzweb.obs.cn-east-3.myhuaweicloud.com:443/shared/Screenrecorder-2021-09-26-06-06-54-891%5B1%5D.mp4
