### ISSUE TITLE
[Bug]: 重启手机 frpc 需要手动重连

### ISSUE THREAD

**Issue by jiashu1024** [pppscn/SmsForwarder#360]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.2.0

### 问题描述

手机重启后，frpc需要重新手动点击连接

### 复现步骤

已经确保 app 不会被 kill，重启 app 是正常自启动的，但是重启后，frpc 没有重连，点进 frpc 页面也是显示没有运行状态

### 是否必现

否（No）

### 出现问题的手机信息

华为matepad pro

### 出现问题的安卓版本、系统版本

鸿蒙 3

**Comment by pppscn** [comment]
参考这个issue：https://github.com/pppscn/SmsForwarder/issues/222

**Comment by jiashu1024** [comment]
> 参考这个issue：#222

这个配置在重启手机情况下也适用吗？我的服务器没有宕机，是手机重启

**Comment by pppscn** [comment]
> > 参考这个issue：#222
> 
> 这个配置在重启手机情况下也适用吗？我的服务器没有宕机，是手机重启

还有 https://github.com/pppscn/SmsForwarder/issues/199

**Comment by jiashu1024** [comment]
> > > 参考这个issue：#222
> > 
> > 
> > 这个配置在重启手机情况下也适用吗？我的服务器没有宕机，是手机重启
> 
> 还有 #199

好呢 感谢

**Comment by jiashu1024** [comment]
> > > 参考这个issue：#222
> > 
> > 
> > 这个配置在重启手机情况下也适用吗？我的服务器没有宕机，是手机重启
> 
> 还有 #199

我尝试了，将那个时间从 60 调到了 1800 了，重启手机后，软件自启动成功我已经确保了，但是内置的 frpc 是无法自启动运行的。这个有解决办法吗

**Comment by pppscn** [comment]
> > > > 参考这个issue：#222
> > > 
> > > 
> > > 这个配置在重启手机情况下也适用吗？我的服务器没有宕机，是手机重启
> > 
> > 
> > 还有 #199
> 
> 我尝试了，将那个时间从 60 调到了 1800 了，重启手机后，软件自启动成功我已经确保了，但是内置的 frpc 是无法自启动运行的。这个有解决办法吗

是没启动还是连接失败？ 有没有日志？

**Comment by jiashu1024** [comment]
> > > > > 参考这个issue：#222
> > > > 
> > > > 
> > > > 这个配置在重启手机情况下也适用吗？我的服务器没有宕机，是手机重启
> > > 
> > > 
> > > 还有 #199
> > 
> > 
> > 我尝试了，将那个时间从 60 调到了 1800 了，重启手机后，软件自启动成功我已经确保了，但是内置的 frpc 是无法自启动运行的。这个有解决办法吗
> 
> 是没启动还是连接失败？ 有没有日志？ FRPC配置有开启自动运行了吧

是没有启动，日志是空的，frpc配置开启自动运行是什么意思，难道我哪个地方没有配置到嘛

**Comment by jiashu1024** [comment]
> > > > > 参考这个issue：#222
> > > > 
> > > > 
> > > > 这个配置在重启手机情况下也适用吗？我的服务器没有宕机，是手机重启
> > > 
> > > 
> > > 还有 #199
> > 
> > 
> > 我尝试了，将那个时间从 60 调到了 1800 了，重启手机后，软件自启动成功我已经确保了，但是内置的 frpc 是无法自启动运行的。这个有解决办法吗
> 
> 是没启动还是连接失败？ 有没有日志？ FRPC配置有开启自动运行了吧

这个解决了，就是 frpc 日志我感觉有些问题，
<img width="686" alt="image" src="https://github.com/pppscn/SmsForwarder/assets/67859663/8de144c5-e37c-41d7-8f30-3d939e6e6f42">
为什么我连接成功后，我手机别的端口也会去连接呢，而且还报 token 不一致的错误。

**Comment by pppscn** [comment]
> > > > > > 参考这个issue：#222
> > > > > 
> > > > > 
> > > > > 这个配置在重启手机情况下也适用吗？我的服务器没有宕机，是手机重启
> > > > 
> > > > 
> > > > 还有 #199
> > > 
> > > 
> > > 我尝试了，将那个时间从 60 调到了 1800 了，重启手机后，软件自启动成功我已经确保了，但是内置的 frpc 是无法自启动运行的。这个有解决办法吗
> > 
> > 
> > 是没启动还是连接失败？ 有没有日志？ FRPC配置有开启自动运行了吧
> 
> 这个解决了，就是 frpc 日志我感觉有些问题， <img alt="image" width="686" src="https://user-images.githubusercontent.com/67859663/284056041-8de144c5-e37c-41d7-8f30-3d939e6e6f42.png"> 为什么我连接成功后，我手机别的端口也会去连接呢，而且还报 token 不一致的错误。

认真研究一下 frp 文档吧，字面意思 token 不匹配

**Comment by jiashu1024** [comment]
> > > > > > > 参考这个issue：#222
> > > > > > 
> > > > > > 
> > > > > > 这个配置在重启手机情况下也适用吗？我的服务器没有宕机，是手机重启
> > > > > 
> > > > > 
> > > > > 还有 #199
> > > > 
> > > > 
> > > > 我尝试了，将那个时间从 60 调到了 1800 了，重启手机后，软件自启动成功我已经确保了，但是内置的 frpc 是无法自启动运行的。这个有解决办法吗
> > > 
> > > 
> > > 是没启动还是连接失败？ 有没有日志？ FRPC配置有开启自动运行了吧
> > 
> > 
> > 这个解决了，就是 frpc 日志我感觉有些问题， <img alt="image" width="686" src="https://user-images.githubusercontent.com/67859663/284056041-8de144c5-e37c-41d7-8f30-3d939e6e6f42.png"> 为什么我连接成功后，我手机别的端口也会去连接呢，而且还报 token 不一致的错误。
> 
> 认真研究一下 frp 文档吧，字面意思 token 不匹配

我是已经成功连接上了，app 里也能获取到定位等信息，但是我服务器上还在输出我手机那个 ip 别的端口在尝试连接服务器 frp 端口，并且显示密码错误。我刚才尝试发现我手机上 froc 配置那里显示并没有运行，也就是是绿色三角的开始按键，但是我却能通过 client 获取到那台手机的 定位等信息。我怀疑就是 app 里有别的线程依旧在运行，没有被结束掉。所以导致我手机里看着 frpc 没有运行，但是实际上有一个看不到的线程在实际运行着。为什么手机上有多个端口在尝试和 frps 建立连接，而且我的 token 肯定是配置对的，因为其中有一个端口是和服务器成功建立连接的
<img width="690" alt="image" src="https://github.com/pppscn/SmsForwarder/assets/67859663/32bd66a6-a0b4-4872-88aa-8b5e6ca93430">

**Comment by pppscn** [comment]
> > > > > > > > 参考这个issue：#222
> > > > > > > 
> > > > > > > 
> > > > > > > 这个配置在重启手机情况下也适用吗？我的服务器没有宕机，是手机重启
> > > > > > 
> > > > > > 
> > > > > > 还有 #199
> > > > > 
> > > > > 
> > > > > 我尝试了，将那个时间从 60 调到了 1800 了，重启手机后，软件自启动成功我已经确保了，但是内置的 frpc 是无法自启动运行的。这个有解决办法吗
> > > > 
> > > > 
> > > > 是没启动还是连接失败？ 有没有日志？ FRPC配置有开启自动运行了吧
> > > 
> > > 
> > > 这个解决了，就是 frpc 日志我感觉有些问题， <img alt="image" width="686" src="https://user-images.githubusercontent.com/67859663/284056041-8de144c5-e37c-41d7-8f30-3d939e6e6f42.png"> 为什么我连接成功后，我手机别的端口也会去连接呢，而且还报 token 不一致的错误。
> > 
> > 
> > 认真研究一下 frp 文档吧，字面意思 token 不匹配
> 
> 我是已经成功连接上了，app 里也能获取到定位等信息，但是我服务器上还在输出我手机那个 ip 别的端口在尝试连接服务器 frp 端口，并且显示密码错误。我刚才尝试发现我手机上 froc 配置那里显示并没有运行，也就是是绿色三角的开始按键，但是我却能通过 client 获取到那台手机的 定位等信息。我怀疑就是 app 里有别的线程依旧在运行，没有被结束掉。所以导致我手机里看着 frpc 没有运行，但是实际上有一个看不到的线程在实际运行着。为什么手机上有多个端口在尝试和 frps 建立连接，而且我的 token 肯定是配置对的，因为其中有一个端口是和服务器成功建立连接的 <img alt="image" width="690" src="https://user-images.githubusercontent.com/67859663/284067898-32bd66a6-a0b4-4872-88aa-8b5e6ca93430.png">

配置列表有几条配置？ 截图看看

正常不会有这样的情况，实在不行就先导出配置，卸载干净了，重装app后导入配置再试试
