### ISSUE TITLE
[Bug]: 腾旭管家检测到木马病毒

### ISSUE THREAD

**Issue by flypigeon** [pppscn/SmsForwarder#361]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

否（No）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

v3.2.0

### 问题描述

![image](https://github.com/pppscn/SmsForwarder/assets/8320971/c9e42bac-a787-4604-bc26-b3eee878712e)

### 复现步骤

![image](https://github.com/pppscn/SmsForwarder/assets/8320971/457926bd-431e-4b09-ac41-2ee9f400b30a)

### 是否必现

是（Yes）

### 出现问题的手机信息

小米

### 出现问题的安卓版本、系统版本

Android 12

**Comment by pppscn** [comment]
听他的，立即删除保平安
