### ISSUE TITLE
[Bug]: 小米澎湃OS安卓14主控端发短信弹出授权窗口！

### ISSUE THREAD

**Issue by mymine** [pppscn/SmsForwarder#362]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.2.0

### 问题描述

客户端控制小米澎湃OS安卓14服务端发短信弹出授权窗口。需要点击确认发送后才会发送短信。发送短信等权限全以始终允许

### 复现步骤

客户端链接控制小米澎湃OS安卓14服务端发短信。

### 是否必现

是（Yes）

### 出现问题的手机信息

红米K60Pro澎湃OS安卓14

### 出现问题的安卓版本、系统版本

14

### 提供截图或视频

![Screenshot_2023-11-19-18-26-36-995_com miui securitycenter-edit](https://github.com/pppscn/SmsForwarder/assets/2943365/577616b6-e872-4e51-9b12-0b15ede3ce52)

**Comment by pppscn** [comment]
参考这个试试

https://github.com/pppscn/SmsForwarder/wiki/%E3%80%90%E5%BF%85%E8%AF%BB%E3%80%91%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#q%E5%B0%8F%E7%B1%B3%E7%BA%A2%E7%B1%B3%E6%89%8B%E6%9C%BA%E7%9F%AD%E4%BF%A1%E9%80%9A%E9%81%93%E5%8F%91%E9%80%81%E6%97%B6%E6%80%BB%E4%BC%9A%E6%98%BE%E7%A4%BA%E8%BF%99%E4%B8%AA%E4%B8%8D%E8%83%BD%E8%87%AA%E5%8A%A8%E8%BD%AC%E5%8F%91%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3%E5%91%A2

目前没有澎湃系统的手机做测试，只能自己折腾看看

PS.  什么家庭条件，旗舰机都沦为备用机了？

**Comment by mymine** [comment]
> 参考这个试试
> 
> https://github.com/pppscn/SmsForwarder/wiki/%E3%80%90%E5%BF%85%E8%AF%BB%E3%80%91%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#q%E5%B0%8F%E7%B1%B3%E7%BA%A2%E7%B1%B3%E6%89%8B%E6%9C%BA%E7%9F%AD%E4%BF%A1%E9%80%9A%E9%81%93%E5%8F%91%E9%80%81%E6%97%B6%E6%80%BB%E4%BC%9A%E6%98%BE%E7%A4%BA%E8%BF%99%E4%B8%AA%E4%B8%8D%E8%83%BD%E8%87%AA%E5%8A%A8%E8%BD%AC%E5%8F%91%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3%E5%91%A2
> 
> 目前没有澎湃系统的手机做测试，只能自己折腾看看
> 
> PS. 什么家庭条件，旗舰机都沦为备用机了？

汉！不是备用机。K60Pro+K20Pro用K60Pro测试的。
K20Pro刷的移植澎湃。
测试了下手机管家的锅把手机管家冻结就可以。MIUI系统还是得留着MIUI优化才还好用！😂

**Comment by pppscn** [comment]
> > 参考这个试试
> > https://github.com/pppscn/SmsForwarder/wiki/%E3%80%90%E5%BF%85%E8%AF%BB%E3%80%91%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#q%E5%B0%8F%E7%B1%B3%E7%BA%A2%E7%B1%B3%E6%89%8B%E6%9C%BA%E7%9F%AD%E4%BF%A1%E9%80%9A%E9%81%93%E5%8F%91%E9%80%81%E6%97%B6%E6%80%BB%E4%BC%9A%E6%98%BE%E7%A4%BA%E8%BF%99%E4%B8%AA%E4%B8%8D%E8%83%BD%E8%87%AA%E5%8A%A8%E8%BD%AC%E5%8F%91%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3%E5%91%A2
> > 目前没有澎湃系统的手机做测试，只能自己折腾看看
> > PS. 什么家庭条件，旗舰机都沦为备用机了？
> 
> 汉！不是备用机。K60Pro+K20Pro用K60Pro测试的。 K20Pro刷的移植澎湃。 测试了下手机管家的锅把手机管家冻结就可以。MIUI系统还是得留着MIUI优化才还好用！😂

一般人不知道怎么排除问题，所以我建议简单粗暴直接关闭MIUI优化
