### ISSUE TITLE
[Suggestion]: 小米14 hyper OS 无法使用，是否要针对优化

### ISSUE THREAD

**Issue by kevinleesky** [pppscn/SmsForwarder#363]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

hyper os 无法进行短信转发，所有权限已开，关闭系统优化，测试通道可以收到短信

**Comment by pppscn** [comment]
有可能还是设置的问题，澎湃OS目前还是安卓心

参考一下 https://github.com/pppscn/SmsForwarder/issues/362

**Comment by aohanhongzhi** [comment]
我也是一样，各种设置都不行。
