### ISSUE TITLE
[Suggestion]: 转发通道应该考虑一下通知转发蓝牙通道

### ISSUE THREAD

**Issue by vikenlau** [pppscn/SmsForwarder#365]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

我一般是工作和生活各使用一台手机做隔离，携带两个手机的确能做到一定的隔离，但也容易消息忽略，因为双设备 通常只要不是走路都会放下，买一个手表，接受通知，以免错过通知，目前使用短信转发可以解决，但是只能解决网络，这是有不足的地方。

### 你觉得该怎么去完善会比较好？【非必答】

建议提供蓝牙转发功能，A手机连接B手机，B手机连接C手表，完成同步， 方便蓝牙设备接受通知，蓝牙耗电更少，响应更快，稳定性更强。

**Comment by ywjheart** [comment]
用蓝牙还不如按需启动wifi/data呢。如果能在收到短信或者电话时，自动启动wifi或者data，我想这样应该更容易实现。可以参考{{location}}这样做成一个可选开关。

**Comment by vikenlau** [comment]
我觉得电一个部分，还有网络拥堵部分，可能会延迟，握手频率也是很频繁， 对于我这个考虑双设备携带的人士，只为了通知的通知的统一性，还不是一个实现远程目的，手机都在身边的。 远程目的可能不考虑用电问题及延迟问题。

**Comment by pppscn** [comment]
不具备可行性（或 通用性）

C手表作为接收端，需要一个app与B手机建立蓝牙连接，才能基于这个连接传输数据

我不可能去为某个手表开发一个接收端，还要申请上它的应用市场来配套smsf使用吧
