### ISSUE TITLE
退出前台闪退

### ISSUE THREAD

**Issue by cat677** [pppscn/SmsForwarder#367]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

否（No）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

3.2.0

### 问题描述

新版应用最小化后闪退，每次都会重新打开应用，导致后台无法运行，老版本可以正常使用，机型小米14， 一加ace

### 复现步骤

最小化闪退

### 是否必现

是（Yes）

### 出现问题的手机信息

小米14，oneplus ace

### 出现问题的安卓版本、系统版本

安卓13

**Comment by pppscn** [comment]
请提供一下logcat抓取的日志，参考： https://blog.csdn.net/m0_64776928/article/details/126005119

**Comment by pppscn** [comment]
无法重现，先卸载干净后重新安装试试
