### ISSUE TITLE
[Bug]: 继续测试每周构建版Socket的mqtt功能，点击测试按钮闪断，不能建立客户端连接

### ISSUE THREAD

**Issue by Andylaux** [pppscn/SmsForwarder#368]
### 是否有人曾提过类似的问题

是（Yes）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

每周构建版

### 问题描述

请求方式 MQTT；端口 8883；通信方式 SSL；点击测试按钮闪断

### 复现步骤

点击测试按钮闪断，不能建立客户端连接

### 是否必现

是（Yes）

### 出现问题的手机信息

Surface Duo

### 出现问题的安卓版本、系统版本

Android 12

### 提供截图或视频

https://github.com/pppscn/SmsForwarder/assets/20061042/18a620f1-e215-4ab0-9449-630bb353923c

**Comment by Andylaux** [comment]
[logcat.log](https://github.com/pppscn/SmsForwarder/files/13467235/logcat.log)
补充堆栈日志

**Comment by pppscn** [comment]
参考一下 https://github.com/pppscn/SmsForwarder/issues/349 

先用python测试你的mqtt服务端

**Comment by Andylaux** [comment]
> 参考一下 #349
> 
> 先用python测试你的mqtt服务端

mqtt服务用的emqx cloud，python测试正常
![微信图片_20231212011145](https://github.com/pppscn/SmsForwarder/assets/20061042/925b4b08-9c1b-4b67-98d5-629efaaaf2ae)

**Comment by pppscn** [comment]
![微信截图_20231213170713](https://github.com/pppscn/SmsForwarder/assets/5105854/9f7c76b7-ef87-4465-b701-721c6492a37a)

这里`通信方式`检查一下，是否勾选对了，目前是有bug默认都没选

**Comment by pppscn** [comment]
请重新下载每周构建版测试

https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml
