### ISSUE TITLE
[Bug]: 应用转发规则中多出来一个不可点击的选项

### ISSUE THREAD

**Issue by pinoren** [pppscn/SmsForwarder#369]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

V3.2.0

### 问题描述

应用转发规则中，启用自定义模板，下面的变量关键字中多出来一个“通知内容”，不可以点击，但是也不影响使用，看着有点别扭......
![Screenshot_20231130_163558_edit_399310568314800](https://github.com/pppscn/SmsForwarder/assets/31525739/519d1578-ff44-4b55-9fdc-8d4d7d0a407f)

### 复现步骤

应用转发规则中，点击启用自定义模板，出现在下面的变量关键字中多出来一个“通知内容”，但是不可以点击。
![Screenshot_20231130_163558_edit_399310568314800](https://github.com/pppscn/SmsForwarder/assets/31525739/5fc24d78-5283-449b-8af2-0e40cd050c9a)

### 是否必现

是（Yes）

### 出现问题的手机信息

华为nova 4

### 出现问题的安卓版本、系统版本

Android 13

### 提供截图或视频

![Screenshot_20231130_163558_edit_399310568314800](https://github.com/pppscn/SmsForwarder/assets/31525739/7103114a-b827-4653-9381-5361a4538351)

**Comment by pppscn** [comment]
已经修复过，只是还没发版

https://github.com/pppscn/SmsForwarder/commit/42794a5b2c27e56f4b1dbb5d118ac9447159e96d

下载 `每周构建版` 或 等 `3.3.0` 发版
