### ISSUE TITLE
偶现[no address associated with hostname]

### ISSUE THREAD

**Issue by w-Bro** [pppscn/SmsForwarder#37]
Android5.1，编译的时候只修改了minSdkVersion。
息屏一段时间后查看App发送记录[Response: Unable to resolve host "qyapi.weixin.qq.com": no address associated with hostname]，亮屏后又能成功发送。
尝试过切换wifi和忘记wifi重新连接也不行，同一网络下的另一台手机不会有这样的情况。

**Comment by pppscn** [comment]
排查一下息屏之后是否断网了
