### ISSUE TITLE
[Suggestion]: 可否监听息屏/亮屏事件

### ISSUE THREAD

**Issue by DetaAdmin** [pppscn/SmsForwarder#370]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

息屏/亮屏事件，记录了很多信息。比如我总是忘记自己几点睡觉，几点起床。

### 你觉得该怎么去完善会比较好？【非必答】

监听息屏亮屏事件

**Comment by DetaAdmin** [comment]
可以记录息屏时间，亮屏时间，比如记录睡觉，起床时间

**Comment by CozmoAlien** [comment]
應用程式中沒有英文

**Comment by pppscn** [comment]
请重新下载每周构建版测试 自动任务功能

https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml
