### ISSUE TITLE
添加一个发送通道

### ISSUE THREAD

**Issue by jdnjk** [pppscn/SmsForwarder#371]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

能添加一个qq频道的发送

**Comment by pppscn** [comment]
有QQ有提供api文档吗？

**Comment by jdnjk** [comment]
> 有QQ有提供api文档吗？

频道机器人https://bot.q.qq.com/wiki/develop/api-v2/

**Comment by crossgg** [comment]
我觉得可以添加一个自定义渠道，可以根据通道文档，自己填写 post或者get的url,请求参数。这样有小众推送软件需求的就可以自己解决

**Comment by pppscn** [comment]
> 我觉得可以添加一个自定义渠道，可以根据通道文档，自己填写 post或者get的url,请求参数。这样有小众推送软件需求的就可以自己解决

webhook 就是你说的自定义渠道了，只是一些通道需要计算签名或获取token之类的，这些需要特殊处理

**Comment by pppscn** [comment]
看文档，这个限制有点多啊，就只能发这么几条，加了也没啥用

https://bot.q.qq.com/wiki/develop/api-v2/server-inter/message/send-receive/send.html#%E5%8D%95%E8%81%8A
