### ISSUE TITLE
[Suggestion]: 发送通道增加ntfy.sh

### ISSUE THREAD

**Issue by yorurr** [pppscn/SmsForwarder#372]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

希望能在发送通道增加ntfy.sh支持，ntfy是一套可以自建的开源推送通知系统，有全端支持，安卓端上架了f-droid商店，相对于gotify，ntfy在消息种类、消息格式方面更加丰富，部署也只需要docker compose即可，长期使用下来个人认为可靠性和及时性都很不错，所以希望能添加ntfy发送通道的支持。

官网地址：https://ntfy.sh/
文档地址：https://docs.ntfy.sh/
文档中消息发送部分：https://docs.ntfy.sh/publish/

**Comment by pppscn** [comment]
先用webhook试试，看上去可以支持了

**Comment by pppscn** [comment]
![Screenshot_20240111_231156](https://github.com/pppscn/SmsForwarder/assets/5105854/87817476-e8b9-4e7d-9408-321b2f2e9bc4)

测试了一下，webhook可以支持，不需要单独新增一个通道

**Comment by lsdxfs** [comment]
> ![Screenshot_20240111_231156](https://private-user-images.githubusercontent.com/5105854/295964678-87817476-e8b9-4e7d-9408-321b2f2e9bc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxODEwNDIsIm5iZiI6MTcyNTE4MDc0MiwicGF0aCI6Ii81MTA1ODU0LzI5NTk2NDY3OC04NzgxNzQ3Ni1lOGI5LTRlN2QtOTQwOC0zMjFiMmYyZTliYzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDFUMDg1MjIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTQ3MjNmNzNhYzY2Yjg5MTIzNzg1ZmQ1ZWUxNTRjMjYzOWIzNWNlMWNjNjg0MWFkNzg5Y2RmZmE1ZjA5MTBiOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.y3A6a_hyPpLgwQiLGiZPb1T1yrHcxLYDGWZr8Q2NuKI)
> 
> 测试了一下，webhook可以支持，不需要单独新增一个通道

大佬这个可以写进教程吗
