### ISSUE TITLE
网络连接异常，请稍后再试  是否有重发的功能 是设置“请求重试机制”么？有成功实现重发的么

### ISSUE THREAD

**Issue by Laura0324** [pppscn/SmsForwarder#373]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

![Snipaste_2023-12-08_09-42-23](https://github.com/pppscn/SmsForwarder/assets/152157822/8ffaef62-1725-4b58-aa16-d1f573a33039)
能够重发的话 能告诉我怎么设置么

**Comment by pppscn** [comment]
首先，排查手机的省电策略，避免还在重试过程就被系统给杀了

其次，建议加大重试次数（第一个输入框），减少单次超时时长（第三个输入框）

例如：`10、5、10`，这样设置将重试10次，第一次间隔10秒，第二次间隔15秒，第三次间隔20秒，以此类推
