### ISSUE TITLE
[Bug]: HyperOS无法使用

### ISSUE THREAD

**Issue by Canary233** [pppscn/SmsForwarder#375]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.2.0

### 问题描述

无法使用，无转发日志。先前MIUI14 14.0.10正常使用

### 复现步骤

百分百复现

### 是否必现

是（Yes）

### 出现问题的手机信息

小米12S

### 出现问题的安卓版本、系统版本

HyperOS1.0.23.12.4 Android14

**Comment by pppscn** [comment]
权限全绿！！！、关闭免费网络短信、关闭各种省电设置

权限全绿！！！

权限全绿！！！（尤其是 `通知类短信` 权限）

**如果还不行试试，开启开发者选项，关闭miui优化**

![微信截图_20231220104800](https://github.com/pppscn/SmsForwarder/assets/5105854/d97802e7-613a-4c7c-94f3-4d16983218ac)
