### ISSUE TITLE
[Bug]: 微信消息，聊天，为啥不行

### ISSUE THREAD

**Issue by icetech233** [pppscn/SmsForwarder#377]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

否（No）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

所有

### 问题描述

微信用不了

### 复现步骤

不支持功能

### 是否必现

是（Yes）

### 出现问题的手机信息

小米

### 出现问题的安卓版本、系统版本

13

**Comment by mingone12345** [comment]
好像无效了

**Comment by pppscn** [comment]
通知栏看到什么只能转发什么，不会主动去侵入任何一个APP
