### ISSUE TITLE
[Suggestion]: 希望加强微信监控功能

### ISSUE THREAD

**Issue by destiny188** [pppscn/SmsForwarder#379]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

希望加强微信的监控

### 你觉得该怎么去完善会比较好？【非必答】

微信打开聊天窗口后的聊天内容就不能被转发了，希望能监控聊天中收到的信息，还有被设置消息免打扰的信息也不能转发。

**Comment by pppscn** [comment]
不会主动去侵入任何一个app，smsf只会转发通知栏看到什么就转发什么

搞这个就等南山必胜客找上门吗？
