### ISSUE TITLE
[Bug]: Wiki 定制开发过时内容更新

### ISSUE THREAD

**Issue by Nash-x9** [pppscn/SmsForwarder#380]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

V3.2.0

### 问题描述

定制开发的在线编译方式，存在过期内容，我在解决方案中完成了修改，可以按照我提供的内容进行更新。可惜Github还不支持Wiki的PR...

### 复现步骤

访问 https://github.com/pppscn/SmsForwarder/wiki/%E5%85%B3%E4%BA%8E%E5%AE%9A%E5%88%B6%E5%BC%80%E5%8F%91

### 是否必现

是（Yes）

### 出现问题的手机信息

None

### 出现问题的安卓版本、系统版本

None

## 严正声明

本人不接受任何形式的定制开发！

## 具体原因

首先感谢大家的厚爱！

鉴于软件的敏感性，我不接任何定制，本来就是自用的app，玩一玩而已，不以盈利为目的！

如果接收定制，对方拿去做非法的事情

_（举例而已，请勿对号入座，是不是非法的事情，可能当事人也不清楚）_

我就有可能负有连带责任，虽然我也挺缺钱的，但是这钱我不敢赚，不能为了这个蝇头小利，惹不必要的麻烦……

人心隔肚皮，更何况隔着屏幕，不知道对面的是神是鬼，更具有迷惑性与不确定性， **所以只能全部拒绝了，请见谅**！

有好的想法或建议，欢迎大家提issue 或 pr 指正，**觉得对您有所帮助，给我点一个星星也就够了！** 

当然，群里热心老板要给我加个鸡腿/请我喝杯咖啡，我也不会拒绝的…… （[打赏名单](https://gitee.com/pp/SmsForwarder/wikis/%E6%89%93%E8%B5%8F%E5%90%8D%E5%8D%95)）

***

## 在线编译方式

仓库内已经包含GitHub Actions脚本，自己fork之后，按键盘上的 `.` 键即可进入编译模式，在线简单改改，然后就可以在线编译了

**1、需要自己创建一个 签名密钥 的仓库：keystore，包含两个文件**

1.1 配置文件 keystore.properties，文件内容

    keyAlias=pppscn
    keyPassword=123456
    storePassword=123456
    storeFile=../keystore/pppscn.jks

1.2 证书文件 pppscn.jks，具体百度一下怎么生成

**2、新建一个Action Secret `TOKEN` , 内容填写能访问 `keystore` 私有仓库的token**

2.1 token生成地址：https://github.com/settings/tokens/new

2.2 Action Secret设置地址：https://github.com/<你的用户名>/SmsForwarder/settings/secrets/actions/new

**3、进入 `GitHub Actions` 开始在线编译**

https://github.com/<你的用户名>/SmsForwarder/actions/workflows/Weekly_Build.yml

## 本地编译方式

参考 `在线编译方式`，在项目根目录新建`keystore`目录，包含两个文件，然后 gradle sync 即可

 **【注意】v2.x分支本地开发时，Android Studio 需要安装 Lombok插件：**

Download IDEA distribution Comunity Edition v. 2021.1.1. https://www.jetbrains.com/idea/download/other.html
Extract from distribution folder plugins/lombok and put it to your ".../Android Studio/plugins/" folder.
Restart AS.
You will see that lombok plugin becomes "bundled".

**Comment by pppscn** [comment]
感谢提醒，已经修正
