### ISSUE TITLE
[Suggestion]: 希望可以自定义飞书消息卡片的内容

### ISSUE THREAD

**Issue by gdfsjunjun** [pppscn/SmsForwarder#381]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

飞书是唯一一个支持发送消息卡片的通道，其他都只能发送纯文本。要是能够自定义消息卡片的格式就好了。
通过[消息卡片搭建工具](https://open.feishu.cn/tool/cardbuilder)可以一键生成代码，直接输入替换就可以了。

**Comment by gdfsjunjun** [comment]
自定义卡片功能正常，非常感谢。

但是如果转发规则设置了正则替换，且通道设置了自定义卡片，正则替换失效。[正则替换内容参考了Wiki](https://github.com/pppscn/SmsForwarder/wiki/%E3%80%90%E5%BF%85%E8%AF%BB%E3%80%91%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#q%E5%A6%82%E4%BD%95%E4%B8%80%E4%B8%AA%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F%E5%8C%B9%E9%85%8D%E5%85%A8%E9%83%A8%E9%AA%8C%E8%AF%81%E7%A0%81%E7%9F%AD%E4%BF%A1)

![转发规则](https://github.com/pppscn/SmsForwarder/assets/20369200/34c6c0fb-6794-4745-b3d8-d2ed44d06a7f)

![消息卡片](https://github.com/pppscn/SmsForwarder/assets/20369200/9f595e59-7a84-4756-896d-583b090065a3)

如果通道设置为纯文本，整体替换是生效的。

另外，建议新增正则替换内容标签，或者新增一个原始内容（未经过正则替换）的内容标签，这样{{短信内容}}本身就是经过替换的内容，不会与发送纯文本那边的规则混淆。


```
{
  "elements": [
    {
      "tag": "column_set",
      "flex_mode": "none",
      "background_style": "grey",
      "horizontal_spacing": "default",
      "columns": [
        {
          "tag": "column",
          "width": "weighted",
          "weight": 1,
          "elements": [
            {
              "tag": "markdown",
              "text_align": "center",
              "content": "**验证码**\n{{短信内容}}（建议新增正则替换字段）\n"
            }
          ]
        }
      ]
    },
    {
      "fields": [
        {
          "is_short": true,
          "text": {
            "content": "**时间**\n{{接收时间}}",
            "tag": "lark_md"
          }
        },
        {
          "is_short": true,
          "text": {
            "content": "**来源**\n{{来源号码}}",
            "tag": "lark_md"
          }
        }
      ],
      "tag": "div"
    },
    {
      "fields": [
        {
          "is_short": true,
          "text": {
            "content": "**卡槽信息**\n{{卡槽信息}}",
            "tag": "lark_md"
          }
        },
        {
          "is_short": true,
          "text": {
            "content": "**设备名称**\n{{设备名称}}",
            "tag": "lark_md"
          }
        }
      ],
      "tag": "div"
    },
    {
      "tag": "div",
      "text": {
        "content": "{{短信内容}}",
        "tag": "lark_md"
      }
    }
  ],
  "header": {
    "template": "blue",
    "title": {
      "content": "{{短信内容}}",
      "tag": "plain_text"
    }
  }
}
```

- 建议转发通话规则新增{{通话类型}}标签，我尝试加了但显示的是“未知通话”，而不是“来电提醒”、“来电挂机”、“未接来电”等。

- 建议通话转发规则新增一个延迟设置，延时3s，因为对于无双通功能的手机，副卡来电时，会有一个短暂切换数据卡的过程，网络会暂时断开，这时候发送推送肯定是失败的，如果能够延迟3s，则能解决这个问题。


![通话卡片](https://github.com/pppscn/SmsForwarder/assets/20369200/9aac3f8a-9ba6-47ce-88bc-4df31015c935)

```
{
  "elements": [
    {
      "fields": [
        {
          "is_short": true,
          "text": {
            "content": "**时间**\n{{接收时间}}",
            "tag": "lark_md"
          }
        },
        {
          "is_short": true,
          "text": {
            "content": "**来源**\n{{来源号码}}",
            "tag": "lark_md"
          }
        }
      ],
      "tag": "div"
    },
    {
      "fields": [
        {
          "is_short": true,
          "text": {
            "content": "**卡槽信息**\n{{卡槽信息}}",
            "tag": "lark_md"
          }
        },
        {
          "is_short": true,
          "text": {
            "content": "**设备名称**\n{{设备名称}}",
            "tag": "lark_md"
          }
        }
      ],
      "tag": "div"
    },
    {
      "tag": "div",
      "text": {
        "content": "{{短信内容}}",
        "tag": "lark_md"
      }
    }
  ],
  "header": {
    "template": "green",
    "title": {
      "content": "{{通话类型}}{{来源号码}}",
      "tag": "plain_text"
    }
  }
}
```

主要是这几点，希望有时间的话可以修复一下，再次感谢

**Comment by pppscn** [comment]
1、`正则替换`是针对【自定义模板】的，不是针对某个标签的，加上了大家就更乱了

用 `{{MSG_TITLE}}` 和 `{{MSG_CONTENT}}` 去获取基于【自定义模板】正则替换后的内容

---

2、`建议通话转发规则新增一个延迟设置，延时3s`  这就不改了，有`请求重试机制`就行了，设置项越多，我当客服解释得越费劲

---

3、`建议转发通话规则新增{{通话类型}}标签，我尝试加了但显示的是“未知通话”，而不是“来电提醒”、“来电挂机”、“未接来电”等`

是所有都不行，还是只有部分对应错误？

**Comment by pppscn** [comment]
请重新下载每周构建版测试`{{通话类型}}`标签

https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by gdfsjunjun** [comment]
{{卡槽信息}}输出异常，只有当“来电挂机”和“去电挂机”才能正确显示。其余四种通话类型都显示异常，输出了`\"\"`导致JSON格式有问题返回`"msg": "params error, unknown card value"`

P.S. 建议日志信息增加一个复制详情的功能，方便我调试

![失败](https://github.com/pppscn/SmsForwarder/assets/20369200/322f0a19-ed7e-4382-baff-b44796ef8834)

![正常](https://github.com/pppscn/SmsForwarder/assets/20369200/015f3a28-92c0-452e-bfad-8b7ae3bf99db)

**Comment by pppscn** [comment]
通用设置里面可以打开调试模式  可以导出日志文件

空值转为 `\"\"` 问题已经去掉，重新下载测试

**Comment by pppscn** [comment]
`来电提醒`等 是接受到系统广播就通知出去，这时还没记录到数据库

`挂机提醒`是从通话记录数据库读取的才有卡槽信息

**Comment by gdfsjunjun** [comment]
好的非常感谢

**Comment by NatralMicsear** [comment]
{{MSG_TITLE}} 和 {{MSG_CONTENT}}能加到WIKI里吗，找了半天才在issue里找到这个功能
