### ISSUE TITLE
[Suggestion]: 将自动管理关闭→转为手动管理可以让华为ART-AL00x保活

### ISSUE THREAD

**Issue by wofbi** [pppscn/SmsForwarder#382]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

关于华为ART-AL00x手机后台保活有问题
其他华为手机应该也可参考

### 你觉得该怎么去完善会比较好？【非必答】

建议在文档中增加下面的说明:

设置→应用→应用启动管理→找到SmsForwarder→将自动管理关闭→转为手动管理→接着手动开启允许自启动、允许关联启动、允许后台活动等按钮。
我是从知乎文章[你的华为手机总是"杀后台"，很烦人！那是这4个设置没调整吧](https://zhuanlan.zhihu.com/p/95583084)看到的

<img width="537" alt="image" src="https://github.com/pppscn/SmsForwarder/assets/45745544/0aad89e0-7480-475c-ae10-df0856bc8c11">

补充, 我使用了那个adb命令

```
adb shell am start -n "com.idormy.sms.forwarder/com.idormy.sms.forwarder.activity.SplashActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
```

使用了该命令之后锁屏仍然不行, 然后我做了将自动管理关闭→转为手动管理就可以了

**Comment by wofbi** [comment]
不好意思, 我没看之前有没有人提过, 我看文档关于保活的说法没有这个

**Comment by wofbi** [comment]
补充, 我使用了那个adb命令
```
adb shell am start -n "com.idormy.sms.forwarder/com.idormy.sms.forwarder.activity.SplashActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
```

**Comment by wofbi** [comment]
使用了该命令之后锁屏仍然不行, 然后我做了将自动管理关闭→转为手动管理就可以了

**Comment by pppscn** [comment]
系统版本号是多少？  建议不要继续升级系统了 ，版本越高杀后台越严重
