### ISSUE TITLE
大佬请问苹果手机怎么办 求教

### ISSUE THREAD

**Issue by iHadDream** [pppscn/SmsForwarder#383]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

非常好

**Comment by pppscn** [comment]
苹果的封闭性，不允许读取用户的短信内容，但是短信拦截功能是可以变相的做到（自行基于此开发app）

https://developer.apple.com/documentation/sms_and_call_reporting/sms_and_mms_message_filtering

或者基于此思路，可以抓包（一些vpn软件自带抓包功能）国内部分厂商的App（带自动上传短信到云端查询是否是垃圾短信）实现，

但是这样也有一个致命弱点——不是所有短信都会上报远端查询（即：不会转发所有短信）
