### ISSUE TITLE
[Suggestion]: 增加摄像头功能，闲置旧手机变身家庭监控

### ISSUE THREAD

**Issue by Magical-Lin** [pppscn/SmsForwarder#384]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

增加摄像头在线查看、录制功能，还有语音对讲功能，闲置旧手机变身家庭监控

**Comment by Patrick-Ze** [comment]
这些功能完全超出了短信转发的周边，建议寻找专门的监控软件

**Comment by pppscn** [comment]
去找找其他app吧，之前还有人把手机改造成行程记录仪的，咱们这个就不考虑添加了
