### ISSUE TITLE
[Suggestion]: 增加收到匹配内容后播放音乐提醒

### ISSUE THREAD

**Issue by wltyzh** [pppscn/SmsForwarder#385]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

比如收到短信包含某些关键字时没有播放音乐提醒功能，在比较紧急的情况下很有用。因为转发邮件或通知这些方式不一定在第一时间看到。

### 你觉得该怎么去完善会比较好？【非必答】

增加收到匹配内容后播放本地音乐提醒

**Comment by pppscn** [comment]
`在比较紧急的情况下很有用` 这一句怎么理解？

SmsF 只是一个转发工具而已，收到信息提醒不应该是系统应用做的事情吗？

**Comment by pppscn** [comment]
后半句`播放音乐提醒`已经实现了，下载每周构建版试试
https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by pppscn** [comment]
没有后续反馈，先行关闭

**Comment by leonall** [comment]
在软件界面上，怎么配置呢？没有看到播放的设置入口啊

**Comment by leonall** [comment]
找到入口了。自己给自己发短信，可以测试ok。但别人给我发短信，就是不成功。
