### ISSUE TITLE
[Bug]: WIKI中的自定义变量的电池、网络、定位等加入自定义模板后，无法获取到相应信息。

### ISSUE THREAD

**Issue by viewfirst** [pppscn/SmsForwarder#387]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

V3.2.0

### 问题描述

自建有关电池电量以及网路状态的转发规则时，使用WIKI提到的自定义规则变量中的电池及定位有关变量（中英文均有尝试），但是未能获取到手机信息。
![1706900100832](https://github.com/pppscn/SmsForwarder/assets/12773071/5caed045-850e-4b59-82e1-efbd48ee7173)

同时网络状态的转发规则也无法转发具体内容（未添加自定义模板以及后续添加包括{{通知内容}}在内的自定义模板均没有作用。
![1706900317624](https://github.com/pppscn/SmsForwarder/assets/12773071/cd5d276f-6f90-477f-ad1d-96a1b750d804)

### 复现步骤

1、自建应用转发规则；
2、输入发送通道选择bark或邮件；
3、匹配字段为“APP包名”；
4、匹配模式 “是”；
5、匹配的值“77777777”或“88888888”，未选择已装APP；
6、
    ①转发电池信息（即88888888）时，启用自定义模板：
       “来自{{设备名称}}的电量警告：
         {{通知内容}}:
         
          电池状态提醒：

          当前设备  {{设备名称}}的电量为  {{电池电量}}
          电池状态：  {{电池状态}}
          充电方式：  {{充电方式}}

          信息发送时间：  {{接收时间}}

          附加信息：
          电池信息：  {{电池信息}}
          设备位置：  {{定位信息}}”

       ②转发网络信息时（即77777777）分别测试过使用自定义模板及未使用，自定义模板如下：
         “来自{{设备名称}}的网络状态提醒：
           {{通知内容}}:  ”
7、上述测试自定义变量所使用的{{}}符号均为复制 {{设备名称}}后修改文字内容所得到的，并非自行输入；
8、测试转发规则时，仅输入包名“77777777”或“88888888”，（第一次尝试有复制完整的电池信息自定义规则，但依然没有获取到设备信息）；
9、测试设备为小米10至尊纪念透明版（12G+256G版），系统版本MIUI14.0.2；
10、当前权限设置中✅的有（未设置空白通行证）：媒体音量控制、读取短信彩信、通知类短信、读取联系人、读取通话记录、定位、获取手机信息、读取应用列表、写入剪贴板、（修改）系统设置、获取加速传感器信息；
11、当前权限设置中禁止的有：发送彩信、读取剪切板、桌面快捷方式、锁屏显示、后台弹出界面、显示悬浮窗、动态壁纸服务；
12、当前未设置的权限有：相机、录音、发送短信、拨打电话、修改联系人、访问日历、访问手机账号、获取手机号码用于一键登录、开启WLAN、开启蓝牙。

### 是否必现

是（Yes）

### 出现问题的手机信息

小米10至尊纪念透明版（12G+256G版）

### 出现问题的安卓版本、系统版本

系统版本MIUI14.0.2

**Comment by pppscn** [comment]
三个问题：
1、要求 `3.3.0+ `
2、标签要跟系统语言匹配
3、`3.3.0+` 已经废除 `77777777`，由 `自动任务` 取代

![微信截图_20240203094919](https://github.com/pppscn/SmsForwarder/assets/5105854/e97e0b51-62de-4da2-850d-a514277e77af)

**Comment by viewfirst** [comment]
好吧，我其实有关注到版本问题，但是一直下意识把自己的3.2.0当成了3.3哈哈。抱歉抱歉。
