### ISSUE TITLE
[Suggestion]: 建议添加通过蓝牙控制的动态转发开关

### ISSUE THREAD

**Issue by nicengi** [pppscn/SmsForwarder#388]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

假设我有一个备用机（平时不带出门），上面的通知消息都转发到主力机上。如果我在家里或随身带了备用机（两个手机在一起），这个时候就不需要转发消息了。**如果手动关闭转发开关，可能在以后会忘记打开。并且也有些不方便**

在Windows中有一个名为“**动态锁**”的功能：选择一个与电脑配对的设备（**手机或手环等**），在这个设备离开电脑的蓝牙信号范围时锁定电脑。一些安卓手机也有在手环靠近时解锁的功能。

**因此，是否可以添加一个类似的功能，在指定设备靠近时自动关闭转发，离开时再开启转发。**
例如：在备用机上选择主力机绑定，主力机离开备用机范围时才开启转发。

**Comment by ywjheart** [comment]
用新版的Task配合network conditions，是否连接到制指定wiifi，来启用关闭channel是否可以达到你需要的效果。

**Comment by pppscn** [comment]
![微信图片_20240317084800](https://github.com/pppscn/SmsForwarder/assets/5105854/77e58480-177b-4ca5-b84a-6a91712bd76c)

覆盖安装 `每周构建版` 试试

**升级操作提示：** 
- `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
-  手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml
