### ISSUE TITLE
[Suggestion]: 通过短信指令触发自动任务/快捷指令或启用禁用快捷指令

### ISSUE THREAD

**Issue by RuioWolf** [pppscn/SmsForwarder#389]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

短信指令目前实现的功能较少，如果参照 [Wiki](https://github.com/pppscn/SmsForwarder/wiki/%E9%99%84%E5%BD%959%EF%BC%9A%E7%9F%AD%E4%BF%A1%E6%8C%87%E4%BB%A4) 所述。

### 你觉得该怎么去完善会比较好？【非必答】

- 在 `自动任务·快捷指令` 中：
  1. 增加条件 `短信触发`，根据关键字或白名单号码触发该任务。
  2. 增加动作 `启停任务`，设定启用或禁用任务。

- 在 `短信指令` 中增加触发指定 `自动任务·快捷指令` 的 `#功能名#动作名#参数`。

**Comment by pppscn** [comment]
覆盖安装 `每周构建版` 试试

**升级操作提示：** 
- `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
-  手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

PS. `短信指令` 就不更新了，有 `自动任务` 足以

**Comment by pppscn** [comment]
没有后续反馈，先行关闭
