### ISSUE TITLE
[Bug]: Wifi 平板无法启用了location设置

### ISSUE THREAD

**Issue by ywjheart** [pppscn/SmsForwarder#391]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

V3.3

### 问题描述

对于没有GPS的wifi平板，但有location 服务，即使选择不同的精度，也会不断提示GPS没有启用。

### 复现步骤

去设置点location，切换不同的accuracy，都会弹出一样的错误，GPS is not enabled.

### 是否必现

是（Yes）

### 出现问题的手机信息

Xiaomi Pad 6 Pro

### 出现问题的安卓版本、系统版本

Android 13

### 提供截图或视频

![IMG_20240214_162800_472](https://github.com/pppscn/SmsForwarder/assets/1262226/a86bacef-4bfe-4a10-ab45-5177dc357ba9)

**Comment by pppscn** [comment]
没有GPS，系统设置里面有类似的  定位服务开关吗？ 因为不开启系统定位，直接启用会FC

修复：手机GPS禁用时，启用增强功能GPS定位服务导致SmsF启动奔溃
https://github.com/pppscn/SmsForwarder/commit/c0afc9f5291839a63a67d0e685aa58d0adf2c8a9

**Comment by ywjheart** [comment]
嗯， wifi based设备也可以用location service的， 估计google用了wifi和bluetooth等信息计算的

**Comment by pppscn** [comment]
> 嗯， wifi based设备也可以用location service的， 估计google用了wifi和bluetooth等信息计算的

系统设置里面有对应的开关吗？  换句话说，你能不能关闭这个定位功能？

**Comment by ywjheart** [comment]
没有，应该是不能关闭。系统有每app独立的location 权限管理。

**Comment by pppscn** [comment]
下载每周构建版试试
https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by ywjheart** [comment]
测试没问题了
