### ISSUE TITLE
[Bug]: 通知栏异常显示两条常驻通知

### ISSUE THREAD

**Issue by lyiton** [pppscn/SmsForwarder#392]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.3.0

### 问题描述

2月14日更新3.3.0版本后，通知栏异常显示两条常驻通知。

### 复现步骤

打开短信转发器APP后，通知栏会常驻一条“短信转发器”的通知。如果此时将短信转发器APP从后台关闭，再次打开APP，通知栏会异常显示两条常驻通知。如果再次重启APP，仍然为两条常驻通知。

我确定旧版本未出现该问题，因为我自己只有在需要时才打开APP，所以我经常打开、关闭APP，如果旧版本有问题，我早发现了。

### 是否必现

是（Yes）

### 出现问题的手机信息

小米10S、Redmi K50、Redmi K30 Pro

### 出现问题的安卓版本、系统版本

Android13、Android14、MIUI14、HyperOS

### 提供截图或视频

![1707910528550](https://github.com/pppscn/SmsForwarder/assets/76651858/8dfeb95e-965b-4a4e-8534-a2493bd9a0bc)

https://github.com/pppscn/SmsForwarder/assets/76651858/2e4b9176-5f89-47e0-b455-2f824eaf0008

**Comment by pppscn** [comment]
开发机也是 小米10S（MIUI14.0.6）重现不了，等其他人测试反馈

看你的录屏，像是在任务列表滑动杀进程的时候没有被杀掉（被杀了通知栏也要消掉了）

**Comment by rikthhpgf2005** [comment]
![Uploading IMG_20240215_131438.jpg…]()

**Comment by rikthhpgf2005** [comment]
![IMG222](https://github.com/pppscn/SmsForwarder/assets/12007009/5f850c51-cd74-4719-85c4-e6ce5bb97d99)
我也有同样问题，通知栏显示2个（android9），另一个手机正常（android10）

**Comment by lyiton** [comment]
> 看你的录屏，像是在任务列表滑动杀进程的时候没有被杀掉（被杀了通知栏也要消掉了）

有的，在我从后台关闭软件后，通知栏的图标变为一个，表明软件已被关闭。您可以再仔细看看视频，谢谢！

**Comment by pppscn** [comment]
重新不了就盲修bug，等每周构建版在线编译完成，下载覆盖安装试试
https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by rikthhpgf2005** [comment]
> 重现不了就盲修bug，等每周构建版在线编译完成，下载覆盖安装试试 https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

合并成一个了。
![image](https://github.com/pppscn/SmsForwarder/assets/12007009/cff0787e-8c92-4e31-bd82-cfec64b59c80)

**Comment by lyiton** [comment]
已尝试安装每周构建版，问题仍在。

但在我重新配置软件时发现，只有打开“启用Cactus增强保活措施（会增加耗电）”这项设置才会异常显示两条常驻通知，关闭该项设置，无异常。已提交视频，希望有助于找到问题所在，谢谢！


https://github.com/pppscn/SmsForwarder/assets/76651858/af0d3a16-5c6a-4988-ace7-8e4683e847d1

**Comment by pppscn** [comment]
> 已尝试安装每周构建版，问题仍在。
> 
> 但在我重新配置软件时发现，只有打开“启用Cactus增强保活措施（会增加耗电）”这项设置才会异常显示两条常驻通知，关闭该项设置，无异常。已提交视频，希望有助于找到问题所在，谢谢！
> 
>  Screenrecorder-2024-02-15-21-26-59-486.mp4

真相了，如果开了Cactus那就解释的通了，它也会启动一个前台服务ID不一样

下载再试

**Comment by lyiton** [comment]
已经解决了。谢谢大佬！如果还有异常，我会再打开issue！
