### ISSUE TITLE
[Suggestion]: 我希望在IP转发中增加ipv6地址检测转发

### ISSUE THREAD

**Issue by nahco365** [pppscn/SmsForwarder#393]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

目前转发的ip地址信息仅包含ipv4的地址，没有包含ipv6的地址信息

### 你觉得该怎么去完善会比较好？【非必答】

在转发的信息中增加ipv6地址信息，麻烦了，谢谢！

**Comment by rikthhpgf2005** [comment]
我也有同样的问题

**Comment by pppscn** [comment]
app版本号是多少？

你用手机浏览器访问 https://api6.ipify.org/  能否返回公网IPv6地址？

**Comment by nahco365** [comment]
> app版本号是多少？
> 
> 你用手机浏览器访问 https://api6.ipify.org/ 能否返回公网IPv6地址？
app版本号3.3.0，安卓版本13，手机机型是小米 note 3（jason），crdroid OS 9.11
手机浏览器可以打开该网址，网址内显示IPV69地址，开头为2409

**Comment by pppscn** [comment]
> > app版本号是多少？
> > 你用手机浏览器访问 https://api6.ipify.org/ 能否返回公网IPv6地址？
> > app版本号3.3.0，安卓版本13，手机机型是小米 note 3（jason），crdroid OS 9.11
> > 手机浏览器可以打开该网址，网址内显示IPV69地址，开头为2409

如果能获取到ipv6，转发出去的预期效果是这样的

![微信截图_20240216205153](https://github.com/pppscn/SmsForwarder/assets/5105854/5548c17a-791f-4d61-99c2-96c8ac8ed181)

**Comment by nahco365** [comment]
我是使用邮箱转发的，实际收到的是我家的WLAN内网IP地址：
![1708091889207](https://github.com/pppscn/SmsForwarder/assets/98928834/d0126f5c-d893-4e5b-8022-cc515eed68d8)

**Comment by pppscn** [comment]
> 我是使用邮箱转发的，实际收到的是我家的WLAN内网IP地址： ![1708091889207](https://private-user-images.githubusercontent.com/98928834/305436449-d0126f5c-d893-4e5b-8022-cc515eed68d8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwOTgxNTYsIm5iZiI6MTcwODA5Nzg1NiwicGF0aCI6Ii85ODkyODgzNC8zMDU0MzY0NDktZDAxMjZmNWMtZDg5My00ZTViLTgwMjItY2M1MTVlZWQ2OGQ4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDE1MzczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNTQ2MGMxZGI3ZWQyODQyOGU3Y2RmODgyNTBkYmI2N2U3NzZmNDQ3YzY2YWIyOTM2NDcyYmY2ZWVmNDdlZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i0Ue5s4RJHNVwena6g6oTbUuy6pnz-C_lsLbZ2vrek4)

你还在用 `77777777` 说明不是最新的版本，请下载每周构建版本测试
https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

参考 https://github.com/pppscn/SmsForwarder/issues/398#issuecomment-1948623729
