### ISSUE TITLE
[Bug]: 自动任务触发条件在未保存情况点测试app自动重启

### ISSUE THREAD

**Issue by rikthhpgf2005** [pppscn/SmsForwarder#394]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

否（No）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

v3.3.0

### 问题描述

自动任务触发条件在未保存情况点测试app自动重启（不是每次都能复现，偶尔）

### 复现步骤

自动任务触发条件在未保存情况点测试app自动重启

### 是否必现

否（No）

### 出现问题的手机信息

华为畅享9e

### 出现问题的安卓版本、系统版本

android9

**Comment by pppscn** [comment]
通用设置里面`开启调试模式`，FC之后再次进入`导出`Log文件

PS. 注意隐私保护，脱敏之后上传

**Comment by rikthhpgf2005** [comment]
重装app后问题暂未复现（原3.2升3.3），神奇

**Comment by ywjheart** [comment]
在Task的任何一个task，去Then部分，进入编辑，点Test，立刻用手势返回2次，回列表。稳定crash

**Comment by pppscn** [comment]
> 在Task的任何一个task，去Then部分，进入编辑，点Test，立刻用手势返回2次，回列表。稳定crash

是测试`推送通知`是不？这个操作太骚了，没等测试倒计时结束返回之前就返回了吧？

**Comment by ywjheart** [comment]
> > 在Task的任何一个task，去Then部分，进入编辑，点Test，立刻用手势返回2次，回列表。稳定crash
> 
> 是测试`推送通知`是不？这个操作太骚了，没等测试倒计时结束返回之前就返回了吧？

嗯，😄

**Comment by pppscn** [comment]
等每周构建版在线编译完成，下载覆盖安装试试
https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml
