### ISSUE TITLE
[Bug]: 自动任务电池状态中充电器任意无法触发

### ISSUE THREAD

**Issue by rikthhpgf2005** [pppscn/SmsForwarder#395]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

v3.3.0

### 问题描述

自动任务电池状态中充电器任意无法触发动作，只能选ac

### 复现步骤

自动任务电池状态中充电器任意无法触发动作，只能选ac

### 是否必现

是（Yes）

### 出现问题的手机信息

华为畅享9e

### 出现问题的安卓版本、系统版本

android9

**Comment by pppscn** [comment]
下载每周构建版试试
https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by rikthhpgf2005** [comment]
> 下载每周构建版试试 https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

可以用
