### ISSUE TITLE
[Suggestion]: 格式化关键字中增加 {{TIME}}/{{时间}}

### ISSUE THREAD

**Issue by ywjheart** [pppscn/SmsForwarder#396]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

格式化关键字中增加 {{TIME}}/{{时间}}， 内容展开为 日期+时间，这可以使得通知消息本身包含系统当前的日期和时间，而不是仅仅依赖通知频道的收发时间。

比如 {{TIME}}：到达补习中心 ， 就可以展开为 2024/12/12 12:12:12: 到达补习中心

参考信息： https://github.com/pppscn/SmsForwarder/wiki/%E9%99%84%E5%BD%953%EF%BC%9A%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A8%A1%E6%9D%BF%E5%8F%AF%E7%94%A8%E5%8F%98%E9%87%8F

**Comment by pppscn** [comment]
已经有了，试试 `{{当前时间}}` `{{CURRENT_TIME}}` `{{當前時間}}`
