### ISSUE TITLE
[Suggestion]: 建议增加变量IP地址

### ISSUE THREAD

**Issue by rikthhpgf2005** [pppscn/SmsForwarder#398]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

自动任务中填加条件网络状态后推送无法取出ip，3.2版还可以发ip信息，客户端能根据新ip连接

**Comment by pppscn** [comment]
| 简体中文 | 繁體中文 | English  | 适用场景  | 标签说明   | 
| :-------------: | :-------------: | :-------------: | :------------: | :------------- | 
| `{{IPV4}}` | `{{IPV4}}` | `{{IPV4}}` | 所有转发 | 网络状态改变时，访问 `https://api6.ipify.org` 返回的公网IPv4，`v3.3.1+`适用  | 
| `{{IPV6}}` | `{{IPV6}}` | `{{IPV6}}` | 所有转发 | 网络状态改变时，访问 `https://api.ipify.org` 返回的公网IPv6，`v3.3.1+`适用  | 

下载每周构建版试试
https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by ywjheart** [comment]
标签说明中的url写反了。
