### ISSUE TITLE
[Suggestion]: 优化Screen On/Off 事件

### ISSUE THREAD

**Issue by ywjheart** [pppscn/SmsForwarder#399]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

目前已经支持两类Screen 事件， On和Off，能否额外增加2个事件， screen unlocked， screen locked。 因为screen unlocked才是实际使用手机吧。

**Comment by pppscn** [comment]
![微信图片_20240216214810](https://github.com/pppscn/SmsForwarder/assets/5105854/9d88e741-10fd-4474-b2a9-53efcc4d78c5)

已经细分四种事件

**【注意】如果有设置锁屏密码，通常按下电源键息屏时会立即锁定，此时触发的是 locked（不会触发 off）；没密码时才会触发 off **

等每周构建版在线编译完成，下载覆盖安装试试

https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by ywjheart** [comment]
Pixel 6P测试正常，创建了4个任务，包括用NovaLauncher的一键锁屏，不同锁屏方式主要差异在screen off事件。

**Comment by ywjheart** [comment]
对不起，刚才测试不仔细，延时似乎无效，虽然不影响使用。默认延迟设置为5分钟，用一键锁屏或者指纹解锁，其实notification是立刻发出的，而不是根据延时设置。

**Comment by ywjheart** [comment]
screen on： 设置为0 可以正确触发。
screen locked、unlocked: 可以正确触发，但延时设置似乎无效。
screen off：不是很容易触发，没什么影响。

**Comment by pppscn** [comment]
> screen locked、unlocked: 可以正确触发，但延时设置似乎无效。

这个问题重新下载测试

> screen off：不是很容易触发，没什么影响。

【注意】如果有设置锁屏密码，通常按下电源键息屏时会立即锁定，此时触发的是 locked（不会触发 off）；没密码时才会触发 off

**Comment by ywjheart** [comment]
使用最新构建，设置屏幕超时30s， Pixel6P可以触发Off 事件（看起来没问题了）。
另外我注意到只有On、Off可以设置为0 mins, Locked/Unlocked 无论改成多少，submit，save之后再回来检查依然是5 mins，不过触发实际上是立刻的。

**Comment by pppscn** [comment]
> 使用最新构建，设置屏幕超时30s， Pixel6P可以触发Off 事件（看起来没问题了）。 另外我注意到只有On、Off可以设置为0 mins, Locked/Unlocked 无论改成多少，submit，save之后再回来检查依然是5 mins，不过触发实际上是立刻的。（等于这个无变化）

抱歉，我太自大了，直接ctrl+c/v了事，没有测试，忘记初始化赋值了，继续测试吧

**Comment by ywjheart** [comment]
我把screen lock, unlocked的延时设置为2mins，测试正常。应该是修好了。

**Comment by pppscn** [comment]
![微信图片_20240217185934](https://github.com/pppscn/SmsForwarder/assets/5105854/7fe4de0b-f886-4fc7-968a-55c7d421d0a2)


继续测试
