### ISSUE TITLE
开机自启后无法转发短信。

### ISSUE THREAD

**Issue by mymine** [pppscn/SmsForwarder#4]
软件虽然会开机自启！但是开机自启后无法转发短信。开机自启后要打开软件后才会转发短信。
以测试小米5s Android8和redmi k20 pro 安卓11

**Comment by pppscn** [comment]
[SmsForwarder_release_20210313_1.6.4.zip](https://github.com/pppscn/SmsForwarder/files/6134942/SmsForwarder_release_20210313_1.6.4.zip)

先试试这个版本能不能解决问题

**Comment by pppscn** [comment]
应该是动态获取权限的问题，启动界面之后才会促发动态获取权限，自启动的是前台服务（它只是为了保证程序不死），它没获得监听短信的权限

我刚才试了一下，Android 7 （MIUI 10）可以变相实现，但是AVD中测试Android 10 还是不行，我再想想办法

**Comment by mymine** [comment]
> 应该是动态获取权限的问题，启动界面之后才会促发动态获取权限，自启动的是前台服务（它只是为了保证程序不死），它没获得监听短信的权限
> 
> 我刚才试了一下，Android 7 （MIUI 10）可以变相实现，但是AVD中测试Android 10 还是不行，我再想想办法

好的👌🏻

**Comment by pppscn** [comment]
[v1.6.4](app/release/SmsForwarder_release_20210313_1.6.4.apk) Android8.1以下手机重启后尝试启动主界面，以便动态获取权限

先试试小米5s Android8 这个行不行了；Android 9 以上暂时无解

**Comment by mymine** [comment]
> [v1.6.4](app/release/SmsForwarder_release_20210313_1.6.4.apk) Android8.1以下手机重启后尝试启动主界面，以便动态获取权限
> 
> 先试试小米5s Android8 这个行不行了；Android 9 以上暂时无解

没有文件
