### ISSUE TITLE
1.7.4 转发失败时重试交互问题

### ISSUE THREAD

**Issue by Neutralization** [pppscn/SmsForwarder#40]
代理未运行时收到短信，转发至telegram失败。
在失败后连接代理，点开失败记录详情，点击重发，详情界面消失，底部toast"你确定要重发吗"。
没有出现进一步的操作界面，无法进行重发。

**Comment by pppscn** [comment]
抱歉，重发功能暂未实现，该按钮不小心再1.7.4版本给打包进去了，后续版本会实现该功能，敬请期待

**Comment by MrDHY** [comment]
实现了吗
