### ISSUE TITLE
[Suggestion]: 增加location的格式化关键字

### ISSUE THREAD

**Issue by ywjheart** [pppscn/SmsForwarder#400]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

目前{{location}} 可以返回很详细的信息，也包含Longitude和Latitude。 那么如果格式化关键字增加{{Longitude}}和{{Latitude}} ，就可以在通知里构造类似https://www.google.com/maps/@{{Latitude}} ,{{Longitude}} 从而实现在通知接收端点击跳转。

**Comment by ywjheart** [comment]
这样也不行：

Longitude(.*)[\r\n]+Latitude(.*)[\r\n]+===https://www.google.com/maps/@$2,$1

**Comment by pppscn** [comment]
下载每周构建版试试
https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by ywjheart** [comment]
安装后，使用 字符串： https://www.google.com/maps/@{{LOCATION_LATITUDE}},{{LOCATION_LONGITUDE}}  格式化正常。
