### ISSUE TITLE
[Suggestion]: 添加Task额外的事件和动作

### ISSUE THREAD

**Issue by ywjheart** [pppscn/SmsForwarder#401]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

目前smsforwarder已经可以很方便的转发消息，但是在没有网络的情况下（WIFI关闭，数据关闭），短信和来电都不能被转发。在新版中已经有许多事件和动作，如果能增加以下特性，那么整个流程会更完善。
1. 事件： 收到sms，来电，
2. 动作：wifi启用或关闭，移动数据启用或关闭。 启用可以考虑加一个可选的时长，比如5分钟，那么5分钟后重新关掉。

应用：
1. 收到sms或来电时，启用wifi或数据，那么smsforwarder就可以发送通知，或者重试时发出
2. 用CRON触发器，定时启用wifi或数据，比如每30分钟启用5分钟，让不同的app有机会收到消息，smsforwarder转发这些通知

**Comment by Saxon-Sun** [comment]
确实有这个需求 希望可以增加收到SMS就打开wifi连接上转发后多久关闭wifi，30秒内连接不上wifi就通过短信或者流量渠道转发。

**Comment by ywjheart** [comment]
> 确实有这个需求 希望可以增加收到SMS就打开wifi连接上转发后多久关闭wifi，30秒内连接不上wifi就通过短信或者流量渠道转发。

WiFi 一般是家里可靠的WiFi, 所以，一般都能连上。而且，如果用的是gotify， 服务器本身也在同一个网络。
如果smsf支持打开wifi/data，那么，设置为重试1-2次，应该就可以发出去了。

至于两个都没法连接的情况下，感觉就看情况了，毕竟不同手机套餐的短信数量差异大，国际漫游的情况下，如果转发，费用太高了。

**Comment by Saxon-Sun** [comment]
> > 确实有这个需求 希望可以增加收到SMS就打开wifi连接上转发后多久关闭wifi，30秒内连接不上wifi就通过短信或者流量渠道转发。
> 
> WiFi 一般是家里可靠的WiFi, 所以，一般都能连上。而且，如果用的是gotify， 服务器本身也在同一个网络。 如果smsf支持打开wifi/data，那么，设置为重试1-2次，应该就可以发出去了。
> 
> 至于两个都没法连接的情况下，感觉就看情况了，毕竟不同手机套餐的短信数量差异大，国际漫游的情况下，如果转发，费用太高了。

我现在就是短信数量多 但是想用wifi走bark比较方便，一直连接也没有必要   已经有快捷指令了 加上这些功能应该是没有太大问题的 
期待大佬加上

**Comment by pppscn** [comment]
### 1、wifi启用或关闭

目前测试仅部分手机系统支持

详见 [附录9：短信指令#4试验性打开或关闭-wifi](https://github.com/pppscn/SmsForwarder/wiki/%E9%99%84%E5%BD%959%EF%BC%9A%E7%9F%AD%E4%BF%A1%E6%8C%87%E4%BB%A4#4%E8%AF%95%E9%AA%8C%E6%80%A7%E6%89%93%E5%BC%80%E6%88%96%E5%85%B3%E9%97%AD-wifi)

###  2、关于 `移动数据启用或关闭`

> 在Android 10及以上版本中，直接开关移动网络的标准API是不再提供的，因为谷歌增加了对用户隐私和安全性的保护，不再允许应用直接控制移动网络开关。用户必须通过系统设置界面手动切换移动网络状态。

> 对于Android 9及以下版本，可以使用反射来调用隐藏的方法来切换移动网络状态。但是这种做法是不被推荐的，可能因为Android系统的更新而失效。

**结论：这个需求做不了**
