### ISSUE TITLE
[Bug]: 自动任务添加启停frpc app自动重启

### ISSUE THREAD

**Issue by rikthhpgf2005** [pppscn/SmsForwarder#402]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

v3.3.0

### 问题描述

自动任务添加启停frpc app自动重启
https://github.com/pppscn/SmsForwarder/assets/12007009/ff123fcc-d7bc-4e50-9a6b-648433e7f285

### 复现步骤

自动任务添加启停frpc app自动重启

### 是否必现

是（Yes）

### 出现问题的手机信息

华为畅享9e

### 出现问题的安卓版本、系统版本

android9

**Comment by pppscn** [comment]
估计是跟这个一样
https://github.com/pppscn/SmsForwarder/issues/394

下载每周构建版覆盖安装试试
https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by rikthhpgf2005** [comment]
> 估计是跟这个一样 #394
> 
> 下载每周构建版覆盖安装试试 https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

经测试，在未下载frpc情况下在任务中添加启停app就崩溃了，建议添加下载检查后再触发添加任务事件

**Comment by pppscn** [comment]
下载每周构建版试试
https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by rikthhpgf2005** [comment]
> 下载每周构建版试试 https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

问题得到解决
