### ISSUE TITLE
[Bug]: 企业应用消息返回301002错误

### ISSUE THREAD

**Issue by ihnic** [pppscn/SmsForwarder#405]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.3.0

### 问题描述

今天发现企业应用消息出现301002错误。之前没有
错误提示：
请求失败:{"errcode"301002,errmsg":"not allow operateanother agent with this accesstoken.hint:[170833****************54from ip: **.***.**.**, more infoat https://open.work.weixin.qq.com/devtool/query?e=301002")

### 复现步骤

点击企业应用消息推送

### 是否必现

是（Yes）

### 出现问题的手机信息

联想Z5

### 出现问题的安卓版本、系统版本

miui 11

**Comment by pppscn** [comment]
```
API错误码: 301002

错误说明: 无权限操作指定的应用

排查方法:
无权限操作指定的应用。access_token来源需要有指定应用的权限。
比如说，[发消息接口](https://open.work.weixin.qq.com/api/doc#10167) 指定了参数 "agentid": 14，但使用的 access_token 是通过应用agentid: 100032 生成的调用凭证，这种就会报该错误码。
access_token的权限查询，可在 [错误码查询工具](https://open.work.weixin.qq.com/devtool/query) 确认。
```

企微都给你链接了自己登录上去看看吧
