### ISSUE TITLE
[Suggestion]: 咨询一下电量提示的那个8888888怎么没有了呢。。。

### ISSUE THREAD

**Issue by pinoren** [pppscn/SmsForwarder#406]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

麻烦问一下，3.3版本为何没有电量区间提醒了呢，这个功能还挺方便的。。。。就是填写8888888转发的那个功能。。。。

**Comment by pppscn** [comment]
https://github.com/pppscn/SmsForwarder/releases/tag/v3.3.0

> 新增：自动任务·快捷指令 —— 触发条件：电池电量&充电状态改变（废弃：88888888）
