### ISSUE TITLE
[Bug]: 【自动任务·快捷指令】里的触发条件bug

### ISSUE THREAD

**Issue by nahco365** [pppscn/SmsForwarder#407]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

3.3.0

### 问题描述

使用新建自动任务，里面添加条件的[定时任务]当填入数字时没有现将预留的“ * ”删除时软件会崩溃

### 复现步骤

1.新建自动任务（+）
![1708399169198](https://github.com/pppscn/SmsForwarder/assets/98928834/e17e9e2e-04b3-4eea-b7f1-0c04b7b0851f)

2.添加条件
![1708399169189](https://github.com/pppscn/SmsForwarder/assets/98928834/33f63403-c1a9-4872-bb1f-77d24a3c5a85)

3.选择定时任务
![1708399169179](https://github.com/pppscn/SmsForwarder/assets/98928834/475686eb-edb8-4a89-9281-2cf692507667)

4.点击时间输入框内任何一个项目，不删除“ * ”的情况下输入数字
![1708399169170](https://github.com/pppscn/SmsForwarder/assets/98928834/54b71f8a-bca4-4cca-97ed-35e320d57334)

5.退出输入框（点击其他输入框或返回）

6.软件崩溃

### 是否必现

否（No）

### 出现问题的手机信息

小米 note 3 (jason)  6+128 

### 出现问题的安卓版本、系统版本

asop crdroid OS 9.11 Android 13

### 提供截图或视频

![1708399169159](https://github.com/pppscn/SmsForwarder/assets/98928834/7cbd0588-e91f-4b79-82ba-017c3fcc5d18)
![1708399169170](https://github.com/pppscn/SmsForwarder/assets/98928834/e81a8cf4-6e60-4815-85ec-10c0a0daa024)
![1708399169179](https://github.com/pppscn/SmsForwarder/assets/98928834/2d78e6b1-bf0e-4c62-85ea-1d01414426b6)
![1708399169189](https://github.com/pppscn/SmsForwarder/assets/98928834/60ada238-77c2-43f0-b816-e23c16a12d01)
![1708399169198](https://github.com/pppscn/SmsForwarder/assets/98928834/dda5cc10-ea96-48d1-804c-659b71d1f9b5)

**Comment by pppscn** [comment]
要不直接把输入框改成只读算了，这样可以避免乱输入

**Comment by pppscn** [comment]
下载每周构建版试试
https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml
