### ISSUE TITLE
[Suggestion]: FCM推送通知的转发问题

### ISSUE THREAD

**Issue by r0ckstill** [pppscn/SmsForwarder#409]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

部分软件的FCM通知（如tg）似乎会带内容推送一遍简洁通知，然后再唤醒app呈现更详细的通知。两者在长短和图片显示上有时会略有不同（相同时可以被自动过滤），因此会被识别为两次通知重复转发。

### 你觉得该怎么去完善会比较好？【非必答】

是否可以通过转发软件识别屏蔽第一次不详细的通知，或者有什么办法让fcm第一次通知不显示，只显示fcm唤醒app后弹出的详细通知呢？
系统是基于原生系统的pixelOS Android13

**Comment by pppscn** [comment]
两次通知的标题一样？就内容不一样？

目前是用通知内容+包名作为唯一判断

```
val key = CipherUtils.md5(msgInfo.type + msgInfo.from + msgInfo.content)
```
你这个需求可能要改成 包名+标题，这样的话  可能会漏掉很多通知，不是所有通知都有标题

**Comment by r0ckstill** [comment]
如图，标题完全一样，就是内容长短不同。
可能是FCM推送和本身app被唤醒后各通知了一次导致的。
目前对相应软件使用消除通知能解决推送两次的问题，但是app不在后台的时候推送的都是简略通知。

![Screenshot_20240223-152327_短信转发器](https://github.com/pppscn/SmsForwarder/assets/47161927/e1b567c0-484b-4322-bc20-402057de8873)
![Screenshot_20240223-152318_短信转发器](https://github.com/pppscn/SmsForwarder/assets/47161927/aab0e8e5-3f5d-4494-bffc-54382e8d2cf6)

**Comment by pppscn** [comment]
因为详细的在简略之后才有，除非做延时队列，简略先暂存，一段时间内收到详细的话，作废掉

可能只是个伪需求，暂不考虑做这个
