### ISSUE TITLE
[Suggestion]: 希望启用免打扰后，在恢复时，能转发期间收到的短信和低电量提醒

### ISSUE THREAD

**Issue by servicehost** [pppscn/SmsForwarder#411]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

我在安装SmsForwarder的手机设定了自动在每天22:00-06:00关闭WIFI以达到节省电量效果。

但在恢复WIFI后，这期间发生的【短信】和【自动任务-低电量提醒】都不会在恢复WIFI后重新发送。（虽然可以设定让它不间断重试，但这恐怕会造成大量的电量消耗）

所以想试下免打扰时间段同样也设定为：22:00-06:00，是否可在恢复WIFI后重新发送该时间段产生的短信和低电量提醒。

与作者沟通知得知，这是无效的，免打扰功能会丢弃该时间段产生的所有消息。

作者告知可以提交一个Issue，所以就来提交了。盼能在下次更新时添加此功能，谢谢。

**Comment by servicehost** [comment]
可以在退出免打扰时间段，将期间收到的消息，一次汇总发送，发送的消息格式如下显示：

> 【以下为免打扰时间段 22:00 - 06:00 收到的消息】
> 23:00 短信：
> XXXXXXXXXXXXXXXX
> 23:15 短信：
> XXXXXXXXXXXXXXXX
> 02:00 自动任务-低电量提醒：
> XXXXXXXXXXXXXXX
> 05:15 未接来电：
> XXXXXXXXXXXXXXX
> 

这样不至于在这个免打扰时间，如果突发大量事件，在恢复后，每一条都都发个消息会显的特别多。

以上仅为个人建议，还需看作者觉的哪种形式更好。

**Comment by pppscn** [comment]
1、其实现有的 [每周构建版](https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml) 已经能满足你的需求

系统每天22:00-06:00关闭WIFI，这时smsf都是转发失败的

添加一个`自动任务`，在`wifi恢复`时且`时间大于6:00`之后，重发失败的消息就可以了

不需要开启smsf的`免打扰`(只是自动丢弃)，开启了只是不转发也不记录了，但是smsf还在后台

2、关于免打扰期间的消息合并不可行，很多通道报文都有长度限制的，发不出去

**Comment by servicehost** [comment]
> 1、其实现有的 [每周构建版](https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml) 已经能满足你的需求
> 
> 系统每天22:00-06:00关闭WIFI，这时smsf都是转发失败的
> 
> 添加一个`自动任务`，在`wifi恢复`时且`时间大于6:00`之后，重发失败的消息就可以了
> 
> 不需要开启smsf的`免打扰`(只是自动丢弃)，开启了只是不转发也不记录了，但是smsf还在后台
> 
> 2、关于免打扰期间的消息合并不可行，很多通道报文都有长度限制的，发不出去

好的，明白了
只有这个每日构建版才可以在【自动任务】中设定【在wifi恢复时且时间大于6:00之后，重发失败的消息就可以了】这个新的功能吗？现有的3.3.0版是无此功能的？

**Comment by servicehost** [comment]
已经安装此每日构建版，并按作者方式进行了设置，待后期测试。
谢谢。

**Comment by pppscn** [comment]
![微信图片_20240225104912](https://github.com/pppscn/SmsForwarder/assets/5105854/1638a436-73a5-4301-8c7c-68305beb5607)

已增加`记录日志`开关，配合`自动任务`可以实现延时发送（自己发挥想象组合条件、动作）

![微信图片_20240225104917](https://github.com/pppscn/SmsForwarder/assets/5105854/4e075914-c16d-4d12-839f-724b8d2e693e)

**Comment by servicehost** [comment]
之前安装了：SmsF_3.3.0_100051_universal_20240224_release 每日构建版

经实测，在【自动任务】中，设定条件在【每天 06:02 重新发送失败的消息】（我设定的WIFI是在06:00恢复），【短信】和【未接来电】都可以正常重发。但是唯有【自动任务】中设定的【低于28%发送低电量提醒】的消息不会重发，我设定的低电量提醒是只发一次，而在 23:00-06:00 断网期间，如果发生了低于28%的低电量发提醒的自动任务则不会重发。（我使用的发送通道都是电子邮件）

现在我暂时在【自动任务】中设定了一个每天 06:05 再检测一次电量如果低于28%就发提醒的任务。

不知道作者是否会修改此问题，必竟【自动任务】中 非短信和来电 的消息，如果在断网或免打扰期间发生，也算是一种【失败消息】？

**Comment by servicehost** [comment]
> 1、其实现有的 [每周构建版](https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml) 已经能满足你的需求
> 
> 系统每天22:00-06:00关闭WIFI，这时smsf都是转发失败的
> 
> 添加一个`自动任务`，在`wifi恢复`时且`时间大于6:00`之后，重发失败的消息就可以了
> 
> 不需要开启smsf的`免打扰`(只是自动丢弃)，开启了只是不转发也不记录了，但是smsf还在后台
> 
> 2、关于免打扰期间的消息合并不可行，很多通道报文都有长度限制的，发不出去

之前安装了：SmsF_3.3.0_100051_universal_20240224_release 每日构建版

经实测，在【自动任务】中，设定条件在【每天 06:02 重新发送失败的消息】（我设定的WIFI是在06:00恢复），【短信】和【未接来电】都可以正常重发。但是唯有【自动任务】中设定的【低于28%发送低电量提醒】的消息不会重发，我设定的低电量提醒是只发一次，而在 23:00-06:00 断网期间，如果发生了低于28%的低电量发提醒的自动任务则不会重发。（我使用的发送通道都是电子邮件）

现在我暂时在【自动任务】中设定了一个每天 06:05 再检测一次电量如果低于28%就发提醒的任务。

不知道作者是否会修改此问题，必竟【自动任务】中 非短信和来电 的消息，如果在断网或免打扰期间发生，也算是一种【失败消息】？
