### ISSUE TITLE
主动控制远程发短信接口需要手动确认才能发短信

### ISSUE THREAD

**Issue by 342523895** [pppscn/SmsForwarder#412]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

主动控制远程发短信接口需要手动确认才能发短信，能不能直接就发送成功不需要手动再确认

**Comment by pppscn** [comment]
参看wiki常见问题：https://github.com/pppscn/SmsForwarder/wiki/%E3%80%90%E5%BF%85%E8%AF%BB%E3%80%91%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#q%E5%B0%8F%E7%B1%B3%E7%BA%A2%E7%B1%B3%E6%89%8B%E6%9C%BA%E7%9F%AD%E4%BF%A1%E9%80%9A%E9%81%93%E5%8F%91%E9%80%81%E6%97%B6%E6%80%BB%E4%BC%9A%E6%98%BE%E7%A4%BA%E8%BF%99%E4%B8%AA%E4%B8%8D%E8%83%BD%E8%87%AA%E5%8A%A8%E8%BD%AC%E5%8F%91%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3%E5%91%A2

或降级Android；或root后冻结“手机管家”之类的系统应用；或刷类原生系统；

**Comment by pppscn** [comment]
目前只留下一个tg群组 https://t.me/+QBZgnL_fxYM0NjE9
