### ISSUE TITLE
[Bug]: 为什么测试发送能正常收到，实际无法转发？

### ISSUE THREAD

**Issue by mijjjj** [pppscn/SmsForwarder#413]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.3.0

### 问题描述

无法转发短信，日志里面也没有任何日志，已经按照wiki所有设置了还行不行。测试发送能正常收到
手机是华为nova6 5g  鸿蒙版本

### 复现步骤

就正常设置，具体设置参考我发的图片

### 是否必现

是（Yes）

### 出现问题的手机信息

华为 nova6 5g版本

### 出现问题的安卓版本、系统版本

harmonyos 4.0.0

### 提供截图或视频

![微信图片_20240229174241](https://github.com/pppscn/SmsForwarder/assets/37797122/9d228ab4-5a8a-4efd-8ce6-a2614b1dc2c7)
![微信图片_20240229174257](https://github.com/pppscn/SmsForwarder/assets/37797122/446864d9-ab9a-4e62-be75-bb2e6e5a8396)
![微信图片_20240229174258](https://github.com/pppscn/SmsForwarder/assets/37797122/abe7f939-81a6-4e12-884a-e17052a5a047)
![微信图片_202402291742571](https://github.com/pppscn/SmsForwarder/assets/37797122/5d625e7c-18c4-4fcc-a6fc-e3635f93fb70)
![微信图片_202402291742572](https://github.com/pppscn/SmsForwarder/assets/37797122/8d76ccab-3c27-4b2c-b27d-4924217d48c6)

**Comment by mijjjj** [comment]
测试过短信转发功能能正常使用，所有就很好奇，既然短信抓发功能能正常的话肯定软件已经成功读取到短信了，很怀疑是不是我设置的转发规则有问题，但是查看了下又感觉没啥问题

**Comment by pppscn** [comment]
1、转发规则、发送通道 页面的【测试】通过，只能代表，你的发送通道（畅通）跟转发规则（命中）没问题

2、实际转发不出去，通常是监听不到 短信广播

2.1 如果 普通手机短信 能转发，只有验证码类或通知类短信不行（通常是验证码保护机制的问题，把【通知信息整合】【验证码安全保护】之类的都关闭了）

2.2 如果连 普通短信都不能转发，应该是权限问题（实在不行就用app通知转发的形式转发，弊端没有卡槽）
