### ISSUE TITLE
[Bug]: 电充满无法触发

### ISSUE THREAD

**Issue by rikthhpgf2005** [pppscn/SmsForwarder#414]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

否（No）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

v3.3

### 问题描述

电充满无法触发，通过远程查看电池状态是充电中，电量100%

### 复现步骤

电充满无法触发，通过远程查看电池状态是充电中，电量100%

### 是否必现

是（Yes）

### 出现问题的手机信息

华为

### 出现问题的安卓版本、系统版本

android 9

**Comment by pinoren** [comment]
我曾经观察过，电量100%和电充满并不是一个事件，当电量达到100%的时候，有可能仍然是充电状态，用检测APP可以查到仍然有对电池的充电电流，这个时候并不是充满状态，但电量100%事件可以被触发。但是电充满状态在电池情况不好的手机上可能会在电量100%的时候多次触发，大概状态是，电压达到4.35V——充电电流=0，提示电充满，随后电池电压下降，降低到某临界值，例如4.23V，重新触发对电池充电，充电电流=xxmA，又进入充电状态，在几分钟后再次进入4.3V电流=0并提示电充满这样的重复震荡提示中。

我不知道你遇到的是不是这种情况，或者是类似的情况，例如电其实没充满，但是电池电量确实是100%。

**Comment by pinoren** [comment]
另外我用的电量检测APP曾经检测到电池被充到103%的电量。应该是系统在校准电池容量造成的。只是系统自身显示的电量最大就是100%而已。

**Comment by rikthhpgf2005** [comment]
电池管理看到的状态是电量已充满。我晚点找个app检测试试

**Comment by pppscn** [comment]
> 另外我用的电量检测APP曾经检测到电池被充到103%的电量。应该是系统在校准电池容量造成的。只是系统自身显示的电量最大就是100%而已。

此时 {{BATTERY_PCT}} 是多少？在你的手机上，这个值与 {{BATTERY_INFO}} 中的是不是对不上？（前者通过计算得到的偏小，后者是原始值）

https://gitee.com/pp/SmsForwarder/wikis/pages?sort_id=5253992&doc_id=1821427

**Comment by pppscn** [comment]
> 电池管理看到的状态是电量已充满。我晚点找个app检测试试

检测的结论是什么？

**Comment by pinoren** [comment]
> > 另外我用的电量检测APP曾经检测到电池被充到103%的电量。应该是系统在校准电池容量造成的。只是系统自身显示的电量最大就是100%而已。
> 
> 此时 {{BATTERY_PCT}} 是多少？在你的手机上，这个值与 {{BATTERY_INFO}} 中的是不是对不上？ 前者是当前电池电量百分比通过计算(level/scale)得到的偏小，后者是level原始值
> 
> https://gitee.com/pp/SmsForwarder/wikis/pages?sort_id=5253992&doc_id=1821427

em，我使用的软件是“3c一体工具箱”中的电池工具组件，在充电的时候曾经见过电池电量被充到过103%，此时系统电量显示仍然是100%，这个100%是我设置的电池状态显示百分比所显示的数字，但是您的软件在3C工具箱提示103%电量的时候，也会和系统一致的提示100%的电量，是正常状态。

您提到的这两个参数，由于我没有这样查看过，所以不太清楚是否对不上。

**Comment by pppscn** [comment]
如果状态不准确，用`自动任务`中的`电量`（注意是：`level`） 作为触发条件解决
