### ISSUE TITLE
[Suggestion]: {{APP_VERSION}} 和关于界面总是固定为3.3.0

### ISSUE THREAD

**Issue by ywjheart** [pppscn/SmsForwarder#416]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

版本号为固定字符，不容易区分自己安装了哪个测试版

### 你觉得该怎么去完善会比较好？【非必答】

能否加上git commit id或者编译日期，这样容易了解自己安装的是那个测试版, 比如 3.3.0.yymmdd

**Comment by pppscn** [comment]
![微信图片_20240305091513](https://github.com/pppscn/SmsForwarder/assets/5105854/1f34bb94-97a2-46aa-9f1e-0eb62bb5ebdd)

直接加个`SmsF预览体验计划`，在线更新每周构建版，动态提示当前安装版本与最新版之间的差异（git 提交记录）

**Comment by ywjheart** [comment]
嗯，这样更彻底。👍
