### ISSUE TITLE
[Suggestion]: 建议给发送通道的"电子邮箱"方式增加S/MIME或PGP加密支持

### ISSUE THREAD

**Issue by zhangjint5** [pppscn/SmsForwarder#417]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

电子邮件具有成本低、跨平台、通用性强等优点，是普通用户的一个重要选择。但是目前3.3.0仍然无法支持电子邮件S/MIME或PGP加密标准。在短信转发过程中极大概率会出现诸如验证码等敏感短信，所以建议在后续版本中考虑支持S/MIME或PGP加密特性。

### 你觉得该怎么去完善会比较好？【非必答】

可以可考虑仅支持S/MIME或PGP加密，而不进行数字签名。这样的话只需要向软件内导入目标邮箱的公钥即可。降低操作难度。

**Comment by pppscn** [comment]
目前支持S/MIME或PGP加密的邮件服务商有哪些？不多的话就不折腾了

**Comment by zhangjint5** [comment]
> 目前支持S/MIME或PGP加密的邮件服务商有哪些？不多的话就不折腾了

S/MIME或PGP加密是邮件客户端，端到端的加密，与邮件服务商无关。

目前测试过IOS自带邮件客户端、小米手机自带邮件客户端、微软Outlook支持S/MIME。

Mozlila ThunderBird 客户端两者都支持。

**Comment by zhangjint5** [comment]
> OK，等其他issue全部关闭后研究一下

感谢！给您提供点资料，方便您研究

受信任的免费S/MIME证书可以去这里免费申请：https://extrassl.actalis.it/portal/uapub/freemail

OpenSSL创建加密邮件方法（为了简化操作，就不数字签名了）
openssl cms -encrypt -text -in 邮件原内容.txt文件 -out 加密后的邮件MIME源码文件 -aes256 -outform SMIME -recip 收件人证书.crt文件 -from 发件人邮箱 -to 收件人邮箱 -subject "邮件标题"

(如果邮件原内容本身就是MIME源码，那么就不需要-text参数)

最后把”加密后的邮件MIME源码“传到发件人SMTP服务器就可以了

解密邮件由目标邮件客户端软件完成，不需要做开发。

比起发普通明码邮件只是多了一个加密步骤，应该不会增加太多工作量吧！

再次感谢！

**Comment by pppscn** [comment]
覆盖安装 `每周构建版` 试试

**升级操作提示：** 
- `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
-  手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**已知问题：OpenPGP 只签名不加密时，签名不正常：**

```
无效的数宁签名
此消息包含数字签名，但检测到技术错误。可能已损坏或遭人窜改。
```

PS. 事实上，这个issue困扰了我好几天了，无数次踩坑试错

**Comment by pppscn** [comment]
> 已知问题：OpenPGP 只签名不加密时，签名不正常

已经修复

覆盖安装 `每周构建版` 试试

**升级操作提示：** 
- `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
-  手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml
