### ISSUE TITLE
为什么测试没问题（可以发到企业微信应用）正式短信就不转发？

### ISSUE THREAD

**Issue by monobo1989** [pppscn/SmsForwarder#42]
不会设置bark有热心朋友带带吗

**Comment by pppscn** [comment]
应该是监听不到短信，加QQ群（562854376）问一下同机型的机油

**Comment by monobo1989** [comment]
> 应该是监听不到短信，加QQ群（562854376）问一下同机型的机油

满人拉。。。。

**Comment by pppscn** [comment]
<html>
<body>


QQ机油互助交流2群：31330492
--



</body>
</html>
