### ISSUE TITLE
[Bug]: webhook 短信转发POST转发内容不完整

### ISSUE THREAD

**Issue by eamd-wq** [pppscn/SmsForwarder#420]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

3.3.0

### 问题描述

使用webhook方式转发 post body传参 json
[msg]为短信只有短信的第一行

### 复现步骤

https://bot.pushplus.plus/m/mine 微信打开注册后可获得token和topic
回复我邮箱地址发送测试token给你

### 是否必现

是（Yes）

### 出现问题的手机信息

*

### 出现问题的安卓版本、系统版本

*

**Comment by pppscn** [comment]
通用设置中开启调试模式，导出日志后贴上来

**Comment by pppscn** [comment]
没有后续反馈，先关闭了
