### ISSUE TITLE
[Suggestion]: 建议正则替换默认短信内容或者可以选择匹配内容标签内容，现在默认的是模板，这就导致了一个有意思的问题

### ISSUE THREAD

**Issue by mdg166** [pppscn/SmsForwarder#421]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

14450为您本次操作的验证码，请勿向他人透露短信内容，如非本人操作，请忽略。【安徽电信】
10001
上面为原来的短信内容，使用正则替换后提取的是电信的发件人10001六位数当成验证码了
最终结果为
10001514450为您本次操作的验证码，请勿向他人透露短信内容，如非本人操作，请忽略。【安徽电信】
10001
创造了一个bug

### 你觉得该怎么去完善会比较好？【非必答】

正则替换字段可以选择替换的自定义模板

**Comment by pppscn** [comment]
这个机制不会轻易调整（历史包袱——调整后现存的几十万用户怎么办？），建议自己优化一下正则表达式

**Comment by pppscn** [comment]
试试每周构建版（加入预览计划在线更新或手动下载）
https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

自定义模板可用变量标签支持正则替换，语法：`{{变量标签###正则表达式===替换结果}}`

例如：`{{FROM###(\d{3}).+(\d{4})===$1****$2}}`，当 FROM 值为 `19912345678`，最终替换为 `199****5678`

自定义模板+变量级的正则替换，不管是标题还是正文，尽情发挥你的想象
