### ISSUE TITLE
[Bug]: 使用多个转发通道时，转发规则自定义顺序失效

### ISSUE THREAD

**Issue by asiacny** [pppscn/SmsForwarder#422]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.3.0

### 问题描述

转发规则设置多个发送通道时，设置顺序保存后会改变成发送通道新建顺序

### 复现步骤

例：
1.新建发送通道webhook，名字web1
2.新建发送通道企业微信，名字weixin
3.新建发送通道webhook，名字web2
4.转发规则添加3个通道，按web1->web2->weixin排序后保存

保存转发规则后转发顺序会变成新建通道时的顺序web1->weixin->web2，点开设置亦一样，实际推送也如此

经测试，新建任意多个通道时均会出现转发规则自定义顺序无效，目前只能通过调整新建顺序避免该问题

### 是否必现

是（Yes）

### 出现问题的手机信息

All Phone

### 出现问题的安卓版本、系统版本

All Android

### 提供截图或视频

![Screenshot_2024-03-05-15-25-18-43_096d07ab25a3fbf7bded23fe4532c4bf](https://github.com/pppscn/SmsForwarder/assets/9075003/25e48a0e-ede4-4f69-a642-b034d369edc1)

**Comment by pppscn** [comment]
下载每周构建版试试
https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by asiacny** [comment]
最新版正常了，感谢作者
