### ISSUE TITLE
[Suggestion]: 邮件主题支持正则替换内容

### ISSUE THREAD

**Issue by himho** [pppscn/SmsForwarder#423]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

现在邮件主题只支持内容标签，或默认模板。导致邮件主题特别长，建议邮件主题也支持正则替换

**Comment by ywjheart** [comment]
目前通过gotify收到的都是android包名，也是很长的。随着smsf支持tasks，默认的在发送通道设置标题的做法比较受限制，能否考虑在rule/task自定义title/subject？

**Comment by pppscn** [comment]
> 目前通过gotify收到的都是android包名，也是很长的。随着smsf支持tasks，默认的在发送通道设置标题的做法比较受限制，能否考虑在rule/task自定义title/subject？

不是所有通道都有标题，gotify现在就支持标题模板了，想要应用名，就通用设置开启预加载App列表，然后插入对应标签就好了，或者专门通道跟专门规则用，标题就可以自己写死
