### ISSUE TITLE
转发结果是处理中是什么原因？

### ISSUE THREAD

**Issue by Laura0324** [pppscn/SmsForwarder#424]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

![image](https://github.com/pppscn/SmsForwarder/assets/152157822/0558e2d9-2dc8-441c-bec5-33c8b22e45d7)
这就导致没有转发成功 日志是黄色感叹号  这情况会触发重发机制吗？目前版本是3.2.0（重试机制好像没实现过） 有必要更新到最新版本吗

**Comment by pppscn** [comment]
这个应该是触发某个发送通道的bug了，调用通道之后直接线程没了，不然不管成功还是失败都会更新状态

建议升级 3.3.0 ，如果还有类似的情况，通用设置里面开启调试模式，导出log贴上来

**Comment by pppscn** [comment]
有后续反馈时再开启话题吧
