### ISSUE TITLE
[Suggestion]: 备份功能-配置导入导出

### ISSUE THREAD

**Issue by QQQQQQQQiu** [pppscn/SmsForwarder#425]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

good

**Comment by pppscn** [comment]
`主动控制` · `客户端` 里面的 `一键换新机`，有 网络 和 离线模式

**Comment by YanMiaoW** [comment]
个人感觉这个一键换新机弄的太复杂了, 可以参考下一下 v2ray, trojan这类需要经常改配置文件的导入方式, 提供 url链接(链接带参数可以复制粘贴), rq二维码(分享二维码,直接扫), json文件的导入和导出, 而且里面还有多个配置文件激活的概念, 可以自由切换(不用担心覆盖之前的配置)

**Comment by hausen1012** [comment]
支持。这个功能还是有必要的，最好可以本地或者网络导入
