### ISSUE TITLE
[Suggestion]: 转发通道能不能不做证书校验

### ISSUE THREAD

**Issue by e-ivan** [pppscn/SmsForwarder#427]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

应该安卓的请求可以不做证书校验吧？虽然我用的是https，但是可以不管证书是否正确。因为现在这个证书问题，有时候可以发送，有时候又报证书验证失败。。。
还有现在没有用证书的http，也会报错。不知道是系统原因还是bug。
我的系统的棒子4.4系统
![image](https://github.com/pppscn/SmsForwarder/assets/29646737/bdba9330-b90e-4920-8742-f3c6c067dc9f)

### 你觉得该怎么去完善会比较好？【非必答】

去掉证书校验
优化http请求

**Comment by pppscn** [comment]
覆盖安装 `每周构建版` 试试

**升级操作提示：** 
- `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
-  手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by pppscn** [comment]
没有后续反馈，先行关闭

**Comment by mapxn** [comment]
```
trust anchor for certification path not found
```
的解决办法：

替换新的的根证书到老旧设备的 `/system/etc/security/cacerts/`内，修改权限为644后重启。

新的的根证书可以从新版本的安卓手机中提取。

经过测试，可以解决证书无效的问题。

**Comment by mapxn** [comment]
[cacerts.zip](https://github.com/user-attachments/files/20394975/cacerts.zip)

这是一个从安卓15中提取的根证书，供参考
