### ISSUE TITLE
[Bug]: 自动任务中的执行动作测试时报错

### ISSUE THREAD

**Issue by gptuser1** [pppscn/SmsForwarder#428]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.3.0

### 问题描述

在【自动任务·快捷指令】-【执行动作】中，测试执行动作上出现 WorkManager 未正确初始化的报错，等一会儿再测试可能就好了，也可能还不行，重启app重装app都是如此

### 复现步骤

一般在启动app后

### 是否必现

是（Yes）

### 出现问题的手机信息

oppo a57

### 出现问题的安卓版本、系统版本

android 6.0.1, coloros 3.0

### 提供截图或视频

![Screenshot_2024-03-12-08-49-39-39](https://github.com/pppscn/SmsForwarder/assets/128674713/18b58502-0f27-40e7-8208-e1be36091831)

**Comment by pppscn** [comment]
下载每周构建版试试
https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by gptuser1** [comment]
> 下载每周构建版试试 https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

好了，没有这个报错了，谢谢！
