### ISSUE TITLE
原先#424的那个问题  刚刚又发现了出现“处理中”这个情况 

### ISSUE THREAD

**Issue by Laura0324** [pppscn/SmsForwarder#430]
### 是否有人曾提过类似的问题？

是（Yes）

### 你觉得APP有什么不足之处？

![lQDPJwWFM911sanNBNTNAhuwFS3RFkGWovAF5aS8stxhAA_539_1236](https://github.com/pppscn/SmsForwarder/assets/152157822/faab02bc-4e19-4ce6-8a77-896726bbeb7d)
这个截图是其中一条一开始显示处理中的短信  我仔细看了钉钉群消息后 发现 他其实在12：45的时候已经转发过了  但是我看日志还是在处理中  好像是有触发重发机制 在之后有重发了一遍 后续又有一条短信进来 也在处理中  但是这两条信息最终都发送出来了  我在发现处理中的这个时候才去开的 “开启调试模式 ” 导出log 显示是
![image](https://github.com/pppscn/SmsForwarder/assets/152157822/8eb78201-4ffb-4fb4-b799-16bc1fbb428b)
ps.导出日志是不是很慢  我点击之后甚至都提示未响应了

**Comment by pppscn** [comment]
覆盖安装最新的 `每周构建版` 试试

**升级操作提示：** 
- `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
-  手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by Laura0324** [comment]
> 覆盖安装最新的 `每周构建版` 试试
> 
> **升级操作提示：**
> 
> * `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
> * 手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

![image](https://github.com/pppscn/SmsForwarder/assets/152157822/cf0a7317-f2d2-4104-9234-543499f65b95)
是下载哪一个？

**Comment by Laura0324** [comment]
> 覆盖安装最新的 `每周构建版` 试试
> 
> **升级操作提示：**
> 
> * `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
> * 手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

感觉是偶发性的问题 之后收到的短信都没有这个问题
