### ISSUE TITLE
[Bug]: Gotify不支持.website域名

### ISSUE THREAD

**Issue by dicolar** [pppscn/SmsForwarder#431]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.3.0

### 问题描述

在之前的`发送通道`中设置`Gotify`时并不会强校验url的格式，这次升级到3.3.0之后发现已有的通道无法保存，提示`WebServer为空 或 不是有效URL`，我仔细尝试了如下步骤：
1. 改为https，无效
2. 去掉端口号，无效
3. 修改token为一个常规字符串，无效
4. 变更.website后缀为.cn或.com，有效

### 复现步骤

1. 在`发送通道`中新增一个`Gotify`通道
2. `WebServer` 中填写`http://gotify.helloworld.website:8080/message?token=abcd`
3. 点击保存

### 是否必现

是（Yes）

### 出现问题的手机信息

vivo y77t

### 出现问题的安卓版本、系统版本

Android 13

### 提供解决方案

WebServer的校验可以改为弱校验

**Comment by pppscn** [comment]
覆盖安装 `每周构建版` 试试

**升级操作提示：** 
- `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
-  手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml
