### ISSUE TITLE
[Suggestion]: 转发日志右上角增加筛选转发状态按钮

### ISSUE THREAD

**Issue by HHHHHHHeart** [pppscn/SmsForwarder#433]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

转发日志右上角增加筛选转发状态按钮，这样可以快速筛选出没有转发成功的日志。以及根据转发内容检索关键词有没有被转发

**Comment by pppscn** [comment]
覆盖安装 `每周构建版` 试试

**升级操作提示：** 
- `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
-  手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml
