### ISSUE TITLE
[Bug]: SigningConfig "release" is missing required property "storeFile".

### ISSUE THREAD

**Issue by I-E-E-E** [pppscn/SmsForwarder#435]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3 

### 问题描述

SigningConfig "release" is missing required property "storeFile".

### 复现步骤

build APK

### 是否必现

是（Yes）

### 出现问题的手机信息

Android Studio

### 出现问题的安卓版本、系统版本

Android 6

**Comment by pppscn** [comment]
https://github.com/pppscn/SmsForwarder/wiki/%E5%85%B3%E4%BA%8E%E5%AE%9A%E5%88%B6%E5%BC%80%E5%8F%91
