### ISSUE TITLE
[Suggestion]: Email加密功能待优化

### ISSUE THREAD

**Issue by vicdorke** [pppscn/SmsForwarder#437]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

Email加密完全不需要发件人密钥，不知道现在留着可选有什么用吗，建议砍掉。
收件人证书希望可以导入后可以直接存下来，我发现现在导入完还是删除不了

**Comment by pppscn** [comment]
1、发件人密钥用于数字签名

2、考虑过，最终还是只存文件路径，
，再斟酌一下

**Comment by pppscn** [comment]
优化：以`Base64`形式保存证书（同时兼容`文件路径`形式） #437

覆盖安装 `每周构建版` 试试

**升级操作提示：** 
- `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
-  手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by cnbilinyj** [comment]
> 1、发件人密钥用于数字签名
> 
> 2、考虑过，最终还是只存文件路径，
> ，再斟酌一下

别斟酌了，给你一个解决办法：
导入的时候，增加一个选择，包含两个选项：
1. 只存文件路径：节省空间，但是容易被误删除或移动
2. 保存收件人证书文件：不易被误删除，但是可能占用更多空间
