### ISSUE TITLE
[Bug]:短信转发器退到后台 自动任务不生效。

### ISSUE THREAD

**Issue by jovelang** [pppscn/SmsForwarder#438]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

V3.3.0

### 问题描述

我设置了两个自动任务。
1、充电状态：充电中，充电器：不限。 则发送通知。 目的是：手机充电了就发通知告知已经充电
2、电池电量 15%，充电状态未充电。则发送通知。目的是：如果电池低于 15%，又没有充电。就通知提醒。
但是我发现应用退到后台就不会触发这个任务。
我以为是进程冷却了被，但是短信转发是正常的。

### 复现步骤

设置自动任务，退到后台。

### 是否必现

是（Yes）

### 出现问题的手机信息

OnePlus 9

### 出现问题的安卓版本、系统版本

Android 14

### 提供截图或视频

无

### 提供报错堆栈【请提供logcat抓取的日志，参考： https://blog.csdn.net/m0_64776928/article/details/126005119 】

无

### 提供解决方案

无

**Comment by laozhuv** [comment]
![S40329-205942](https://github.com/pppscn/SmsForwarder/assets/59519407/99de1460-2581-4180-b15f-52dae4dadbb7)
同样问题，设置自动任务电池充电中提示不生效，然后点击下方的“测试”按钮，弹出这个报错。信息和电话转发都是正常的，只有自动任务有问题。魅族pro7，安卓7.0。

**Comment by jovelang** [comment]
我把充电器改为 AC 好像就可以了

**Comment by laozhuv** [comment]
> 我把充电器改为 AC 好像就可以了

牛呀，改成AC之后就可以了！

**Comment by pppscn** [comment]
已经修复过了，覆盖安装 `每周构建版` 试试

**升级操作提示：** 
- `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
-  手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml
