### ISSUE TITLE
[Bug]: 企业微信测试短信转发，能够正常转发，但在实际上(比如用手机号注册或登录一些app需要收验证)却不能正常转发，而日志里却有收到的短信的信息。

### ISSUE THREAD

**Issue by doublez-ten** [pppscn/SmsForwarder#440]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.3.0

### 问题描述

企业微信测试短信转发，能够正常转发，但在实际上(比如用手机号注册或登录一些app需要收验证)却不能正常转发，而日志里却有收到的短信的信息。

### 复现步骤

1.企业微信设置机器人，复制机器人的webhook地址。
2.在SmsForwarder添加企业微信发送通道，粘贴webhook地址。
3.点击测试，提示成功。
4.在转发规则里添加规则，选择企业微信通道。
5.匹配卡槽，全部选择。
6.测试，提示成功，并在企业微信里能正常收到测试的内容。
7.随机找个需要手机登录并收验证码的app进行登录。
8.进行登录后，会进行收取验证码，等待一会企业微信里并没有任何信息。
9.在SmsForwarder通用设置里导出输出日志，并查看log日志，日志里有刚才登录所收的短信验证码信息，而企业微信里没有任何消息。

### 是否必现

是（Yes）

### 出现问题的手机信息

华为Mate20-Pro

### 出现问题的安卓版本、系统版本

鸿蒙3.0

### 提供截图或视频

![image](https://github.com/pppscn/SmsForwarder/assets/102229872/e1743036-2ead-4ba5-bd39-c967c615eb29)

**Comment by pppscn** [comment]
你打码的那几行说明短信广播有正常收到了，权限什么的都没有问题了

**排查一下原因：**

1、通用设置中的总开关没打开

2、没有匹配中转发规则

3、如果`转发日志`里面有日志，但是没转发出去，点击小图标查看具体转发返回

**Comment by doublez-ten** [comment]
> 你打码的那几行说明短信广播有正常收到了，权限什么的都没有问题了
> 
> **排查一下原因：**
> 
> 1、通用设置中的总开关没打开
> 
> 2、没有匹配中转发规则
> 
> 3、如果`转发日志`里面有日志，但是没转发出去，点击小图标查看具体转发返回

1.通用设置里的开关该开的都开了，如图：
![c89ea3a774d940230ad11ece24d11c4](https://github.com/pppscn/SmsForwarder/assets/102229872/3529d976-1da0-4d11-b011-823b99f0d6cb)
2.转发规则的配置，之前就这样配置的能够收到，如图
![68dfd6d762c13c54dd7fb42a1c2615a](https://github.com/pppscn/SmsForwarder/assets/102229872/5510ee1a-7db4-4994-9858-069cc9f67255)
3.转发日志里面没有日志，只有导出的日志才有信息。

好像从3.2.0升级到3.3.0的时候，就转发不到短信了。

**Comment by pppscn** [comment]
这么神奇？卸载干净，全新安装试试

**Comment by doublez-ten** [comment]
> 这么神奇？卸载干净，全新安装试试
解决了，重装就可以了。
