### ISSUE TITLE
[Suggestion]: 快捷指令的发送短信功能无法实现 自定义，发给谁，发什么内容的问题，

### ISSUE THREAD

**Issue by tomcat927** [pppscn/SmsForwarder#441]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

目前的快捷指令的发送短信功能无法实现
自己定义，发给谁，发什么内容的问题，

——
目前的发送功能，都是固定的，一个指令被框死了发给谁，发什么内容

————

比如一个场景:我要给10086发送短信内容为108的短信（下次我可能发109到10086）

下次我可能给10010发110（也就是发给谁，发什么内容不固定）

——————

由此需求我产生了一个实现方法:

当设备接受的内容为SMS,{手机号1,手机号2},{短信内容}

触发功能:发送对应短信内容给对应手机号

————下面是目前的一些情况，

我配置了一条自动任务触发条件:
接收到任意卡短信广播当内容正则匹配^SMS,[0-9]*,

→此步骤目前可行
————
到执行动作这里，选择发送短信，就无法获取到原来短信内容，导致无法实现发给谁，发什么内容的问题。

————

最后一些思路:

短信触发条件内容，作为执行命令部分，应该能获取到，触发的短信内容

这样就涉及到一个分割短信内容问题，需要提供分割和取值的功能

【如果作者把触发的短信指令固定了，就回归当初的短信指令功能了。。。】

**Comment by pppscn** [comment]
工具是死的，但是人是活的

尝试以下操作：

1、添加`发送通道`的`手机短信`

2、`自动任务`中使用`推送通知`，然后选`手机短信`发送通道，配合`正则替换内容`

**Comment by tomcat927** [comment]
没有完全解决，

发送通道的，手机短信发送，只能设置接收号码为固定值/接收一个变量:{{FROM}}，来源号码


无法满足通过短信指令实现自定义发给谁的问题

**Comment by pppscn** [comment]
覆盖安装 `每周构建版` 试试

**升级操作提示：** 
- `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
-  手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by tomcat927** [comment]
构建失败了

**Comment by pppscn** [comment]
> 构建失败了 @pppscn

好了

**Comment by tomcat927** [comment]
看了附录3：自定义模板可用变量。和特别提醒，还是不太理解，

请问是，是通过正则表达式，替换{from}/{sms}对应的标签，从而实现发给谁的，发什么内容吗？


但是特别提醒部分，功能成立条件是好像是，该值是什么，才能实现替换，而不是针对短信内容

**Comment by pppscn** [comment]
假设：你自定义的短信指令格式：`SMS,{手机号1,手机号2},{短信内容123456}`

**实现方式：**

1、添加 `自动任务`，触发条件： `短信广播`

![image](https://github.com/pppscn/SmsForwarder/assets/5105854/86774b51-ac88-4676-b933-f640ee05cb49)

2、执行动作： `发送短信`

`手机号码` 填写： `10086;{{SMS###\s*SMS,\{([^}]+)\},\{([^}]+)\}\s*===$1}}`，预期结果：`10086;手机号1,手机号2`

`短信内容` 填写：`{{SMS###\s*SMS,\{([^}]+)\},\{([^}]+)\}\s*===$2}}`，预期结果：`短信内容123456`

![image](https://github.com/pppscn/SmsForwarder/assets/5105854/4de2b72c-2045-4c1d-afea-58a5dc704da0)

3、执行结果：

![image](https://github.com/pppscn/SmsForwarder/assets/5105854/7a4d09b7-a5ab-4d1e-b880-71d686ad18cf)

**Comment by pppscn** [comment]
覆盖安装 `每周构建版` 试试

**升级操作提示：** 
- `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
-  手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by tomcat927** [comment]
感谢，已经解决了。 @pppscn ，支付宝已打赏30。
