### ISSUE TITLE
[Bug]: 切换语言时，短信转发规则的自定义模板的string无法自动改变语言，导致转发内容无法获取

### ISSUE THREAD

**Issue by SkyHighR** [pppscn/SmsForwarder#443]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.3.0

### 问题描述

本人使用TelegramBot短信转发通道；匹配卡槽全部；匹配字段全部；启用自定义模板为：  
```
( 🎀ᗜ`v´ᗜ 🌸){{短信内容}}
{{接收时间}}
``` 

当App语言切换为英语时，自定义模板中的`{{短信内容}}`，`{{接收时间}}`并不会自动转变为`SMS`，`Time`  
导致无法获取短信内容，转发状态仍然成功会出现如下情况。  

![image](https://github.com/pppscn/SmsForwarder/assets/63498542/6104fa81-0ddd-4c1f-9901-864bda6aff4b)

### 复现步骤

见问题描述

### 是否必现

否（No）

### 出现问题的手机信息

红米

### 出现问题的安卓版本、系统版本

类原生，A14

**Comment by pppscn** [comment]
升级到 3.3.1 已经统一为英文标签了

覆盖安装 `每周构建版` 试试

**升级操作提示：** 
- `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
-  手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by SkyHighR** [comment]
感谢  
已解决
