### ISSUE TITLE
希望适配一下折叠屏Vivo fold3

### ISSUE THREAD

**Issue by androidcn** [pppscn/SmsForwarder#444]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

直接放大，没有利用折叠屏优势
![Screenshot_20240410_093823](https://github.com/pppscn/SmsForwarder/assets/271715/8f3b6e17-b316-4d32-8e1b-01ccb87c39bd)
![Screenshot_20240410_093825](https://github.com/pppscn/SmsForwarder/assets/271715/2cecf085-5337-4cdd-9d47-0a4879d2ec35)
![Screenshot_20240410_093827](https://github.com/pppscn/SmsForwarder/assets/271715/0bdb60b8-7c48-45d7-95cd-e002072821a2)

**Comment by pppscn** [comment]
暂不考虑，毕竟小众，不是人人家里都有矿，折叠屏手机都沦为备用机了

**Comment by androidcn** [comment]
> 暂不考虑，毕竟小众，不是人人家里都有矿，折叠屏手机都沦为备用机了

好的…
