### ISSUE TITLE
[Suggestion]: 希望增加通过自动任务更改设备名称的动作

### ISSUE THREAD

**Issue by tomcat927** [pppscn/SmsForwarder#447]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

希望可以增加增加自动任务的动作:修改设备名称

这样搭配短信指令，就能通过收到什么短信内容，实现实现更新设备名称

比如定义短信指令
SET,DEVICE NAME, pppscn的小米11

就可以修改设备名称

需求场景主要是

远程场景。

@

**Comment by pppscn** [comment]
什么情况下需要不停的切换设备名称？ 而且还要通过短信的形式？ 改一次一毛钱
