### ISSUE TITLE
[Suggestion]: 优化Telegram机器人发送通道的Wiki

### ISSUE THREAD

**Issue by SkyHighR** [pppscn/SmsForwarder#449]
### 是否有人曾提过类似的问题？

是（Yes）

### 你觉得APP有什么不足之处？

#319 [简化 tgbot 配置流程](https://github.com/pppscn/SmsForwarder/issues/319) 这个issue里谈到关于这个userID和chatID的事情。  
Telegram里面每个用户，群组都对应着一个唯一ID，很多第三方的Telegram客户端可以直接查看。 #319 里面提到的userinfobot只可以查看用户的ID，不能查看群组的ID。所以这里推荐使用get_id_bot，和这个bot私聊可以获取自己的ID，拉入群组中就可以自动获得群组的ID。  

实际上拉到群组里去推送的人比较少吧，一般大家都是建立一个bot然后给自己用于推送，所以感觉可以修改一些Wiki，如下：

### 你觉得该怎么去完善会比较好？【非必答】

- 获取自己（或群组）的ChatID，粘贴到「设置被通知人的ChatId」一栏 （方案1）
  - 在Telegram中搜索`get_id_bot`这个bot，输入/start后即可获得自己的ChatID
  - 如果想要获得群组的ChatID，只需把`get_id_bot`拉入群组中即可获得负数开头的群组ChatID
 
- 获取自己（或群组）的ChatID，粘贴到「设置被通知人的ChatId」一栏 （方案2）
  - 跟自己的机器人聊天，随便说点什么；或者创建一个群组，把机器人拉入群组，在群组里随便说点什么。
  - 然后打开这个链接 https://api.tele****.org/bot<apiToken>/getUpdates 获取（PS.注意<apiToken>整个换成你自己的）
  - ChatID 取值 result->message->chat->id (个人是纯数字；群组是负数，type：group；)

**Comment by pppscn** [comment]
感谢，已更新wiki
