### ISSUE TITLE
[Suggestion]: 希望增加蓝牙发送通道

### ISSUE THREAD

**Issue by zhuguli3005** [pppscn/SmsForwarder#450]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

希望增加蓝牙发送通道，即两台手机均安装此APP，分为发送端和接受端，当发送端有新的短信或通知时，通过蓝牙传送信息过去，如果是电话，可以弹出通话的提醒，并可以在接收端接电话。

**Comment by pppscn** [comment]
建议你买个手机品牌对应的手表更好一些

**Comment by zhuguli3005** [comment]
关键是我两台手机不同品牌，而接收端的设备已经有买一个手表了，总不能戴两个手表吧，通话那个建议可以忽略，其他的建议大佬增加

**Comment by pppscn** [comment]
**暂不考虑添加，原因如下：**

1、项目的定位是给备用机用的，SmsF只是转发器，如果只是为了接受一个文本通知，主力机还要多装一个app，个人觉得没有必要

2、目前有16种发送通道了，总有一种是主力机上能收到消息的吧，只要主力机能收到转发，app通知就能转发到你的手表上

3、17个通道的话，会孤零零的一个，多一行出来，逼死强迫症（或许这才是最重要的，以上两点可以不看了）

**Comment by ddonano** [comment]
可以增加蓝牙通道，现在很多pc都安装有蓝牙了，可以实现手机和pc互通 通过蓝牙通道
