### ISSUE TITLE
[Suggestion]: apk中的frpclib是怎么编译打包的？

### ISSUE THREAD

**Issue by CMingTseng** [pppscn/SmsForwarder#451]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

app很好

讓我可以參考一些寫法

### 你觉得该怎么去完善会比较好？【非必答】

請問一下 frpclib怎麼編譯 aar ?

不好意思

這問題跟 SmsForwarder不太相關

但是看到SmsForwarder有使用  frpclib

然後有專門改寫 https://github.com/pppscn/frpclib/tree/dev/cmd/frpclib

因為參考舊有2016的無法完成編譯
https://github.com/FrpcCluster/frpc-Android/blob/master/Compile_zh.md

想問問可否透露怎麼配置環境跟編譯 ?

謝謝

**Comment by pppscn** [comment]
直接借助 GitHub Actions 在线编译完成，具体脚本参看

https://github.com/pppscn/frpclib/blob/dev/.github/workflows/frpclib.yml
