### ISSUE TITLE
[Suggestion]: 将应用注册为短信应用

### ISSUE THREAD

**Issue by luomoxu** [pppscn/SmsForwarder#452]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

提供一条新的保活思路，把应用注册为默认短信应用，理论上就算被杀了也会在收到短信后自动唤醒应用

**Comment by holai** [comment]
臣附议

**Comment by lhndygit** [comment]
我用的OPPO R15  系统有个自带的功能，“breeno指令” 类似iPhone的快捷指令，我设置为每小时自动打开短信转发软件一次，这样就解决了保活的问题，同时还设置了一个只要来电就打开短信转发软件的自动任务，以防着急使用短信的情况，目前测试暂无问题，以供大家参考

**Comment by holai** [comment]
有源码吗，  我按照网上的说法配置成了默认短信应用， 但是只在 低版本手机 上适用，  高版本的手机注册不成功

**Comment by nuandong666** [comment]
复议，现在的保活太费电了

**Comment by miaozilong** [comment]
> 有源码吗， 我按照网上的说法配置成了默认短信应用， 但是只在 低版本手机 上适用， 高版本的手机注册不成功

大哥，如何设置的？ 我网上没找到资料呀。
