### ISSUE TITLE
[Suggestion]: 转发器强制更新？

### ISSUE THREAD

**Issue by vistal8** [pppscn/SmsForwarder#453]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

为何会强制更新？

**Comment by pppscn** [comment]
3.3.0 强制建议更新 3.3.1，主要有几个bug

**Comment by spring59** [comment]
腾讯管家 提示有病毒 咋回事

**Comment by pppscn** [comment]
> 腾讯管家 提示有病毒 咋回事

赶紧卸载保平安，去安装其他软件

100% 开源的东西

**Comment by spring59** [comment]
> > 腾讯管家 提示有病毒 咋回事
> 
> 赶紧卸载保平安，去安装其他软件
> 
> 100% 开源的东西

大佬 不要误会，我的意思是误报能不能打包的时候解决这个问题，我一直用这个软件几年了，很好用

**Comment by pppscn** [comment]
> 腾讯管家 提示有病毒 咋回事

具体查看 https://github.com/pppscn/SmsForwarder/issues/556 杀毒分析
