### ISSUE TITLE
[Bug]: 强制更新又不能自动下载安装包卡住了，这么搞不合适吧

### ISSUE THREAD

**Issue by lclalalalala** [pppscn/SmsForwarder#454]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

否（No）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

3.0

### 问题描述

强制更新无法安装

### 复现步骤

强制更新无法安装

### 是否必现

是（Yes）

### 出现问题的手机信息

MI 6

### 出现问题的安卓版本、系统版本

Android 12

**Comment by pppscn** [comment]
看 https://github.com/pppscn/SmsForwarder/issues/453
