### ISSUE TITLE
[Suggestion]: 转发通知时是否可以加入通知标题

### ISSUE THREAD

**Issue by zeplee** [pppscn/SmsForwarder#455]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

转发通知时是否可以加入通知标题呢，目前我只发现有通知内容，比如转发邮箱通知，绑定多个邮箱时，无法知道是哪个邮箱发来的消息

**Comment by zeplee** [comment]
![e44f321bce252004554dcdafce5c34cb](https://github.com/pppscn/SmsForwarder/assets/17584472/b0ab1470-8523-4779-8a19-2f80c501d3bc)
![WX20240426-111517](https://github.com/pppscn/SmsForwarder/assets/17584472/53cd4ad1-3bf0-4bf9-be1f-e221116dbdda)

**Comment by pppscn** [comment]
`{{TITLE}}`

看wiki：[附录3：自定义模板可用变量](https://github.com/pppscn/SmsForwarder/wiki/%E9%99%84%E5%BD%953%EF%BC%9A%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A8%A1%E6%9D%BF%E5%8F%AF%E7%94%A8%E5%8F%98%E9%87%8F)

**Comment by zeplee** [comment]
太棒了
