### ISSUE TITLE
[Suggestion]: 添加对bark其他服务器网址的支持

### ISSUE THREAD

**Issue by yuzhuoxin** [pppscn/SmsForwarder#457]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

目前的版本只能使用bark最基础的地址，要不要考虑一下添加对bark其他地址的支持从而开发出更多的新玩法呢？
例子:添加对bark”copy test”的支持，搭配合适的自定义模板和相应规则就可以实现验证码转发加长按复制了

**Comment by pppscn** [comment]
什么是 `对bark其他服务器网址的支持` ?

现在不就允许填写自定义服务器地址吗？

**Comment by yuzhuoxin** [comment]
我指的是bark上其他类型的url，比如https://api.day.app/key/推送标题    
或者https://api.day.app/key/CopyTest?copy=test
之类的都不行，相当于“key/”后面不能有内容

**Comment by pppscn** [comment]
覆盖安装 `每周构建版` 试试

**升级操作提示：** 
- `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
-  手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml
