### ISSUE TITLE
[Bug]: 自动任务监控电量-重复发送bark通知

### ISSUE THREAD

**Issue by ixieyu** [pppscn/SmsForwarder#458]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

否（No）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.3.1.240427

### 问题描述

自动任务监控电池状态时，当插入充电器后重复发送4条bark通知；当拔掉充电器后重复发送两条bark通知

### 复现步骤

反复插拔充电器。

### 是否必现

是（Yes）

### 出现问题的手机信息

小米8

### 出现问题的安卓版本、系统版本

MIUI12

### 提供截图或视频

![photo_2024-04-28_21-40-43](https://github.com/pppscn/SmsForwarder/assets/44598469/354081bd-4748-4e50-bbf4-281bb6c0379e)

[log_2024-04-28 (3).txt](https://github.com/pppscn/SmsForwarder/files/15142289/log_2024-04-28.3.txt)

**Comment by pppscn** [comment]
覆盖安装 `每周构建版` 试试，这样修改只能保证`inputData`一样时只会调用一次`BatteryWorker`

**升级操作提示：** 
- `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
-  手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by pppscn** [comment]
但是插上充电时，如果充电器设置的是`不限`，由于此时系统会推送两次广播（充电器改变），这个除非你指定`充电器`

![微信截图_20240429115529](https://github.com/pppscn/SmsForwarder/assets/5105854/cfadd99f-52d1-403a-85fa-6e8d7e30791a)
