### ISSUE TITLE
大佬方便建个微信群？

### ISSUE THREAD

**Issue by PonKing66** [pppscn/SmsForwarder#46]
企业微信群都可以。上班摸鱼都方便。

**Comment by PonKing66** [comment]
> 企业微信群都可以。上班摸鱼都方便。

不经常上QQ

**Comment by pppscn** [comment]
![企业微信群](https://user-images.githubusercontent.com/5105854/135799697-cd8d02fd-08d5-40c7-aaf3-5a95f1528561.png)

刚建的群，估计没人陪你划水

**Comment by shawine** [comment]
> ![企业微信群](https://user-images.githubusercontent.com/5105854/135799697-cd8d02fd-08d5-40c7-aaf3-5a95f1528561.png)
> 
> 刚建的群，估计没人陪你划水

群进不了了

**Comment by shenwenbin0227** [comment]
再来更新下 @pppscn

**Comment by pppscn** [comment]
> 再来更新下 @pppscn

国内群已经全部解散，加入 TG 群组吧 https://t.me/+QBZgnL_fxYM0NjE9
