### ISSUE TITLE
[Bug]: 转发通知内容不齐

### ISSUE THREAD

**Issue by isysc1** [pppscn/SmsForwarder#461]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

否（No）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

3.3.1

### 问题描述

机型：oppoR11
转发渠道：钉钉
转发规则：钉钉

实际信息内容：测试看见的看我姐夫普京俄外婆佛前我饿姐夫那我去染发工具；wrqg
弹窗通知：测试看见
其实转发过去后通知也只有测试看见

### 复现步骤

oppoR11 直接测试即可

### 是否必现

否（No）

### 出现问题的手机信息

oppo r11

### 出现问题的安卓版本、系统版本

安卓 8.1

### 提供截图或视频

无

### 提供报错堆栈【请提供logcat抓取的日志，参考： https://blog.csdn.net/m0_64776928/article/details/126005119 】

无

### 提供解决方案

无

**Comment by pppscn** [comment]
通知栏能看到什么（文本）只能转发什么
