### ISSUE TITLE
[help wanted]: 在线编译 --Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

### ISSUE THREAD

**Issue by leonall** [pppscn/SmsForwarder#462]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

否（No）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

v3.3.1

### 问题描述

本人是安卓的小白，跟着手册做在线编译。捣鼓了好久，一直编译不成功，终于开始编译了，但在 `build with Gradle`  出现兼容性的错误。

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

### 2. 修改 yml 文件中的 仓库引用

```
uses: actions/checkout@v4
        with:
          repository: pppscn/keystore
```
为

```
 uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
```

### 3. 点击 action，手动触发 `run workflow`

终于开始编译了，但在 `build with Gradle`  出现了报错。

![image](https://github.com/pppscn/SmsForwarder/assets/28797517/aed288a1-a830-4190-bbfa-eeb3cfbec48c)

```
> Task :app:lintVitalReportRelease
> Task :app:lintVitalRelease
> Task :app:compileReleaseArtProfile
> Task :app:shrinkReleaseRes
> Task :app:optimizeReleaseResources
> Task :app:packageRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageRelease'.
Build failed, cleanTxt not executed.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
      > SigningConfig "release" is missing required property "storeFile".
   > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
      > SigningConfig "release" is missing required property "storeFile".
   > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
      > SigningConfig "release" is missing required property "storeFile".
   > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
      > SigningConfig "release" is missing required property "storeFile".
   > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
      > SigningConfig "release" is missing required property "storeFile".

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 6m 17s

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.
47 actionable tasks: 47 executed```

### 是否必现

是（Yes）

### 出现问题的手机信息

NO

### 出现问题的安卓版本、系统版本

NO

### 提供截图或视频

_No response_

### 提供报错堆栈【请提供logcat抓取的日志，参考： https://blog.csdn.net/m0_64776928/article/details/126005119 】

_No response_

### 提供解决方案

_No response_

**Comment by pppscn** [comment]
pppscn/keystore 是证书仓库，私有的，自己弄一个改个地址，不是 fork 后的当前仓库，认真看看 Wiki

**Comment by leonall** [comment]
单独建一个私有的仓库是为了安全。我遇到的问题是 `Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0. ` 呀，`[help wanted]`

**Comment by pppscn** [comment]
认真看报错信息，都不知道你在质疑什么？所有发版都基于 GitHub Actions 的，让你建一个证书仓库，不建，我也不知道该怎么说了

Build failed, cleanTxt not executed. > Multiple task action failures occurred: > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable > SigningConfig "release" is missing required property "storeFile". > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable > SigningConfig "release" is missing required property "storeFile". > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable > SigningConfig "release" is missing required property "storeFile". > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable > SigningConfig "release" is missing required property "storeFile". > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable > SigningConfig "release" is missing required property "storeFile".

**Comment by pppscn** [comment]
https://github.com/pppscn/SmsForwarder/wiki/%E5%85%B3%E4%BA%8E%E5%AE%9A%E5%88%B6%E5%BC%80%E5%8F%91
