### ISSUE TITLE
[Bug]: 日志删除不掉

### ISSUE THREAD

**Issue by Dream935** [pppscn/SmsForwarder#463]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（yes）

### 是否已经查阅Wiki文档还未能解决的

是（yes）

### APP版本

v.3.1.240429

### 问题描述

日志右上角删除垃圾桶确定删除该分类文件删除不了需要一个一个删除

### 复现步骤

日志右上角删除垃圾桶确定删除该分类文件删除不了需要一个一个删除

### 是否必现

否（No）

### 出现问题的手机信息

小米9

### 出现问题的安卓版本、系统版本

miui12.5.6

**Comment by pppscn** [comment]
先试试搜索之后能不能删除筛选后的

**Comment by Dream935** [comment]
不好使，筛选不到信息

**Comment by pppscn** [comment]
> ![0fc7ea62c6eabf031da9329fccd30146](https://private-user-images.githubusercontent.com/83900691/327938422-e4286df6-d88f-42fd-9442-8c8bb68a329a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MzEwODAsIm5iZiI6MTcxNDgzMDc4MCwicGF0aCI6Ii84MzkwMDY5MS8zMjc5Mzg0MjItZTQyODZkZjYtZDg4Zi00MmZkLTk0NDItOGM4YmI2OGEzMjlhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDEzNTMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxYTM4N2UwNDJiMDMyMjg1NGRjMjIxZWQ3NWE2MWNjMDM2MmFhMDBiZWEzNjhmMjMxOThhNzY5YTczZjdjOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p9jVSQXFdnV9y6TsAE0YLx-7htZg4VWNGPj8CCm6lOY) 不好使，筛选不到信息

这提示都不是搜索后的

**Comment by Dream935** [comment]
![5b7ee3a8ec59a9892828f49fd6a6dd2a](https://github.com/pppscn/SmsForwarder/assets/83900691/4dbb556b-7980-4edb-b3c2-8ea88b9078ee)
![4a2f2253e9fcd92344ba30ebcbf46209](https://github.com/pppscn/SmsForwarder/assets/83900691/c8c04874-9c11-48e1-ba9a-b6477e9590ab)
第一张是搜索，第二章是结果啥都没有

**Comment by pppscn** [comment]
> ![5b7ee3a8ec59a9892828f49fd6a6dd2a](https://private-user-images.githubusercontent.com/83900691/327953581-4dbb556b-7980-4edb-b3c2-8ea88b9078ee.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MzE3OTIsIm5iZiI6MTcxNDgzMTQ5MiwicGF0aCI6Ii84MzkwMDY5MS8zMjc5NTM1ODEtNGRiYjU1NmItNzk4MC00ZWRiLWIzYzItOGVhODhiOTA3OGVlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDE0MDQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMjY3N2NlYTAyY2M2OTlkZTE4NmQ4MjU4ZTgyNzI3NDcyMjdhOTA1ZGMwYjZlMmZkNmNhM2M0YzI1MWU5NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0Z1282DSirHXrTJuP59P221bYKVH7YnWf8RjK-6BtEw) ![4a2f2253e9fcd92344ba30ebcbf46209](https://private-user-images.githubusercontent.com/83900691/327953584-c8c04874-9c11-48e1-ba9a-b6477e9590ab.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MzE3OTIsIm5iZiI6MTcxNDgzMTQ5MiwicGF0aCI6Ii84MzkwMDY5MS8zMjc5NTM1ODQtYzhjMDQ4NzQtOWMxMS00OGUxLWJhOWEtYjY0NzdlOTU5MGFiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDE0MDQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiZDc3YzM5NjM1MjdiNzUwMjM3MjM3MmQ2ZTIxYTM5ZWE0OWVjOGE2NjQzOWU5MDM2Y2Q3OWMyMzVhZWQyZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eM7y_UbpQ6O86nqSWhnooDqLTRHPBYA9dwnNa9uaTVI) 第一张是搜索，第二章是结果啥都没有

来源是 号码，你填写【短信】都没搜索到日志

**Comment by Dream935** [comment]
难道我还需要一个一个搜索在删除吗，不是一键删除所有日志吗，自从升级完这个版本就不能一键删除了上一个版本还可以

**Comment by pppscn** [comment]
是让你试验！分类清空跟筛选后删除走的两个分支

难道来源不能留空，只筛选日期吗？变通一下吧

**Comment by pppscn** [comment]
覆盖安装 `每周构建版` 试试

**升级操作提示：** 
- `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
-  手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml
