### ISSUE TITLE
[Suggestion]: 能否通过自动任务实现开机通知功能？

### ISSUE THREAD

**Issue by tomcat927** [pppscn/SmsForwarder#465]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

就是希望开机了，能推送开机通知，通过自动任务实现，是为了，满足一部分不需要这个功能的用户，不选择即可。
@

**Comment by pppscn** [comment]
目前没有监听开机事件来作为触发条件

变通一下用 网络状态 或 开屏 或 SIM卡状态 来实现

**Comment by tomcat927** [comment]
试过了，这几个都无法开机后，实现推送通知
@pppscn

**Comment by pppscn** [comment]
那就没辙了，暂不考虑
