### ISSUE TITLE
[Bug]: 设置每2小时转发一次短信--每到凌晨0点到早上8点之前 短信就是不转发  短信已经达到SmsForwarder

### ISSUE THREAD

**Issue by yangyz** [pppscn/SmsForwarder#467]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

V3.3.1.240418

### 问题描述

![image](https://github.com/pppscn/SmsForwarder/assets/6257884/831ce008-ee3d-4085-b82d-3dba33e8d062)
![image](https://github.com/pppscn/SmsForwarder/assets/6257884/c949ccaf-7f40-415a-92e4-7b084947f149)
![image](https://github.com/pppscn/SmsForwarder/assets/6257884/198f0116-676f-48a7-96dc-d2d48636e8dd)
我的SmsForwarder配置信息
![e67387540ec24cc6297cfa006061f98](https://github.com/pppscn/SmsForwarder/assets/6257884/c85fbb1c-5c80-45b6-9797-df27593cb7d6)
![3de9d4feb31c1d83cb8c93e03b5a028](https://github.com/pppscn/SmsForwarder/assets/6257884/0d5a1a0d-3ddc-4044-8aba-be75dba402cc)
![25a27a474cdb27f951263e349dcecb2](https://github.com/pppscn/SmsForwarder/assets/6257884/f6f966d0-1857-4a8a-a9a4-c0e6a76c243e)
![669a36f75e65a94993574d592bd8af6](https://github.com/pppscn/SmsForwarder/assets/6257884/f112451f-7e87-4076-803d-7b1268f8ab10)

### 复现步骤

没晚凌晨0点8点之前必现

### 是否必现

是（Yes）

### 出现问题的手机信息

Redmi 9A 

### 出现问题的安卓版本、系统版本

MUI12.0.4

**Comment by pppscn** [comment]
点开小红叉就知道为什么了

你的省电策略 晚间断网了，[参考这个](https://github.com/pppscn/SmsForwarder/wiki/%E3%80%90%E5%BF%85%E8%AF%BB%E3%80%91%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#q%E8%BD%AF%E4%BB%B6%E7%99%BD%E5%A4%A9%E5%88%B0%E6%99%9A%E4%B8%8A11%E5%B7%A6%E5%8F%B3%E8%BD%AC%E5%8F%91%E5%88%B0qq%E9%82%AE%E7%AE%B1%E9%83%BD%E6%88%90%E5%8A%9F%E4%BA%86%E4%BD%86%E6%98%AF%E6%99%9A%E4%B8%8A12%E7%82%B9%E4%B9%8B%E5%90%8E%E5%88%B0%E6%97%A9%E4%B8%8A8%E7%82%B9%E5%B7%A6%E5%8F%B3%E6%97%A0%E4%B8%80%E4%B8%AA%E6%88%90%E5%8A%9F%E5%85%A8%E9%83%A8%E5%A4%B1%E8%B4%A5%E4%BA%86%E8%BF%99%E5%8F%AF%E8%83%BD%E4%BC%9A%E6%98%AF%E4%BB%80%E4%B9%88%E9%97%AE%E9%A2%98%E5%91%80)

**Comment by pppscn** [comment]
![微信图片_20240509102610](https://github.com/pppscn/SmsForwarder/assets/5105854/9ecb01d1-d554-407c-b415-7ba1c09f4340)

去手机的设置里面排查，关掉一切所谓的省电设置
