### ISSUE TITLE
[Bug]: 天眼查这个号码1068353304500004发来的验证码无法自动转发，其他的转发都没问题

### ISSUE THREAD

**Issue by c26411** [pppscn/SmsForwarder#468]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.3.1.040418

### 问题描述

天眼查这个号码1068353304500004发来的验证码无法自动转发，用应用通知的方式也不转发，就像是根本没有识别到收到了1068353304500004发来的短信，其他的转发都没问题

### 复现步骤

移动号码接收天眼查登录验证码短信，只要是这个号码发来的1068353304500004，都不转发

### 是否必现

是（Yes）

### 出现问题的手机信息

Redmi Note9 

### 出现问题的安卓版本、系统版本

miui12.5.9

**Comment by pppscn** [comment]
关闭MIUI免费网络短信，[参考这个](https://github.com/pppscn/SmsForwarder/wiki/%E3%80%90%E5%BF%85%E8%AF%BB%E3%80%91%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#q%E5%B0%8F%E7%B1%B3%E7%BA%A2%E7%B1%B3%E6%89%8B%E6%9C%BA%E4%B8%BA%E4%BB%80%E4%B9%88%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9nft%E6%95%B0%E5%AD%97%E8%97%8F%E5%93%81%E4%B9%8B%E7%B1%BBapp%E7%9A%84%E9%80%9A%E7%9F%A5%E7%B1%BB%E7%9F%AD%E4%BF%A1%E7%BB%8F%E5%B8%B8%E6%80%A7%E8%BD%AC%E5%8F%91%E4%B8%8D%E4%BA%86)

**Comment by c26411** [comment]
有效，谢谢
