### ISSUE TITLE
[suggestion]: 应用通知的转发规则中, 可否简单的在"不包含"的匹配规则中, 设置多个可能的匹配值, 来实现黑名单的效果. 

### ISSUE THREAD

**Issue by rsyqvthv** [pppscn/SmsForwarder#470]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

当前"不包含"匹配规则中, 只能填写一个关键词. 
实际效果是只能屏蔽某个app的转发. 

但如果想屏蔽多个app, 就要另找其他方法. 

### 你觉得该怎么去完善会比较好？【非必答】

希望能允许简单的输入多个关键词, 

比如, 
每行的输入作为一个排查关键词,
可以输入多行建立一个排查列表.
配合"不包含"的规则, 就可以实现比较直观的做一个黑名单效果.

在这个名单中的app就不会被转发.

而不用使用其他复杂的方法(正则, 另加规则等)

当然此功能也适用于其他的匹配规则, 我仅从自己的需要, 以"不包含"做例子. 

希望采纳.

**Comment by pppscn** [comment]
看wiki  [附录5：转发规则之多重规则](https://github.com/pppscn/SmsForwarder/wiki/%E9%99%84%E5%BD%955%EF%BC%9A%E8%BD%AC%E5%8F%91%E8%A7%84%E5%88%99%E4%B9%8B%E5%A4%9A%E9%87%8D%E8%A7%84%E5%88%99)

**Comment by rsyqvthv** [comment]
感谢回复, 您提到的两个连接我都仔细看过. 

我现在就是使用正则, 但稍微显得复杂一些. 
而使用多重规则显得有些重, 可能适合逻辑更加复杂的场景. 

我之所以建议可以在"匹配值"中用多行的方式设定多个值, 
就是为了能简化一下这个(也许是)比较常用的匹配模式,
同时也更加直观一些. 

不知道实现起来是不是很复杂,
都由您定夺. 

我很喜欢这个工具, 
感谢你的创作.

**Comment by pppscn** [comment]
> 感谢回复, 您提到的两个连接我都仔细看过.
> 
> 我现在就是使用正则, 但稍微显得复杂一些. 而使用多重规则显得有些重, 可能适合逻辑更加复杂的场景.
> 
> 我之所以建议可以在"匹配值"中用多行的方式设定多个值, 就是为了能简化一下这个(也许是)比较常用的匹配模式, 同时也更加直观一些.
> 
> 不知道实现起来是不是很复杂, 都由您定夺.
> 
> 我很喜欢这个工具, 感谢你的创作.

多个值是 `且` 还是 `或` 的关系呢？ 允许多个值之后还要让使用者来选这个，不然无论我选哪一个  都会造成异议吧

**Comment by rsyqvthv** [comment]
是的, 你考虑的比较周全, 

但从某种角度来说, 这个应用场景可能不会有"且"的关系, 
因为且的部分在同一行中已经实现了
而不同行之间只是表达"或"的关系. 

这种方式在我们很多的设置场景中都是如此使用的, 
应该说, 对于用户来说是比较自然的, 
不太会存在分歧.

比如: 
在编辑hosts文件的时候, 多行之间就表达的是或的关系
在adblock中, 多行规则也是或的关系.
等等..

希望我表达清楚了我的意思.
也感谢你能认真考虑我的建议.

**Comment by pppscn** [comment]
> 是的, 你考虑的比较周全,
> 
> 但从某种角度来说, 这个应用场景可能不会有"且"的关系, 因为且的部分在同一行中已经实现了 而不同行之间只是表达"或"的关系.
> 
> 这种方式在我们很多的设置场景中都是如此使用的, 应该说, 对于用户来说是比较自然的, 不太会存在分歧.
> 
> 比如: 在编辑hosts文件的时候, 多行之间就表达的是或的关系 在adblock中, 多行规则也是或的关系. 等等..
> 
> 希望我表达清楚了我的意思. 也感谢你能认真考虑我的建议.

不对，

其实当判断词是 `包含` 时，大多数人希望的是 `或` 的关系

当判断词是 `不包含` 时，大多数人又希望的是 `且` 的关系

这样才能实现你说的 `白名单` 或 `黑名单`

---

不管怎么说，类似的问题一直有人提起，我也不厌其烦的解释，在 [wiki中备注](https://github.com/pppscn/SmsForwarder/wiki/3.%E8%BD%AC%E5%8F%91%E8%A7%84%E5%88%99)

**容我想想，或许是时候做一些改变了**

**Comment by pppscn** [comment]
转发规则 `匹配的值` 允许传入 `逻辑运算符`：`与(&&)`、`或(||)`（用于支持多个关键词）

例如：短信内容包含 `取件码` 或 `取货码` 且 `驿站` 时，`匹配模式` 选 `包含`，`匹配的值` 填写 `取件码||取货码&&驿站`

---

覆盖安装 `每周构建版` 试试

**升级操作提示：** 
- `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
-  手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by oldtree61** [comment]
小米手机仍然会被杀后台，设置该APP电池管理无限制使用，同时锁了APP，仍然被杀后台

**Comment by rsyqvthv** [comment]
> 转发规则 `匹配的值` 允许传入 `逻辑运算符`：`与(&&)`、`或(||)`（用于支持多个关键词）

感谢您的努力, 我会尝试使用weeklybuild, 感谢你给我们提供了这么好的工具.

> 小米手机仍然会被杀后台，设置该APP电池管理无限制使用，同时锁了APP，仍然被杀后台

我建议您另外开issue提问, 或者寻找已经closed的相关问题. hijack不相干的主题不会让您尽快得到答案.

**Comment by pppscn** [comment]
![image](https://github.com/pppscn/SmsForwarder/assets/5105854/63453340-8119-4ebe-8d49-cef818e405ed)

改出bug了，请重新覆盖安装 `每周构建版` 试试

**升级操作提示：** 
- `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
-  手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml
