### ISSUE TITLE
[Bug]: 使用验证码正则后 当前行内容丢失

### ISSUE THREAD

**Issue by T888T** [pppscn/SmsForwarder#471]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

否（No）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

SmsF_3.3.2.240519_200053_armeabi-v7a_release.apk

### 问题描述

![image](https://github.com/pppscn/SmsForwarder/assets/77049769/baa7b45f-d6e0-4694-8524-90234ea34911)
### 邮箱收到的
![image](https://github.com/pppscn/SmsForwarder/assets/77049769/57b7ec98-60ef-43c7-8f11-ae3f9373eb20)

### 复现步骤

使用wiki中的验证码正则
验证码链接
https://cn.account.xiaomi.com/fe/service/register?source=&region=CN&sid=mi_eshop&qs=sid%3Dmi_eshop&callback=https%3A%2F%2Forder.mi.com%2Flogin%2Fcallback&_locale=zh_CN&_uRegion=CN

### 是否必现

是（Yes）

### 出现问题的手机信息

410

### 出现问题的安卓版本、系统版本

Android 4.4

**Comment by pppscn** [comment]
替换机制： 在自定义模板的基础上进行全局替换(.replaceAll)

[wiki](https://github.com/pppscn/SmsForwarder/wiki/%E3%80%90%E5%BF%85%E8%AF%BB%E3%80%91%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#q%E5%8D%87%E7%BA%A7%E5%88%B0-230-%E7%89%88%E6%9C%AC%E4%BB%A5%E4%B8%8A%E8%BD%AC%E5%8F%91%E8%A7%84%E5%88%99%E4%B8%8A%E6%96%B0%E5%A2%9E%E7%9A%84%E6%AD%A3%E5%88%99%E6%9B%BF%E6%8D%A2%E5%86%85%E5%AE%B9%E5%8A%9F%E8%83%BD%E6%80%8E%E4%B9%88%E7%94%A8)

**Comment by T888T** [comment]
> 替换机制： 在自定义模板的基础上进行全局替换(.replaceAll)
> 
> [wiki](https://github.com/pppscn/SmsForwarder/wiki/%E3%80%90%E5%BF%85%E8%AF%BB%E3%80%91%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#q%E5%8D%87%E7%BA%A7%E5%88%B0-230-%E7%89%88%E6%9C%AC%E4%BB%A5%E4%B8%8A%E8%BD%AC%E5%8F%91%E8%A7%84%E5%88%99%E4%B8%8A%E6%96%B0%E5%A2%9E%E7%9A%84%E6%AD%A3%E5%88%99%E6%9B%BF%E6%8D%A2%E5%86%85%E5%AE%B9%E5%8A%9F%E8%83%BD%E6%80%8E%E4%B9%88%E7%94%A8)

### 使用这个的时候遇到长一点的正则他就直接返回代码了
### 比如还是这个短信验证码的
![image](https://github.com/pppscn/SmsForwarder/assets/77049769/5f623d0b-5f8d-439d-96b1-2341d6176797)
