### ISSUE TITLE
[Suggestion]: 丰富一下短信指令

### ISSUE THREAD

**Issue by shenwenbin0227** [pppscn/SmsForwarder#475]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

# 给app权限，想让收到短信指令打开&关闭 数据流量/蓝牙/位置信息/等系统级设置。数据流量开关 可能使用更多见，比如收到短信包含流量已用完后关闭数据流量
# 支持一下直接发变量，转发消息时直接发替换后的信息（可能需要处理下特殊变量或者控制替换次数），例如发 \{\{NEY_TYPE\}\}  ， 转发时直接换成  5G / WIFI

**Comment by pppscn** [comment]
暂不考虑

首先，`短信指令` 已打算废弃，放在 `自动任务·快捷指令` 中实现

其次，修改系统级设置之前做过尝试，不具备通用性（或者是我能力不够、测试设备不足）

[附录9：短信指令](https://github.com/pppscn/SmsForwarder/wiki/%E9%99%84%E5%BD%959%EF%BC%9A%E7%9F%AD%E4%BF%A1%E6%8C%87%E4%BB%A4)
