### ISSUE TITLE
[Suggestion]: 真心不建议在每次启动应用后启动软件主界面，你作为一个短信转发工具，没必要，你又不是像launch3一样的桌面软件

### ISSUE THREAD

**Issue by cnbilinyj** [pppscn/SmsForwarder#478]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

你不是桌面类软件，没必要每次启动的时候就打开软件主界面
还有，当软件被杀后台之后（因为你这款软件有的时候经常会出现严重卡顿，加上我这部手机七年前的手机了，而且我玩游戏的话运行内存占用也会比较大，会导致这款软件卡退或者无响应，无响应之后系统会提示我是否要关闭，不关闭的话，整个系统整个手机都是卡的离谱的，那我选择关闭，关闭之后等一会儿软件自启动，它又会打开主界面）
关键你说开机之后自动打开主界面我都算了，因为卡顿，我主动把他的进程给关闭了自启动之后依然会有概率打开主界面就过分了啊

**Comment by cnbilinyj** [comment]
不要搞反了，不是软件不适合我的手机，是手机不适合这款软件
这手机毕竟是七年前的手机了，好歹他是能跑得动，进程频繁被杀那都是常有的事儿，不管是什么软件都经常会出现这种情况，问题是你这个软件的定位和实际的制作结果有点问题啊
你一个信息转发的软件为什么在每次启动的时候都非要同时打开主界面呢？
你之前在Gitee上面有说过，就是你特地这么设计的，但为什么要这样设计呢

于 2024年6月1日 GMT+08:00 下午8:43:08，pppscn ***@***.***> 写道：
>你要解决的是为什么 SmsForwarder 频繁被杀
>
>也许这个软件不太适合你的机器，用的不顺心咱就换一个吧
>

农药君
***@***.***

**Comment by ShadowWaIker** [comment]
> 不要搞反了，不是软件不适合我的手机，是手机不适合这款软件 这手机毕竟是七年前的手机了，好歹他是能跑得动，进程频繁被杀那都是常有的事儿，不管是什么软件都经常会出现这种情况，问题是你这个软件的定位和实际的制作结果有点问题啊 你一个信息转发的软件为什么在每次启动的时候都非要同时打开主界面呢？ 你之前在Gitee上面有说过，就是你特地这么设计的，但为什么要这样设计呢 于 2024年6月1日 GMT+08:00 下午8:43:08，pppscn ***@***.***> 写道：
> 你要解决的是为什么 SmsForwarder 频繁被杀 也许这个软件不太适合你的机器，用的不顺心咱就换一个吧
> 农药君 ***@***.***

道理很简单，避免被拿去用于诈骗或者其他违法用途。现在这年头，隐私最不值钱，但是泄露隐私的帽子被扣上了没谁受得了。打开app就会弹出来界面，对于没能力修改的不法分子来说就不是合适的工具，对于有能力修改的不法分子来说，这个项目顶多是能拿来复制粘贴一些功能的参考。综上，一个弹界面，能避免不少“麻烦”。

**Comment by cnbilinyj** [comment]
“综上所述，让用户变得麻烦可以保护用户隐私”

于 2024年6月5日 GMT+08:00 下午1:30:26，"小马" ***@***.***> 写道：
>> 不要搞反了，不是软件不适合我的手机，是手机不适合这款软件 这手机毕竟是七年前的手机了，好歹他是能跑得动，进程频繁被杀那都是常有的事儿，不管是什么软件都经常会出现这种情况，问题是你这个软件的定位和实际的制作结果有点问题啊 你一个信息转发的软件为什么在每次启动的时候都非要同时打开主界面呢？ 你之前在Gitee上面有说过，就是你特地这么设计的，但为什么要这样设计呢 于 2024年6月1日 GMT+08:00 下午8:43:08，pppscn ***@***.***> 写道：
>> 你要解决的是为什么 SmsForwarder 频繁被杀 也许这个软件不太适合你的机器，用的不顺心咱就换一个吧
>> 农药君 ***@***.***
>
>道理很简单，避免被拿去用于诈骗或者其他违法用途。现在这年头，隐私最不值钱，但是泄露隐私的帽子被扣上了没谁受得了。打开app就会弹出来界面，对于没能力修改的不法分子来说就不是合适的工具，对于有能力修改的不法分子来说，这个项目顶多是能拿来复制粘贴一些功能的参考。综上，一个弹界面，能避免不少“麻烦”。
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/pppscn/SmsForwarder/issues/478#issuecomment-2148889472
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
农药君
***@***.***
@cnbilinyj

**Comment by ShadowWaIker** [comment]
> “综上所述，让用户变得麻烦可以保护用户隐私”
> 
> 
> 
> 于 2024年6月5日 GMT+08:00 下午1:30:26，"小马" ***@***.***> 写道：
> 
> >> 不要搞反了，不是软件不适合我的手机，是手机不适合这款软件 这手机毕竟是七年前的手机了，好歹他是能跑得动，进程频繁被杀那都是常有的事儿，不管是什么软件都经常会出现这种情况，问题是你这个软件的定位和实际的制作结果有点问题啊 你一个信息转发的软件为什么在每次启动的时候都非要同时打开主界面呢？ 你之前在Gitee上面有说过，就是你特地这么设计的，但为什么要这样设计呢 于 2024年6月1日 GMT+08:00 下午8:43:08，pppscn ***@***.***> 写道：
> 
> >> 你要解决的是为什么 SmsForwarder 频繁被杀 也许这个软件不太适合你的机器，用的不顺心咱就换一个吧
> 
> >> 农药君 ***@***.***
> 
> >
> 
> >道理很简单，避免被拿去用于诈骗或者其他违法用途。现在这年头，隐私最不值钱，但是泄露隐私的帽子被扣上了没谁受得了。打开app就会弹出来界面，对于没能力修改的不法分子来说就不是合适的工具，对于有能力修改的不法分子来说，这个项目顶多是能拿来复制粘贴一些功能的参考。综上，一个弹界面，能避免不少“麻烦”。
> 
> >
> 
> >-- 
> 
> >Reply to this email directly or view it on GitHub:
> 
> >https://github.com/pppscn/SmsForwarder/issues/478#issuecomment-2148889472
> 
> >You are receiving this because you authored the thread.
> 
> >
> 
> >Message ID: ***@***.***>
> 
> 农药君
> 
> ***@***.***
> 
> @cnbilinyj 

我没觉得能保护，但是大环境如此，不顺着来只能消失，远控类的软件就是例子，基本找不到能用的了，国外的软件国内用户登陆直接提示不可用

**Comment by cnbilinyj** [comment]
> > “综上所述，让用户变得麻烦可以保护用户隐私”
> > 于 2024年6月5日 GMT+08:00 下午1:30:26，"小马" _**@**_.***> 写道：
> > > > 不要搞反了，不是软件不适合我的手机，是手机不适合这款软件 这手机毕竟是七年前的手机了，好歹他是能跑得动，进程频繁被杀那都是常有的事儿，不管是什么软件都经常会出现这种情况，问题是你这个软件的定位和实际的制作结果有点问题啊 你一个信息转发的软件为什么在每次启动的时候都非要同时打开主界面呢？ 你之前在Gitee上面有说过，就是你特地这么设计的，但为什么要这样设计呢 于 2024年6月1日 GMT+08:00 下午8:43:08，pppscn _**@**_.***> 写道：
> > 
> > 
> > > > 你要解决的是为什么 SmsForwarder 频繁被杀 也许这个软件不太适合你的机器，用的不顺心咱就换一个吧
> > 
> > 
> > > > 农药君 _**@**_.***
> > 
> > 
> > > 
> > 
> > 
> > > 道理很简单，避免被拿去用于诈骗或者其他违法用途。现在这年头，隐私最不值钱，但是泄露隐私的帽子被扣上了没谁受得了。打开app就会弹出来界面，对于没能力修改的不法分子来说就不是合适的工具，对于有能力修改的不法分子来说，这个项目顶多是能拿来复制粘贴一些功能的参考。综上，一个弹界面，能避免不少“麻烦”。
> > 
> > 
> > > 
> > 
> > 
> > > --
> > 
> > 
> > > Reply to this email directly or view it on GitHub:
> > 
> > 
> > > [#478 (comment)](https://github.com/pppscn/SmsForwarder/issues/478#issuecomment-2148889472)
> > 
> > 
> > > You are receiving this because you authored the thread.
> > 
> > 
> > > 
> > 
> > 
> > > Message ID: _**@**_.***>
> > 
> > 
> > 农药君
> > _**@**_.***
> > @cnbilinyj
> 
> 我没觉得能保护，但是大环境如此，不顺着来只能消失，远控类的软件就是例子，基本找不到能用的了，国外的软件国内用户登陆直接提示不可用

我觉得是这样，就是如果你是用这个功能作为一个提醒的话，你弹个悬浮窗也可以啊。
另外有一点，真的，我感觉你这软件跟360似的，没有恶意软件的时候，你就跟最大的恶意软件一样。我日，我把你这软件的后台弹出界面权限给关了，然后重启或者在玩游戏的时候，因为总的运行内存占用过大，这款软件被杀后台了，等一会儿它自动启动之后它一样有能力弹出主界面，不是，我都把你后台弹出界面的权限给关了，你是怎么弹出界面来的啊？你这权限是怎么拿到的？所以我觉得如果你是为了提醒用户，不是为了保护，而是说提醒用户的话，那么你完全可以选择弹出悬浮窗，而不是弹出界面

**Comment by cnbilinyj** [comment]
还有我真正要问的是你是怎么启动的主界面？我没有给你后台弹出界面的权限啊
![Screenshot_20240607_134038](https://github.com/pppscn/SmsForwarder/assets/99505726/08f4e5d6-848c-4ae4-97b8-af3ea4d5320d)
@pppscn

**Comment by ShadowWaIker** [comment]
你关的是后台弹出界面的权限，但是你遇到的问题是后台已经被杀了，你启用保活机制重新启动了程序，现在的程序已经不是在后台了。不想让他弹出来就把第一步设置里面的保活关掉。
而且你是真轴，github 都会上，应该也会写点代码吧，代码都全给你放出来了，你哪儿用着不满意按自己想法改不就得了。
或者按作者一开始就说的“也许这个软件不太适合你的机器，用的不顺心咱就换一个吧”。
跟你掰扯也真是我犯贱，纯纯浪费时间。

**Comment by cnbilinyj** [comment]
> 你关的是后台弹出界面的权限，但是你遇到的问题是后台已经被杀了，你启用保活机制重新启动了程序，现在的程序已经不是在后台了。不想让他弹出来就把第一步设置里面的保活关掉。 而且你是真轴，github 都会上，应该也会写点代码吧，代码都全给你放出来了，你哪儿用着不满意按自己想法改不就得了。 或者按作者一开始就说的“也许这个软件不太适合你的机器，用的不顺心咱就换一个吧”。 跟你掰扯也真是我犯贱，纯纯浪费时间。

是`会写点`，不是`会写`，HTML CSS JavaScript PHP会一些，Python刚入门，其他的你给我一个现有的，我也可以勉强改一改，但是仅仅只是勉强改而已，完全按照自己的意思改，那是没那个能力，好吧
