### ISSUE TITLE
[Suggestion]: 在创建自动任务的条件“到达地点”和“离开地点”中，允许其中需要填写的任何输入框留空和焦点脱离 

### ISSUE THREAD

**Issue by cnbilinyj** [pppscn/SmsForwarder#479]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

在创建自动任务的条件`到达地点`和`离开地点`中允许其中的所有输入框留空和焦点脱离，我知道在提交的时候不能留空，但是比如说它上面我需要填写半径3m，而他默认填写的是0，这个时候正常情况下我是会把它全部删除，再填3，但是按照你的这种界面配置，那么一旦我全部删除，它就会自动填写一个1上去，这个时候我删不掉这个1，我必须首先填写3，然后再把1删除，这样子非常麻烦

### 你觉得该怎么去完善会比较好？【非必答】

所以允许其中所有输入框留空，如果可以的话，允许输入框焦点脱离（关于焦点脱离，详情可看视频）在焦点脱离后或者软键盘收起后或者按下回车后，或者点击`提交`按钮后，再进行检测，而不是当输入框内容变化时立刻进行检测，当检测到输入框内容为空时的行为可以保留原样；而检测输入框内容是否为空的时机应当更改

https://github.com/pppscn/SmsForwarder/assets/99505726/f05585ea-1f8e-454a-b6cf-8d3a04e693b4

**Comment by pppscn** [comment]
覆盖安装 `每周构建版` 试试 **（等待在线编译完成）**

**升级操作提示：** 
- `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
-  手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by cnbilinyj** [comment]
> 覆盖安装 `每周构建版` 试试 **（等待在线编译完成）**
> 
> **升级操作提示：**
> 
> * `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
> * 手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

6，Issues是下午提的，修改与构建新版本安装包以及提供更新日志是晚上完成的
