### ISSUE TITLE
[Suggestion]: 自动任务 条件 充电状态中出现不合适的文本引用

### ISSUE THREAD

**Issue by cnbilinyj** [pppscn/SmsForwarder#481]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

如题
充电状态条件的提示文本是`当剩余电量满足条件时触发`，但条件的名称是充电状态。所以引用的并不适当。在进行安装包解包后，我发现在整个资源列表文件（`resources.arsc`）中并不存在
![Screenshot_20240603_172341](https://github.com/pppscn/SmsForwarder/assets/99505726/73d14c8d-7f13-4e9a-889d-5faf458b912b)
![Screenshot_20240603_170955](https://github.com/pppscn/SmsForwarder/assets/99505726/e539975a-79c7-4c91-a469-948f4baac548)

### 你觉得该怎么去完善会比较好？【非必答】

我已知`resources.arsc`不直接存在于源码中，再通过各种渠道了解到该文件中的内容在源码中存放于`app/src/main/res/values*/*`中，再根据拆包结果得到字符串资源ID，以及字符串资源index（字符串资源索引），接着通过字符串资源索引查找出该字符串资源在源码中的位置，并将其进行更改
具体怎么完善，我已经完善好了，只需要同意fork合并请求 #480 即可

**Comment by pppscn** [comment]
感谢PR
