### ISSUE TITLE
[Suggestion]: 增加快捷指令动作组功能 增加快捷指令条件逻辑或功能 允许部分动作重复使用 

### ISSUE THREAD

**Issue by cnbilinyj** [pppscn/SmsForwarder#482]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

# 增加快捷指令动作组功能
这一点与第2点可以选一个增加，就是第1点增加了，你可以选择不增加第2点；如果你增加了第2点，你也可以选择不增加第1点。
主要是这样子的，就是有的时候我希望多种情况都可以触发同一组动作
比如说当到达a地或者到达b地都可以触发声音报警
那么现在的版本我必须创建两个快捷指令，然后条件不一致，动作相同
这样子的话，首先是对于剩余存储空间不算多的人而言，如果他需要多添加几个这样子的指令，那么占用的存储空间可能会比较大
或者我还得保存，然后复制，然后再改变条件，那么如果条件很多，尤其是需要更改的条件，那么我必须要先把所有条件全部删除，然后再重新创建新的条件
如果添加动作组功能或者添加条件逻辑或功能，那么在出现多种触发可能的情况下我可以很方便的直接添加这些触发可能（包括触发条件和触发后的条件判断）

_其实1和2你可以选择不管它，但至少做一下3，就是允许部分动作重复使用_

# 允许部分动作重复使用
这个你应该懂我啥意思。就像触发完条件之后，我希望启用a规则，停用b规则，那现在我必须将这条快捷指令复制然后修改启用a规则，停用b规则，还是刚才的说法，这个很麻烦，而且可能会占用更多的存储空间
目前的自动任务的动作中，我个人建议以下动作允许重复使用：
- 推送通知  其中的禁用时间段可以多次设置，比如当我触发事件后，如果时间段为凌晨3点到早上7点，我对发送通道td01推送一条消息，如果时间段是中午11点到下午3点，我对发送通道td02推送一条消息，那这个时候我可以重复使用，然后设置第一次的推送通知禁用时段为早上7点至次日凌晨3点，同时设置第二次的推送通知禁用时段为下午3点至次日中午11点
    
    > 另外，推送通知这个方法的名称建议是推送事件或者叫运行发送通道
- 所有通道规则等功能的启用停止，这个在我前面打的比喻中有提到过，这里就不再赘述，其中包括：
    - 启停Frpc
    - 启停HttpServer
    - 启停规则
    - 启停通道
    - 启停任务

然后我再提两点动作建议：
- 你现在能够在触发条件之后执行声音警报，这个声音警报是外放加耳机。如果可以的话，我希望可以选择`仅外放报警` `优先使用耳机报警`或者`外放加耳机同时报警`，毕竟就比如说哈，有些人手机里面没有什么比较合适的音频，就用他的默认警报声，怕社死，所以插了个耳机，结果发现尼玛用的是外放，哎妈，那可尴尬死了（我就是这类人之一，当时我恨不得在地上抠出个亿室亿厅）
- 另外你也可以再增加一个动作：震动警报，声音都有了，加个震动不过分吧，最好能加一个自定义频率，比如说我震多少秒，停多少秒循环几次；以及自定义节奏
![Screenshot_20240607_152223](https://github.com/pppscn/SmsForwarder/assets/99505726/62aafad2-c582-4eeb-a946-6a7b93483ef7)
自定义节奏灵感来源于`一条通知`APP（未在GitHub开源，开发者 @realskyrin ）

**Comment by pppscn** [comment]
暂无计划

**Comment by pppscn** [comment]
![警报提醒](https://github.com/user-attachments/assets/322d8cc6-431e-4f6d-bef2-10d8ef363a60)

> 语法：=[强振动], -[弱震动], _[不振动], 每次100ms

覆盖安装 `每周构建版` 试试 **（等待在线编译完成）**

**升级操作提示：** 
- `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
-  手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml
