### ISSUE TITLE
[Suggestion]: 主界面 通用设置 打开“发现蓝牙设备服务”时，如果蓝牙服务未开启所出现不合适的文本引用

### ISSUE THREAD

**Issue by cnbilinyj** [pppscn/SmsForwarder#484]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

如题
`主界面->通用设置->打开“发现蓝牙设备服务”`时，如果蓝牙服务未开启时的提示是`位置服务未开启，请先前往系统设置中开启！`，但开关的名称是`发现蓝牙设备服务`。所以引用的并不适当。在进行安装包解包后，我发现在整个资源列表文件（`resources.arsc`）中并不存在正确的资源文本
![Screenshot_20240610_220914](https://github.com/pppscn/SmsForwarder/assets/99505726/c0748b38-6f19-498f-9724-f7f1bc6d212f)
![Screenshot_20240610_220907](https://github.com/pppscn/SmsForwarder/assets/99505726/7c03eb6b-f37f-4923-a4b9-82375b6ffbbb)
![Screenshot_20240610_220859](https://github.com/pppscn/SmsForwarder/assets/99505726/da74db22-9029-4d88-a818-ed94102317c7)

### 你觉得该怎么去完善会比较好？【非必答】

我已知`resources.arsc`不直接存在于源码中，再通过各种渠道了解到该文件中的内容在源码中存放于`app/src/main/res/values*/*`中，再根据拆包结果得到字符串资源ID，以及字符串资源index（字符串资源索引），接着通过字符串资源索引查找出该字符串资源在源码中的位置，并将其进行更改
具体怎么完善，我已经完善好了，只需要同意fork合并请求 #483 即可
6月3日的提交项无需合并，那是之前没有从源项目合并到分支

**Comment by pppscn** [comment]
感谢PR，已合并
