### ISSUE TITLE
[Suggestion]: 应用转发顶部包名动态定义为消息来源

### ISSUE THREAD

**Issue by lzqoscar** [pppscn/SmsForwarder#485]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

转发消息模板最开头一定有包名（package_name）

### 你觉得该怎么去完善会比较好？【非必答】

以微信为例，请问是否可以实现将固定出现的包名替换为发送者的名字（TITLE），不同的app我已经使用不同的图标区分，这样更加符合手表逻辑，感谢回答！

**Comment by cnbilinyj** [comment]
你可以学习一下怎么使用正则替换
![Screenshot_20240613_175549](https://github.com/pppscn/SmsForwarder/assets/99505726/1bd048c0-6095-4558-aa8c-822aa4d1774b)

**Comment by pppscn** [comment]
这个？

[Q：APP通知转发，怎么显示APP应用名称，而不是APP包名？](https://github.com/pppscn/SmsForwarder/wiki/%E3%80%90%E5%BF%85%E8%AF%BB%E3%80%91%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#qapp%E9%80%9A%E7%9F%A5%E8%BD%AC%E5%8F%91%E6%80%8E%E4%B9%88%E6%98%BE%E7%A4%BAapp%E5%BA%94%E7%94%A8%E5%90%8D%E7%A7%B0%E8%80%8C%E4%B8%8D%E6%98%AFapp%E5%8C%85%E5%90%8D)

**Comment by lzqoscar** [comment]
> 你可以学习一下怎么使用正则替换
> ![Screenshot_20240613_175549](https://github.com/pppscn/SmsForwarder/assets/99505726/1bd048c0-6095-4558-aa8c-822aa4d1774b)
> 

这个地方怎么可以传入title信息呢比如我这里想要把mm这个包名使用tiltle进行替换 实际上是不可行的。同时我注意到新版支持模板中更换不同的标签中的信息，但是我的诉求是通过其他标签内容修改另一个标签(使用tilte覆盖package-Name)。请问在这里是如何实现呢![Screenshot_2024-06-14-00-27-03-755_com.idormy.sms.forwarder.jpg](https://github.com/pppscn/SmsForwarder/assets/50994301/a1dfef87-48d8-4222-92d2-03ee2db3178b)

**Comment by lzqoscar** [comment]
实际上我就是想实现{{package_name###[ ]===TITLTE}}这种意思的功能，但是我这么设置的时候显示和我想要的意思不太一样

**Comment by pppscn** [comment]
没有多大意义，反正增加复杂度，容易出错，暂不考虑
