### ISSUE TITLE
[Bug]: realme手机，系统是realme UI 3.0，权限配置正常，无法转发短信

### ISSUE THREAD

**Issue by wingser** [pppscn/SmsForwarder#487]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

否（No）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

最新版本

### 问题描述

realme手机，系统是realme UI 3.0，权限配置正常，无法转发短信，看起来是没有读到系统短信。验证码保护已经关闭。用了好久这个软件了，该设置的我都会，就是关了realme手机就不行了。

### 复现步骤

必现问题

### 是否必现

是（Yes）

### 出现问题的手机信息

realme gt neo

### 出现问题的安卓版本、系统版本

Android 12

**Comment by pppscn** [comment]
实在接收不到短信广播，就换成转发APP通知的形式，再不行就卸载吧
