### ISSUE TITLE
[Suggestion]: 是否能增加通话转发功能？

### ISSUE THREAD

**Issue by xmhlg** [pppscn/SmsForwarder#489]
### 是否有人曾提过类似的问题？

是（Yes）

### 你觉得APP有什么不足之处？

这个功能我看记录22年就有人提出，能不能更新？这个出国的时候很实用。

**Comment by ihipop** [comment]
很刑

**Comment by pppscn** [comment]
不会有这样的功能，你自己去找 GOIP 设备吧

踩缝纫机警告
