### ISSUE TITLE
Realme UI2.0无法在后台自动发送短信

### ISSUE THREAD

**Issue by venpong** [pppscn/SmsForwarder#49]
机型:Realme Q2
系统版本:Realme UI V2.0,基于Android 11
描述:
应用短信权限配置正常，程序无法在后台自动发送短信，在app页面上测试短信转发时，系统会弹出发送短信确认框，需要手动点击确定才可以发送，可是当系统待机时无法自动发送，之前用Tasker软件时也是相同的问题，向Realme官方咨询后反馈为第三方软件未兼容系统权限。。。不知道作者是否有解决办法。
![image](https://user-images.githubusercontent.com/14030911/137625358-9d37d01f-8c19-4854-ae03-a09ddd208769.png)

**Comment by wyywang** [comment]
如果有root的话，把他用scene之类的转换成系统软件就可以了，实操。

**Comment by wyywang** [comment]
> 好的，谢谢，那我就先用Bark推送了。

如果有root的话，用scene转换成系统软件就可以正常发送了，测试过，我是绿芽，同系统搜到你的issus。

**Comment by wingser** [comment]
我也是real me的系统，现在已经是3.0的版本了，没有办法转发短信，你们还有办法解决吗？还是说需要把手机版本降级到2.0才可以？
