### ISSUE TITLE
[Suggestion]: 失败重试的有效计次应该从有有效网络连接开始计算

### ISSUE THREAD

**Issue by ihipop** [pppscn/SmsForwarder#490]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

有些时候如果设备收到以后暂时没有网络，（比如家里宽带断网（**但是有WIFI**）或者在外面流量不够暂时关闭了数据链接），程序还是会正常进行重试，一直到计次超过设定的数值为止，目前最多10次，每次递增间隔是一个数列 ,假设全部调整到最大 ，那么经过 1小时还是没有恢复网络连接，则此消息永远不会自动被送达

### 你觉得该怎么去完善会比较好？【非必答】

失败重试的有效计次应该从有有效网络连接开始计算
有效网络链接的判断可以访问 **generate 204** 或者 **类captive portal检测服务 (generate 200)**， 因为有WIFI也不代表有有效网络链接
国内可用的  **generate 204** 服务有
- ~小米: http://connect.rom.miui.com/generate_204~ 已下线
- 华为: http://connectivitycheck.platform.hicloud.com/generate_204
- 荣耀: http://connectivitycheck.platform.hihonorcloud.com/generate_204
- OPPO: 
    - http://conn1.oppomobile.com/generate_204 
    - http://conn2.oppomobile.com/generate_204
- 高通中国: http://www.qualcomm.cn/generate_204
- VIVO: http://wifi.vivo.com.cn/generate_204

**类captive portal检测服务 (generate 200)**
- 苹果：
    - http://captive.apple.com/
    - http://captive.apple.com/hotspotdetect.html
    - http://www.apple.com/library/test/success.html
- 微软: http://www.msftconnecttest.com/connecttest.txt

建议：
- 自定义一个设置项目，默认可以从上面选一个或者输入一个用户自定义URL，**当 _每次_ 触发转发失败后**，如果设置项的URL响应 `200` 或者 `204` 即认为当然网络正常，**本次转发失败**计入失败重试的有效计次
- 或者，干脆，粗暴的做法，恢复以前那种 失败重试几次的输入方法，让用户能够输入一个足够大的重试时间（个人认为累计的重试周期至少能覆盖24小时），这么长网络还没恢复也不是正常可控制的，只能让他算失败了。

**Comment by cnbilinyj** [comment]
个人觉得可以ping而不是一定要使用204网站
比如说，首先ping目标网站，如果失败则尝试ping百度(`www.baidu.com`)，腾讯(`www.tencent.com`, `www.qq.com`)，360(`www.360.cn`, `www.360.com`, `www.hao123.com`, `www.soso.com`)，知乎(`www.zhihu.com`)，淘宝(`www.taobao.com`)，搜狐(`www.sohu.com`)，京东(`www.jd.com`, `www.jd.hk`, `www.jdpay.com`)，阿里巴巴(`www.alipay.com`, `www.aliyun.com`, `www.aliexpress.com`, `www.alibaba.com`, `www.alibaba-inc.com`)

> ***以上举例网址有18个***

若其中有成功ping响应包，或者成功率为60%以上，或者70%或者75%或者80%或者100%以上，需要开发者在以上条件中选择至多一个作为认为当前网络是有效连接的判断条件，当达到该条件时，则认为具有有效连接。
换句话说，需要开发者在以下条件中选择至多一个作为有效连接的判断条件：
1. 至少ping成功1次
2. 至少ping成功60%以上的网站（至少ping成功11次）
3. 至少ping成功70%以上的网站（至少ping成功13次）
4. 至少ping成功75%以上的网站（至少ping成功14次）
5. 至少ping成功80%以上的网站（至少ping成功15次）
6. 必须全部ping成功（必须18个网站全部ping成功）

**Comment by cnbilinyj** [comment]
个人觉得可以ping而不是一定要使用204网站
比如说，首先ping目标网站，如果失败则尝试ping百度(`www.baidu.com`)，腾讯(`www.tencent.com`, `www.qq.com`)，360(`www.360.cn`, `www.360.com`, `www.hao123.com`, `www.soso.com`)，知乎(`www.zhihu.com`)，淘宝(`www.taobao.com`)，搜狐(`www.sohu.com`)，京东(`www.jd.com`, `www.jd.hk`, `www.jdpay.com`)，阿里巴巴(`www.alipay.com`, `www.aliyun.com`, `www.aliexpress.com`, `www.alibaba.com`, `www.alibaba-inc.com`)

> ***以上举例网址有18个***

若其中有成功ping响应包，或者成功率为60%以上，或者70%或者75%或者80%或者100%以上，需要开发者在以上条件中选择至多一个作为认为当前网络是有效连接的判断条件，当达到该条件时，则认为具有有效连接。
换句话说，需要开发者在以下条件中选择至多一个作为有效连接的候选条件判断条件：
1. 至少ping成功1次
2. 至少ping成功60%以上的网站（至少ping成功11次）
3. 至少ping成功70%以上的网站（至少ping成功13次）
4. 至少ping成功75%以上的网站（至少ping成功14次）
5. 至少ping成功80%以上的网站（至少ping成功15次）
6. 必须全部ping成功（必须18个网站全部ping成功）

候选条件的使用前提为主条件失败，主条件是ping目标网站成功
如果不成功才使用候选条件，主条件和候选条件成功任意一个则认为有效网络连接
比如说ping目标网站成功了，那就直接认为有效网络连接，如果失败则对后面的网站进行ping，如果达到开发者所选择的候选条件（比如说开发者选择的是至少ping成功70%以上的网站。那么根据我的举例，候选条件判断时，应当至少ping成功13次，则认为是候选条件判断成功，也就认为当前网络是有效网络连接，如果ping目标网站成功，则候选条件无需进行判断，直接认为当前网络是有效网络连接，如果目标网站失败，也没有达到候选条件，则认为当前网络是无效网络连接）

**Comment by ihipop** [comment]
> 个人觉得可以ping而不是一定要使用204网站 比如说，首先ping目标网站，如果失败则尝试ping百度(`www.baidu.com`)，腾讯(`www.tencent.com`, `www.qq.com`)，360(`www.360.cn`, `www.360.com`, `www.hao123.com`, `www.soso.com`)，知乎(`www.zhihu.com`)，淘宝(`www.taobao.com`)，搜狐(`www.sohu.com`)，京东(`www.jd.com`, `www.jd.hk`, `www.jdpay.com`)，阿里巴巴(`www.alipay.com`, `www.aliyun.com`, `www.aliexpress.com`, `www.alibaba.com`, `www.alibaba-inc.com`)
> 
> > _**以上举例网址有18个**_
> 
> 若其中有成功ping响应包，或者成功率为60%以上，或者70%或者75%或者80%或者100%以上，需要开发者在以上条件中选择至多一个作为认为当前网络是有效连接的判断条件，当达到该条件时，则认为具有有效连接。 换句话说，需要开发者在以下条件中选择至多一个作为有效连接的候选条件判断条件：
> 
> 1. 至少ping成功1次
> 2. 至少ping成功60%以上的网站（至少ping成功11次）
> 3. 至少ping成功70%以上的网站（至少ping成功13次）
> 4. 至少ping成功75%以上的网站（至少ping成功14次）
> 5. 至少ping成功80%以上的网站（至少ping成功15次）
> 6. 必须全部ping成功（必须18个网站全部ping成功）
> 
> 候选条件的使用前提为主条件失败，主条件是ping目标网站成功 如果不成功才使用候选条件，主条件和候选条件成功任意一个则认为有效网络连接 比如说ping目标网站成功了，那就直接认为有效网络连接，如果失败则对后面的网站进行ping，如果达到开发者所选择的候选条件（比如说开发者选择的是至少ping成功70%以上的网站。那么根据我的举例，候选条件判断时，应当至少ping成功13次，则认为是候选条件判断成功，也就认为当前网络是有效网络连接，如果ping目标网站成功，则候选条件无需进行判断，直接认为当前网络是有效网络连接，如果目标网站失败，也没有达到候选条件，则认为当前网络是无效网络连接）



我认为不应该使用ping，一些使用 captive portal 认证的内网，ping通或者访问通不代表可以上网。这也是事先约定一些相应码或者响应内容的意义。而且你一次ping那么多网站，极大增加复杂度，我们所需要的其实只要一个被选中的配置项正常响应预期的内容即可。

**Comment by cnbilinyj** [comment]
说的也是，或者用其他的网站也可以

于 2024年7月28日 GMT+08:00 下午8:36:58，ihipop ***@***.***> 写道：

**Comment by cnbilinyj** [comment]
说的也是，或者也可以ping目标网站，失败之后再使用204判断网络是否可用，如果网络可用但ping不通，说明网站域名异常。ping得通代表网络对于目标网站可用，这种也认为可用

于 2024年7月28日 GMT+08:00 下午8:36:58，ihipop ***@***.***> 写道：

**Comment by cnbilinyj** [comment]
说的也是，或者也可以ping目标网站，失败之后再使用204判断网络是否可用，如果网络可用但ping不通，说明网站域名异常。ping得通代表网络对于目标网站可用，这种也应当认为网络可用

于 2024年7月28日 GMT+08:00 下午8:36:58，ihipop ***@***.***> 写道：

**Comment by pppscn** [comment]
暂不考虑，还是先提升网络环境稳定性更靠谱些

**Comment by ihipop** [comment]
> 暂不考虑，还是先提升网络环境稳定性更靠谱些

是否考虑恢复以前那种 失败重试几次的输入方法，让用户能够输入一个足够大的重试次数,现在拉杆方式的可调节范围太短了
