### ISSUE TITLE
[Suggestion]: 消息通道消息体是否为json的判断建议

### ISSUE THREAD

**Issue by Jesn** [pppscn/SmsForwarder#491]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

```
{
    "from": "[from]",
    "app_name": "[app_name]",
    "content": "[content]",
    "msg": "[msg]",
    "receive_time": "[receive_time]"
}
```

请求体是否为json的判断能改成 Content-Type=applicaton/json ?
例如我想通过Webhook发送这样一个json请求体到我的服务端进行处理，发现在 通道模板里设置的话APP_Name 获取不到直，在转发规则里设置，发现是作为Content的值传递的，不符合我上面的要求。

如果在消息通道里面把是否为json的请求判断改为 Content-Type ，那么就可以直接把转发规则里面的内容作为JSON请求体

刚刚接触，如有不正确的请指教

**Comment by pppscn** [comment]
不要自创标签，参看 [webParams 可用标签列表](https://github.com/pppscn/SmsForwarder/wiki/%E9%99%84%E5%BD%951%EF%BC%9A%E5%90%91webhook%E5%8F%91%E9%80%81post-get-put-patch%E8%AF%B7%E6%B1%82#4webparams-%E5%8F%AF%E7%94%A8%E6%A0%87%E7%AD%BE%E5%88%97%E8%A1%A8%E6%B3%A8%E6%84%8Fv243-%E9%80%82%E7%94%A8)

`[content]` `[msg]` 是 `自定义模板` 替换后的结果

[附录3：自定义模板可用变量](https://github.com/pppscn/SmsForwarder/wiki/%E9%99%84%E5%BD%953%EF%BC%9A%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A8%A1%E6%9D%BF%E5%8F%AF%E7%94%A8%E5%8F%98%E9%87%8F)

**Comment by pppscn** [comment]
通过`Content-Type=applicaton/json`指定请求体为`json`格式

覆盖安装 `每周构建版` 试试 **（等待在线编译完成）**

**升级操作提示：** 
- `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
-  手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml
