### ISSUE TITLE
[Suggestion]: 小红书APP的评论消息无法通知，但点赞收藏通知却可以

### ISSUE THREAD

**Issue by Looper0331** [pppscn/SmsForwarder#492]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

不确定是SmsForwarder的问题，还是小红书APP本身的机制问题。用红米note8和三星S8都试过了，点赞和收藏消息可以正常通知，但评论不会产生通知，是手机本身不会触发通知。不知道为啥

**Comment by pppscn** [comment]
APP通知转发，只能转发通知栏看到的内容（文本）

**Comment by Looper0331** [comment]
> APP通知转发，只能转发通知栏看到的内容（文本）

嗯嗯，明白的。感觉是小红书app的问题，测试了好几个账号都一样。。
