### ISSUE TITLE
[Bug]: 免打扰时段跨天不成功bug

### ISSUE THREAD

**Issue by danielthb** [pppscn/SmsForwarder#493]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.3.1.240418

### 问题描述

![IMG_2471](https://github.com/pppscn/SmsForwarder/assets/64071813/9a0a229e-596f-42a6-9387-05dd4e9d4afc)
免打扰时段设定的跨天确定是有bug了。按照设定，应该是第一天的18:30到第二天早上的09:30都是免打扰时段，跨天了。
但是只有18：30-0:00是正常免打扰的；00:00-09:30免打扰失效，依然会收到转发通知。

无法跨天免打扰

### 复现步骤

设定免到扰时段为开始时间大于结束时间（跨天），就可复现

### 是否必现

是（Yes）

### 出现问题的手机信息

Win10 蓝叠 模拟器

### 出现问题的安卓版本、系统版本

Android 12

### 提供截图或视频

![IMG_2471](https://github.com/pppscn/SmsForwarder/assets/64071813/20916a1f-71aa-4969-8405-56f03c6d6087)

**Comment by pppscn** [comment]
本次提交未经过测试，请帮忙仔细测试一遍，包括 `转发规则`、`通用设置` 的两处免打扰设置

覆盖安装 `每周构建版` 试试 **（等待在线编译完成）**

**升级操作提示：** 
- `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
-  手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml
