### ISSUE TITLE
[Suggestion]: 增加快捷指令重启手机功能

### ISSUE THREAD

**Issue by Saxon-Sun** [pppscn/SmsForwarder#494]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

老手机老版本安卓开机久了会变卡，希望可以增加一个重启的动作，这样就能通过添加定时条件执行重启手机动作了

**Comment by gs666** [comment]
很多安卓手机自带定时开关机功能吧。

**Comment by Saxon-Sun** [comment]
> 很多安卓手机自带定时开关机功能吧。

随身WiFi这类的老系统就不行呀  用久了就卡死了

**Comment by pppscn** [comment]
[附录9：短信指令#3试验性重启或关闭手机](https://github.com/pppscn/SmsForwarder/wiki/%E9%99%84%E5%BD%959%EF%BC%9A%E7%9F%AD%E4%BF%A1%E6%8C%87%E4%BB%A4#3%E8%AF%95%E9%AA%8C%E6%80%A7%E9%87%8D%E5%90%AF%E6%88%96%E5%85%B3%E9%97%AD%E6%89%8B%E6%9C%BA)

仅部分手机系统支持，所以不考虑添加
