### ISSUE TITLE
[Bug]: 应用-通知转发规则-匹配模式-匹配的值。app列表下拉框有些手机没有。

### ISSUE THREAD

**Issue by pzistart** [pppscn/SmsForwarder#496]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

v3.2.0

### 问题描述

![image](https://github.com/pppscn/SmsForwarder/assets/91709633/092a3af7-8745-446c-b768-4c8a02338425)

[Bug]: 应用-通知转发规则-匹配模式-匹配的值。app列表下拉框有些手机没有。

### 复现步骤

[Bug]: 应用-通知转发规则-匹配模式-匹配的值。app列表下拉框有些手机没有。

### 是否必现

否（No）

### 出现问题的手机信息

红米k70

### 出现问题的安卓版本、系统版本

hyperOS

### 提供截图或视频

![image](https://github.com/pppscn/SmsForwarder/assets/91709633/e492cd17-17d9-4e7f-93c0-38a9f824d205)

**Comment by pppscn** [comment]
`通用设置` 中开启 `启动时异步获取已安装App列表`

**Comment by pzistart** [comment]
谢谢大佬
