### ISSUE TITLE
[Suggestion]:建议在自动任务的动作里添加“启动APP”功能 

### ISSUE THREAD

**Issue by stoncn** [pppscn/SmsForwarder#497]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

APP日益完善。这个功能是起个锦上添花的作用。

### 你觉得该怎么去完善会比较好？【非必答】

想实现自动充电、断电功能，思路是将手机连接到可由APP控制的开关上，当sf检测到电量低于报警值，则启动一个可选app（比如向日葵远程控制app，或博联智能app）。app启动后，由类似李跳跳、轻启动等app检测到并自动点击，打开电源开关实现充电。充满后类似操作关闭。后一部分自动操作我已经在鸿蒙/安卓系统实验成功，回到sf设定动作时发现没有启动APP这个选项。

**Comment by stoncn** [comment]
看到奇思妙想里有一个ios系统通过siri实现类似功能的相法。在安卓系统里能实现最好了。华为的智慧生活自动场景里要实现也需要一个触发开关，希望sf能提供这个触发器。

**Comment by btzee** [comment]
支持！~ 目前我也有类似需求，就是备用机始终放在家里只用作接收短信转发用，然后如果长时间插着充电电池会鼓包，不同手机的电池效率又不同充电时间各不一样。如果能由手机自主控制智能插座的开启与关闭的话会更合适。

**Comment by Leo-lithe** [comment]
> 支持！~ 目前我也有类似需求，就是备用机始终放在家里只用作接收短信转发用，然后如果长时间插着充电电池会鼓包，不同手机的电池效率又不同充电时间各不一样。如果能由手机自主控制智能插座的开启与关闭的话会更合适。

你可以用MacroDriod来实现，这个可以实现webhook，可以直接远程控制

**Comment by stoncn** [comment]
MacroDriod 里设定好的操作是不是也需要一个触发？比如地址变换、时间改变这些事件，我现在要解决的问题是电量达到一个程度就触发一个自动化操作app能检测到的事件，目前sf可以发一个特定标题邮件，但这个事件不太好捕捉，所有希望sf能触发一个启动设定好的app事件。不知电量预警如何能触发MarcoDriod操作?

启动app如果能实现，不仅仅能解决自动充电问题，而且会打开sf一个很大的可玩想象空间。

**Comment by Leo-lithe** [comment]
![image](https://github.com/user-attachments/assets/b19efde7-5c5f-47e6-aff9-fcbc65236a79)
md是有这个触发器的，你可以测试并使用一下

**Comment by Leo-lithe** [comment]
> MacroDriod 里设定好的操作是不是也需要一个触发？比如地址变换、时间改变这些事件，我现在要解决的问题是电量达到一个程度就触发一个自动化操作app能检测到的事件，目前sf可以发一个特定标题邮件，但这个事件不太好捕捉，所有希望sf能触发一个启动设定好的app事件。不知电量预警如何能触发MarcoDriod操作?
> 
> 启动app如果能实现，不仅仅能解决自动充电问题，而且会打开sf一个很大的可玩想象空间。
并且md是可以和短信转发器联动的，md原生支持webhook，当然需要开启fcn推送服务，但是md的编码好像有一点问题webhook对中文的支持不是很好，哪怕用json格式传入参数也会乱码，不过用英文就没事了。

**Comment by stoncn** [comment]
> ![image](https://private-user-images.githubusercontent.com/175391861/349405994-b19efde7-5c5f-47e6-aff9-fcbc65236a79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzODg5MzMsIm5iZiI6MTcyMTM4ODYzMywicGF0aCI6Ii8xNzUzOTE4NjEvMzQ5NDA1OTk0LWIxOWVmZGU3LTVjNWYtNDdlNi1hZmY5LWZjYmM2NTIzNmE3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQxMTMwMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZWJiNWIxNzQ3ZWFmNDZhZTc1OWExYmNmNTYxZWU5MDBiNTZmNjk0ZGY0MWRkYjk4OTM2ZDFkYWI5NjM0ZTQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4n0BcYiwMEzM875gHSaQQeHaX5Ken4YrfTWjlDvwYDs) md是有这个触发器的，你可以测试并使用一下

测试成功了，可以实现自动充放电了，Md 的功能太强了，谢谢大佬指点🙏
