### ISSUE TITLE
[Suggestion]: 可以设置来电转接的功能

### ISSUE THREAD

**Issue by r1235613** [pppscn/SmsForwarder#498]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

若能根据目前的条件设置电话卡的一律转接、忙线转接、无信号时转接与未接听时转接就好了

### 你觉得该怎么去完善会比较好？【非必答】

使用环境是，我工作的地方只能带公司发的手机
目前我是上班时将我私人手机扔到车子里面转发短信与电话、若能设置一个功能让私人手机在仅在特定时间转发来电就太好了
目前设定未接听转接，有些来电等不久会直接挂掉；设定一律转接我会忘记取消
注： 我的手机有刷机Root

**Comment by pppscn** [comment]
通话类的功能一律不会碰，可刑可拷！

你这个场景没问题，问题是多少搞黑灰产的人盯着这个项目，会被他们用于非法用途
