### ISSUE TITLE
[Bug]: 偶尔崩溃

### ISSUE THREAD

**Issue by Leo-lithe** [pppscn/SmsForwarder#499]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.3.2.240711

### 问题描述

有时候会崩溃，但具体原因不太清楚，可能有冲突？runtimeExection

### 复现步骤

无法具体复现，因为这是应用崩溃问题，提示是蓝牙出问题但我并没有开启接收蓝牙

### 是否必现

否（No）

### 出现问题的手机信息

redmi k50

### 出现问题的安卓版本、系统版本

android14 hyperos1.0

### 提供截图或视频

java.lang.RuntimeException: Error receiving broadcast Intent { act=android.bluetooth.device.action.ACL_CONNECTED flg=0x5000010 (has extras) } in com.idormy.sms.forwarder.receiver.BluetoothReceiver@673b0ad

### 提供报错堆栈【请提供logcat抓取的日志，参考： https://blog.csdn.net/m0_64776928/article/details/126005119 】

java.lang.RuntimeException: Error receiving broadcast Intent { act=android.bluetooth.device.action.ACL_CONNECTED flg=0x5000010 (has extras) } in com.idormy.sms.forwarder.receiver.BluetoothReceiver@673b0ad

**Comment by pppscn** [comment]
通用设置 中 导出日志 ，把 crash_*** 文件贴上了看看

**Comment by Leo-lithe** [comment]
> 通用设置 中 导出日志 ，把 crash_*** 文件贴上了看看

![image](https://github.com/user-attachments/assets/e46a9d54-9705-4c0b-a1e0-8cbb9b18c66e)
就这点

**Comment by pppscn** [comment]
添加了try-catch块来捕获并记录可能的异常，再观察看看

---

覆盖安装 `每周构建版` 试试 **（等待在线编译完成）**

**升级操作提示：** 
- `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
-  手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by Leo-lithe** [comment]
> 添加了try-catch块来捕获并记录可能的异常，再观察看看
> 
> 覆盖安装 `每周构建版` 试试 **（等待在线编译完成）**
> 
> **升级操作提示：**
> 
> * `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
> * 手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

现在好了系统没有提示经常崩溃了
