### ISSUE TITLE
可以添加转发未接来电吗？

### ISSUE THREAD

**Issue by mymine** [pppscn/SmsForwarder#5]
可以添加转发未接来电功能吗？

**Comment by pppscn** [comment]
这个项目不会加上来电，毕竟叫 *Sms*Forwarder了，加上有点不伦不类，而且界面调整、规则改动也比较大，后面可以再考虑另起一个项目

**Comment by mymine** [comment]
> 这个项目不会加上来电，毕竟叫 _Sms_Forwarder了，加上有点不伦不类，而且界面调整、规则改动也比较大，后面可以再考虑另起一个项目

改个名字好了。😁

**Comment by tenwx** [comment]
同支持楼主，求加转发未接来电提醒短信

**Comment by egdw** [comment]
https://github.com/egdw/mobile_monitor_android_simple
我的可以

**Comment by mymine** [comment]
> https://github.com/egdw/mobile_monitor_android_simple 我的可以

闪退。MIUI12。安卓11。

**Comment by egdw** [comment]
留个联系方式，我看看

**Comment by mymine** [comment]
> 留个联系方式，我看看

QQ550162729
