### ISSUE TITLE
[Bug]: 棒子安卓4.4无法下载frpc模块

### ISSUE THREAD

**Issue by e-ivan** [pppscn/SmsForwarder#501]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

否（No）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

3.3.2

### 问题描述

高通410棒子，下载frpc模块报错，还有什么办法可以下载这个模块的依赖？

### 复现步骤

内网穿透frpc，下载模块

### 是否必现

是（Yes）

### 出现问题的手机信息

高通410

### 出现问题的安卓版本、系统版本

4.4.4

### 提供截图或视频

![image](https://github.com/user-attachments/assets/17c76116-5cbb-4b2d-b8bc-1b35a2cd02fa)
![image](https://github.com/user-attachments/assets/e885e02a-d1f2-467e-958e-bfd5b6a544cf)

**Comment by pppscn** [comment]
确定是 3.3.2 ？

这个提交已经忽略证书了
https://github.com/pppscn/SmsForwarder/commit/894155df229845f2ac1048be4e111d6745dfceb6

如果还是无效，那就无解了

**Comment by e-ivan** [comment]
> 确定是 3.3.2 ？
> 
> 这个提交已经忽略证书了 [894155d](https://github.com/pppscn/SmsForwarder/commit/894155df229845f2ac1048be4e111d6745dfceb6)
> 
> 如果还是无效，那就无解了

除了这种方式下载，还有什么其它方式吗。能不能自定义下载链接
