### ISSUE TITLE
[Suggestion]: 希望android app能够默认（或提供选项）信任用户证书

### ISSUE THREAD

**Issue by meoow** [pppscn/SmsForwarder#503]
### 是否有人曾提过类似的问题？

是（Yes）

### 你觉得APP有什么不足之处？

我的bark服务SSL用的自签名证书，因为我没有用public domain的需求。与iOS不同的是，在android上导入CA证书后，默认只有浏览器会信任该证书，APP默认则不会，需要开发者使app信任用户证书。目前SmsForwarder添加使用自签名证书的bark服务地址会失败。   

### 你觉得该怎么去完善会比较好？【非必答】

希望APP能够默认（或提供选项）信任用户证书。

**Comment by pppscn** [comment]
建议去搞一个免费的ssl证书
