### ISSUE TITLE
[Bug]: 夜间转发时间过长

### ISSUE THREAD

**Issue by jhx1024** [pppscn/SmsForwarder#504]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

否（No）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

xxx

### 问题描述

1、手机转发记录显示转发成功的时间为凌晨 02：12分
2、系统成功接收时间为早上  07：13分
整体表现：从转发到接收这个过程时间间隔较长，此问题只在夜间出现

### 复现步骤

1、手机转发记录显示转发成功的时间为凌晨 02：12分
2、系统成功接收时间为早上  07：13分
整体表现：从转发到接收这个过程时间间隔较长，此问题只在夜间出现

### 是否必现

是（Yes）

### 出现问题的手机信息

小米

### 出现问题的安卓版本、系统版本

小米

### 提供截图或视频

![image](https://github.com/user-attachments/assets/51990a76-49ab-4179-906a-90fef09887d6)
![image](https://github.com/user-attachments/assets/9e9d9f4e-acf9-480a-8073-48960c1769e5)

**Comment by pppscn** [comment]
参考这个排查一下，手机的系统设置

https://github.com/pppscn/SmsForwarder/wiki/%E3%80%90%E5%BF%85%E8%AF%BB%E3%80%91%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#q%E8%BD%AF%E4%BB%B6%E7%99%BD%E5%A4%A9%E5%88%B0%E6%99%9A%E4%B8%8A11%E5%B7%A6%E5%8F%B3%E8%BD%AC%E5%8F%91%E5%88%B0qq%E9%82%AE%E7%AE%B1%E9%83%BD%E6%88%90%E5%8A%9F%E4%BA%86%E4%BD%86%E6%98%AF%E6%99%9A%E4%B8%8A12%E7%82%B9%E4%B9%8B%E5%90%8E%E5%88%B0%E6%97%A9%E4%B8%8A8%E7%82%B9%E5%B7%A6%E5%8F%B3%E6%97%A0%E4%B8%80%E4%B8%AA%E6%88%90%E5%8A%9F%E5%85%A8%E9%83%A8%E5%A4%B1%E8%B4%A5%E4%BA%86%E8%BF%99%E5%8F%AF%E8%83%BD%E4%BC%9A%E6%98%AF%E4%BB%80%E4%B9%88%E9%97%AE%E9%A2%98%E5%91%80
