### ISSUE TITLE
[Suggestion]: 能不能增加一个心跳设置，每N秒给Webhook推送一个消息

### ISSUE THREAD

**Issue by codemain** [pppscn/SmsForwarder#505]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

App非常棒，谢谢

### 你觉得该怎么去完善会比较好？【非必答】

App非常棒，谢谢

**Comment by pppscn** [comment]
去 `自动任务`，加一个定时任务试试？
