### ISSUE TITLE
[Bug]: 在熄屏状态下，无法正常运行服务

### ISSUE THREAD

**Issue by ndaydayup** [pppscn/SmsForwarder#506]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

否（No）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

v3.1.1

### 问题描述

在熄屏状态下，手机无法正常运行服务

### 复现步骤

在熄屏状态下，手机无法正常运行服务

### 是否必现

是（Yes）

### 出现问题的手机信息

1+ACE3

### 出现问题的安卓版本、系统版本

Android14

**Comment by pppscn** [comment]
保活问题，自行排查手机系统省电策略
