### ISSUE TITLE
[Bug]:好奇怪啊 配置多事一样的 过一会 就包 Failed to send email: 535 Login Fail.Please enter your authorization

### ISSUE THREAD

**Issue by yangyz** [pppscn/SmsForwarder#507]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

否（No）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

V3.3.1.240418

### 问题描述

配置什么多没有动  
![2bfb3b3b99589e79a6aab17d0d29492](https://github.com/user-attachments/assets/acdbb505-1d4f-4e2d-9162-a66ca3783c0e)

### 复现步骤

半个小时候是好的 现在又出问题了  之前处理的方式是删除发送通道  重新新增一个发送通道 好了 ，  过了一会又不行了 最近搞了好几次了 最近2-3天内发生着情况

### 是否必现

否（No）

### 出现问题的手机信息

Redmi 9A 

### 出现问题的安卓版本、系统版本

MUI12.0.4

### 提供截图或视频

![2bfb3b3b99589e79a6aab17d0d29492](https://github.com/user-attachments/assets/246c7601-fb3c-4e8c-96df-e5426bfb159a)

**Comment by yangyz** [comment]
邮箱服务器换成 网易的 现在似乎没有问题  。。。可能真是 QQ邮箱服务器问题 还是 QQ邮箱服务器最近安全升级 什么鬼...?

**Comment by pppscn** [comment]
字面意思是  需要用授权码登录（非邮箱密码），每个设备各自弄一个授权码试试

**Comment by yangyz** [comment]
登录肯定是 授权码  
今天0凌晨有发生几个  6点多又号了
![image](https://github.com/user-attachments/assets/81a71922-436e-4a1a-8fd8-bdef40847d5f)
![37dfdf8269dd6f9d41095214cfd0e8a](https://github.com/user-attachments/assets/182a70b2-fdce-4704-b149-d40c8ddc198d)

**Comment by yangyz** [comment]
> 字面意思是 需要用授权码登录（非邮箱密码），每个设备各自弄一个授权码试试

是授权码   换了网易邮件服务器  昨晚 0点左右 还是报错了 认证问题    今天6点以后 就好了  
![image](https://github.com/user-attachments/assets/28c36fa8-bd0d-47aa-b969-0c65abab6001)
