### ISSUE TITLE
[Bug]: 清空转发日志无效

### ISSUE THREAD

**Issue by dicolar** [pppscn/SmsForwarder#508]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.3.1

### 问题描述

在转发列表，点击右上角的垃圾桶图标，弹出确认对话框选是，提示已经清空记录，但是实际上没有任何变化
手机：vivo y77t

### 复现步骤

在转发列表，点击右上角的垃圾桶图标，弹出确认对话框选是，提示已经清空记录

### 是否必现

是（Yes）

### 出现问题的手机信息

vivo y77t

### 出现问题的安卓版本、系统版本

Android 13

**Comment by pppscn** [comment]
覆盖安装 `每周构建版` 试试

**升级操作提示：** 
- `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
-  手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

https://github.com/pppscn/SmsForwarder/issues/463

**Comment by dicolar** [comment]
我安装了0804的那个版本，依然有这个问题。
并且以前老版本是可以设置保留多久的日志的，现在设置里也没有这个选项了。
