### ISSUE TITLE
[Bug]: Xiaomi HyperOS 权限全绿也没有读取短信记录

### ISSUE THREAD

**Issue by bowencool** [pppscn/SmsForwarder#509]
### 是否有人曾提过类似的问题

是（Yes）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.3.1

### 问题描述

首先是权限和开关的检查
![Screenshot_2024-08-10-12-20-50-265_com idormy sms forwarder](https://github.com/user-attachments/assets/f4747b24-f903-4914-8739-a8e88d17e0fe)
![Screenshot_2024-08-10-12-19-19-800_com miui securitycenter](https://github.com/user-attachments/assets/a19befbd-0875-433e-bcab-661c20c4a48c)
今天升级系统，测试了，但没有读取短信记录，可以看到昨天旧系统（MIUI 14）还有读取记录：
![Screenshot_2024-08-10-12-15-49-379_com miui securitycenter](https://github.com/user-attachments/assets/7406ae27-f48a-4212-a71d-5d7012d25ceb)

### 复现步骤

同上

### 是否必现

是（Yes）

### 出现问题的手机信息

红米 K40

### 出现问题的安卓版本、系统版本

HyperOS 1.0.6.0

**Comment by bowencool** [comment]
还需要什么信息，我会配合提供

**Comment by OnlyU1** [comment]
xiaomi 4C  同样的BUG

**Comment by pppscn** [comment]
小米/红米手机（MIUI 或 Hyper OS）目前应该还能支持，检查权限是否全绿（关闭空白通行证），关闭免费网络短信、关闭各种省电策略（包括不限于：息屏后断开网络，省电模式，应用智能省电，智能场景省电-睡眠模式）。

实在都不行的话，开启开发者模式，关闭MIUI优化，然后重新安装SmsForwarder重新配置（导出设置后，重新安装app再导入设置）

**Comment by bowencool** [comment]
> 小米/红米手机（MIUI 或 Hyper OS）目前应该还能支持，检查权限是否全绿（关闭空白通行证），关闭免费网络短信、关闭各种省电策略（包括不限于：息屏后断开网络，省电模式，应用智能省电，智能场景省电-睡眠模式）。
> 
> 实在都不行的话，开启开发者模式，关闭MIUI优化，然后重新安装SmsForwarder重新配置（导出设置后，重新安装app再导入设置）

我重新安装了一下，现在正常了

**Comment by Zylsjsp** [comment]
红米 K70pro hyperos 1.0.22.0 同样给了短信和通知类短信的权限 但是权限日志里面看不到任何相关权限请求 清除数据 重新安装均无效果

**Comment by rangerzhou** [comment]
关闭免费网络短信，关闭5G消息就可以收到了
