### ISSUE TITLE
[Bug]: 在小米12上完全没法用

### ISSUE THREAD

**Issue by yutent** [pppscn/SmsForwarder#511]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

否（No）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

最新版

### 问题描述

HyperOS 1.0.5
只能转发我自己另一个手机发的短信, 其他的号码发的短信, 如验证码, 通知类短信, 完全不转发。
自己发的短信, 也只能是一开始能转发, 放1天之后, 就再也转发不了了, 需要卸载重装app才可以转发

### 是否必现

是（Yes）

### 出现问题的手机信息

小米12

### 出现问题的安卓版本、系统版本

HyperOS 1.0.5

**Comment by pppscn** [comment]
小米/红米手机（MIUI 或 Hyper OS）目前应该还能支持，检查权限是否全绿（关闭空白通行证），关闭免费网络短信、关闭各种省电策略（包括不限于：息屏后断开网络，省电模式，应用智能省电，智能场景省电-睡眠模式）。

实在都不行的话，开启开发者模式，关闭MIUI优化，然后重新安装SmsForwarder重新配置（导出设置后，重新安装app再导入设置）


最后还是不行，就卸载了吧

**Comment by rangerzhou** [comment]
> 小米/红米手机（MIUI 或 Hyper OS）目前应该还能支持，检查权限是否全绿（关闭空白通行证），关闭免费网络短信、关闭各种省电策略（包括不限于：息屏后断开网络，省电模式，应用智能省电，智能场景省电-睡眠模式）。
> 
> 实在都不行的话，开启开发者模式，关闭MIUI优化，然后重新安装SmsForwarder重新配置（导出设置后，重新安装app再导入设置）
> 
> 最后还是不行，就卸载了吧

还要关闭短信设置里的5G消息
