### ISSUE TITLE
[Bug]: 熄屏状态下无法转发到url

### ISSUE THREAD

**Issue by gfhdhytghd** [pppscn/SmsForwarder#514]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.3.1

### 问题描述

系统:AIOS/Flyme 11

具体问题:
在手机熄屏/锁定状态下无法使用短信转发器转发任何消息到url,解锁状态下可以
这似乎是因为短信转发器使用调用浏览器的方式来访问url,能否允许用户更改为使用curl?

### 复现步骤

添加url发送通道
(我使用的是阿里云+napcat的onebot的send_private_msg api)
添加消息转发规则
锁定屏幕

### 是否必现

是（Yes）

### 出现问题的手机信息

魅族21

### 出现问题的安卓版本、系统版本

安卓14/Flyme11

**Comment by pppscn** [comment]
请使用 `Webhook` 发送通道，而不是 `URL Scheme`

https://github.com/pppscn/SmsForwarder/wiki/2.%E5%8F%91%E9%80%81%E9%80%9A%E9%81%93#webhook

**Comment by pppscn** [comment]
另外，关注一下wiki常见问题

https://github.com/pppscn/SmsForwarder/wiki/%E3%80%90%E5%BF%85%E8%AF%BB%E3%80%91%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#q%E4%B8%BA%E4%BB%80%E4%B9%88%E9%94%81%E5%B1%8F%E4%BA%86%E8%BD%AF%E4%BB%B6%E5%B0%B1%E4%B8%8D%E8%BF%90%E8%A1%8C%E8%A7%A3%E9%94%81%E4%BA%86%E6%89%8D%E8%BD%AC%E5%8F%91%E4%BA%AE%E5%B1%8F%E7%8A%B6%E6%80%81%E4%B8%8B%E8%BD%AC%E5%8F%91%E9%83%BD%E6%AD%A3%E5%B8%B8%E9%94%81%E5%B1%8F%E5%B0%B1%E6%B2%A1%E6%9C%89%E6%97%A5%E5%BF%97%E6%88%96%E8%80%85%E9%83%BD%E6%98%AF%E8%BD%AC%E5%8F%91%E5%A4%B1%E8%B4%A5

**Comment by gfhdhytghd** [comment]
> 请使用 `Webhook` 发送通道，而不是 `URL Scheme`
> 
> https://github.com/pppscn/SmsForwarder/wiki/2.%E5%8F%91%E9%80%81%E9%80%9A%E9%81%93#webhook

好的，感谢
