### ISSUE TITLE
[Suggestion]: 关于新增获取消息通知栏icon的建议

### ISSUE THREAD

**Issue by hmcxfws** [pppscn/SmsForwarder#515]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

希望作者能新增一个icon变量可以获取到通知栏的icon图片然后转换成base64供用户使用。比方说转发wx消息到电脑时时间的通知栏消息的icon就是wx头像，如果有了这么一个icon变量可以更好的方便用户进行个性定制化

**Comment by pppscn** [comment]
暂不考虑，通知栏的icon只是app的图标而已，可以自己在接收端去个性化

这里面可能没有你想那么简单（你以为它是一个url？），要把获取到 Bitmap 或 Drawable 转成你能用的 base64，还要去猜它原本 MIME 类型（拍脑袋想的，没试过）
