### ISSUE TITLE
[Suggestion]: Webhook能否增加”应用名称“标签

### ISSUE THREAD

**Issue by wzn556** [pppscn/SmsForwarder#516]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

通过NotifyMe接收应用消息：https://github.com/wzn556/NotifyMe-Tutorials/wiki/Usage_Scenarios_zh#%E5%BA%94%E7%94%A8%E9%80%9A%E7%9F%A5%E8%BD%AC%E5%8F%91

如果通过一个发送通道发送所有应用通知，并通过NotifyMe分组不同app的消息。由于目前Webhook标签不支持”应用名称“，只能通过包名进行分组，组名显示为包名。

建议增加”应用名称“标签，使Webhook可以传递应用名称，配合NotifyMe分组可以显示为应用名称。
![分组](https://github.com/user-attachments/assets/5130fa07-20c7-4e11-a01b-002b6d784b47)

**Comment by pppscn** [comment]
> **特别提醒：** `v3.3.2+` 开始，允许在 `消息模板` 中直接使用 《[附录3：自定义模板可用变量](https://github.com/pppscn/SmsForwarder/wiki/%E9%99%84%E5%BD%953%EF%BC%9A%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A8%A1%E6%9D%BF%E5%8F%AF%E7%94%A8%E5%8F%98%E9%87%8F)》，**但是**，请务必注意 `适用场景` 和 `标签说明`

覆盖安装 `每周构建版` 试试 **（等待在线编译完成）**

**升级操作提示：** 
- `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
-  手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by wzn556** [comment]
> > **特别提醒：** `v3.3.2+` 开始，允许在 `消息模板` 中直接使用 《[附录3：自定义模板可用变量](https://github.com/pppscn/SmsForwarder/wiki/%E9%99%84%E5%BD%953%EF%BC%9A%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A8%A1%E6%9D%BF%E5%8F%AF%E7%94%A8%E5%8F%98%E9%87%8F)》，**但是**，请务必注意 `适用场景` 和 `标签说明`
> 
> 覆盖安装 `每周构建版` 试试 **（等待在线编译完成）**
> 
> **升级操作提示：** 
> - `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
> -  手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

已测试成功，可正常使用。

转发规则处字符串有点问题。
![IMG_20240815_124303.jpg](https://github.com/user-attachments/assets/b8bf990f-c34e-43d9-9749-9d712e85a1ed)

**Comment by pppscn** [comment]
> > > **特别提醒：** `v3.3.2+` 开始，允许在 `消息模板` 中直接使用 《[附录3：自定义模板可用变量](https://github.com/pppscn/SmsForwarder/wiki/%E9%99%84%E5%BD%953%EF%BC%9A%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A8%A1%E6%9D%BF%E5%8F%AF%E7%94%A8%E5%8F%98%E9%87%8F)》，**但是**，请务必注意 `适用场景` 和 `标签说明`
> > 
> > 
> > 覆盖安装 `每周构建版` 试试 **（等待在线编译完成）**
> > **升级操作提示：**
> > 
> > * `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
> > * 手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml
> 
> 已测试成功，可正常使用。
> 
> 转发规则处字符串有点问题。 ![IMG_20240815_124303.jpg](https://private-user-images.githubusercontent.com/52151659/358124196-b8bf990f-c34e-43d9-9749-9d712e85a1ed.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2OTk5NDQsIm5iZiI6MTcyMzY5OTY0NCwicGF0aCI6Ii81MjE1MTY1OS8zNTgxMjQxOTYtYjhiZjk5MGYtYzM0ZS00M2Q5LTk3NDktOWQ3MTJlODVhMWVkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA1MjcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NmIwNWZmNWVhZWFjN2JkZTJhYzRmMzE2MGYxZGY0NWE2ZjE3ZWFjOGQ4ZGE4NWQ2ZTMwZTg5ODFjMmI5MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mgdZUx4jBx-OGf7ET4MOj8mIyb10r38LsZU7uslY2uI)

app转发 已去掉 `任意卡`
