### ISSUE TITLE
[Suggestion]: 把通话时长的变量说下

### ISSUE THREAD

**Issue by Mr-Roxe** [pppscn/SmsForwarder#518]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

默认模板有通话时长，但，手册里我并没有找到这个变量，难道要我用正则？不至于吧

![image](https://github.com/user-attachments/assets/d38f193b-be9a-4c40-9585-50b16f0f5164)

**Comment by pppscn** [comment]
没有单独的变量，自行使用正则从 `{{SMS}}` 提取

https://github.com/pppscn/SmsForwarder/wiki/%E9%99%84%E5%BD%953%EF%BC%9A%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A8%A1%E6%9D%BF%E5%8F%AF%E7%94%A8%E5%8F%98%E9%87%8F
