### ISSUE TITLE
[Bug]: 自动任务・快捷指令的模板有问题

### ISSUE THREAD

**Issue by Tabbto** [pppscn/SmsForwarder#520]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.3.2

### 问题描述

![Snipaste_2024-09-04_20-53-30](https://github.com/user-attachments/assets/59016fac-13d9-4e3e-9e47-216410b4b48e)
自动任务推送通知的标题会变成脚本内容。

### 复现步骤

![Snipaste_2024-09-04_20-54-37](https://github.com/user-attachments/assets/30ed7a4f-a0a5-4600-993b-de15c0fde50c)
配置如图。
推送使用默认模板的话，内容底部倒数第三行同样是脚本内容。

### 是否必现

是（Yes）

### 出现问题的手机信息

Moto edge s

### 出现问题的安卓版本、系统版本

Android12

**Comment by DavidSousaZ** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by pppscn** [comment]
自动任务的 `描述` 本来就是作为消息的 `标题`

`自定义模板` 和 `自定义标题`（发送通道）试试

**Comment by Tabbto** [comment]
> 自动任务的 `描述` 本来就是作为消息的 `标题`
> 
> `自定义模板` 和 `自定义标题`（发送通道）试试

之前就都是自定义了。

刚才又试验了一下：

![1](https://github.com/user-attachments/assets/0de4753d-caba-4448-be1e-bb285875cf4c)
发送通道的标题模板为{{TITLE}} DEVICE_NAME，任务推送的自定义模板为时间，收到的通知。

![2](https://github.com/user-attachments/assets/7e450fd6-ecdc-4acb-ad7c-f20bbf131363)
发送通道的标题模板为{{TITLE}} DEVICE_NAME，任务推送使用默认模板，收到的通知。

![3](https://github.com/user-attachments/assets/40b177c8-b6c1-455d-876c-7406101ce132)
发送通道的标题模板为DEVICE_NAME，任务推送使用默认模板，收到的通知。

自动任务的名称分别为【电量低】【充电停止test】【正在充电test】。
【电量低】这个任务的通知始终没有问题。
而充电变化的任务在发送通道的标题模板去掉{{TITLE}}后标题就正常了，但默认内容的倒数第三行还是脚本内容，从【电量低】的内容看这行本该和第一行一样是任务名称才对吧？

**Comment by pppscn** [comment]
懒得折腾 自动任务 了
