### ISSUE TITLE
[Bug]: 转发企微、webhook都延迟严重。

### ISSUE THREAD

**Issue by eoc2015** [pppscn/SmsForwarder#521]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

否（No）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

v3.3.2

### 问题描述

红米 Redmi 12c  电源管理权限都没问题。关屏后台挂了两天，今天开始发现部分短信转发延迟很严重。app的日志也能看到，5点的短信，7点才转发。
![0779b3ae3a2664f59bbf5c63416f420](https://github.com/user-attachments/assets/3c1ec154-44bc-427c-a771-849340e58495)

<img width="353" alt="1725501034118" src="https://github.com/user-attachments/assets/3d644556-fcbe-4f82-ab3e-d3ce317fa92c">

### 复现步骤

挂机等两天

### 是否必现

否（No）

### 出现问题的手机信息

红米 Redmi 12c  

### 出现问题的安卓版本、系统版本

安卓最新

### 提供截图或视频

![image](https://github.com/user-attachments/assets/4904bb2a-3c30-45d8-bb17-ab1725310a06)

**Comment by pppscn** [comment]
参考这个

https://github.com/pppscn/SmsForwarder/wiki/%E3%80%90%E5%BF%85%E8%AF%BB%E3%80%91%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#q%E8%BD%AF%E4%BB%B6%E7%99%BD%E5%A4%A9%E5%88%B0%E6%99%9A%E4%B8%8A11%E5%B7%A6%E5%8F%B3%E8%BD%AC%E5%8F%91%E5%88%B0qq%E9%82%AE%E7%AE%B1%E9%83%BD%E6%88%90%E5%8A%9F%E4%BA%86%E4%BD%86%E6%98%AF%E6%99%9A%E4%B8%8A12%E7%82%B9%E4%B9%8B%E5%90%8E%E5%88%B0%E6%97%A9%E4%B8%8A8%E7%82%B9%E5%B7%A6%E5%8F%B3%E6%97%A0%E4%B8%80%E4%B8%AA%E6%88%90%E5%8A%9F%E5%85%A8%E9%83%A8%E5%A4%B1%E8%B4%A5%E4%BA%86%E8%BF%99%E5%8F%AF%E8%83%BD%E4%BC%9A%E6%98%AF%E4%BB%80%E4%B9%88%E9%97%AE%E9%A2%98%E5%91%80

**Comment by eoc2015** [comment]
> 参考这个
> 
> https://github.com/pppscn/SmsForwarder/wiki/%E3%80%90%E5%BF%85%E8%AF%BB%E3%80%91%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#q%E8%BD%AF%E4%BB%B6%E7%99%BD%E5%A4%A9%E5%88%B0%E6%99%9A%E4%B8%8A11%E5%B7%A6%E5%8F%B3%E8%BD%AC%E5%8F%91%E5%88%B0qq%E9%82%AE%E7%AE%B1%E9%83%BD%E6%88%90%E5%8A%9F%E4%BA%86%E4%BD%86%E6%98%AF%E6%99%9A%E4%B8%8A12%E7%82%B9%E4%B9%8B%E5%90%8E%E5%88%B0%E6%97%A9%E4%B8%8A8%E7%82%B9%E5%B7%A6%E5%8F%B3%E6%97%A0%E4%B8%80%E4%B8%AA%E6%88%90%E5%8A%9F%E5%85%A8%E9%83%A8%E5%A4%B1%E8%B4%A5%E4%BA%86%E8%BF%99%E5%8F%AF%E8%83%BD%E4%BC%9A%E6%98%AF%E4%BB%80%E4%B9%88%E9%97%AE%E9%A2%98%E5%91%80

其实，所有电源和后台都设置，没得办法，只能插着充电线，然后屏幕常亮，app前台显示，这两天没延迟了~
