### ISSUE TITLE
[Suggestion]: 能否在启动时或者自动任务里增加打开某个设置或执行脚本的功能

### ISSUE THREAD

**Issue by cjd6568358** [pppscn/SmsForwarder#522]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

高版本安卓每次重启后会自动关闭网络adb调试功能，同时adb端口也会变更。对于备用机而言想要通过开机自动打开adb网络调试+固定adb端口+VPN接入+甲壳虫ADB助手实现远程控制手机的功能

**Comment by pppscn** [comment]
这个需求做不了
