### ISSUE TITLE
[Suggestion]: 请问可以筛选过滤彩信吗？

### ISSUE THREAD

**Issue by ChenCyril** [pppscn/SmsForwarder#524]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

我也不指望能转发彩信（看了看之前的issue），目前有些彩信是分两个短信发的，第一个是图片第二个是文本。这种情况下如果转发的话显示的是空消息。

我之前想着设置过滤规则，如果是空消息就不转发。但是我看到过滤设置，如果输入框为空是不能保存的。请问这种是怎样解决呢？
目前就想把这种彩信给屏蔽掉

**Comment by cnbilinyj** [comment]
你可以试一下用正则表达式，正则表达式的能力非常强大，你可以试试`^\S*$`

**Comment by cnbilinyj** [comment]
> 你可以试一下用正则表达式，正则表达式的能力非常强大，你可以试试`^\s*$`手机刚好不在手上，没办法尝试，所以只能你自己试试了

实际测试后发现可以使用

```
并且 是 短信内容 正则匹配 ^[\s\S]*?$
```

的多重匹配方案或者直接使用`^[\s\S]*?$`的短信内容正则匹配方案

**Comment by ChenCyril** [comment]
> > 你可以试一下用正则表达式，正则表达式的能力非常强大，你可以试试`^\s*$`手机刚好不在手上，没办法尝试，所以只能你自己试试了
> 
> 实际测试后发现可以使用
> 
> ```
> 并且 是 短信内容 正则匹配 ^[\s\S]*?$
> ```
> 
> 的多重匹配方案或者直接使用`^[\s\S]*?$`的短信内容正则匹配方案

好的，我设置好了，等到时候有彩信来的时候试试看。谢谢您~

**Comment by cnbilinyj** [comment]
忘记说了，这个只适合有内容的，换句话说彩信他匹配不到，而你是不想匹配彩信，也就是说这个时候你能匹配到你想匹配的发件人: ***@***.*** ***@***.***> 代表 ChenCyril ***@***.***>发送时间: 星期一, 十月 28, 2024 9:47:57 上午收件人: pppscn/SmsForwarder ***@***.***>抄送: 农药君 ***@***.***>; Comment ***@***.***>主题: Re: [pppscn/SmsForwarder] [Suggestion]: 请问可以筛选过滤彩信吗？ (Issue #524)


你可以试一下用正则表达式，正则表达式的能力非常强大，你可以试试^\s*$手机刚好不在手上，没办法尝试，所以只能你自己试试了

实际测试后发现可以使用
并且 是 短信内容 正则匹配 ^[\s\S]*?$

的多重匹配方案或者直接使用^[\s\S]*?$的短信内容正则匹配方案

好的，我设置好了，等到时候有彩信来的时候试试看。谢谢您~
