### ISSUE TITLE
[Suggestion]: 企业微信重置access_token功能

### ISSUE THREAD

**Issue by soul3075** [pppscn/SmsForwarder#525]
### 是否有人曾提过类似的问题？

是（Yes）

### 你觉得APP有什么不足之处？

企业微信重置access_token功能，access_token有效期内，无法新增其他企业微信渠道

**Comment by pppscn** [comment]
`access_token` 是以 `AgentID` 作为缓存主键的，你有多个 `企业ID` 下存在  `AgentID` 一样的应用？

`通用设置` 中 `开启调试模式`，操作之后 `导出` 日志，贴上来看看（注意：隐私信息脱敏）
