### ISSUE TITLE
[Suggestion]: Server酱API域名更新

### ISSUE THREAD

**Issue by ashaquecat** [pppscn/SmsForwarder#529]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

你好，目前Server酱推送，使用的API域名是sc.ftqq.com，此域名即将下线，请替换为sctapi.ftqq.com，谢谢。

**Comment by leangjia** [comment]
附议。Server酱通道报错：http 400，应该是旧域名作废了导致报400错误。

**Comment by pppscn** [comment]
一直用的是 `sctapi.ftqq.com` 域名，自己打开调试模式导出日志看看

3.x版本
https://github.com/pppscn/SmsForwarder/blob/main/app/src/main/java/com/idormy/sms/forwarder/utils/sender/ServerchanUtils.kt

2.x 版本
https://github.com/pppscn/SmsForwarder/blob/v2.x/app/src/main/java/com/idormy/sms/forwarder/sender/SenderServerChanMsg.java

1.x 版本
https://github.com/pppscn/SmsForwarder/blob/v1.x/app/src/main/java/com/idormy/sms/forwarder/sender/SenderServerChanMsg.java
