### ISSUE TITLE
两个小建议

### ISSUE THREAD

**Issue by lincww** [pppscn/SmsForwarder#53]
非常感谢您的开发，现在有一点小建议望您能采纳
1.telegram转发支持自定义bot地址
2.在发送失败时支持fallback到另一个转发源
谢谢！

**Comment by armila-o** [comment]
1.telegram转发支持自定义bot地址，这个可以，telegram通过cf worker反代后就不用开启代理软件都可以发送成功，只是需要修改下api地址。

**Comment by pppscn** [comment]
自定义bot地址的话 是不是 apitoken 已经包含在定义地址里面了 或者 在服务端了？

即：设置界面只要一个输入框就好了？

![Screenshot_1635989373](https://user-images.githubusercontent.com/5105854/140242155-cb25032f-0a47-4b50-a3a6-9a38ed28198d.png)

**Comment by pppscn** [comment]
在发送失败时支持fallback到另一个转发源，这个暂不考虑，变通的做法：

1、创建两个发送方，两个地址同时发

2、fallback动作放在自定义地址的服务端，app端已经有延时重试了，不想搞得太复杂

**Comment by armila-o** [comment]
> 自定义bot地址的话 是不是 apitoken 已经包含在定义地址里面了 或者 在服务端了？
> 
> 即：设置界面只要一个输入框就好了？
> 
> ![Screenshot_1635989373](https://user-images.githubusercontent.com/5105854/140242155-cb25032f-0a47-4b50-a3a6-9a38ed28198d.png)

两种都可以的，看怎么设置反代，不过我一般是仅仅反代api地址，token这些还是保持和官方的调用方式一致

**Comment by pppscn** [comment]
[main b214d2d] 优化：Telegram转发支持自定义bot地址(复用ApiToken字段，http开头)
