### ISSUE TITLE
[Suggestion]: 转发消息显示不全

### ISSUE THREAD

**Issue by Ksnqwe** [pppscn/SmsForwarder#530]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

转发应用消息的时候，信息显示不全，转发短信的时候字数很多都能显示全，但是转发应用消息的时候，会显示省略号，复制出来也是显示省略号

**Comment by pppscn** [comment]
无解，通知栏看到什么（文本）只能转发什么（文本）

自己捣腾一下系统设置，看看能不能不省略
