### ISSUE TITLE
[Suggestion]: 允许自定义时间戳格式

### ISSUE THREAD

**Issue by StellarHS** [pppscn/SmsForwarder#531]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

无法自定义时间戳格式

### 你觉得该怎么去完善会比较好？【非必答】

两种，也可以都有，fallback顺序：`标签配置 -> 通用配置 -> 默认格式`
第一种：通用设置中加入时间戳格式配置
第二种：使用类似以下正则模式的标签，冒号后为时间戳格式字符串(规则可能不完整)
`\{\{[(RECEIVE)(CURRENT)]_TIME(:[^(\}\})\n\r\f\v]+)?\}\}`

如果格式字符串解析失败则使用默认格式，并紧跟一个提示说明格式字符串错误

**Comment by pppscn** [comment]
参考一下：

https://github.com/pppscn/SmsForwarder/issues/327

**Comment by StellarHS** [comment]
在电子邮箱发送通道配置中不会生效

**Comment by StellarHS** [comment]
在电子邮箱发送通道配置中无效
另外, 在转发规则中似乎并不能自定义, 其中硬编码了 `yyyy-MM-dd HH:mm:ss` 模式
```
.replaceTag(
    getString(R.string.tag_receive_time),
    SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(date),
    encoderName
)
.replaceTag(
    getString(R.string.tag_current_time),
    SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(Date()),
    encoderName
)
```
