### ISSUE TITLE
[Bug]: VoceChat WebHook 415 错误

### ISSUE THREAD

**Issue by katriyda** [pppscn/SmsForwarder#532]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

3.3.2.240815

### 问题描述

在 VoceChat 中创建的机器人，添加了 content-type ，测试报错 415 。
[VoceChat 类型文档](https://doc.voce.chat/zh-cn/bot/bot-and-webhook#%E6%B6%88%E6%81%AF%E7%B1%BB%E5%9E%8B%E4%BB%8B%E7%BB%8D)
个人在已经测试了 VoceChat 的 WebHook 是有效的，我简单尝试了下用 okhttp 发送，会报 415，不知道有没有关系。

### 复现步骤

在 VoceChat 创建机器人后, 添加 WebHook 点击测试就会 415.

### 是否必现

是（Yes）

### 出现问题的手机信息

红米 K60

### 出现问题的安卓版本、系统版本

Android 14 、 HyperOs 1.0.13.0

### 提供截图或视频

![1728910242459](https://github.com/user-attachments/assets/e47d376c-2a7a-4920-867e-092e1bfa6afd)

**Comment by pppscn** [comment]
`通用设置` 开启 `调试模式`，`导出日志` 看看  你的api 是否有返回报文？

- 如果有，直接复制一个能代表成功的 关键词 到 上图的 `成功应答关键字` 试试

或者  提供测试参数 给我

**Comment by pppscn** [comment]
覆盖安装 `每周构建版` 试试 **（等待在线编译完成）**

**升级操作提示：** 
- `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
-  手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**使用方式：**

1. `消息模板`  保持非空，按需插入 [可用标签](https://github.com/pppscn/SmsForwarder/wiki/%E9%99%84%E5%BD%951%EF%BC%9A%E5%90%91webhook%E5%8F%91%E9%80%81post-get-put-patch%E8%AF%B7%E6%B1%82)
2.  `headers`，添加一个  `Key` = `content-type` ，`Value`  = `text/plain`、`text/html`、`text/css`、`text/javascript`、`text/xml` （选一种）

**Comment by pppscn** [comment]
具体代码提交见：

https://github.com/pppscn/SmsForwarder/commit/5c19c10121b3701dba941f427337d78684d11c9e

**Comment by pppscn** [comment]
> > 覆盖安装 `每周构建版` 试试 **（等待在线编译完成）**
> > **升级操作提示：**
> > 
> > * `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
> > * 手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml
> > 
> > **使用方式：**
> > 
> > 1. `消息模板`  保持非空，按需插入 [可用标签](https://github.com/pppscn/SmsForwarder/wiki/%E9%99%84%E5%BD%951%EF%BC%9A%E5%90%91webhook%E5%8F%91%E9%80%81post-get-put-patch%E8%AF%B7%E6%B1%82)
> > 2. `headers`，添加一个  `Key` = `content-type` ，`Value`  = `text/plain`、`text/html`、`text/css`、`text/javascript`、`text/xml` （选一种）
> 
> 谢谢你的回复。目前问题仍未解决。
> 
> 我发现，当将 `Content-Type` 设置为 `text/plain` 时，OkHttp 的 `RequestBody.create` 方法会在没有设置 `charset` 的情况下自动添加 `; charset=utf-8`，导致请求头变成了 `text/plain; charset=utf-8`。
> 
> ![image](https://private-user-images.githubusercontent.com/63391334/377814823-49db3a7f-2e3a-4927-ac9b-81312af9f5e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNTEzOTYsIm5iZiI6MTcyOTI1MTA5NiwicGF0aCI6Ii82MzM5MTMzNC8zNzc4MTQ4MjMtNDlkYjNhN2YtMmUzYS00OTI3LWFjOWItODEzMTJhZjlmNWU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDExMzEzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiZDQ4YzU2YWNkMWUxY2ZjNTRkMWY3MjIzMzlhOWIwZDFhODgyZjRhNjJiMmEzZDJkNzJhN2VjNGE0Y2I5ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eHV7q2LMsvo_Ir6of4ytPAjKPxKl4YbAvYUQP-NeYTU) ![image](https://private-user-images.githubusercontent.com/63391334/377821906-e5e404de-6f81-46fa-88be-a9c2736dc219.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNTEzOTYsIm5iZiI6MTcyOTI1MTA5NiwicGF0aCI6Ii82MzM5MTMzNC8zNzc4MjE5MDYtZTVlNDA0ZGUtNmY4MS00NmZhLTg4YmUtYTljMjczNmRjMjE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDExMzEzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5Yzc1ZGZmYTk0YTQ1YTVkMWY0YjVkZjRiMTdhOWU2NWQ2NjY1ZWViYzE4M2ZiMjMxN2I1NjczN2JjZjkwNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OeGXJ-6beL1nLbCy2GUjA0nvXqTucGrDlzdyfj9RjG0)

这就无解了，我总不能为了它去换掉 okhttp 吧？只能说这个 VoceChat  比较奇葩

**Comment by pppscn** [comment]
这么改不具备通用性了，还是自己 fork 后改一下，在线编译吧

参考wiki：[在线编译方式](https://github.com/pppscn/SmsForwarder/wiki/%E5%85%B3%E4%BA%8E%E5%AE%9A%E5%88%B6%E5%BC%80%E5%8F%91#%E5%9C%A8%E7%BA%BF%E7%BC%96%E8%AF%91%E6%96%B9%E5%BC%8F)

**Comment by RoeWade** [comment]
```
POST /api/bot/send_to_user/1 h2
host: vocechat.com
accept-language: zh-CN,zh;q=0.8
user-agent: Mozilla/5.0 (Linux; U; Android 14; zh-cn; M2006J10C Build/AP2A.240805.005) AppleWebKit/533.1 (KHTML, like Gecko) Version/5.0 Mobile Safari/533.1
x-api-key: xxxxxx
content-type: application/x-www-form-urlencoded
content-length: 416
accept-encoding: gzip
cache-control: no-cache

from=19999999999&content=19999999999%0A%E3%80%90vocechat%E3%80%91%E6%81%AD%E5%96%9C%E6%82%A8%EF%BC%8C%E8%AF%A5%E5%8F%91%E9%80%81%E9%80%9A%E9%81%93%E6%B5%8B%E8%AF%95%E6%88%90%E5%8A%9F%EF%BC%8C%E8%AF%B7%E7%BB%A7%E7%BB%AD%E6%B7%BB%E5%8A%A0%E8%BD%AC%E5%8F%91%E8%A7%84%E5%88%99%EF%BC%81%0ASIM1_%E6%B5%8B%E8%AF%95%E8%BF%90%E8%90%A5%E5%95%86_18888888888%0ASubId%EF%BC%9A0%0A2024-10-16%2014%3A46%3A32&timestamp=1729061192760
```

这里的 content-type: application/x-www-form-urlencoded 需要改为 content-type: text/plain
像如下：
```
POST /api/bot/send_to_user/1 h2
host: vocechat.com
accept-language: zh-CN,zh;q=0.8
user-agent: Mozilla/5.0 (Linux; U; Android 14; zh-cn; M2006J10C Build/AP2A.240805.005) AppleWebKit/533.1 (KHTML, like Gecko) Version/5.0 Mobile Safari/533.1
x-api-key: xxxxxx
content-type: application/x-www-form-urlencoded
content-length: 416
accept-encoding: gzip
cache-control: no-cache

Some Message
```

详情请参看 http://localhost:3009/api/doc

**Comment by pppscn** [comment]
> ```
> POST /api/bot/send_to_user/1 h2
> host: vocechat.com
> accept-language: zh-CN,zh;q=0.8
> user-agent: Mozilla/5.0 (Linux; U; Android 14; zh-cn; M2006J10C Build/AP2A.240805.005) AppleWebKit/533.1 (KHTML, like Gecko) Version/5.0 Mobile Safari/533.1
> x-api-key: xxxxxx
> content-type: application/x-www-form-urlencoded
> content-length: 416
> accept-encoding: gzip
> cache-control: no-cache
> 
> from=19999999999&content=19999999999%0A%E3%80%90vocechat%E3%80%91%E6%81%AD%E5%96%9C%E6%82%A8%EF%BC%8C%E8%AF%A5%E5%8F%91%E9%80%81%E9%80%9A%E9%81%93%E6%B5%8B%E8%AF%95%E6%88%90%E5%8A%9F%EF%BC%8C%E8%AF%B7%E7%BB%A7%E7%BB%AD%E6%B7%BB%E5%8A%A0%E8%BD%AC%E5%8F%91%E8%A7%84%E5%88%99%EF%BC%81%0ASIM1_%E6%B5%8B%E8%AF%95%E8%BF%90%E8%90%A5%E5%95%86_18888888888%0ASubId%EF%BC%9A0%0A2024-10-16%2014%3A46%3A32&timestamp=1729061192760
> ```
> 
> 这里的 content-type: application/x-www-form-urlencoded 需要改为 content-type: text/plain 像如下：
> 
> ```
> POST /api/bot/send_to_user/1 h2
> host: vocechat.com
> accept-language: zh-CN,zh;q=0.8
> user-agent: Mozilla/5.0 (Linux; U; Android 14; zh-cn; M2006J10C Build/AP2A.240805.005) AppleWebKit/533.1 (KHTML, like Gecko) Version/5.0 Mobile Safari/533.1
> x-api-key: xxxxxx
> content-type: application/x-www-form-urlencoded
> content-length: 416
> accept-encoding: gzip
> cache-control: no-cache
> 
> Some Message
> ```
> 
> 详情请参看 http://localhost:3009/api/doc
> 
> ```
> 发现，当将 Content-Type 设置为 text/plain 时，OkHttp 的 RequestBody.create 方法会在没有设置 charset 的情况下自动添加 ; charset=utf-8，导致请求头变成了 text/plain; charset=utf-8。
> ```
> 
> 这个可能与 Cloudflare 有关？正常是不会修改头的。

只能说 `VoceChat` 不够规范（或 `content-type` 判断没做好）

`OkHttp` 在请求时自动拼接 `charset=utf-8` 主要是为了确保文本内容能够被正确解析和显示。`text/plain` 本身并没有默认的字符编码，添加 `charset=utf-8` 明确了使用的编码方式，避免了潜在的乱码问题，这也符合网络协议的最佳实践！

注意看56行代码：

![OkHttp](https://private-user-images.githubusercontent.com/63391334/377814823-49db3a7f-2e3a-4927-ac9b-81312af9f5e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMzE2MzAsIm5iZiI6MTcyOTMzMTMzMCwicGF0aCI6Ii82MzM5MTMzNC8zNzc4MTQ4MjMtNDlkYjNhN2YtMmUzYS00OTI3LWFjOWItODEzMTJhZjlmNWU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDA5NDg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2NDcxY2ZhMDBiZmU3NmQyZDdjNjllMjVkYTQ3ZTMzMDQ4MGY2MDM2M2U5OWNmMjJjYzM1YmI5M2JhNmVjYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rLzVgxcUqNt3IwCA6E7Ggeu9ZHpe3to76bWfr6qXSWQ "OkHttp")

PS. `application/x-www-form-urlencoded` 不需要，是因为它已经 `urlencoded`
