### ISSUE TITLE
[Bug]: [发送通道], [转发规则]都测试成功. 但是不能自动转发短信, 并且没有转发日志

### ISSUE THREAD

**Issue by murara1900** [pppscn/SmsForwarder#533]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

否（No）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

v3.3.2.240815

### 问题描述

发送通道:
我分别设置了短信和钉钉机器人 / 测试成功
![image](https://github.com/user-attachments/assets/9719095a-bc42-4218-a233-b45be104d8a1)

转发规则:
分别配置了短信和应用 / 测试成功
![image](https://github.com/user-attachments/assets/404b0c65-7dd9-47b7-aeeb-988258a2678c)

但均无转发日志

### 复现步骤

用我的主机给备机发送一条短信. 备机成功收到短信 

### 是否必现

是（Yes）

### 出现问题的手机信息

主机: Google Pixel8 / 备机: 华为P30

### 出现问题的安卓版本、系统版本

主机 Android 15 / 备机 鸿蒙4

### 提供截图或视频

![微信图片_20241015103631](https://github.com/user-attachments/assets/d7c18c77-1015-438e-b1c0-f4f615f9dab1)
![微信图片_20241015103638](https://github.com/user-attachments/assets/a8a1afcd-3b67-43c3-b24a-894a0e4a5cdb)
![微信图片_20241015103624](https://github.com/user-attachments/assets/d5fa5abc-f898-47c3-a4c8-ff8c22c71e99)
![微信图片_20241015103621](https://github.com/user-attachments/assets/a082aa86-a936-4a2d-aefc-c4cb35f90e3e)
![微信图片_20241015103619](https://github.com/user-attachments/assets/bc23151a-ae54-4ff6-83ef-ce65fd7994cd)
![微信图片_20241015103616](https://github.com/user-attachments/assets/edb9fe79-aa86-428e-90af-88664f1ac9ef)
![微信图片_20241015103605](https://github.com/user-attachments/assets/9d4a1896-11c9-4429-94db-c11c72cab38c)

**Comment by hiytom** [comment]
我也遇到了一模一样的问题，也是这个app版本。
手机：vivo iQOO，安卓14

**Comment by amassare** [comment]
检查一下设置中sm卡的名称，通知文本是否为空。

**Comment by amassare** [comment]
我当时就是sm卡别名，通知文本那里是空的，日志里面怎么都是空的

**Comment by miaozilong** [comment]
我的也有这个情况，把短信通知打开就好了。

**Comment by murara1900** [comment]
> 我当时就是sm卡别名，通知文本那里是空的，日志里面怎么都是空的

请问通知文本在哪里呀？我没找到

**Comment by murara1900** [comment]
> 我的也有这个情况，把短信通知打开就好了。

请问在哪里设置呀？

**Comment by amassare** [comment]
![Screenshot_20241017_105127_SmsForwarder](https://github.com/user-attachments/assets/29425e2e-9563-4f48-8e49-df7e7e063d8f)

**Comment by murara1900** [comment]
> ![Screenshot_20241017_105127_SmsForwarder](https://private-user-images.githubusercontent.com/62787567/377293220-29425e2e-9563-4f48-8e49-df7e7e063d8f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxMzQ2OTgsIm5iZiI6MTcyOTEzNDM5OCwicGF0aCI6Ii82Mjc4NzU2Ny8zNzcyOTMyMjAtMjk0MjVlMmUtOTU2My00ZjQ4LThlNDktZGY3ZTdlMDYzZDhmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDAzMDYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2MzYwMDg1Y2VjMDJlZWMwNDRlY2E2OGIzMzU4ZjI0Njg3YmZkMzdjMDRjY2Y1NDE4ZjIxN2VjZTM2ZGE2YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3Sa7z-IXrs_ctCJOM-ehZm5A8FECAMeS_vEGSuibWCs)

我的有设置了还是不行。。
![PXL_20241017_030626354](https://github.com/user-attachments/assets/680db423-1d18-410d-86d9-edd99cd40108)

**Comment by pppscn** [comment]
1、短信广播 转发不出去的话，试试 通知转发 行不行；如果后者可以，考虑权限和验证码保护问题；如果连后者都不行，考虑保活问题

2、短信卡槽不对的，认真看看wiki， subid 不是随便填的
https://github.com/pppscn/SmsForwarder/wiki/1.%E9%80%9A%E7%94%A8%E8%AE%BE%E7%BD%AE

**Comment by murara1900** [comment]
> 1、短信广播 转发不出去的话，试试 通知转发 行不行；如果后者可以，考虑权限和验证码保护问题；如果连后者都不行，考虑保活问题
> 
> 2、短信卡槽不对的，认真看看wiki， subid 不是随便填的 https://github.com/pppscn/SmsForwarder/wiki/1.%E9%80%9A%E7%94%A8%E8%AE%BE%E7%BD%AE

我全都是按照wiki一步步设置的 短信/通知转发都不行

**Comment by leekHotline** [comment]
监听不到短信，可以尝试**转发**系统**应用**"短信"的**通知**
