### ISSUE TITLE
[Suggestion]: 请问能否做每隔一段时间唤醒一次短信转发器来转发消息

### ISSUE THREAD

**Issue by hzy132** [pppscn/SmsForwarder#534]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

备用机有的不太需要通知转发的实时性，短信转发器一直在后台运行太费电了(备用机电池一般都不行了)，

### 你觉得该怎么去完善会比较好？【非必答】

可以让用户设定一个30分钟或者其他的时间，可以用闹钟权限每隔固定时间唤醒一次短信转发器，判断哪些通知是没转发的，转发完后等待下一次

**Comment by miaozilong** [comment]
睡着的人最不容易醒了。

**Comment by pppscn** [comment]
smsf 都不在了，还怎么帮你先收着消息？

其他的看看 `自动任务` 发挥自己想象 组合
