### ISSUE TITLE
[Suggestion]: 可以在主动控制功能页内新增 esim管理配置吗🤩

### ISSUE THREAD

**Issue by Calle-99** [pppscn/SmsForwarder#535]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

远程管理esim 启用/禁用 配置
https://github.com/estkme-group/lpac/blob/main/docs/USAGE.md
这个程序会方便实现这个功能吗🥰

有个类似的项目 https://github.com/damonto/telegram-sms 是通过tg管理esim配置

**Comment by pppscn** [comment]
不会增加类似的功能（去修改系统设置或禁用启用信号等），这是红线，怕被别有用心的人利用，已经有人拿着这个app去诈骗了
