### ISSUE TITLE
[Suggestion]: 添加 telegram 消息10分钟自动删除； 添加支持 google voice

### ISSUE THREAD

**Issue by Acytoo** [pppscn/SmsForwarder#536]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

需求场景：帮一些朋友收验证码。

1. tg bot 在群组中转发消息时，过多的短信消息会淹没正常的聊天消息，加入自动删除功能方便聊天。

2. 支持转发 google voice 的短信。

**Comment by pppscn** [comment]
1、去找一个 群机器人 实现

2、直接监听不行，或许可以通过 app通知转发的形式实现
