### ISSUE TITLE
[Suggestion]: bark 加入copy字段

### ISSUE THREAD

**Issue by dirichy** [pppscn/SmsForwarder#538]
### 是否有人曾提过类似的问题？

是（Yes）

### 你觉得APP有什么不足之处？

转发验证码时想要转发整个短信而只复制验证码的部分，bark有一个copy字段可以支持内容与复制内容不同，但是在app中没有找到对应的设置项目。希望可以增加一个copy字段，支持模板和正则。这样就可以在转发整个短信的基础上实现只复制验证码了。

### 你觉得该怎么去完善会比较好？【非必答】

希望可以增加一个copy字段，支持模板和正则。这样就可以在转发整个短信的基础上实现只复制验证码了。

此外，有些替换可能用正则并不能实现，是否考虑支持使用脚本进行替换，例如js或者lua？这样可以极大提高替换规则的上限。

**Comment by pppscn** [comment]
覆盖安装 `每周构建版` 试试 **（等待在线编译完成）**

**升级操作提示：** 
- `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
-  手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml
