### ISSUE TITLE
Android5.1表示无缘了吗？

### ISSUE THREAD

**Issue by yanjianbo77** [pppscn/SmsForwarder#54]
我是魅蓝3s  放在现在都是垃圾玩意，但就是省电持久待机，偏偏只有5.1

**Comment by pppscn** [comment]
Android 5.x 系列之前 1.6.3 或 1.6.4 先试试，部分功能可能不正常，所以1.7.0就去掉了

自己编译的话，可以尝试把 minSdkVersion 改为 21 然后试试

**Comment by pppscn** [comment]
V2.2.0 已经增加Android 5.x 支持，可以试试

https://github.com/pppscn/SmsForwarder/releases/tag/v2.2.0

**Comment by yanjianbo77** [comment]
谢谢，已成功安装使用，稳定性待观察




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月23日(星期二) 中午12:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pppscn/SmsForwarder] Android5.1表示无缘了吗？ (Issue #54)





 
V2.2.0 已经增加Android 5.x 支持，可以试试
 
https://github.com/pppscn/SmsForwarder/releases/tag/v2.2.0
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
