### ISSUE TITLE
[Suggestion]: 首页弹窗标题和内容没做 i18n

### ISSUE THREAD

**Issue by kvii** [pppscn/SmsForwarder#544]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

首页的这个弹窗内容看了一下是拿的 wiki 里面的 tips.json。但是这个东西没做 i18n 啊。比如用英语的话就是这样。

<img src="https://github.com/user-attachments/assets/92c6122e-c8c6-4e2b-a536-7819e53da359" height="600">

当然这纯属我吹毛求疵了。不改也行。

**Comment by pppscn** [comment]
覆盖安装 `每周构建版` 试试 **（等待在线编译完成）**

**升级操作提示：** 
- `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
-  手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by kvii** [comment]
没安装每周构建版，自己本地打包试了下，是可以的。关闭 issue。
