### ISSUE TITLE
[Suggestion]:  如果转发设备断网了，如何发送离线提醒给接收设备

### ISSUE THREAD

**Issue by gqs4352** [pppscn/SmsForwarder#551]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

如果转发设备断网了，如何发送离线提醒给接收设备，能否在某个自建服务端弄一个定时任务 ，隔一段时间去看看设备是否在线，不在线了就发送提醒给接受设备

### 你觉得该怎么去完善会比较好？【非必答】

能否在某个自建服务端弄一个定时任务 ，隔一段时间去看看设备是否在线，不在线了就发送提醒给接受设备

**Comment by ZGLinus** [comment]
我的方法是通过frp把主动控制的服务端端口映射到公网，然后用uptimerobot监控这个端口，免费计划的每5分钟检查一次对我来说够用了。这样无论是转发器后台被杀还是网络断了，都会导致公网服务不可用，uptimerobot会发邮件提醒我这个情况。
![1731158615631](https://github.com/user-attachments/assets/f8eb5022-326c-4871-bdc6-9b6eaa0499b5)

**Comment by gqs4352** [comment]
> 我的方法是通过frp把主动控制的服务端端口映射到公网，然后用uptimerobot监控这个端口，免费计划的每5分钟检查一次对我来说够用了。这样无论是转发器后台被杀还是网络断了，都会导致公网服务不可用，uptimerobot会发邮件提醒我这个情况。 ![1731158615631](https://private-user-images.githubusercontent.com/69845097/384606946-f8eb5022-326c-4871-bdc6-9b6eaa0499b5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNTkxODQsIm5iZiI6MTczMTE1ODg4NCwicGF0aCI6Ii82OTg0NTA5Ny8zODQ2MDY5NDYtZjhlYjUwMjItMzI2Yy00ODcxLWJkYzYtOWI2ZWFhMDQ5OWI1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDEzMjgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhYWQ0MWEyNzllMDM3YmNlNWYxYmE5ZDhhMzU1ODI3ZTIyZjhhYjg2ZGJmOWFmZTM0ODE0MzM0MzdkY2VmYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.k_bx4mv81zNQoJj-yxZYUVqH0FxJcIOcr2BP-s5h6Co)

通过frp把主动控制的服务端端口映射到公网, 这个是怎么操作的 大佬

**Comment by ZGLinus** [comment]
> > 我的方法是通过frp把主动控制的服务端端口映射到公网，然后用uptimerobot监控这个端口，免费计划的每5分钟检查一次对我来说够用了。这样无论是转发器后台被杀还是网络断了，都会导致公网服务不可用，uptimerobot会发邮件提醒我这个情况。 ![1731158615631](https://private-user-images.githubusercontent.com/69845097/384606946-f8eb5022-326c-4871-bdc6-9b6eaa0499b5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNTkxODQsIm5iZiI6MTczMTE1ODg4NCwicGF0aCI6Ii82OTg0NTA5Ny8zODQ2MDY5NDYtZjhlYjUwMjItMzI2Yy00ODcxLWJkYzYtOWI2ZWFhMDQ5OWI1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDEzMjgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhYWQ0MWEyNzllMDM3YmNlNWYxYmE5ZDhhMzU1ODI3ZTIyZjhhYjg2ZGJmOWFmZTM0ODE0MzM0MzdkY2VmYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.k_bx4mv81zNQoJj-yxZYUVqH0FxJcIOcr2BP-s5h6Co)
> 
> 通过frp把主动控制的服务端端口映射到公网, 这个是怎么操作的 大佬

具体是那一步有问题？如果是没有公网服务器，那就可以去找那些提供内网穿透的服务商，最好是带有海外节点的，因为可以用tcp隧道直接穿透http流量。

**Comment by gqs4352** [comment]
> > > 我的方法是通过frp把主动控制的服务端端口映射到公网，然后用uptimerobot监控这个端口，免费计划的每5分钟检查一次对我来说够用了。这样无论是转发器后台被杀还是网络断了，都会导致公网服务不可用，uptimerobot会发邮件提醒我这个情况。 ![1731158615631](https://private-user-images.githubusercontent.com/69845097/384606946-f8eb5022-326c-4871-bdc6-9b6eaa0499b5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNTkxODQsIm5iZiI6MTczMTE1ODg4NCwicGF0aCI6Ii82OTg0NTA5Ny8zODQ2MDY5NDYtZjhlYjUwMjItMzI2Yy00ODcxLWJkYzYtOWI2ZWFhMDQ5OWI1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDEzMjgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhYWQ0MWEyNzllMDM3YmNlNWYxYmE5ZDhhMzU1ODI3ZTIyZjhhYjg2ZGJmOWFmZTM0ODE0MzM0MzdkY2VmYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.k_bx4mv81zNQoJj-yxZYUVqH0FxJcIOcr2BP-s5h6Co)
> > 
> > 
> > 通过frp把主动控制的服务端端口映射到公网, 这个是怎么操作的 大佬
> 
> 具体是那一步有问题？如果是没有公网服务器，那就可以去找那些提供内网穿透的服务商，最好是带有海外节点的，因为可以用tcp隧道直接穿透http流量。

我弄好了， 非常完美感谢🙇‍
