### ISSUE TITLE
[Suggestion]: 自动任务-快捷指令中，可以添加震动的功能

### ISSUE THREAD

**Issue by limit81995** [pppscn/SmsForwarder#554]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

目前我在其中看到的有声音提示，但是想要个震动提示。因为有时候在一些特定场景可能带着耳机，只有手机震动才能感觉到手机收到了一些信息。

**Comment by pppscn** [comment]
![警报提醒](https://github.com/user-attachments/assets/322d8cc6-431e-4f6d-bef2-10d8ef363a60)

> 语法：=[强振动], -[弱震动], _[不振动], 每次100ms

覆盖安装 `每周构建版` 试试 **（等待在线编译完成）**

**升级操作提示：** 
- `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
-  手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml

**Comment by cnbilinyj** [comment]
这个我有提过，但是不是单独提的，你单独提了之后他就加了，也算是你帮我提过了吧，也是谢谢你哈

**Comment by limit81995** [comment]
很感谢，但是如果可以  设置重复次数为0时，循环震动。那么就符合我希望的功能。
@pppscn

**Comment by limit81995** [comment]
> 很感谢，但是如果可以 设置重复次数为0时，循环震动。那么就符合我希望的功能。 @pppscn

可以看一下这个功能可以添加吗

**Comment by cnbilinyj** [comment]
那还需要能够停止震动的功能发件人: ***@***.*** ***@***.***> 代表 limit81995 ***@***.***>发送时间: 星期五, 十一月 15, 2024 10:14:10 上午收件人: pppscn/SmsForwarder ***@***.***>抄送: 农药君 ***@***.***>; Comment ***@***.***>主题: Re: [pppscn/SmsForwarder] [Suggestion]: 自动任务-快捷指令中，可以添加震动的功能 (Issue #554)

很感谢，但是如果可以 设置重复次数为0时，循环震动。那么就符合我希望的功能。 @pppscn

可以看一下这个功能可以添加吗

**Comment by pppscn** [comment]
`停止警报` 会停止 播放 和 振动

无限重复震动  没多大意义吧？   自定义模板没长度限制了，重复次数最大能30次了   一条提醒   你还要振动多久？

**Comment by cnbilinyj** [comment]
也许他是怕万一震动的时候，当时人刚好不在场呢，那么只要拿到手机一看，诶，它在震动就知道哦，他现在还在持续提醒，这些是有一些极其紧急的提醒所需要的发件人: ***@***.*** ***@***.***> 代表 pppscn ***@***.***>发送时间: 星期五, 十一月 15, 2024 12:06:57 下午收件人: pppscn/SmsForwarder ***@***.***>抄送: 农药君 ***@***.***>; Comment ***@***.***>主题: Re: [pppscn/SmsForwarder] [Suggestion]: 自动任务-快捷指令中，可以添加震动的功能 (Issue #554)
停止警报 会停止 播放 和 振动
无限重复震动  没多大意义吧？   自定义模板没长度限制了，重复次数最大能30次了   一条提醒   你还要振动多久？

**Comment by limit81995** [comment]
> `停止警报` 会停止 播放 和 振动
> 
> 无限重复震动 没多大意义吧？ 自定义模板没长度限制了，重复次数最大能30次了 一条提醒 你还要振动多久？

场景和 @cnbilinyj  说的上面提到的相似。

具体需求这些功能是这样。
有些时候有一些提醒是需要第一时间去相应的，此时刚好在公共场合大家都在安静休息（图书馆，办公区域等），这个时候肯定是不能使用铃声的只能使用震动代替，但是此时如果刚好出门拿了个东西或者去洗了个手等 2-3分钟的时间，回来的时候震动刚好消失，却错过了一些重要的内容。

晚上在带着耳机看视频的时候，一些声音可能过大，此时可能在吃东西 身体可能并未与桌面接触，可能就感受不到震动，所以就需要长时间的震动来让我尽快的感知到一些重要的提示。

这些就是需要的场景。

我平时做开发的时候遵循配置相似功能相似的规则，这样可以让用户再不看教程的情况下更快的使用自己开发的功能。所以再使用你的预发布版时候就直接尝试了设置为0想体验到无限的功能，然后发现并没有无限的设置。

再次感谢作者关注到我们这些的求助。

**Comment by pppscn** [comment]
```kotlin
data class AlarmSetting(
    var description: String = "", //描述
    var action: String = "stop", //动作: start=启动警报, stop=停止警报
    var volume: Int = 80, //播放音量，0-100
    var playTimes: Int = 1, //播放次数，0=无限循环，-1=禁用
    var music: String = "", //音乐文件
    var repeatTimes: Int = 5, //振动重复次数，0=无限循环，-1=禁用
    var vibrate: String = "---___===___", //振动律动：=强振动, -弱震动, _不振动, 时长都是100ms
) : Serializable
```

覆盖安装 `每周构建版` 试试 **（等待在线编译完成）**

**升级操作提示：** 
- `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
-  手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml
