### ISSUE TITLE
[Bug]: 保活问题

### ISSUE THREAD

**Issue by canglanpojing** [pppscn/SmsForwarder#555]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

否（No）

### 是否已经查阅Wiki文档还未能解决的

是（Yes）

### APP版本

SmsF_3.3.2.240815_100053_universal_release.apk

### 问题描述

我是转发至钉钉群 现在有一个问题就是 软件如果是后台运行 钉钉群就无法收到转发的信息 只有点开软件 钉钉群才会收到短信转发

### 复现步骤

我是转发至钉钉群 现在有一个问题就是 软件如果是后台运行 钉钉群就无法收到转发的信息 只有点开软件 钉钉群才会收到短信转发

### 是否必现

是（Yes）

### 出现问题的手机信息

一加手机

### 出现问题的安卓版本、系统版本

Android14

**Comment by pppscn** [comment]
应该属于保活问题，手机设置先排查，再不行看看下面这个wiki，还不行的话用第三方app保活（可能需要root之类的）

https://github.com/pppscn/SmsForwarder/wiki/%E9%99%84%E5%BD%954%EF%BC%9AAPP%E6%80%8E%E4%B9%88%E4%BF%9D%E6%B4%BB%EF%BC%88%E6%9D%80%E4%B8%8D%E6%AD%BB%EF%BC%89%EF%BC%9F
