### ISSUE TITLE
[Bug]: 卡巴斯基报毒

### ISSUE THREAD

**Issue by Payton443** [pppscn/SmsForwarder#556]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

否（No）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

v3.3.2

### 问题描述

使用电脑下载直接被卡巴斯基拦截

### 复现步骤

<img width="516" alt="smsf-kaba" src="https://github.com/user-attachments/assets/42125e8b-4aa2-42e2-8c59-d2bf2d62a26b">
下载完成后卡巴斯基直接报毒

### 是否必现

是（Yes）

### 出现问题的手机信息

无关手机

### 出现问题的安卓版本、系统版本

无关手机

### 提供截图或视频

<img width="516" alt="smsf-kaba" src="https://github.com/user-attachments/assets/5e756a4e-fb4c-4ce4-a91c-86fb8512900b">

**Comment by pppscn** [comment]
疑似跟 frp （或 golang）有关，实在不放心就换一个app吧

一个手机APP难道还要给PC杀毒软件交保护费？

**Comment by pppscn** [comment]
这是在线检测的结果，自辨

> Kaspersky：not-a-virus:HEUR:RiskTool.AndroidOS.Revpn.m
> Avira：Android/SmsFow.YJT.Gen
> AhnLab：PUP/Android.SmsForw.1234562

https://www.virscan.org/report/b659469172d00b8f1092ade86ae0d8ae471e0629697d0bb60911bb7381e33cf1

https://www.virscan.org/report/46927d3de5c47f1a8137108dd8b35035f8a8aa2b3042ee699ae1cb90a13b181b

**Comment by pppscn** [comment]
再看看GPT的解析吧，100%开源的东西，不放心就自己编译，还担心我夹带私货的话，出门右拐不送

![wechat_2024-11-16_201911_254](https://github.com/user-attachments/assets/ef89bf3f-ece6-4e6e-acfd-34932b4ea60b)
![wechat_2024-11-16_201944_594](https://github.com/user-attachments/assets/f1ed9ad0-9f49-4252-9dfb-a5f130a47ed8)
![wechat_2024-11-16_201959_092](https://github.com/user-attachments/assets/e7e43d5d-e483-43f8-a1a7-25d0faf2ff50)

**Comment by pppscn** [comment]
另外，再告诉你一件更恐怖的事情，这是 96110 钦定的诈骗软件！请各位谨慎考虑是否安装！

![微信图片_2024-11-16_202754_514](https://github.com/user-attachments/assets/b76d81ef-9f28-4c6c-8429-2c4ed3d959f8)
![微信图片_2024-11-16_202759_066](https://github.com/user-attachments/assets/1457985e-74bf-4d4a-a6ac-f6ebba5f9854)
