### ISSUE TITLE
是否有适配鸿蒙NEXT的安排

### ISSUE THREAD

**Issue by x-herror** [pppscn/SmsForwarder#557]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

公司统一分配工作机是华为的，后续将会升到NEXT上，而自己主力安卓，之前都是将信息转发到主力机上，请问后续是否有适配鸿蒙NEXT的安排

### 你觉得该怎么去完善会比较好？【非必答】

是否有适配鸿蒙NEXT的安排

**Comment by pppscn** [comment]
什么公司让它也给我安排一台鸿蒙next吧，目前买不起，等我买得起再考虑
