### ISSUE TITLE
[Bug]: 只能在前台模式下会转发，锁屏或者亮屏后处于后台都不行

### ISSUE THREAD

**Issue by jjj252525** [pppscn/SmsForwarder#558]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

v3.3.2

### 问题描述

只能在前台模式下会转发，锁屏或者亮屏后处于后台都不行

### 复现步骤

锁屏或者亮屏后处于后台都不行

### 是否必现

是（Yes）

### 出现问题的手机信息

华为p30pro

### 出现问题的安卓版本、系统版本

鸿蒙4.0

**Comment by pppscn** [comment]
参考这个看看，不行的话就没辙了，华为跟荣耀杀后台比较严重

https://github.com/pppscn/SmsForwarder/wiki/%E3%80%90%E5%BF%85%E8%AF%BB%E3%80%91%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#q%E4%B8%BA%E4%BB%80%E4%B9%88%E9%94%81%E5%B1%8F%E4%BA%86%E8%BD%AF%E4%BB%B6%E5%B0%B1%E4%B8%8D%E8%BF%90%E8%A1%8C%E8%A7%A3%E9%94%81%E4%BA%86%E6%89%8D%E8%BD%AC%E5%8F%91%E4%BA%AE%E5%B1%8F%E7%8A%B6%E6%80%81%E4%B8%8B%E8%BD%AC%E5%8F%91%E9%83%BD%E6%AD%A3%E5%B8%B8%E9%94%81%E5%B1%8F%E5%B0%B1%E6%B2%A1%E6%9C%89%E6%97%A5%E5%BF%97%E6%88%96%E8%80%85%E9%83%BD%E6%98%AF%E8%BD%AC%E5%8F%91%E5%A4%B1%E8%B4%A5

**Comment by hanwenhao369** [comment]
我也是只能开着前台才可以转发，后台就不行，有没有什么办法

**Comment by wuxianggujun** [comment]
我的一加手机也是，都给了全部的权限。比如开启自启。省电不优化

**Comment by Z46I4W5476SJA** [comment]
> 我也是只能开着前台才可以转发，后台就不行。VIVO 手机，感觉应该不是后台被杀，有没有什么办法解决

vivo-设置-电池-省电管理-有一个睡眠待机优化  关了试试看呢
