### ISSUE TITLE
[Suggestion]: 建议自定义模板里的选项自动换行显示

### ISSUE THREAD

**Issue by huangzengsheng** [pppscn/SmsForwarder#559]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

自定义模板里的选项多会缩起来挤在一行显示，且显示不齐全。

### 你觉得该怎么去完善会比较好？【非必答】

建议自定义模板里的选项多了要自动换行，保证选项显示完整，不然缩短选项内容，挤在一行看不懂。

配图为自动任务里里面的。
![IMG_20241119_211601_990](https://github.com/user-attachments/assets/12ef2178-6bb1-4161-97fb-9eaaa180e70f)

**Comment by pppscn** [comment]
覆盖安装 `每周构建版` 试试 **（等待在线编译完成）**

**升级操作提示：** 
- `加入SmsF预览体验计划`后在线更新（`关于软件`页面开启，`v3.3.0_240305+`适用）
-  手动下载：https://github.com/pppscn/SmsForwarder/actions/workflows/Weekly_Build.yml
