### ISSUE TITLE
几个小建议

### ISSUE THREAD

**Issue by Sunny7010** [pppscn/SmsForwarder#56]
**非常感谢您开发次应用，给了我很大帮助，以下建议希望采纳，打造一个更好的应用**

建议加上转发所有通知消息，不仅仅是短信和电话，还有微信、QQ等等

建议在离线状态获取的短信消息暂存，待畅通网络状态时一并转发

**Comment by pppscn** [comment]
原计划双11来一个版本，这几天晚上都在医院陪护，只能搁浅了

第一点进行种

第二点暂不考虑

**Comment by pppscn** [comment]
第一点已经提交，准备QQ群内测
