### ISSUE TITLE
[Suggestion]: 希望在钉钉群添加根据短信转发内容@指定成员的功能

### ISSUE THREAD

**Issue by alphafeichuman** [pppscn/SmsForwarder#560]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

并不是不足，而是我目前想要和主创(感兴趣的技术人也可以)一起开创这个项目，因为这在实现办公自动化非常有用

### 你觉得该怎么去完善会比较好？【非必答】

具体细节我可以实现，但是我不知道如何进入app内核钉钉模块进行修改，希望得到主创和大家的支持

**Comment by pppscn** [comment]
一组 `@指定成员`  建立一个 `发送通道`

创建多条 `转发规则` 分别根据匹配规则转到对应的 `发送通道`
