### ISSUE TITLE
[Suggestion]: frpc是否可以自由选择使用老版本？

### ISSUE THREAD

**Issue by lovehfn** [pppscn/SmsForwarder#562]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

直接使用到最新的frpc，还要重新部署frps，其他地方的frpc也要重新部署。

### 你觉得该怎么去完善会比较好？【非必答】

是否可以自由选择frpc版本

**Comment by pppscn** [comment]
这个就没有必要再做向前兼容，都想直接砍了，自己安装第三方app也能实现
