### ISSUE TITLE
[Suggestion]: import/export config

### ISSUE THREAD

**Issue by Hamed-Deve** [pppscn/SmsForwarder#563]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

The app currently lacks the functionality to import and export configuration settings. This limitation makes it difficult for users to efficiently transfer, back up, or replicate their configurations across different phone

### 你觉得该怎么去完善会比较好？【非必答】

Adding the ability to import and export configuration files would significantly enhance the app's usability. It would provide users with greater flexibility, simplify the setup process, and improve overall user experience by saving time and reducing manual effort.

**Comment by pppscn** [comment]
![微信图片_2024-11-30_110948_320](https://github.com/user-attachments/assets/47885785-00b8-44a9-a849-aa84e4d0622f)
![微信图片_2024-11-30_110954_104](https://github.com/user-attachments/assets/ec0c84af-ab81-4d50-bf86-f7af0edcac29)
![微信图片_2024-11-30_110958_265](https://github.com/user-attachments/assets/82152697-3780-455a-b91c-dd1eb2fb2085)
![微信图片_2024-11-30_111007_181](https://github.com/user-attachments/assets/ffa57572-4379-4e23-b683-94515a719909)

The import and export settings feature is already available, with two options: network and offline.
