### ISSUE TITLE
[Bug]: 在同一时间接收并转发两个短信至邮箱，会有一方或者两方转发失败。

### ISSUE THREAD

**Issue by RisingRealmMinecraftserver** [pppscn/SmsForwarder#565]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

是（Yes）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

v3.3.2

### 问题描述

可不可以在通用设置里面添加一个调整每个短信至少间隔多少秒转发

### 复现步骤

前提设置：
发送通道设置：发件邮箱为QQ邮箱，再复制一个。
转发规则：
 1号规则：
  多重匹配：并且 是 短信内容 开头 【腾讯科技】你正在「登录QQ
   或者 是 手机号 相等 106586780151800
  并且 是 短信内容 包含 验证码

  使用设置的一号通道
  不限卡槽
 二号规则：
  匹配字段：全部
  不限卡槽
  使用设置的二号通道

情景还原：

在同一时间（精确到分）
发送：【腾讯科技】你正在「登录QQxx******xx」，验证码xxxxxx。提供给他人会导致QQ被盗和资产损失，若非本人操作，请修改密码。

(使用任意数字代替x)
错误截图如下
（图1）![Screenshot_20241203_194500_com idormy sms forwarder](https://github.com/user-attachments/assets/cac8efb9-b2ac-4505-bb5f-fc2ee1a8058b)

4分钟前的截图
（图2）

### 是否必现

是（Yes）

### 出现问题的手机信息

华为畅享10 plus

### 出现问题的安卓版本、系统版本

鸿蒙OS3

### 提供截图或视频

图1
![Uploading Screenshot_20241203_201538.jpg…]()
图2
![Uploading Screenshot_20241203_194500_com.idormy.sms.forwarder.jpg…]()

**Comment by pppscn** [comment]
认真看看你截图的中的错误提示，这是QQ邮箱要求使用授权码（不是邮箱登录密码）

**Comment by RisingRealmMinecraftserver** [comment]
当时我正在上学，如无法触碰手机，而我第二个截图是在这个时间的前四分钟，这个四分钟前授权码是OK的，在上学就意味着我无法修改授权码

**Comment by RisingRealmMinecraftserver** [comment]
后来我又去测试了一下，授权码是OK的

**Comment by RisingRealmMinecraftserver** [comment]
的确，我是在QQ直接申请的QQ授权码，但是我在学校里面，往我手机上发送了多个短信，只有部分短信会收到，



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月3日(周二) 晚上8:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [pppscn/SmsForwarder] [Bug]: 在同一时间接收并转发两个短信至邮箱，会有一方或者两方转发失败。 (Issue #565)




 
认真看看你截图的中的错误提示，这是QQ邮箱要求使用授权码（不是邮箱登录密码）

**Comment by RisingRealmMinecraftserver** [comment]
RisingRealm_server的自动回复邮件我们已经收到您的邮件我们会在1-5个工作日回复您的邮件
