### ISSUE TITLE
[Suggestion]: 部分系统消息无法屏蔽（量很大，但又没有用的系统消息）

### ISSUE THREAD

**Issue by yhbylb** [pppscn/SmsForwarder#566]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

com.android.mms
点按即可了解详情或停止应用。
“短信”正在运行
UID：10129
2024-12-08 02:04:01
红米K50

com.xiaomi.market
应用商店正在检查应用更新
UID：10165
2024-12-08 02:00:02
红米K50

这类消息又多又没办法屏蔽，看消息如果屏蔽“短信”这个APP，那么会收到短信消息嘛？

### 你觉得该怎么去完善会比较好？【非必答】

在屏蔽的时候，检测关键字，其实这类系统消息都是一致的除了时间不一致，其他几乎一致，就直接屏蔽《点按即可了解详情或停止应用。“短信”正在运行》即可。

钉钉不支持屏蔽关键字，所以只有希望作者了。

屏蔽规则可以是这种格式
com.android.mms 《关键字1》：屏蔽短信APP含有关键1的信息
com.android.mms 《关键字2》：屏蔽短信APP含有关键2的信息
com.android.mms  ：屏蔽短信APP所有信息

**Comment by pppscn** [comment]
1、`短信转发` 基于短信广播，`APP(通知)转发`是读取通知栏

2、`APP(通知)转发` 建议指定包名转发，而不是全部
