### ISSUE TITLE
[Bug]: 发件人的号码比较长的时候，就无法转发短信。例如，10682367547812254591

### ISSUE THREAD

**Issue by cheng2004237** [pppscn/SmsForwarder#567]
### 是否有人曾提过类似的问题

否（No）

### 升级到最新的版本是否存在这个问题

否（No）

### 是否已经查阅Wiki文档还未能解决的

否（No）

### APP版本

3.3.2.241121

### 问题描述

发件人的号码比较长的时候，就无法转发短信。例如，10682367547812254591，这个号码发过来的验证码就无法转发，已经打开了所有权限，以及关闭了验证码保护。

### 复现步骤

一直都是无法转发这些超长号码的

### 是否必现

否（No）

### 出现问题的手机信息

红米note12turbo

### 出现问题的安卓版本、系统版本

13

### 提供截图或视频

![20241211-151003](https://github.com/user-attachments/assets/c971b34e-ffba-4b4a-9f80-f0d77fb4a587)
![20241211-151009](https://github.com/user-attachments/assets/d4fab46c-564f-4359-ab44-922c36ba9bf4)

**Comment by oyyq99999** [comment]
我的小米civic也有类似问题，后来发现是权限设置里面最下面的其他权限，然后靠下最后一类“设置相关”里面的通知类短信没有授权，打开就好了
系统是hyperos 1.0.2.0
