### ISSUE TITLE
[Suggestion]: 建议提供远程通话功能

### ISSUE THREAD

**Issue by finch71** [pppscn/SmsForwarder#569]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

建议提供远程拨号和通话功能（如支持sip协议）

### 你觉得该怎么去完善会比较好？【非必答】

adb shell am start -a android.intent.action.CALL -d tel:+CCXXXXXXXXXX

With root:
https://github.com/chenxiaolong/BCP

**Comment by pppscn** [comment]
通话类的功能一律不会碰，可刑可拷！
