### ISSUE TITLE
[Suggestion]: 小米手机使用url发送get请求 会弹出浏览器

### ISSUE THREAD

**Issue by larancia** [pppscn/SmsForwarder#571]
### 是否有人曾提过类似的问题？

否（No）

### 你觉得APP有什么不足之处？

[Suggestion]: 小米手机使用url发送get请求 会弹出浏览器   在锁屏状态下 会丢失消息   是否可以优化 发送方式  类似请求企业微信机器人接口哪样 发送get请求 避免浏览器弹出

**Comment by pppscn** [comment]
你需要的是 `webhook`  而不是 `URL Scheme`，自己是不是选错发送通道了

**Comment by larancia** [comment]
用其他方式弄好了 感谢
