### ISSUE TITLE
SmsForwarder不兼容机型列表

### ISSUE THREAD

**Issue by pppscn** [pppscn/SmsForwarder#58]
https://kdocs.cn/l/cnWcY88VibLq
[金山文档] SmsForwarder不兼容机型列表.xlsx

**收集一下不能成功的机型列表  避免浪费机油的宝贵时间**

**Comment by Mosney** [comment]
“作者已设置文档需要登录查看”好不方便啊，可以试试石墨文档，这个好像支持公开查看

**Comment by shellus** [comment]
反了，不支持的试用一下就跑了，建议反过来，收集可用机型列表
