### ISSUE TITLE
可否添加转发到短信呢

### ISSUE THREAD

**Issue by lancelotpro** [pppscn/SmsForwarder#6]

**Comment by pppscn** [comment]
直接发短信，毕竟成本有点高，有其他的朋友有这个需求吗？ 超过5个人要的话就准备加上

**Comment by hh6681314** [comment]
我的手机卡套餐有免费短信。。反正不用白不用，所以我也想要这个功能

**Comment by lancelotpro** [comment]
有移动亲情网自带的免费短信互发，其实用途还是挺广的，最关键是副手机省掉联网装app，只要有信号就可以了

**Comment by pppscn** [comment]
今晚会发一个包，大家测试一下

**Comment by pppscn** [comment]
[v1.7.0](app/release/SmsForwarder_release_20210318_1.7.0.apk) 新增转发到其他手机短信 & 避免热插卡时FC & 规则展示优化 & 获取多卡信息&获取卡槽备注优 & 新增恢复初始化配置
