### ISSUE TITLE
miui 12 经常被杀

### ISSUE THREAD

**Issue by shaohongwu** [pppscn/SmsForwarder#60]
手机 ：小米8
系统： miui 12.0.4 稳定版
软件版本：2.1.1 
如题，我们在使用中，经常半夜出现掉线情况，猜测是被系统后台杀掉，有给加锁，有设置 电池无限制。不知道还有小米的用户也有这样的情况么？

**Comment by pppscn** [comment]
加QQ群吧，问问其他机油有没有类似的情况吧

**Comment by pppscn** [comment]
**稳定保活发送方案 使用红米9A手机：**

- 使用usb线接入电脑或者服务器。
- 安装adb组件。
- 打开开发者模式
- adb进行授权 `adb attach` 然后允许授权
- 配置定时任务每分钟执行命令 `adb shell am start -n com.idormy.sms.forwarder/com.idormy.sms.forwarder.MainActivity`
