### ISSUE TITLE
时间有误，会在手机时间的基础上加上8个小时

### ISSUE THREAD

**Issue by staywithdream** [pppscn/SmsForwarder#63]
时间有误，会在手机时间的基础上加上8个小时，如题，希望修改
手机时间：2021-11-17 16:41:22
接收时间字段：2021-11-18 00:41:22

接收时间不应该修改时间，应该按照手机时间直接转发，或者允许设置时区

**Comment by pppscn** [comment]
你的手机时区不是东八区？

**Comment by staywithdream** [comment]
是东八区，但是还是加了8小时。


pppscn ***@***.***> 于 2021年11月18日周四 14:12写道：

**Comment by pppscn** [comment]
具体的截图出来看看，使用哪个发送通道 会这样

**Comment by pppscn** [comment]
无法重现，QQ群友也没有类似现象

**Comment by longbinzhao** [comment]
我也遇到了，我的手机是 一加6T 两个手机插槽 只有第一个插槽有问题 并且两个SIM 卡也是不同的运营商 
所以不知道是手机问题 还是运营商问题
顺便说一句 我在国外
