### ISSUE TITLE
是否可以添加转发条件

### ISSUE THREAD

**Issue by harleywong** [pppscn/SmsForwarder#64]
如果可以的话，是否可以添加一些转发的条件，比如设置时间段，连上了某些WiFi之后才转发等等？
比如在公司的时候，手机静音了，连上了公司的WiFi，可以转发短信到飞书，这样就不用看手机了。但是一旦断开了公司的WiFi，就不需要再转发了。只是小建议，谢谢！

**Comment by pppscn** [comment]
太过复杂了，暂不考虑添加，谢谢你的建议
