### ISSUE TITLE
App通知转发和未接来电转发有冲突

### ISSUE THREAD

**Issue by DwayneZhang** [pppscn/SmsForwarder#65]
因为手机来电弹窗其实相当于App通知，然后会转发多次，截图还有一条来电通知没截完全。我这边一个电话打过来，会推送5条记录，一条来电，四条应用
![9c31dff4d592b11aeb91c585522a63f](https://user-images.githubusercontent.com/19589329/142232095-e06b4d53-c34f-4528-ab98-b56266f333cc.jpg)

**Comment by DwayneZhang** [comment]
应该过滤一下来电通知的包名的就行，如图上显示的com.android.dialer

**Comment by pppscn** [comment]
你自己编译偷跑了？app通知这一块还没完善，跟短信转发一样，需要手动指定规则的，目前界面还没搞，等下一次发版吧

**Comment by DwayneZhang** [comment]
QAQ，明白了，不好意思哈

**Comment by pppscn** [comment]
![Screenshot_1637246596](https://user-images.githubusercontent.com/5105854/142436893-134cc809-acc0-4773-9fd1-403e89625a81.png)

下一版本即将来临，我再琢磨一下 准备QQ群内测了
