### ISSUE TITLE
Telegram 自定义 api 的具体格式是什么

### ISSUE THREAD

**Issue by Editi0** [pppscn/SmsForwarder#69]
你好，比如我自己的 api 地址为 https://telegram.example.com ，Token 是 xxxx:xxxx，那么填入的具体格式是什么？

**Comment by pppscn** [comment]
http开头的就算自定义，至于token怎么传给你的自定义api，由你的api决定

**Comment by pppscn** [comment]
` 
       if (!apiToken.startsWith("http")) {
            apiToken = "https://api.telegram.org/bot" + apiToken + "/sendMessage";
        }
`
