### ISSUE TITLE
两个小建议，希望作者能加进ToDoList

### ISSUE THREAD

**Issue by xushuduo** [pppscn/SmsForwarder#7]
1. 新增模板页面，不同的转发规则使用不同的模板。
    - 比如我可以转发到邮箱的内容使用正常模板，转发到服务器的内容使用JSON的模板。
2. 关于邮件的发件人和主题，希望能自定义。
    - 现在发件人默认是“SmsForwarder”，我想通过“{{卡槽信息}}”标签改成卡槽手机号为发件人，这样微信或QQMail的推送过来通知就知道是那个手机收到的信息。

希望作者能加进ToDoList，抽空使App功能更加完善。
🌹小红花送上

**Comment by pppscn** [comment]
第一点，后面想想怎么规划比较合理

第二点 ，发送方邮箱允许自定义发件人昵称 见 v1.7.2；其他的也是要得空了想想怎么做，要支持标签的话变动挺大的

**Comment by pppscn** [comment]
添加转发规则时允许自定义模板，留空则取全局设置

![Uploading Screenshot_1636014441.png…]()
