### ISSUE TITLE
未接来电不能显示是哪个卡槽的

### ISSUE THREAD

**Issue by InImpasse** [pppscn/SmsForwarder#71]
未接来电不能显示是哪个卡槽的，希望可以在新功能中加入
现在是这样的
188xxxxxxxx
未知号码来电
未知号码
2021-11-20 23:40:42

**Comment by pppscn** [comment]
新版已经支持，等待发版后试试

提交记录：https://github.com/pppscn/SmsForwarder/commit/519ca3db5a6350793ccf1648b930443f5d687be4

**Comment by InImpasse** [comment]
好滴，很期待！
