### ISSUE TITLE
钉钉机器人的设置方法

### ISSUE THREAD

**Issue by Rambin** [pppscn/SmsForwarder#74]
发送通道设置参考
钉钉机器人
~~任意拉两个人成立一个群组，然后将其他人踢出群~~
使用手机面对面建群，输入4位数字后直接点击进入群聊

不过群聊机器人必须在电脑上配置

（另求配置文件保存到文件，从文件恢复，以及恢复初始化设置的二次确认）

**Comment by pppscn** [comment]
下一版再优化一键克隆的机制

**Comment by pppscn** [comment]
优化：恢复初始设置增加二次确认（防止误操作），初始化操作包括：重置设置、删除发送通道、规则、日志

下一版发布时带上
