### ISSUE TITLE
邮件转发是否可以新增POP和IAMP协议

### ISSUE THREAD

**Issue by findyy99** [pppscn/SmsForwarder#78]
目前我的邮箱账号暂时不支持SMTP协议，后期会考虑添加那两种协议吗

**Comment by pppscn** [comment]
POP不是用来收邮件的吗？  IMAP 可以考虑加上

**Comment by pppscn** [comment]
什么邮箱目前只能采用 IMAP 发送的，给个网址什么，我去看看

**Comment by findyy99** [comment]
> 

您好，我这边比较尴尬，学校把邮件系统托管在网易的邮件系统上，无法使用SMTP协议。我也不太懂IMAP能否用在客户端上发送邮件。
<img width="407" alt="image" src="https://user-images.githubusercontent.com/26852735/143591365-7f0b2060-5c56-42cd-a2c4-749ccf44b901.png">

**Comment by pppscn** [comment]
> 

你这截图的是收取，收取邮件确实可以有 POP 和 IMAP，我想知道的是 你发邮件出去也是用 IMAP ？

**Comment by findyy99** [comment]
> 

感谢回复，这个issue我关了吧，我已经换其他邮箱实现转发啦 :-)!!!

**Comment by pppscn** [comment]
![163-email](https://user-images.githubusercontent.com/5105854/143601315-ba689554-faaa-4dda-b57e-3321fd0c787e.png)

我去看了一下，163邮箱应该也是用smtp发邮件，imap收邮件

**Comment by findyy99** [comment]
> ![163-email](https://user-images.githubusercontent.com/5105854/143601315-ba689554-faaa-4dda-b57e-3321fd0c787e.png)
> 
> 我去看了一下，163邮箱应该也是用smtp发邮件，imap收邮件

嗯嗯，可能是因为那个邮箱是学生邮箱被阉割了SMTP。。。。

**Comment by pppscn** [comment]
了解了，有空的时候我去研究一下  用imap发邮件，你关注一下后续版本迭代

**Comment by RookieTerry** [comment]
> 了解了，有空的时候我去研究一下 用imap发邮件，你关注一下后续版本迭代

请问如果要使用自有域名邮箱发送邮件，应该在哪里填写@后面的自有域名呢？我的SMTP服务器托管在其它平台，所以域名和自有域名不一样
