### ISSUE TITLE
[Request] 请求添加Telegram通过socks5/HTTP代理转发的功能

### ISSUE THREAD

**Issue by fzxiao233** [pppscn/SmsForwarder#79]

**Comment by pppscn** [comment]
![QQ图片20211208223911](https://user-images.githubusercontent.com/5105854/145227366-5c77e201-3ba2-4aa9-95c8-f6a73c6d189a.png)

进QQ群来一波测试吧

**Comment by pppscn** [comment]
重点测试一下  带密码的 行不行  我没条件测试
