### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by RRZ1214** [pppscn/SmsForwarder#8]
安卓6.01 在应用市场下载其他软件安装正常，但在安装该软件时显示解析软件包时出现问题，已尝试过各种版本，都无法安装完成，用ADB安装显示[INSTALL_PARSE_FAILED_NO_CERTIFICATES]，麻烦大佬修复下吧
![image](https://user-images.githubusercontent.com/76157418/112265001-b393bf00-8cac-11eb-99a8-65b94a012f5f.png)
![image](https://user-images.githubusercontent.com/76157418/112409091-d5944c80-8d53-11eb-9f10-1f30ede041ba.png)

**Comment by pppscn** [comment]
[v1.7.2](app/release/SmsForwarder_release_20210325_1.7.2.apk) 新增V1版证书签名，避免部分低版本系统(Android 6.x)无证书错误 & 发送方邮箱允许自定义发件人昵称

**Comment by linkimfly** [comment]
> [v1.7.2](app/release/SmsForwarder_release_20210325_1.7.2.apk) 新增V1版证书签名，避免部分低版本系统(Android 6.x)无证书错误 & 发送方邮箱允许自定义发件人昵称

我也遇到无法安装的问题，1.7.2链接打不开了，是删除了吗
