### ISSUE TITLE
加电源状态提醒

### ISSUE THREAD

**Issue by zhebvuhuiya** [pppscn/SmsForwarder#81]
有没有办法充电百分百时候，提醒一下，拔下充电器，并且把低电量模式提醒时候，插入充电器不会到那个临界值再次提醒一遍，希望开发者可以完善！千万感谢🙏🙏

**Comment by pppscn** [comment]
![QQ图片20211207005942](https://user-images.githubusercontent.com/5105854/144888945-b83d9fdd-099b-433f-bcb6-ff516a66e41d.png)
![QQ图片20211207005946](https://user-images.githubusercontent.com/5105854/144888950-cfbec1b7-68a1-427c-8448-9c2b1c4ff447.png)
![Screenshot_1638803975](https://user-images.githubusercontent.com/5105854/144888951-6a867526-8499-4dc3-92ec-9c94ed894d4c.png)

**Comment by pppscn** [comment]
https://github.com/pppscn/SmsForwarder/commit/cdeed5cfc3b90b55ab6ecd26624591b6e5f3ceb5

已提交
