### ISSUE TITLE
数次没有发送电量预警消息

### ISSUE THREAD

**Issue by Rambin** [pppscn/SmsForwarder#82]
能否在自定义模板里添加当前电量标签，允许用户自主选择是否每条消息发送电量

**Comment by pppscn** [comment]
暂不考虑，已经有电量提醒与状态通知了

参见：https://github.com/pppscn/SmsForwarder/issues/81

**Comment by Rambin** [comment]
然而我说的就是电量提醒根本没发
电池优化关掉了，通知也开着的

**Comment by pppscn** [comment]
Q：升级到2.2.0+，为什么低电量预警不转发了？
A：2.2.0之后，规则分成三种类型（短信、来电、APP），APP规则里面加一条，包名 是 88888888

包名：88888888、内容：当前剩余电量：xx%，已经到达低电量预警阈值，请及时充电！

https://github.com/pppscn/SmsForwarder/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by Rambin** [comment]
算我没看到，电量通知还作为需要看在线QA的隐藏功能了
不过这操作太怪了，电量通知作为APP通知发
设置里电量阈值也没提示要加规则，未来建议考虑改到设置里去
