### ISSUE TITLE
希望增加规则顺序和是否继续的 配置

### ISSUE THREAD

**Issue by kuyagic** [pppscn/SmsForwarder#83]
场景如下
一条短信 有 银行 又有 验证码 的关键字

我针对银行 和验证码 配置了2条规则 则这条短信会被转发2次到目标。
有时候我只想不错过所有的银行 和 所有的验证码的消息。

是否可以设置一条短信只匹配一次规则 或者 有个 规则的执行顺序 和是否执行吓一条匹配的 配置。

**Comment by pppscn** [comment]
现在每一条规则是独立判断的  从上到下遍历  规则与规则之间没有逻辑关系

例如：

内容  正则匹配   电信|平安|验证码|密码

要手机号与内容还有逻辑判断  就用  多重匹配规则

现有的能满足你的要求  只要你想想这么配置  一条规则能覆盖你要转发的内容

多条规则之间不要有交集  就不会重复发
