### ISSUE TITLE
多重匹配问题

### ISSUE THREAD

**Issue by photkey** [pppscn/SmsForwarder#85]
![Snipaste_2021-12-14_10-24-33](https://user-images.githubusercontent.com/60434581/145921666-cc3bc71c-7535-4cb3-8a50-c8ef47aa62db.png)
请问一下，是软件的问题，还是我写的规则有问题？

**Comment by pppscn** [comment]
已经修复bug

详见 https://github.com/pppscn/SmsForwarder/commit/1c2d4c7b0a8f5c4972c0d352c7597339aa869059

**Comment by pppscn** [comment]
QQ群文件：SmsForwarder_release_20211214_2.3.0.apk 已经是修复此问题的包
