### ISSUE TITLE
更新2.3.0后，不转发未接来电

### ISSUE THREAD

**Issue by daveccc** [pppscn/SmsForwarder#87]
2.1.1版本正常
2.3.0设置中转发应用通知、转发未接来电、转发短信广播都已打开
小米9  MIUI 12.0.6，权限读取短信、通知类短信、读取彩信、读取联系人、读取通话记录、获取手机信息已赋予
短信转发正常

**Comment by pppscn** [comment]
查看一下 WIKI

https://github.com/pppscn/SmsForwarder/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by daveccc** [comment]
大意了，搞定了，谢谢！

pppscn ***@***.***> 于 2021年12月16日周四 01:48写道：
