### ISSUE TITLE
锁屏一段时间后 不会转发推送

### ISSUE THREAD

**Issue by esbylan** [pppscn/SmsForwarder#88]
系统是华为鸿蒙，消息通道是通过短信转发
只要锁屏几分钟后，新的消息进来就不会发短信了，然后解锁手机后才会自动发送
电池优化已经设置过了

**Comment by pppscn** [comment]
https://github.com/pppscn/SmsForwarder/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

电源设置检查一下，还有自启动管理（弄成手动管理：允许自启动、允许关联启动、允许后台运行），国内部分手机定制系统有省电模式（息屏断网等）检查一下

**Comment by pppscn** [comment]
日志里面如果有记录，只是发送失败的话，重点排查 息屏断网

**Comment by esbylan** [comment]
感谢，确实是自启动的问题
