### ISSUE TITLE
能否可以更进以实现短信的发送

### ISSUE THREAD

**Issue by zy10010** [pppscn/SmsForwarder#89]
希望软件可以通过接收短信或者邮箱等方式实现短信功能的发送与查看，以及通话记录的查看
现在部分网站的认证已然不再是接收短信，而是需要主动发送短信，即有了上述的功能需求
查看记录则是因为   部分转发失败，故只能通过查看或调取记录的方式实现远程控制

**Comment by pppscn** [comment]
鉴于软件的特殊性，为了避免被不法分子利用，开源版本暂时不会考虑加入远程控制相关的功能

**Comment by xmsz** [comment]
+1

**Comment by pppscn** [comment]
参见 https://github.com/pppscn/SmsForwarder/pull/102
