### ISSUE TITLE
短信内容解析失败

### ISSUE THREAD

**Issue by longbinzhao** [pppscn/SmsForwarder#91]
短信内容 为
<#> Please enter 1894 into LINE within the next 30 mins.
JFoHLtfsxga
接收方为telegram

另外请问多重匹配是否可以支持正则？

**Comment by pppscn** [comment]
解析失败那个没看懂

多重匹配支持正则，但是现有发布的有bug，已经修复等下一个版本发布

https://github.com/pppscn/SmsForwarder/commit/1c2d4c7b0a8f5c4972c0d352c7597339aa869059
