### ISSUE TITLE
建议支持多信道

### ISSUE THREAD

**Issue by longbinzhao** [pppscn/SmsForwarder#92]
建议支持多信道，同意规则转发多个信道，而不是现在配置多次

**Comment by pppscn** [comment]
暂不考虑，实际上只是规则界面上看起来爽一点，

但是增加了复杂度，越简单越好，复杂了更容易出错，而且转发日志也要聚合更不好展示

如果只是为了配置规则简便，考虑 长按 规则弹出的对话框允许 复制一条

**Comment by pppscn** [comment]
![Screenshot_1640074866](https://user-images.githubusercontent.com/5105854/146895808-428604ee-8025-41f1-8caf-ae1a7355a8aa.png)

效果类似左下角的【一键克隆】
