### ISSUE TITLE
可以兼容安卓4吗？

### ISSUE THREAD

**Issue by miaozilong** [pppscn/SmsForwarder#96]
我的手机版本是4.3的，能支持吗

**Comment by pppscn** [comment]
抱歉，不会再向下兼容，最低5.0，因为很多api需要做调整

你可以可以基于开源代码调整只适配4.3的，估计会更简单一些

**Comment by miaozilong** [comment]
谢谢作者，我重新找个其他的软件吧  不会安卓开发
