### ISSUE TITLE
应用后台时，WebHook没有触发

### ISSUE THREAD

**Issue by qq84266454** [pppscn/SmsForwarder#99]
当应用在后台时，没有转发的webHook，进入应用后，才会发送到设置的webHook

**Comment by qq84266454** [comment]
> webHook
当应用在后台时，没有转发到webHook，进入应用后，才会发送到设置的webHook

**Comment by pppscn** [comment]
参考FAQ第二条
https://github.com/pppscn/SmsForwarder/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
